import { randomUUID } from "node:crypto";
import type { Prisma } from "@prisma/client";
import type { TenantDb } from "./db";
import { appendSchoolAudit } from "./audit";
import { AppError } from "./errors";
import { requirePermission } from "./rbac";

type DayConfig = { dayOfWeek:number; name:string; enabled:boolean; start:string; end:string };
type BreakConfig = { name:string; start:string; end:string };
type TimetableConfig = { days:DayConfig[]; periodMinutes:number; breaks:BreakConfig[]; periodsPerDay:number; published:boolean };
type AssessmentConfig = { categories:Array<{name:string;weight:number}>; rounding:"nearest"|"down"|"up"; missingScorePolicy:"blank"|"zero"; allowTeacherOverride:boolean };
type ReportCardConfig = { includePosition:boolean; includeSubjectPosition:boolean; includeAttendance:boolean; includeTeacherRemark:boolean; includeHeadRemark:boolean; includeSignatures:boolean; includeSchoolContacts:boolean; rankMethod:"total_average"|"weighted_total"; showGrades:boolean; showClassAverage:boolean };

function jsonObject(value: Prisma.JsonValue|null|undefined): Record<string, Prisma.JsonValue> { return value && !Array.isArray(value) && typeof value === "object" ? value as Record<string, Prisma.JsonValue> : {}; }
const DEFAULT_TIMETABLE:TimetableConfig={days:[1,2,3,4,5].map(day=>({dayOfWeek:day,name:["","Monday","Tuesday","Wednesday","Thursday","Friday"][day],enabled:true,start:"08:00",end:day===5?"14:00":"15:00"})),periodMinutes:40,breaks:[{name:"Break",start:"10:00",end:"10:20"},{name:"Lunch",start:"12:20",end:"13:00"}],periodsPerDay:8,published:false};
const DEFAULT_ASSESSMENT:AssessmentConfig={categories:[{name:"Classwork",weight:20},{name:"Homework",weight:10},{name:"Exercises",weight:10},{name:"Quizzes",weight:10},{name:"Project",weight:10},{name:"Exam",weight:40}],rounding:"nearest",missingScorePolicy:"blank",allowTeacherOverride:false};
const DEFAULT_REPORT:ReportCardConfig={includePosition:true,includeSubjectPosition:true,includeAttendance:true,includeTeacherRemark:true,includeHeadRemark:true,includeSignatures:true,includeSchoolContacts:true,rankMethod:"total_average",showGrades:true,showClassAverage:true};
function asTimeMinutes(value:string){const [h,m]=value.split(":").map(Number);if(!Number.isInteger(h)||!Number.isInteger(m)||h<0||h>23||m<0||m>59)throw new AppError("Time must use HH:MM.",400,"INVALID_TIME");return h*60+m;}
function buildPeriods(day:DayConfig,config:TimetableConfig){const start=asTimeMinutes(day.start),end=asTimeMinutes(day.end),breaks=config.breaks.map(b=>({start:asTimeMinutes(b.start),end:asTimeMinutes(b.end),name:b.name})).sort((a,b)=>a.start-b.start);const periods:{period:number;start:string;end:string}[]=[];let cursor=start,period=1;while(cursor+config.periodMinutes<=end&&period<=config.periodsPerDay){const next=cursor+config.periodMinutes;const crossing=breaks.find(b=>cursor<b.end&&next>b.start);if(crossing){cursor=Math.max(cursor,crossing.end);continue;}const fmt=(n:number)=>`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;periods.push({period,start:fmt(cursor),end:fmt(next)});cursor=next;period++;}return periods;}
function parse<T>(value:unknown,fallback:T):T{return value==null?fallback:value as T;}
export async function getAcademicEngineConfig(tx:TenantDb){const row=await tx.$queryRawUnsafe<Array<{timetableConfig:Prisma.JsonValue|null;assessmentConfig:Prisma.JsonValue|null;reportCardConfig:Prisma.JsonValue|null}>>(`SELECT "timetableConfig","assessmentConfig","reportCardConfig" FROM "SchoolSettings" LIMIT 1`);const r=row[0];return{timetable:parse(r?.timetableConfig,DEFAULT_TIMETABLE),assessment:parse(r?.assessmentConfig,DEFAULT_ASSESSMENT),reportCard:parse(r?.reportCardConfig,DEFAULT_REPORT)};}
export async function saveAcademicEngineConfig(tx:TenantDb,input:{schoolId:string;actorId:string;timetable?:TimetableConfig;assessment?:AssessmentConfig;reportCard?:ReportCardConfig}){await requirePermission(tx,input.actorId,"settings:manage_school");const current=await getAcademicEngineConfig(tx);const next={timetable:input.timetable??current.timetable,assessment:input.assessment??current.assessment,reportCard:input.reportCard??current.reportCard};if(next.assessment.categories.length===0||Math.abs(next.assessment.categories.reduce((n,c)=>n+c.weight,0)-100)>0.01)throw new AppError("Assessment category weights must add up to 100%.",400,"INVALID_WEIGHTS");await tx.$executeRawUnsafe(`UPDATE "SchoolSettings" SET "timetableConfig"=$1::jsonb,"assessmentConfig"=$2::jsonb,"reportCardConfig"=$3::jsonb WHERE "schoolId"=$4`,JSON.stringify(next.timetable),JSON.stringify(next.assessment),JSON.stringify(next.reportCard),input.schoolId);await appendSchoolAudit(tx,{schoolId:input.schoolId,actorId:input.actorId,action:"academic.configuration_updated",entityType:"SchoolSettings",entityId:input.schoolId,after:next});return next;}
export async function generateAutomaticTimetable(tx:TenantDb,input:{schoolId:string;actorId:string;replaceExisting:boolean;classIds?:string[]}){await requirePermission(tx,input.actorId,"calendar:manage");const config=await getAcademicEngineConfig(tx);const timetable=config.timetable as TimetableConfig;const activeDays=timetable.days.filter(d=>d.enabled);if(activeDays.length===0)throw new AppError("Enable at least one school day before generating a timetable.",400,"NO_SCHOOL_DAYS");const periodsByDay=new Map<number,ReturnType<typeof buildPeriods>>();for(const day of activeDays)periodsByDay.set(day.dayOfWeek,buildPeriods(day,timetable));const classes=await tx.class.findMany({where:input.classIds?.length?{id:{in:input.classIds}}:{},select:{id:true,name:true}});const assignments=await tx.classSubjectTeacher.findMany({where:{classId:{in:classes.map(c=>c.id)}},include:{subject:true,teacher:true,class:true}});if(assignments.length===0)throw new AppError("Assign subjects to classes and teachers before generating the timetable.",409,"NO_ASSIGNMENTS");const preferredRaw=jsonObject(config.timetable as unknown as Prisma.JsonValue).weeklyPeriods as Prisma.JsonValue|undefined;const weeklyMap:Record<string,number>=preferredRaw&&typeof preferredRaw==="object"&&!Array.isArray(preferredRaw)?Object.fromEntries(Object.entries(preferredRaw).filter((e):e is [string,Prisma.JsonValue]=>typeof e[1]==="number")) as Record<string,number>:{};const classBusy=new Set<string>(),teacherBusy=new Set<string>(),chosen:{schoolId:string;classId:string;subjectId:string;teacherId:string;dayOfWeek:number;period:number}[]=[];const ordered=[...assignments].sort((a,b)=>a.classId.localeCompare(b.classId)||a.subject.name.localeCompare(b.subject.name));for(const assignment of ordered){const key=`${assignment.classId}:${assignment.subjectId}:${assignment.teacherId}`;const target=Math.max(1,Math.min(10,weeklyMap[key]??2));let placed=0;for(let pass=0;pass<target;pass++){let found=false;for(const day of activeDays){for(const p of periodsByDay.get(day.dayOfWeek)??[]){const classKey=`${assignment.classId}:${day.dayOfWeek}:${p.period}`,teacherKey=`${assignment.teacherId}:${day.dayOfWeek}:${p.period}`;if(classBusy.has(classKey)||teacherBusy.has(teacherKey))continue;chosen.push({schoolId:input.schoolId,classId:assignment.classId,subjectId:assignment.subjectId,teacherId:assignment.teacherId,dayOfWeek:day.dayOfWeek,period:p.period});classBusy.add(classKey);teacherBusy.add(teacherKey);placed++;found=true;break;}if(found)break;}if(!found)break;}if(placed<target)throw new AppError(`Could not fit ${assignment.subject.name} for ${assignment.class.name}. Reduce weekly periods or expand the available timetable window.`,409,"TIMETABLE_UNSATISFIABLE");}
if(input.replaceExisting)await tx.timetableSlot.deleteMany({where:{schoolId:input.schoolId}});for(const slot of chosen)await tx.timetableSlot.create({data:slot});const result={scheduled:chosen.length,classes:classes.length,teachers:new Set(chosen.map(x=>x.teacherId)).size,days:activeDays.length,periodsPerDay:Math.max(...activeDays.map(d=>(periodsByDay.get(d.dayOfWeek)??[]).length)),published:false};await appendSchoolAudit(tx,{schoolId:input.schoolId,actorId:input.actorId,action:"timetable.auto_generated",entityType:"Timetable",entityId:randomUUID(),after:{...result,replaceExisting:input.replaceExisting}});return result;}
export async function getGradebookConfiguration(tx:TenantDb){const config=await getAcademicEngineConfig(tx);const assignments=await tx.classSubjectTeacher.findMany({include:{class:{select:{id:true,name:true,level:true}},subject:{select:{id:true,name:true}},teacher:{select:{id:true,name:true}}},orderBy:{classId:"asc"}});const terms=await tx.term.findMany({orderBy:{startDate:"desc"},select:{id:true,name:true,startDate:true,endDate:true}});return{assessment:config.assessment,reportCard:config.reportCard,assignments,terms};}
export async function getClassSubjectPerformance(tx:TenantDb,classId:string,subjectId:string,termId:string){const [students,assessments]=await Promise.all([tx.student.findMany({where:{classId,status:"active"},select:{id:true,name:true,admissionNo:true},orderBy:{name:"asc"}}),tx.assessment.findMany({where:{classId,subjectId,termId},include:{scores:{select:{studentId:true,value:true}},subject:{select:{name:true}}},orderBy:{name:"asc"}})]);const config=(await getAcademicEngineConfig(tx)).assessment as AssessmentConfig;const categoryWeight=new Map(config.categories.map(c=>[c.name.toLowerCase(),c.weight]));const rows=students.map(student=>{const scores=assessments.filter(a=>a.scores.some(s=>s.studentId===student.id)).map(a=>{const value=Number(a.scores.find(s=>s.studentId===student.id)?.value??0);const percentage=Number(a.maxScore)>0?value/Number(a.maxScore)*100:0;const weight=categoryWeight.get(a.type.toLowerCase())??Number(a.weight);return{assessmentId:a.id,name:a.name,type:a.type,value,maxScore:Number(a.maxScore),percentage,weight};});const total=assessments.length?scores.reduce((sum,s)=>sum+s.percentage*s.weight/100,0):0;return{student,total,scores};});return{rows,assessments:assessments.map(a=>({id:a.id,name:a.name,type:a.type,maxScore:Number(a.maxScore),weight:Number(a.weight)})),config};}
