import { appendSchoolAudit } from "./audit";
import type { TenantDb } from "./db";
import { withTenant } from "./db";
import { AppError } from "./errors";
import { requirePermission } from "./rbac";
import { enqueueNotification } from "./message-outbox";

const MAX_EVENT_NOTIFICATION_RECIPIENTS=1000;
const STAFF_ROLE_KEYS=["owner","administrator","principal","vice_principal","academic_coordinator","department_head","accountant","hr_officer","admissions_officer","front_desk_security","transport_officer","teacher","class_teacher","subject_teacher"];
function orderedDates(startDate:Date,endDate:Date){if(!Number.isFinite(startDate.getTime())||!Number.isFinite(endDate.getTime())||endDate<startDate)throw new AppError("End date must be on or after start date.",400,"INVALID_DATE_RANGE");}
export async function createAcademicYear(input:{schoolId:string;actorId:string;name:string;startDate:Date;endDate:Date}){orderedDates(input.startDate,input.endDate);return withTenant(input.schoolId,async tx=>{await requirePermission(tx,input.actorId,"calendar:manage");const year=await tx.academicYear.create({data:{schoolId:input.schoolId,name:input.name.trim(),startDate:input.startDate,endDate:input.endDate}});await appendSchoolAudit(tx,{schoolId:input.schoolId,actorId:input.actorId,action:"academic_year.created",entityType:"AcademicYear",entityId:year.id,after:year});return year;});}
export async function createTerm(input:{schoolId:string;actorId:string;academicYearId:string;name:string;startDate:Date;endDate:Date}){orderedDates(input.startDate,input.endDate);return withTenant(input.schoolId,async tx=>{await requirePermission(tx,input.actorId,"calendar:manage");await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`academic-year-terms:${input.schoolId}:${input.academicYearId}`}))`;const year=await tx.academicYear.findFirst({where:{id:input.academicYearId,schoolId:input.schoolId},select:{id:true,startDate:true,endDate:true}});if(!year)throw new AppError("The selected academic year does not belong to this school.",400,"INVALID_ACADEMIC_YEAR");if(input.startDate<year.startDate||input.endDate>year.endDate)throw new AppError("Term dates must fall inside the academic year.",400,"TERM_OUTSIDE_YEAR");const overlap=await tx.term.findFirst({where:{schoolId:input.schoolId,academicYearId:input.academicYearId,startDate:{lt:input.endDate},endDate:{gt:input.startDate}},select:{name:true}});if(overlap)throw new AppError(`Term dates overlap ${overlap.name}.`,409,"TERM_OVERLAP");const term=await tx.term.create({data:{schoolId:input.schoolId,academicYearId:year.id,name:input.name.trim(),startDate:input.startDate,endDate:input.endDate}});await appendSchoolAudit(tx,{schoolId:input.schoolId,actorId:input.actorId,action:"term.created",entityType:"Term",entityId:term.id,after:term});return term;});}
const CALENDAR_EVENT_TYPES=new Set(["holiday","vacation","exam_week","closure","academic","parent","operational","sports","trip","meeting","other"]);const ATTENDANCE_BLOCKING_EVENT_TYPES=new Set(["holiday","vacation","closure"]);
type CalendarEventInput={schoolId:string;actorId:string;academicYearId:string;type:string;name:string;startDate:Date;endDate:Date;affectsAttendance?:boolean;affectsTransport?:boolean;notifyGuardians?:boolean;notifyStaff?:boolean;location?:string|null;description?:string|null};
type CalendarEventRow={id:string;schoolId:string;academicYearId:string;type:string;name:string;startDate:Date;endDate:Date;affectsAttendance:boolean;affectsTransport:boolean;location:string|null;description:string|null};
export async function createCalendarEventTx(tx:TenantDb,input:CalendarEventInput){
  orderedDates(input.startDate,input.endDate);if(!CALENDAR_EVENT_TYPES.has(input.type))throw new AppError("Invalid calendar event type.",400,"INVALID_EVENT_TYPE");await requirePermission(tx,input.actorId,"calendar:manage");const year=await tx.academicYear.findFirst({where:{id:input.academicYearId,schoolId:input.schoolId},select:{id:true,startDate:true,endDate:true}});if(!year)throw new AppError("The selected academic year does not belong to this school.",400,"INVALID_ACADEMIC_YEAR");if(input.startDate<year.startDate||input.endDate>year.endDate)throw new AppError("Calendar event dates must fall inside the academic year.",400,"EVENT_OUTSIDE_YEAR");
  const affectsAttendance=input.affectsAttendance??ATTENDANCE_BLOCKING_EVENT_TYPES.has(input.type);const affectsTransport=input.affectsTransport??false;const location=input.location?.trim()||null;const description=input.description?.trim()||null;
  const eventRows=await tx.$queryRaw<CalendarEventRow[]>`INSERT INTO "CalendarEvent" ("id","schoolId","academicYearId","type","name","startDate","endDate","affectsAttendance","affectsTransport","location","description") VALUES (gen_random_uuid()::text,${input.schoolId},${year.id},${input.type},${input.name.trim()},${input.startDate},${input.endDate},${affectsAttendance},${affectsTransport},${location},${description}) RETURNING "id","schoolId","academicYearId","type","name","startDate","endDate","affectsAttendance","affectsTransport","location","description"`;
  const event=eventRows[0];if(!event)throw new AppError("Calendar event could not be created.",500,"EVENT_CREATE_FAILED");
  let guardianRecipients=0,staffRecipients=0,queuedDeliveryJobs=0;const startText=input.startDate.toISOString().slice(0,10);const endText=input.endDate.toISOString().slice(0,10);const dateText=startText===endText?startText:`${startText} to ${endText}`;const messageBody=`School calendar event: ${event.name}\nDate: ${dateText}\nType: ${event.type}`;
  if(input.notifyGuardians){const guardianCount=await tx.guardian.count({where:{schoolId:input.schoolId,phone:{not:null}}});if(guardianCount>MAX_EVENT_NOTIFICATION_RECIPIENTS)throw new AppError(`Guardian notifications exceed the ${MAX_EVENT_NOTIFICATION_RECIPIENTS} recipient request limit. Narrow the notification audience and create the event again.`,409,"EVENT_NOTIFICATION_AUDIENCE_TOO_LARGE");const guardians=await tx.guardian.findMany({where:{schoolId:input.schoolId,phone:{not:null}},select:{id:true,phone:true},orderBy:{id:"asc"}});for(const guardian of guardians){if(!guardian.phone)continue;const rows=await enqueueNotification(tx,{schoolId:input.schoolId,recipientType:"guardian",recipientId:guardian.id,recipientPhone:guardian.phone,body:messageBody,templateKey:"school_announcement",templateVariables:{title:event.name,body:messageBody},idempotencyKey:`calendar-event:${event.id}:guardian:${guardian.id}`});guardianRecipients++;queuedDeliveryJobs+=rows.length;}}
  if(input.notifyStaff){const staffWhere={schoolId:input.schoolId,status:"active",phone:{not:null},userRoles:{some:{role:{key:{in:STAFF_ROLE_KEYS}}}}};const staffCount=await tx.user.count({where:staffWhere});if(staffCount>MAX_EVENT_NOTIFICATION_RECIPIENTS)throw new AppError(`Staff notifications exceed the ${MAX_EVENT_NOTIFICATION_RECIPIENTS} recipient request limit. Narrow the notification audience and create the event again.`,409,"EVENT_NOTIFICATION_AUDIENCE_TOO_LARGE");const staff=await tx.user.findMany({where:staffWhere,select:{id:true,phone:true},orderBy:{id:"asc"}});for(const user of staff){if(!user.phone)continue;const rows=await enqueueNotification(tx,{schoolId:input.schoolId,recipientType:"staff",recipientId:user.id,recipientPhone:user.phone,body:messageBody,templateKey:"school_announcement",templateVariables:{title:event.name,body:messageBody},idempotencyKey:`calendar-event:${event.id}:staff:${user.id}`});staffRecipients++;queuedDeliveryJobs+=rows.length;}}
  await appendSchoolAudit(tx,{schoolId:input.schoolId,actorId:input.actorId,action:"calendar_event.created",entityType:"CalendarEvent",entityId:event.id,after:{...event,notifyGuardians:Boolean(input.notifyGuardians),notifyStaff:Boolean(input.notifyStaff),guardianRecipients,staffRecipients,queuedDeliveryJobs}});return{event,guardianRecipients,staffRecipients,queuedDeliveryJobs};
}
export async function createCalendarEvent(input:CalendarEventInput){return withTenant(input.schoolId,async tx=>(await createCalendarEventTx(tx,input)).event);}
