import { randomInt } from "node:crypto";
import type { ArcadeWorldQuestion, ArcadeWorldScene } from "./arcade-world-content";

export type ChronicleMission = "timeline" | "evidence" | "cause" | "source";
export type ChronicleScene = ArcadeWorldScene & {
  mission: ChronicleMission;
  era: string;
  archiveWing: string;
  artifact: string;
  contextClues: string[];
  evidenceTags: string[];
  paradoxLevel: 1 | 2 | 3 | 4 | 5;
  caseId: string;
};
export type ChronicleQuestion = ArcadeWorldQuestion & { conceptKey: string; scene: ChronicleScene };

type TimelineTemplate = {
  id: string; mission: "timeline"; minDifficulty: number; era: string; archiveWing: string; artifact: string;
  prompt: string; ordered: readonly string[]; explanation: string; clues: string[]; tags: string[];
};
type ChoiceTemplate = {
  id: string; mission: "evidence" | "cause" | "source"; minDifficulty: number; era: string; archiveWing: string; artifact: string;
  prompt: string; answer: string; wrong: [string,string,string]; explanation: string; clues: string[]; tags: string[];
};
type Template = TimelineTemplate | ChoiceTemplate;

const CASES: readonly Template[] = [
  { id:"ghana-independence-path", mission:"timeline", minDifficulty:1, era:"Gold Coast to Independence", archiveWing:"Ghana Freedom Gallery", artifact:"Independence dossier", prompt:"Restore these milestones from earliest to latest.", ordered:["1948 · Accra riots","1951 · CPP wins the general election","1956 · Election confirms the independence mandate","1957 · Ghana becomes independent on 6 March"], explanation:"The 1948 unrest came before the 1951 and 1956 elections, followed by independence on 6 March 1957.", clues:["The archive begins in the late 1940s.","Political organisation and elections shape this sequence.","The final milestone is independence."], tags:["Ghana","chronology","independence"] },
  { id:"ghana-republic-path", mission:"timeline", minDifficulty:1, era:"Independent Ghana", archiveWing:"Republic Hall", artifact:"Constitution cabinet", prompt:"Place these constitutional milestones from earliest to latest.", ordered:["1957 · Ghana gains independence","1960 · Ghana becomes a republic","1992 · Fourth-Republic Constitution is approved","1993 · Fourth Republic begins"], explanation:"Independence came in 1957, republican status in 1960, the current constitutional order was approved in 1992 and the Fourth Republic began in 1993.", clues:["Two milestones belong to the Nkrumah era.","The later pair establishes the Fourth Republic.","Think in decades before exact dates."], tags:["Ghana","constitution","chronology"] },
  { id:"gold-coast-coast", mission:"timeline", minDifficulty:2, era:"Gold Coast coastal history", archiveWing:"Coastal Encounters", artifact:"Fort record strip", prompt:"Repair this coastal-history timeline from earliest to latest.", ordered:["1482 · Portuguese build Elmina Castle","1637 · Dutch capture Elmina Castle","1872 · Britain takes control of former Dutch forts","1874 · Gold Coast Crown Colony is proclaimed"], explanation:"Elmina Castle was built by the Portuguese in 1482, captured by the Dutch in 1637, and British colonial control expanded in the 1870s.", clues:["The first two records concern Elmina Castle.","The later records are both in the 1870s.","European control changed over several centuries."], tags:["Ghana","coast","colonial-history"] },
  { id:"african-empires", mission:"timeline", minDifficulty:2, era:"West African empires", archiveWing:"African Civilisations", artifact:"Trade-route chronicle", prompt:"Order these West African historical markers from earliest to latest.", ordered:["Ancient Ghana Empire flourishes before Mali","13th century · Mali Empire rises","1324 · Mansa Musa makes his pilgrimage to Mecca","15th century · Songhai expands as a major empire"], explanation:"The ancient Ghana Empire preceded Mali; Mali rose in the 13th century, Mansa Musa travelled in 1324, and Songhai became dominant later.", clues:["Do not confuse the ancient Ghana Empire with modern Ghana.","Mali follows the ancient Ghana Empire.","Songhai becomes prominent later."], tags:["Africa","empires","chronology"] },
  { id:"world-conflict-sequence", mission:"timeline", minDifficulty:2, era:"Twentieth century", archiveWing:"World Turning Points", artifact:"Newsreel canisters", prompt:"Restore these world events from earliest to latest.", ordered:["1914 · First World War begins","1918 · First World War ends","1939 · Second World War begins","1945 · Second World War ends"], explanation:"The First World War ran from 1914 to 1918; the Second World War ran from 1939 to 1945.", clues:["Two conflicts are represented.","Each beginning must precede its ending.","The First World War belongs before the Second."], tags:["world-history","wars","chronology"] },
  { id:"ideas-industry", mission:"timeline", minDifficulty:3, era:"Technology and society", archiveWing:"Change Through Time", artifact:"Innovation reel", prompt:"Arrange these broad historical developments from earliest to latest.", ordered:["c.1450 · Gutenberg printing press spreads movable-type printing in Europe","late 18th century · Industrial Revolution accelerates in Britain","1903 · Wright brothers achieve powered flight","1969 · Apollo 11 lands humans on the Moon"], explanation:"Movable-type printing in Europe predates the Industrial Revolution, powered flight and the Moon landing by centuries.", clues:["Start in the fifteenth century.","Industrialisation comes before aviation.","Space exploration is the latest development here."], tags:["technology","world-history","chronology"] },

  { id:"primary-diary", mission:"source", minDifficulty:2, era:"Historical method", archiveWing:"Evidence Lab", artifact:"Handwritten diary", prompt:"A diary was written by a participant during an event. How should a historian usually classify it?", answer:"A primary source created close to the event", wrong:["A secondary source written only by later historians","A fictional source that cannot contain evidence","A future prediction rather than a historical source"], explanation:"A participant's contemporary diary is normally a primary source, though historians still examine its perspective and limitations.", clues:["Ask who created it and when.","Being primary does not make a source automatically unbiased.","Perspective still matters."], tags:["source-analysis","primary-source","evidence"] },
  { id:"secondary-textbook", mission:"source", minDifficulty:2, era:"Historical method", archiveWing:"Evidence Lab", artifact:"Modern textbook", prompt:"A textbook written decades after an event uses many earlier records to explain what happened. What type of source is it mainly?", answer:"A secondary source that interprets earlier evidence", wrong:["A primary source created during the event","An archaeological artefact from the event","An eyewitness account recorded at the time"], explanation:"Later works that analyse and synthesise earlier evidence are generally secondary sources.", clues:["Creation time matters.","The author is interpreting earlier evidence.","Classification is different from reliability."], tags:["source-analysis","secondary-source","evidence"] },
  { id:"witness-photo", mission:"evidence", minDifficulty:3, era:"Historical method", archiveWing:"Evidence Lab", artifact:"Photograph and caption", prompt:"A photograph taken during a political rally is being used to study crowd size. What is the strongest first step?", answer:"Check when, where and by whom the photograph was taken, then compare it with other evidence", wrong:["Assume the image shows the entire event without checking","Ignore the photograph because images are never historical evidence","Use only the caption and avoid examining the image"], explanation:"Historians establish provenance and context, then corroborate evidence rather than treating one source as complete proof.", clues:["Provenance means origin and context.","One image captures only a viewpoint.","Corroboration strengthens a conclusion."], tags:["evidence","corroboration","photograph"] },
  { id:"1948-effect", mission:"cause", minDifficulty:3, era:"Gold Coast nationalism", archiveWing:"Ghana Freedom Gallery", artifact:"1948 investigation file", prompt:"Which statement best connects the 1948 Accra riots to later Gold Coast politics?", answer:"The unrest intensified pressure for political change and helped accelerate nationalist organisation", wrong:["The riots immediately created the Republic of Ghana in 1948","The riots ended all political activity until 1957","The riots caused Ghana to become independent without later elections or negotiations"], explanation:"The 1948 unrest was an important turning point that increased pressure for reform and nationalist mobilisation, but independence still followed later political organisation, elections and negotiations.", clues:["Avoid treating a turning point as the only cause.","Look for a consequence that allows later developments.","Historical change often has multiple causes."], tags:["Ghana","cause-consequence","nationalism"] },
  { id:"1951-election", mission:"cause", minDifficulty:3, era:"Gold Coast nationalism", archiveWing:"Ghana Freedom Gallery", artifact:"Election return", prompt:"Why is the 1951 Gold Coast election significant in the path toward self-government?", answer:"The CPP won a major electoral victory, strengthening the push for self-government", wrong:["It was the election that made Ghana a republic in 1960","It ended the Second World War","It transferred Elmina Castle from Portugal to the Dutch"], explanation:"The CPP's 1951 electoral victory was a major step in the transition toward internal self-government and later independence.", clues:["Keep the event inside the early 1950s independence process.","Separate electoral progress from the later republic.","Chronology helps reject anachronisms."], tags:["Ghana","elections","cause-consequence"] },
  { id:"bond-1844", mission:"evidence", minDifficulty:4, era:"Nineteenth-century Gold Coast", archiveWing:"Treaties & Authority", artifact:"Bond of 1844 facsimile", prompt:"When studying the Bond of 1844, what question most directly helps a historian understand its political significance?", answer:"Which authorities agreed to it, what powers it recognised, and how those arrangements changed over time", wrong:["Whether the paper uses a modern font","Which twentieth-century political party printed it","Whether it predicted the exact date of independence"], explanation:"Historical significance comes from participants, terms, power relationships and consequences, not superficial features or anachronistic questions.", clues:["Interrogate actors, terms and consequences.","Avoid questions from the wrong century.","A document's meaning depends on context."], tags:["Ghana","historical-method","treaties"] },
  { id:"oral-history", mission:"source", minDifficulty:4, era:"Historical method", archiveWing:"Voices Archive", artifact:"Recorded oral testimony", prompt:"A historian records an elderly witness describing an event experienced decades earlier. How should the testimony be used?", answer:"Treat it as valuable primary testimony while checking memory, perspective and other evidence", wrong:["Reject it automatically because spoken evidence has no historical value","Accept every detail as certain because the speaker was present","Classify it only as fiction because it was recorded later"], explanation:"Oral testimony can preserve crucial firsthand evidence, but historians evaluate memory, perspective and corroboration like other sources.", clues:["Firsthand experience matters.","Time can affect memory.","Corroboration remains important."], tags:["oral-history","evidence","corroboration"] },
  { id:"anachronism", mission:"evidence", minDifficulty:4, era:"Historical reasoning", archiveWing:"Paradox Desk", artifact:"Suspicious archive card", prompt:"A supposed 1850 Gold Coast letter refers to a radio broadcast. What should the archive team suspect first?", answer:"An anachronism that may indicate the document is misdated, altered or not authentic", wrong:["Proof that radio was common in the Gold Coast in 1850","Evidence that chronology does not matter to historians","A reason to ignore all written sources from the nineteenth century"], explanation:"An anachronism places something in a time where it does not fit and can be a warning sign about dating or authenticity.", clues:["Check whether the technology fits the claimed period.","One inconsistency does not invalidate every source.","Dating evidence is part of source criticism."], tags:["anachronism","source-criticism","chronology"] },
  { id:"multi-cause", mission:"cause", minDifficulty:5, era:"Historical reasoning", archiveWing:"Causation Chamber", artifact:"Cause web", prompt:"What is the strongest way to explain a major historical change such as independence?", answer:"Weigh several interacting causes and distinguish long-term conditions from immediate triggers", wrong:["Choose one dramatic event and treat it as the only cause","List dates without explaining relationships","Assume every cause mattered equally without evidence"], explanation:"Strong historical explanations compare multiple causes, their timing, importance and interaction rather than reducing change to one event.", clues:["Separate long-term conditions from triggers.","Importance must be argued with evidence.","Causation is a relationship, not just a list."], tags:["historical-thinking","causation","evidence"] },
  { id:"corroboration", mission:"evidence", minDifficulty:5, era:"Historical reasoning", archiveWing:"Evidence Lab", artifact:"Conflicting source bundle", prompt:"Two sources disagree about the size of a demonstration. What should the historian do next?", answer:"Compare provenance, purpose and additional independent evidence before reaching a conclusion", wrong:["Automatically choose the source with the larger number","Discard both sources because disagreement makes history impossible","Average the two numbers without checking how either was produced"], explanation:"Disagreement is a reason to investigate source origin, purpose and corroborating evidence, not to guess or discard the record.", clues:["Source disagreement is normal historical work.","Ask how each claim was produced.","Independent evidence can help resolve uncertainty."], tags:["corroboration","source-criticism","evidence"] },
];

function shuffle<T>(values: readonly T[]): T[] { const out=[...values]; for(let i=out.length-1;i>0;i-=1){const j=randomInt(i+1);[out[i],out[j]]=[out[j],out[i]];} return out; }
function safeDifficulty(value:number){ return Math.max(1,Math.min(5,Math.trunc(value))); }
function poolFor(difficulty:number){ const level=safeDifficulty(difficulty); return CASES.filter((item)=>item.minDifficulty<=level); }

export function createChronicleVaultQuestions(difficulty:number,length=5): ChronicleQuestion[] {
  const level=safeDifficulty(difficulty), count=Math.max(1,Math.min(40,Math.trunc(length)));
  const pool=poolFor(level); let deck=shuffle(pool); const chosen:Template[]=[];
  for(let i=0;i<count;i+=1){ if(!deck.length) deck=shuffle(pool); chosen.push(deck.pop()!); }
  return chosen.map((item,index)=>{
    const scene:ChronicleScene={ boardTitle:"Chronicle Vault", mission:item.mission, era:item.era, archiveWing:item.archiveWing, artifact:item.artifact, contextClues:item.clues, evidenceTags:item.tags, paradoxLevel:Math.max(1,Math.min(5,Math.ceil((level+item.minDifficulty)/2))) as 1|2|3|4|5, caseId:`CV-${String(index+1).padStart(2,"0")}-${randomInt(100,999)}`, cue:item.mission==="timeline"?"Reconstruct the record without creating a chronology paradox.":"Use provenance, chronology and evidence before sealing the archive decision.", meterLabels:[item.era,item.mission,`paradox ${Math.max(1,Math.min(5,Math.ceil((level+item.minDifficulty)/2)))}/5`] };
    if(item.mission==="timeline") return { id:String(index), kind:"sort_plus", prompt:item.prompt, options:shuffle(item.ordered), answer:JSON.stringify(item.ordered), explanation:item.explanation, conceptKey:`chronicle:${item.mission}:${item.id}`, scene };
    return { id:String(index), kind:"simulation", prompt:item.prompt, options:shuffle([item.answer,...item.wrong]), answer:item.answer, explanation:item.explanation, conceptKey:`chronicle:${item.mission}:${item.id}`, scene };
  });
}
