import { randomInt } from "node:crypto";
import type { ArcadeResponseQuestion } from "./arcade-response-content";

export type CircuitForgeMission = "path" | "component" | "series" | "parallel" | "fault" | "measure" | "load" | "safety";
export type CircuitForgeScene = {
  boardTitle: "Circuit Forge";
  mission: CircuitForgeMission;
  sector: string;
  device: string;
  supplyV: number;
  loadLabel: string;
  circuitTags: string[];
  faultLevel: 1 | 2 | 3 | 4 | 5;
  bay: string;
  caseId: string;
  cue: string;
  meterLabels: string[];
};
export type CircuitForgeQuestion = ArcadeResponseQuestion & { conceptKey: string; scene: CircuitForgeScene };

type Template = {
  id: string;
  mission: CircuitForgeMission;
  minDifficulty: number;
  sector: string;
  device: string;
  supplyV: number;
  loadLabel: string;
  prompt: string;
  answer: string;
  wrong: readonly [string, string, string];
  explanation: string;
  clues: readonly string[];
};

const CASES: readonly Template[] = [
  { id:"closed-loop",mission:"path",minDifficulty:1,sector:"Library lighting",device:"Reading lamp",supplyV:6,loadLabel:"one lamp",prompt:"The lamp is off. Which repair creates a complete conducting path from the cells through the lamp and back to the cells?",answer:"Close the open switch so the loop is complete",wrong:["Remove one connecting wire","Add a plastic gap in the wire","Disconnect the cells from the circuit"],explanation:"Current needs a complete conducting loop. Closing the switch completes the path.",clues:["Trace the path from one terminal back to the other.","A gap stops current.","A switch controls whether the path is complete."] },
  { id:"conductor",mission:"component",minDifficulty:1,sector:"Workshop bench",device:"Jumper lead",supplyV:3,loadLabel:"test lamp",prompt:"Which material should form the conducting core of a safe classroom jumper lead?",answer:"Copper wire",wrong:["Dry rubber","Plastic strip","Glass rod"],explanation:"Copper is a good electrical conductor; rubber, plastic and glass are commonly insulating materials.",clues:["The inner core must carry current.","Insulators are useful around conductors, not instead of them.","Think about common electrical wiring."] },
  { id:"insulator",mission:"safety",minDifficulty:1,sector:"Maintenance desk",device:"Cable cover",supplyV:6,loadLabel:"protected cable",prompt:"Why is the copper core of a school circuit lead covered with plastic?",answer:"Plastic insulates the conductor and reduces accidental contact",wrong:["Plastic creates the electric current","Plastic automatically increases the voltage","Plastic makes every circuit parallel"],explanation:"Plastic is an electrical insulator that helps prevent unintended contact with the conducting metal.",clues:["The covering should not carry current easily.","The metal core already provides the conducting path.","Safety depends on separating users from bare conductors."] },
  { id:"switch-open",mission:"path",minDifficulty:1,sector:"Classroom display",device:"Indicator lamp",supplyV:3,loadLabel:"lamp branch",prompt:"A switch is open in a simple series loop. What best describes the circuit?",answer:"The conducting path is broken, so current cannot complete the loop",wrong:["The switch doubles the cell voltage","The lamp becomes the power source","The open switch makes current flow faster"],explanation:"An open switch creates a gap, interrupting the conducting loop.",clues:["Open means there is a gap.","Current requires continuity.","The switch changes the path, not the battery chemistry."] },
  { id:"series-cells",mission:"series",minDifficulty:2,sector:"Science block",device:"Emergency beacon",supplyV:6,loadLabel:"two cells",prompt:"Two identical 3 V cells are connected correctly in series. What supply potential difference is available across the pair?",answer:"6 V",wrong:["1.5 V","3 V","9 V"],explanation:"Series cell voltages add when the cells are oriented correctly: 3 V + 3 V = 6 V.",clues:["The cells are identical.","They are connected in series.","Combine their potential differences."] },
  { id:"series-failure",mission:"series",minDifficulty:2,sector:"Assembly hall",device:"Series lamp string",supplyV:9,loadLabel:"three lamps",prompt:"Three lamps are in one series path. One lamp is removed and leaves a gap. What happens to the other lamps?",answer:"They go off because the only current path is broken",wrong:["They stay on at exactly the same brightness","Only the battery switches off permanently","They become separate parallel branches automatically"],explanation:"A series circuit has one path. Removing a component and leaving a gap breaks that path for every component.",clues:["There is only one route for current.","A missing lamp leaves a gap.","Trace the same path through all three lamps."] },
  { id:"parallel-failure",mission:"parallel",minDifficulty:2,sector:"ICT lab",device:"Parallel desk lamps",supplyV:12,loadLabel:"two branches",prompt:"Two lamps are on separate parallel branches. One branch opens. What is most likely for the lamp on the healthy branch?",answer:"It can remain lit because its branch still forms a complete path",wrong:["It must go off because all parallel branches share one path","It becomes a battery","Its branch automatically becomes a short circuit"],explanation:"Parallel branches provide separate current paths, so one open branch need not interrupt another complete branch.",clues:["Parallel means more than one route.","Only one branch has opened.","Check whether the second route still returns to the source."] },
  { id:"parallel-voltage",mission:"parallel",minDifficulty:3,sector:"Library annex",device:"Parallel lighting board",supplyV:12,loadLabel:"two lamp branches",prompt:"Two lamp branches are connected in parallel across a 12 V source. Approximately what potential difference is across each complete branch?",answer:"12 V",wrong:["3 V","6 V","24 V"],explanation:"Components connected across the same two supply nodes have the same potential difference as the source.",clues:["Both branches connect to the same two supply nodes.","Parallel branches share terminal voltage.","Do not divide voltage simply because there are two branches."] },
  { id:"ammeter",mission:"measure",minDifficulty:3,sector:"Physics lab",device:"Current monitor",supplyV:6,loadLabel:"lamp circuit",prompt:"Where should an ammeter be connected to measure current through a lamp?",answer:"In series with the lamp so the branch current passes through the meter",wrong:["Across the lamp in parallel like a voltmeter","Directly across the battery with no load","Outside the conducting circuit"],explanation:"An ammeter is connected in series so the current being measured flows through it.",clues:["The meter must carry the branch current.","This is different from measuring potential difference.","Avoid placing a low-resistance ammeter directly across a source."] },
  { id:"voltmeter",mission:"measure",minDifficulty:3,sector:"Physics lab",device:"Voltage monitor",supplyV:9,loadLabel:"resistor",prompt:"How should a voltmeter be connected to measure potential difference across a resistor?",answer:"In parallel across the resistor terminals",wrong:["In series as the only path through the circuit","Directly replacing the resistor","Across an open air gap unrelated to the resistor"],explanation:"A voltmeter compares potential between two points and is connected in parallel across the component.",clues:["Potential difference compares two points.","Use the component's two terminals.","A voltmeter is not inserted as the main current path."] },
  { id:"short-circuit",mission:"fault",minDifficulty:3,sector:"Robotics room",device:"Motor controller",supplyV:9,loadLabel:"motor branch",prompt:"A wire accidentally creates a very low-resistance path directly across the source. What fault should the grid controller report?",answer:"Short circuit — isolate the path and disconnect power before repair",wrong:["Normal open circuit — increase the voltage","Healthy parallel load — touch the bare wire","Insulation success — add another cell immediately"],explanation:"A low-resistance path across a source can produce a dangerously large current and should be isolated safely.",clues:["The unintended path has very low resistance.","Large current can cause heating.","Safety comes before troubleshooting under power."] },
  { id:"fuse",mission:"safety",minDifficulty:3,sector:"Administration block",device:"Protected supply",supplyV:12,loadLabel:"branch protection",prompt:"What is the job of a correctly rated fuse in a circuit?",answer:"Break the circuit if current becomes dangerously high",wrong:["Keep increasing current until the load works","Store electrical energy like a battery","Force every appliance into series"],explanation:"A fuse melts and opens the circuit when excessive current passes, helping protect wiring and equipment.",clues:["It is a protective component.","Its response is linked to excessive current.","Protection may intentionally open the circuit."] },
  { id:"ohm-current",mission:"load",minDifficulty:4,sector:"STEM lab",device:"Resistive heater model",supplyV:12,loadLabel:"6 Ω load",prompt:"A 6 Ω resistor is connected across 12 V. Using I = V/R, what current should the monitor expect?",answer:"2 A",wrong:["0.5 A","6 A","72 A"],explanation:"I = V/R = 12/6 = 2 A.",clues:["Use I = V/R.","Voltage is 12 V.","Resistance is 6 Ω."] },
  { id:"ohm-resistance",mission:"load",minDifficulty:4,sector:"Electronics bay",device:"Sensor resistor",supplyV:10,loadLabel:"2 A branch",prompt:"A branch has 10 V across it and carries 2 A. Using R = V/I, what is the resistance?",answer:"5 Ω",wrong:["0.2 Ω","8 Ω","20 Ω"],explanation:"R = V/I = 10/2 = 5 Ω.",clues:["Rearrange Ohm's law for resistance.","Divide voltage by current.","Keep the unit in ohms."] },
  { id:"power",mission:"load",minDifficulty:5,sector:"Solar learning hub",device:"DC learning load",supplyV:12,loadLabel:"3 A load",prompt:"A device operates at 12 V and 3 A. Using P = VI, what electrical power is it using?",answer:"36 W",wrong:["4 W","15 W","144 W"],explanation:"P = V × I = 12 × 3 = 36 W.",clues:["Power uses voltage multiplied by current.","The current is 3 A.","The answer unit is watts."] },
  { id:"overload",mission:"fault",minDifficulty:5,sector:"School microgrid",device:"Distribution bus",supplyV:24,loadLabel:"multiple loads",prompt:"After several high-current loads are added to one protected branch, the breaker trips repeatedly. What is the best engineering response?",answer:"Reduce or redistribute the load, then verify the branch rating before restoring power",wrong:["Bypass the breaker so it cannot trip","Replace the breaker with bare wire","Keep resetting it without investigating current demand"],explanation:"Repeated tripping can indicate overload or another fault. The safe response is to isolate, investigate demand and keep protection correctly rated.",clues:["Protection is signalling a problem.","Do not defeat a safety device.","Load can be redistributed across suitable circuits."] },
  { id:"diagnose-open",mission:"fault",minDifficulty:5,sector:"Security lighting",device:"Lamp branch",supplyV:12,loadLabel:"one branch",prompt:"A lamp branch has supply voltage at its input but no current, and continuity testing shows a break after the switch. Which diagnosis best fits?",answer:"An open-circuit fault after the switch",wrong:["A confirmed short circuit across the source","A healthy closed circuit","A battery that is definitely overcharged"],explanation:"Voltage can be present upstream while a break prevents branch current. Continuity testing localises the open path.",clues:["No current is flowing in the branch.","Continuity testing found a break.","The fault is after the switch."] },
];

function shuffle<T>(values: readonly T[]) { const out=[...values]; for(let i=out.length-1;i>0;i-=1){const j=randomInt(i+1);[out[i],out[j]]=[out[j],out[i]];} return out; }
function safeDifficulty(value:number){return Math.max(1,Math.min(5,Math.trunc(value)));}
export function createCircuitForgeQuestions(difficulty:number,length=5):CircuitForgeQuestion[]{
  const level=safeDifficulty(difficulty),count=Math.max(1,Math.min(40,Math.trunc(length))),pool=CASES.filter((item)=>item.minDifficulty<=level);let deck=shuffle(pool);const selected:Template[]=[];
  for(let i=0;i<count;i+=1){if(!deck.length)deck=shuffle(pool);selected.push(deck.pop()!);}
  return selected.map((item,index)=>{const faultLevel=Math.max(1,Math.min(5,Math.ceil((level+item.minDifficulty)/2))) as 1|2|3|4|5;return {id:String(index),kind:"path",prompt:item.prompt,options:shuffle([item.answer,...item.wrong]),answer:item.answer,explanation:item.explanation,conceptKey:`circuit-forge:${item.mission}:${item.id}`,scene:{boardTitle:"Circuit Forge",mission:item.mission,sector:item.sector,device:item.device,supplyV:item.supplyV,loadLabel:item.loadLabel,circuitTags:[...item.clues],faultLevel,bay:`GRID-${String(index+1).padStart(2,"0")}`,caseId:`CF-${randomInt(100,999)}`,cue:item.mission==="fault"||item.mission==="safety"?"Isolate danger first, then reason from the circuit evidence.":"Trace the electrical path before committing the switching plan.",meterLabels:[`${item.supplyV} V`,item.loadLabel,`fault ${faultLevel}/5`]}};});
}
