import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { TenantDb } from "./db";
import { withTenant } from "./db";
import { appendSchoolAudit } from "./audit";
import { AppError } from "./errors";
import { requirePermission } from "./rbac";
import encodeQR from "qr";
import { PDFDocument, StandardFonts, rgb, translate, pushGraphicsState, popGraphicsState, type PDFPage, type PDFFont } from "pdf-lib";

export const DEFAULT_VALIDITY_MONTHS = 24;
export const MAX_BULK_CARDS = 2000;
const PT_PER_MM = 72 / 25.4;
const CARD_WIDTH = 85.6 * PT_PER_MM;
const CARD_HEIGHT = 53.98 * PT_PER_MM;
const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;

type CardRow = {
  id:string; schoolId:string; personType:"student"|"staff"; studentId:string|null; staffId:string|null;
  serial:string; issuedAt:Date; expiresAt:Date; status:"active"|"revoked"; version:number;
  personName:string; admissionNo:string|null; className:string|null; roleName:string|null; photoUrl:string|null;
};
export type IdentityCardKind="student"|"staff";
export type IdentityCardScope="all"|IdentityCardKind|"selected";

function secret(){const value=process.env.SCHOOL_AUTH_SECRET;if(!value||value.length<32)throw new AppError("SCHOOL_AUTH_SECRET is not configured securely.",500,"CONFIGURATION_ERROR");return createHash("sha256").update(`${value}:identity-card:v1`).digest();}
function canonical(card:Pick<CardRow,"schoolId"|"serial"|"personType"|"issuedAt"|"expiresAt"|"version">){return ["sukuunova-id-card-v1",card.schoolId,card.serial,card.personType,card.issuedAt.toISOString(),card.expiresAt.toISOString(),String(card.version)].join("|");}
export function identityCardSignature(card:Pick<CardRow,"schoolId"|"serial"|"personType"|"issuedAt"|"expiresAt"|"version">){return createHmac("sha256",secret()).update(canonical(card)).digest("hex");}
export function identityCardVerificationPath(schoolCode:string,serial:string){return `/verify/id-card/${encodeURIComponent(schoolCode)}/${encodeURIComponent(serial)}`;}
export function identityCardVerificationUrl(origin:string,schoolCode:string,card:CardRow){return `${origin.replace(/\/+$/g,"")}${identityCardVerificationPath(schoolCode,card.serial)}?sig=${identityCardSignature(card)}`;}
export function verifyIdentityCardSignature(card:Pick<CardRow,"schoolId"|"serial"|"personType"|"issuedAt"|"expiresAt"|"version">,supplied:string){const normalized=supplied.trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(normalized))return false;const expected=identityCardSignature(card);return timingSafeEqual(Buffer.from(expected),Buffer.from(normalized));}
function expiry(from:Date){const value=new Date(from);value.setUTCMonth(value.getUTCMonth()+DEFAULT_VALIDITY_MONTHS);return value;}
function cleanCode(value:string){return value.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,20)||"SCHOOL";}
function serial(schoolCode:string,kind:IdentityCardKind){return `SNV-${cleanCode(schoolCode)}-${kind==="student"?"ST":"SF"}-${randomBytes(8).toString("hex").toUpperCase()}`;}
async function allocateSerial(tx:TenantDb,schoolId:string,schoolCode:string,kind:IdentityCardKind){for(let i=0;i<8;i+=1){const value=serial(schoolCode,kind);const hit=await tx.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "IdentityCard" WHERE "schoolId"=$1 AND "serial"=$2 LIMIT 1`,schoolId,value);if(!hit[0])return value;}throw new AppError("Unable to allocate a unique identity card number.",500,"CARD_SERIAL_ALLOCATION_FAILED");}
async function insertCard(tx:TenantDb,schoolId:string,schoolCode:string,kind:IdentityCardKind,personId:string,now:Date){const id=`ic_${randomBytes(12).toString("hex")}`;const value=await allocateSerial(tx,schoolId,schoolCode,kind);const expiresAt=expiry(now);if(kind==="student")await tx.$queryRawUnsafe(`INSERT INTO "IdentityCard" ("id","schoolId","personType","studentId","serial","issuedAt","expiresAt","status","version","createdAt","updatedAt") VALUES ($1,$2,'student',$3,$4,$5,$6,'active',1,$5,$5)`,id,schoolId,personId,value,now,expiresAt);else await tx.$queryRawUnsafe(`INSERT INTO "IdentityCard" ("id","schoolId","personType","staffId","serial","issuedAt","expiresAt","status","version","createdAt","updatedAt") VALUES ($1,$2,'staff',$3,$4,$5,$6,'active',1,$5,$5)`,id,schoolId,personId,value,now,expiresAt);return{id,serial:value};}
async function staffPeople(tx:TenantDb,schoolId:string){return tx.$queryRawUnsafe<Array<{id:string;name:string}>>(`SELECT u."id",u."name" FROM "User" u WHERE u."schoolId"=$1 AND u."status"='active' AND EXISTS (SELECT 1 FROM "UserRole" ur JOIN "Role" r ON r."id"=ur."roleId" AND r."schoolId"=ur."schoolId" WHERE ur."schoolId"=$1 AND ur."userId"=u."id" AND r."name" NOT IN ('Parent','Student')) ORDER BY u."name" COLLATE "C"`,schoolId);}
export async function ensureIdentityCardsForSchool(tx:TenantDb,schoolId:string,schoolCode:string,actorId="system"){await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`identity-cards:${schoolId}`}))`;const[students,staff,existing]=await Promise.all([tx.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "Student" WHERE "schoolId"=$1 AND "status"='active'`,schoolId),staffPeople(tx,schoolId),tx.$queryRawUnsafe<Array<{id:string;personType:IdentityCardKind;studentId:string|null;staffId:string|null}>>(`SELECT "id","personType","studentId","staffId" FROM "IdentityCard" WHERE "schoolId"=$1 AND "status"='active'`,schoolId)]);const studentSet=new Set(students.map((row)=>row.id));const staffSet=new Set(staff.map((row)=>row.id));const stale=existing.filter((row)=>row.personType==='student'?(!row.studentId||!studentSet.has(row.studentId)):(!row.staffId||!staffSet.has(row.staffId)));const now=new Date();for(const card of stale)await tx.$executeRawUnsafe(`UPDATE "IdentityCard" SET "status"='revoked',"version"="version"+1,"updatedAt"=$3 WHERE "schoolId"=$1 AND "id"=$2 AND "status"='active'`,schoolId,card.id,now);const studentCardSet=new Set(existing.filter(r=>r.personType==='student'&&r.studentId&&studentSet.has(r.studentId)).map(r=>r.studentId));const staffCardSet=new Set(existing.filter(r=>r.personType==='staff'&&r.staffId&&staffSet.has(r.staffId)).map(r=>r.staffId));let created=0;for(const student of students)if(!studentCardSet.has(student.id)){await insertCard(tx,schoolId,schoolCode,"student",student.id,now);created+=1;}for(const staffMember of staff)if(!staffCardSet.has(staffMember.id)){await insertCard(tx,schoolId,schoolCode,"staff",staffMember.id,now);created+=1;}if((created||stale.length)&&actorId!=="system")await appendSchoolAudit(tx,{schoolId,actorId,action:"identity_cards.reconciled",entityType:"IdentityCard",entityId:`${schoolId}:${now.toISOString()}`,after:{created,revokedStale:stale.length,activeStudents:students.length,activeStaff:staff.length}});return{created,revokedStale:stale.length,totalPeople:students.length+staff.length};}
export async function listIdentityCards(tx:TenantDb,schoolId:string,schoolCode:string,actorId:string){await ensureIdentityCardsForSchool(tx,schoolId,schoolCode,actorId);const rows=await tx.$queryRawUnsafe<CardRow[]>(`SELECT * FROM (SELECT c."id",c."schoolId",c."personType",c."studentId",c."staffId",c."serial",c."issuedAt",c."expiresAt",c."status",c."version",COALESCE(s."name",u."name") AS "personName",s."admissionNo",cl."name" AS "className",CASE WHEN c."personType"='staff' THEN (SELECT r."name" FROM "UserRole" ur JOIN "Role" r ON r."id"=ur."roleId" AND r."schoolId"=ur."schoolId" WHERE ur."schoolId"=c."schoolId" AND ur."userId"=u."id" ORDER BY r."name" LIMIT 1) ELSE NULL END AS "roleName",s."photoUrl" FROM "IdentityCard" c LEFT JOIN "Student" s ON s."id"=c."studentId" AND s."schoolId"=c."schoolId" LEFT JOIN "Class" cl ON cl."id"=s."classId" AND cl."schoolId"=c."schoolId" LEFT JOIN "User" u ON u."id"=c."staffId" AND u."schoolId"=c."schoolId" WHERE c."schoolId"=$1) cards ORDER BY "personType", "personName" COLLATE "C"`,schoolId);const now=Date.now();return rows.map(row=>({...row,isExpired:row.expiresAt.getTime()<=now||row.status!=="active"}));}
export async function getIdentityCardsByScope(tx:TenantDb,schoolId:string,schoolCode:string,scope:IdentityCardScope,ids:string[]=[],actorId:string){const all=await listIdentityCards(tx,schoolId,schoolCode,actorId);if(scope==='all')return all;if(scope==='student'||scope==='staff')return all.filter(r=>r.personType===scope);if(scope==='selected'){const wanted=new Set(ids);return all.filter(r=>wanted.has(r.id));}throw new AppError("Unknown identity-card scope.",400,"INVALID_SCOPE");}
function photoData(value:string|null){if(!value?.startsWith("data:"))return null;const m=value.match(/^data:(image\/(?:png|jpeg|jpg));base64,(.+)$/i);return m?{mime:m[1].toLowerCase(),bytes:Buffer.from(m[2],"base64")}:null;}
function hexColor(value:string|undefined,fallback:[number,number,number]){const m=value?.match(/^#?([0-9a-f]{6})$/i);return m?rgb(parseInt(m[1].slice(0,2),16)/255,parseInt(m[1].slice(2,4),16)/255,parseInt(m[1].slice(4,6),16)/255):rgb(...fallback);}
function palette(value:unknown){const row=value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};return{primary:hexColor(typeof row.primary==='string'?row.primary:typeof row.primaryColor==='string'?row.primaryColor:undefined,[.06,.16,.26]),accent:hexColor(typeof row.accent==='string'?row.accent:typeof row.secondary==='string'?row.secondary:undefined,[.85,.65,.12])};}
function fitText(p:PDFPage,f:PDFFont,t:string,x:number,y:number,w:number,size:number,c:ReturnType<typeof rgb>){let s=size;while(s>5&&f.widthOfTextAtSize(t,s)>w)s-=.25;p.drawText(t,{x,y,size:s,font:f,color:c,maxWidth:w});}
function initials(n:string){return n.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()||'').join('')||'SN';}
function qrMatrix(v:string){const raw=encodeQR(v,'raw',{ecc:'high'}) as unknown;return Array.isArray(raw)?raw.map(r=>Array.isArray(r)?r:Array.from(r as ArrayLike<unknown>)):[];}
function drawQr(p:PDFPage,m:unknown[][],x:number,y:number,size:number,dark:ReturnType<typeof rgb>){const n=m.length;if(!n)return;const q=4,u=size/(n+q*2);p.drawRectangle({x,y,width:size,height:size,color:rgb(1,1,1)});for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(m[r]?.[c]===1||m[r]?.[c]===true||m[r]?.[c]==='1')p.drawRectangle({x:x+(c+q)*u,y:y+(n-r-1+q)*u,width:u+.08,height:u+.08,color:dark});}
async function drawCard(doc:PDFDocument,p:PDFPage,card:CardRow,school:{name:string;uniqueCode:string;logoUrl:string|null;brandColors:unknown},origin:string,x:number,y:number){const{primary,accent}=palette(school.brandColors);const white=rgb(1,1,1),muted=rgb(.36,.42,.48),border=rgb(.83,.86,.9),light=rgb(.965,.975,.985),green=rgb(.08,.45,.24),dark=rgb(.055,.12,.18),red=rgb(.67,.12,.12),bold=await doc.embedFont(StandardFonts.HelveticaBold),regular=await doc.embedFont(StandardFonts.Helvetica);p.pushOperators(pushGraphicsState(),translate(x,y));p.drawRectangle({x:0,y:0,width:CARD_WIDTH,height:CARD_HEIGHT,color:white,borderColor:primary,borderWidth:.8});p.drawRectangle({x:0,y:CARD_HEIGHT-34,width:CARD_WIDTH,height:34,color:primary});p.drawRectangle({x:0,y:CARD_HEIGHT-38,width:CARD_WIDTH,height:4,color:accent});p.drawCircle({x:17,y:CARD_HEIGHT-17,size:10,color:accent});fitText(p,bold,initials(school.name),10,CARD_HEIGHT-19,14,5.5,primary);fitText(p,bold,school.name.toUpperCase(),33,CARD_HEIGHT-12.2,CARD_WIDTH-43,9.2,white);p.drawText(card.personType==='student'?'STUDENT IDENTIFICATION CARD':'STAFF IDENTIFICATION CARD',{x:33,y:CARD_HEIGHT-25,size:4.8,font:bold,color:accent,maxWidth:CARD_WIDTH-43});const px=8,py=28,pw=55,ph=68;p.drawRectangle({x:px,y:py,width:pw,height:ph,color:light,borderColor:accent,borderWidth:1});const photo=photoData(card.photoUrl);if(photo)try{const image=photo.mime.includes('png')?await doc.embedPng(photo.bytes):await doc.embedJpg(photo.bytes);const sc=Math.min(pw/image.width,ph/image.height);p.drawImage(image,{x:px+(pw-image.width*sc)/2,y:py+(ph-image.height*sc)/2,width:image.width*sc,height:image.height*sc});}catch{fitText(p,bold,initials(card.personName),15,py+28,40,20,primary);}else fitText(p,bold,initials(card.personName),15,py+28,40,20,primary);const dx=70;fitText(p,bold,card.personName,dx,CARD_HEIGHT-50,158,11,dark);p.drawLine({start:{x:dx,y:CARD_HEIGHT-55},end:{x:dx+72,y:CARD_HEIGHT-55},thickness:1.2,color:accent});p.drawText('IDENTIFICATION',{x:dx,y:CARD_HEIGHT-65,size:4.2,font:bold,color:muted});fitText(p,bold,card.personType==='student'?(card.admissionNo||card.serial):(card.roleName||'STAFF MEMBER'),dx,CARD_HEIGHT-74,158,7.3,primary);p.drawText(card.personType==='student'?'CLASS':'CARD SERIAL',{x:dx,y:CARD_HEIGHT-84,size:4.2,font:bold,color:muted});fitText(p,regular,card.personType==='student'?(card.className||'Not assigned'):card.serial,dx,CARD_HEIGHT-93,158,6.2,dark);p.drawRectangle({x:8,y:18,width:95,height:17,color:light,borderColor:border,borderWidth:.5});p.drawText('ISSUED',{x:12,y:28.4,size:3.4,font:bold,color:muted});p.drawText(card.issuedAt.toISOString().slice(0,10),{x:12,y:22,size:5.3,font:bold,color:primary});p.drawText('EXPIRES',{x:58,y:28.4,size:3.4,font:bold,color:muted});p.drawText(card.expiresAt.toISOString().slice(0,10),{x:58,y:22,size:5.3,font:bold,color:primary});const active=card.status==='active'&&card.expiresAt.getTime()>Date.now(),status=active?'ACTIVE':card.status==='revoked'?'REV... (truncated)