import { Prisma } from "@prisma/client";
import { createId } from "@paralleldrive/cuid2";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { TenantDb } from "./db";
import { appendSchoolAudit } from "./audit";
import { AppError, ForbiddenError } from "./errors";
import { hasPermission, requirePermission } from "./rbac";

export type DeductionInput = {
  label: string;
  type: "fixed" | "percent";
  value: number;
};

function money(value: number | string | Prisma.Decimal) {
  return new Prisma.Decimal(value.toString()).toDecimalPlaces(2);
}

function deductionSnapshot(gross: number, deductions: DeductionInput[]) {
  const grossAmount = money(gross);
  let totalDeductions = new Prisma.Decimal(0);
  const snapshot = deductions.map((row) => {
    if (!row.label.trim() || row.value < 0 || !Number.isFinite(row.value)) {
      throw new AppError("Invalid payroll deduction.", 400, "INVALID_DEDUCTION");
    }
    if (row.type === "percent" && row.value > 100) {
      throw new AppError("Percentage deductions cannot exceed 100%.", 400, "INVALID_DEDUCTION");
    }
    const value = new Prisma.Decimal(row.value.toString());
    const amount = row.type === "percent"
      ? grossAmount.mul(value).div(100).toDecimalPlaces(2)
      : value.toDecimalPlaces(2);
    if (amount.gt(grossAmount)) {
      throw new AppError("A payroll deduction cannot exceed gross salary.", 400, "INVALID_DEDUCTION");
    }
    totalDeductions = totalDeductions.add(amount);
    return {
      label: row.label.trim(),
      type: row.type,
      value: Number(value.toString()),
      amount: Number(amount.toString())
    };
  });
  if (totalDeductions.gt(grossAmount)) {
    throw new AppError("Total payroll deductions cannot exceed gross salary.", 400, "TOTAL_DEDUCTIONS_EXCEED_GROSS");
  }
  return snapshot;
}

async function payslipPdf(input: {
  schoolName: string;
  staffName: string;
  period: string;
  gross: number;
  deductions: Array<{ label: string; amount: number }>;
  net: number;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 420]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  page.drawText(input.schoolName, { x: 45, y: 370, size: 18, font: bold, color: rgb(0.05, 0.2, 0.42) });
  page.drawText("SukuuNova Payslip · " + input.period, { x: 45, y: 344, size: 11, font: regular });
  page.drawText("Staff: " + input.staffName, { x: 45, y: 310, size: 11, font: bold });
  page.drawText("Gross salary", { x: 45, y: 275, size: 10, font: regular });
  page.drawText("GHS " + input.gross.toFixed(2), { x: 410, y: 275, size: 10, font: bold });
  let y = 250;
  for (const row of input.deductions) {
    page.drawText(row.label.slice(0, 45), { x: 45, y, size: 9, font: regular });
    page.drawText("- GHS " + row.amount.toFixed(2), { x: 410, y, size: 9, font: regular });
    y -= 20;
  }
  page.drawText("Net pay", { x: 45, y: 85, size: 12, font: bold });
  page.drawText("GHS " + input.net.toFixed(2), { x: 410, y: 85, size: 12, font: bold });
  page.drawText("Generated by SukuuNova", { x: 45, y: 35, size: 8, font: regular });
  return Buffer.from(await pdf.save());
}

export async function setSalaryStructure(
  tx: TenantDb,
  input: {
    schoolId: string;
    actorId: string;
    staffId: string;
    grossSalary: number;
    deductions: DeductionInput[];
  }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  if (input.grossSalary <= 0 || !Number.isFinite(input.grossSalary)) {
    throw new AppError("Gross salary must be positive.", 400, "INVALID_SALARY");
  }
  const staff = await tx.user.findFirst({
    where: { id: input.staffId, schoolId: input.schoolId, status: "active" },
    select: { id: true }
  });
  if (!staff) throw new AppError("Staff account not found in this school.", 404, "STAFF_NOT_FOUND");

  const grossSalary = money(input.grossSalary);
  const snapshot = deductionSnapshot(input.grossSalary, input.deductions);
  const before = await tx.salaryStructure.findUnique({
    where: { schoolId_staffId: { schoolId: input.schoolId, staffId: input.staffId } }
  });
  const structure = await tx.salaryStructure.upsert({
    where: { schoolId_staffId: { schoolId: input.schoolId, staffId: input.staffId } },
    update: {
      grossSalary,
      deductions: snapshot
    },
    create: {
      schoolId: input.schoolId,
      staffId: input.staffId,
      grossSalary,
      deductions: snapshot
    }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: before ? "salary_structure.updated" : "salary_structure.created",
    entityType: "SalaryStructure",
    entityId: structure.id,
    before,
    after: structure
  });
  return structure;
}

export async function createPayrollRun(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; period: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(input.period)) {
    throw new AppError("Payroll period must use YYYY-MM.", 400, "INVALID_PAYROLL_PERIOD");
  }

  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`payroll-run:${input.schoolId}:${input.period}`}))`;
  const existing = await tx.payrollRun.findFirst({
    where: { schoolId: input.schoolId, period: input.period },
    select: { id: true, status: true }
  });
  if (existing) {
    throw new AppError(
      `A payroll run already exists for ${input.period}.`,
      409,
      "PAYROLL_RUN_ALREADY_EXISTS"
    );
  }

  const run = await tx.payrollRun.create({
    data: { schoolId: input.schoolId, period: input.period }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "payroll.created",
    entityType: "PayrollRun",
    entityId: run.id,
    after: { period: run.period, status: run.status }
  });
  return run;
}

export async function processPayrollRun(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; payrollRunId: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`payroll-process:${input.schoolId}:${input.payrollRunId}`}))`;

  const run = await tx.payrollRun.findFirst({
    where: { id: input.payrollRunId, schoolId: input.schoolId }
  });
  if (!run) throw new AppError("Payroll run not found in this school.", 404, "NOT_FOUND");
  if (run.status !== "draft") {
    throw new AppError("Only draft payroll runs can be processed.", 409, "INVALID_STATE");
  }

  const [structures, school] = await Promise.all([
    tx.salaryStructure.findMany({
      where: { schoolId: input.schoolId },
      include: { staff: true }
    }),
    tx.school.findFirst({ where: { id: input.schoolId }, select: { name: true } })
  ]);
  if (!school || structures.length === 0) {
    throw new AppError("Salary structures are required before processing.", 409, "NO_SALARY_STRUCTURES");
  }

  for (const structure of structures) {
    if (structure.staff.schoolId !== input.schoolId || structure.staff.status !== "active") continue;
    const grossAmount = money(structure.grossSalary);
    const source = Array.isArray(structure.deductions) ? structure.deductions as unknown as DeductionInput[] : [];
    const deductions = deductionSnapshot(Number(grossAmount.toString()), source);
    const totalDeductions = deductions.reduce((sum, row) => sum.plus(money(row.amount)), new Prisma.Decimal(0)).toDecimalPlaces(2);
    const netAmount = grossAmount.minus(totalDeductions);
    const net = netAmount.lt(0) ? new Prisma.Decimal(0) : netAmount.toDecimalPlaces(2);
    const id = createId();
    const pdfData = await payslipPdf({
      schoolName: school.name,
      staffName: structure.staff.name,
      period: run.period,
      gross: Number(grossAmount.toString()),
      deductions,
      net: Number(net.toString())
    });
    await tx.payslip.create({
      data: {
        id,
        schoolId: input.schoolId,
        payrollRunId: run.id,
        staffId: structure.staffId,
        gross: grossAmount,
        deductions,
        net,
        pdfUrl: "/api/phase2/payroll/payslips/" + id + "/pdf",
        pdfData
      }
    });
  }

  const updated = await tx.payrollRun.update({
    where: { id: run.id },
    data: { status: "processed", processedAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "payroll.processed",
    entityType: "PayrollRun",
    entityId: run.id,
    after: { period: run.period, payslips: structures.filter((structure) => structure.staff.schoolId === input.schoolId && structure.staff.status === "active").length }
  });
  return updated;
}

export async function markPayrollPaid(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; payrollRunId: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`payroll-pay:${input.schoolId}:${input.payrollRunId}`}))`;

  const run = await tx.payrollRun.findFirst({ where: { id: input.payrollRunId, schoolId: input.schoolId } });
  if (!run || run.status !== "processed") {
    throw new AppError("Only processed payroll can be marked paid.", 409, "INVALID_STATE");
  }
  const updated = await tx.payrollRun.update({
    where: { id: run.id },
    data: { status: "paid", paidAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "payroll.paid",
    entityType: "PayrollRun",
    entityId: run.id,
    before: { status: run.status },
    after: { status: updated.status }
  });
  return updated;
}

export async function visiblePayslips(
  tx: TenantDb,
  input: { schoolId: string; userId: string }
) {
  if (await hasPermission(tx, input.userId, "payroll:manage")) {
    return tx.payslip.findMany({
      where: { schoolId: input.schoolId },
      include: { staff: { select: { id: true, name: true } }, payrollRun: true },
      orderBy: { createdAt: "desc" }
    });
  }
  await requirePermission(tx, input.userId, "payroll:view_own");
  return tx.payslip.findMany({
    where: { schoolId: input.schoolId, staffId: input.userId },
    include: { payrollRun: true },
    orderBy: { createdAt: "desc" }
  });
}

export async function getVisiblePayslipPdf(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; payslipId: string }
) {
  const payslip = await tx.payslip.findFirst({
    where: { id: input.payslipId, schoolId: input.schoolId }
  });
  if (!payslip?.pdfData) throw new AppError("Payslip PDF not found.", 404, "NOT_FOUND");
  const manager = await hasPermission(tx, input.actorId, "payroll:manage");
  const own = await hasPermission(tx, input.actorId, "payroll:view_own");
  if (!manager && (!own || payslip.staffId !== input.actorId)) {
    throw new ForbiddenError("A staff member may view only their own payslips.");
  }
  return { ...payslip, pdfData: payslip.pdfData };
}