import { Prisma } from "@prisma/client";
import { createId } from "@paralleldrive/cuid2";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { TenantDb } from "./db";
import { appendSchoolAudit } from "./audit";
import { AppError, ForbiddenError } from "./errors";
import { hasPermission, requirePermission } from "./rbac";

export type DeductionInput = {
  label: string;
  type: "fixed" | "percent";
  value: number;
};

function deductionSnapshot(gross: number, deductions: DeductionInput[]) {
  return deductions.map((row) => {
    if (!row.label.trim() || row.value < 0) {
      throw new AppError("Invalid payroll deduction.", 400, "INVALID_DEDUCTION");
    }
    const amount = row.type === "percent"
      ? gross * row.value / 100
      : row.value;
    return {
      label: row.label.trim(),
      type: row.type,
      value: row.value,
      amount: Math.round(amount * 100) / 100
    };
  });
}

async function payslipPdf(input: {
  schoolName: string;
  staffName: string;
  period: string;
  gross: number;
  deductions: Array<{ label: string; amount: number }>;
  net: number;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 420]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  page.drawText(input.schoolName, { x: 45, y: 370, size: 18, font: bold, color: rgb(0.05, 0.2, 0.42) });
  page.drawText("SukuuNova Payslip · " + input.period, { x: 45, y: 344, size: 11, font: regular });
  page.drawText("Staff: " + input.staffName, { x: 45, y: 310, size: 11, font: bold });
  page.drawText("Gross salary", { x: 45, y: 275, size: 10, font: regular });
  page.drawText("GHS " + input.gross.toFixed(2), { x: 410, y: 275, size: 10, font: bold });
  let y = 250;
  for (const row of input.deductions) {
    page.drawText(row.label.slice(0, 45), { x: 45, y, size: 9, font: regular });
    page.drawText("- GHS " + row.amount.toFixed(2), { x: 410, y, size: 9, font: regular });
    y -= 20;
  }
  page.drawText("Net pay", { x: 45, y: 85, size: 12, font: bold });
  page.drawText("GHS " + input.net.toFixed(2), { x: 410, y: 85, size: 12, font: bold });
  page.drawText("Generated by SukuuNova", { x: 45, y: 35, size: 8, font: regular });
  return Buffer.from(await pdf.save());
}

export async function setSalaryStructure(
  tx: TenantDb,
  input: {
    schoolId: string;
    actorId: string;
    staffId: string;
    grossSalary: number;
    deductions: DeductionInput[];
  }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  if (input.grossSalary <= 0) {
    throw new AppError("Gross salary must be positive.", 400, "INVALID_SALARY");
  }
  const snapshot = deductionSnapshot(input.grossSalary, input.deductions);
  const before = await tx.salaryStructure.findUnique({
    where: { schoolId_staffId: { schoolId: input.schoolId, staffId: input.staffId } }
  });
  const structure = await tx.salaryStructure.upsert({
    where: { schoolId_staffId: { schoolId: input.schoolId, staffId: input.staffId } },
    update: {
      grossSalary: new Prisma.Decimal(input.grossSalary),
      deductions: snapshot
    },
    create: {
      schoolId: input.schoolId,
      staffId: input.staffId,
      grossSalary: new Prisma.Decimal(input.grossSalary),
      deductions: snapshot
    }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: before ? "salary_structure.updated" : "salary_structure.created",
    entityType: "SalaryStructure",
    entityId: structure.id,
    before,
    after: structure
  });
  return structure;
}

export async function createPayrollRun(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; period: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(input.period)) {
    throw new AppError("Payroll period must use YYYY-MM.", 400, "INVALID_PAYROLL_PERIOD");
  }
  return tx.payrollRun.create({
    data: { schoolId: input.schoolId, period: input.period }
  });
}

export async function processPayrollRun(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; payrollRunId: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  const run = await tx.payrollRun.findUnique({ where: { id: input.payrollRunId } });
  if (!run) throw new AppError("Payroll run not found.", 404, "NOT_FOUND");
  if (run.status !== "draft") {
    throw new AppError("Only draft payroll runs can be processed.", 409, "INVALID_STATE");
  }
  const [structures, school] = await Promise.all([
    tx.salaryStructure.findMany({ include: { staff: true } }),
    tx.school.findFirst({ select: { name: true } })
  ]);
  if (!school || structures.length === 0) {
    throw new AppError("Salary structures are required before processing.", 409, "NO_SALARY_STRUCTURES");
  }
  for (const structure of structures) {
    const gross = Number(structure.grossSalary);
    const source = structure.deductions as unknown as DeductionInput[];
    const deductions = deductionSnapshot(gross, source);
    const totalDeductions = deductions.reduce((sum, row) => sum + row.amount, 0);
    const net = Math.max(0, Math.round((gross - totalDeductions) * 100) / 100);
    const id = createId();
    const pdfData = await payslipPdf({
      schoolName: school.name,
      staffName: structure.staff.name,
      period: run.period,
      gross,
      deductions,
      net
    });
    await tx.payslip.create({
      data: {
        id,
        schoolId: input.schoolId,
        payrollRunId: run.id,
        staffId: structure.staffId,
        gross: new Prisma.Decimal(gross),
        deductions,
        net: new Prisma.Decimal(net),
        pdfUrl: "/api/phase2/payroll/payslips/" + id + "/pdf",
        pdfData
      }
    });
  }
  const updated = await tx.payrollRun.update({
    where: { id: run.id },
    data: { status: "processed", processedAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "payroll.processed",
    entityType: "PayrollRun",
    entityId: run.id,
    after: { period: run.period, payslips: structures.length }
  });
  return updated;
}

export async function markPayrollPaid(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; payrollRunId: string }
) {
  await requirePermission(tx, input.actorId, "payroll:manage");
  const run = await tx.payrollRun.findUnique({ where: { id: input.payrollRunId } });
  if (!run || run.status !== "processed") {
    throw new AppError("Only processed payroll can be marked paid.", 409, "INVALID_STATE");
  }
  const updated = await tx.payrollRun.update({
    where: { id: run.id },
    data: { status: "paid", paidAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "payroll.paid",
    entityType: "PayrollRun",
    entityId: run.id,
    before: { status: run.status },
    after: { status: updated.status }
  });
  return updated;
}

export async function visiblePayslips(tx: TenantDb, userId: string) {
  if (await hasPermission(tx, userId, "payroll:manage")) {
    return tx.payslip.findMany({
      include: { staff: { select: { id: true, name: true } }, payrollRun: true },
      orderBy: { createdAt: "desc" }
    });
  }
  await requirePermission(tx, userId, "payroll:view_own");
  return tx.payslip.findMany({
    where: { staffId: userId },
    include: { payrollRun: true },
    orderBy: { createdAt: "desc" }
  });
}

export async function getVisiblePayslipPdf(
  tx: TenantDb,
  input: { actorId: string; payslipId: string }
) {
  const payslip = await tx.payslip.findUnique({ where: { id: input.payslipId } });
  if (!payslip?.pdfData) throw new AppError("Payslip PDF not found.", 404, "NOT_FOUND");
  const manager = await hasPermission(tx, input.actorId, "payroll:manage");
  const own = await hasPermission(tx, input.actorId, "payroll:view_own");
  if (!manager && (!own || payslip.staffId !== input.actorId)) {
    throw new ForbiddenError("A staff member may view only their own payslips.");
  }
  return { ...payslip, pdfData: payslip.pdfData };
}
