import { randomInt } from "node:crypto";
import type { ArcadeResponseQuestion } from "./arcade-response-content";

export type ReadingQuestQuestion = ArcadeResponseQuestion & {
  scene: { cue: string; meterLabels: string[] };
};

type ReadingRow = {
  minDifficulty: number;
  passage: string;
  prompt: string;
  answer: string;
  wrong: readonly [string, string, string];
  explanation: string;
  focus: readonly string[];
};

const READING_BANK: readonly ReadingRow[] = [
  { minDifficulty: 1, passage: "Kofi left home with a dry shirt. By the time he reached school, drops of water covered his shoulders and he shook out his umbrella at the doorway.", prompt: "What most likely happened on Kofi's way to school?", answer: "It rained", wrong: ["He went swimming", "He washed his shirt", "The classroom flooded"], explanation: "The wet shoulders and umbrella are evidence that rain fell during the journey.", focus: ["Inference", "Evidence"] },
  { minDifficulty: 1, passage: "Adwoa placed two bowls outside. One was under the roof and one was in the open yard. After the storm, only the bowl in the yard contained water.", prompt: "Why was the yard bowl useful in the observation?", answer: "It collected rain directly", wrong: ["It made the roof larger", "It stopped the storm", "It dried the other bowl"], explanation: "The uncovered bowl could receive rainfall directly, unlike the bowl protected by the roof.", focus: ["Cause + effect", "Observation"] },
  { minDifficulty: 1, passage: "The notice beside the library door reads: 'Quiet study from 2:00–4:00. Group discussions should use the courtyard.'", prompt: "What should a group do at 3:00 if they need to discuss a project?", answer: "Use the courtyard", wrong: ["Talk loudly in the library", "Wait beside the shelves", "Close the library"], explanation: "The notice directs group discussions to the courtyard during quiet-study time.", focus: ["Explicit detail", "Instructions"] },
  { minDifficulty: 1, passage: "Mansa watered one seedling every morning but forgot the second seedling for several days. The first stayed firm and green while the second began to droop.", prompt: "Which idea is best supported by the passage?", answer: "Regular watering helped the first seedling", wrong: ["Plants never need sunlight", "Drooping always means too much water", "Both seedlings received equal care"], explanation: "The main difference described is regular watering, and the watered seedling stayed healthy.", focus: ["Comparison", "Evidence"] },
  { minDifficulty: 1, passage: "Yaw packed his football boots, water bottle and team jersey before leaving home early on Saturday.", prompt: "Where is Yaw most likely going?", answer: "To a football activity", wrong: ["To a swimming lesson", "To a library meeting", "To repair a computer"], explanation: "Football boots and a team jersey strongly suggest a football activity.", focus: ["Inference", "Key details"] },
  { minDifficulty: 1, passage: "The market seller moved the ripe tomatoes into the shade when the afternoon sun became very hot.", prompt: "What was the seller most likely trying to do?", answer: "Protect the tomatoes from too much heat", wrong: ["Make the sun brighter", "Turn the tomatoes green", "Stop customers entering the market"], explanation: "Moving produce into shade during strong heat is a protective action.", focus: ["Purpose", "Context"] },
  { minDifficulty: 1, passage: "The class cleaned the playground, separated plastic bottles into a sack and placed leaves in a compost pile.", prompt: "What is the main idea?", answer: "The class sorted waste while cleaning", wrong: ["The class planted only flowers", "The playground was closed forever", "Plastic bottles were used as food"], explanation: "The actions describe cleaning and separating different kinds of waste.", focus: ["Main idea", "Summary"] },
  { minDifficulty: 1, passage: "Abena checked the timetable twice, then hurried to the science room with her notebook five minutes before the bell.", prompt: "What does Abena's behaviour suggest?", answer: "She wanted to arrive prepared and on time", wrong: ["She wanted to miss science", "She had lost her notebook", "The timetable had no lessons"], explanation: "Checking the timetable and arriving early are signs of preparation and punctuality.", focus: ["Character inference", "Evidence"] },
  { minDifficulty: 1, passage: "A sign near the tap says, 'Turn me off tightly after use.' Kojo notices a slow drip after washing his hands.", prompt: "What action best follows the sign?", answer: "Close the tap properly", wrong: ["Leave the water running", "Break the tap handle", "Cover the sign"], explanation: "The instruction asks users to stop water flow after using the tap.", focus: ["Instructions", "Responsible action"] },
  { minDifficulty: 1, passage: "Esi borrowed a novel on Monday. She read ten pages each evening and finished it before the Friday return date.", prompt: "What helped Esi finish before Friday?", answer: "She read a little each evening", wrong: ["She returned it on Monday", "She skipped every page", "The book became shorter"], explanation: "Regular daily reading allowed her to make steady progress before the deadline.", focus: ["Sequence", "Cause + effect"] },
  { minDifficulty: 1, passage: "The school garden soil was dry in the morning. After a long shower, the soil became dark and soft.", prompt: "Which event caused the change in the soil?", answer: "The shower", wrong: ["The morning bell", "A new timetable", "A football match"], explanation: "The passage directly links the long shower with the soil becoming wet and soft.", focus: ["Cause + effect", "Explicit detail"] },
  { minDifficulty: 1, passage: "Kwame wrote each homework task in a small notebook as the teachers announced it. At home he checked the list before packing his bag.", prompt: "Why did Kwame keep the list?", answer: "To remember and organise his tasks", wrong: ["To make homework disappear", "To avoid taking any books", "To change the school timetable"], explanation: "Recording and checking tasks is an organisation strategy.", focus: ["Purpose", "Summary"] },
  { minDifficulty: 2, passage: "The community clinic introduced numbered cards for patients. Before the change, people often argued about who arrived first. Afterwards, the waiting line became calmer.", prompt: "What problem did the numbered cards mainly address?", answer: "Uncertainty about the order of patients", wrong: ["A shortage of medicine", "The size of the clinic building", "The weather outside"], explanation: "The before-and-after details connect the cards with clearer waiting order.", focus: ["Problem + solution", "Evidence"] },
  { minDifficulty: 2, passage: "Nana compared two phone plans. Plan A had a lower monthly fee but charged more for extra data. Plan B cost more each month but included more data. Nana uses very little data.", prompt: "Which fact matters most to Nana's choice?", answer: "She uses very little data", wrong: ["Both plans use phones", "Plan B has a higher monthly fee", "The plans have different names"], explanation: "Low data use makes the lower fixed cost especially relevant to her needs.", focus: ["Relevant evidence", "Decision"] },
  { minDifficulty: 2, passage: "A school report shows 120 books borrowed in January and 180 in February after a reading campaign began. The report does not measure why each learner borrowed a book.", prompt: "Which conclusion is supported without claiming too much?", answer: "More books were borrowed in February", wrong: ["The campaign definitely caused every extra loan", "Every learner borrowed a book", "Borrowing fell by sixty books"], explanation: "The figures show an increase, but they do not prove the reason for every loan.", focus: ["Data evidence", "Careful conclusion"] },
  { minDifficulty: 2, passage: "Before the debate, Akosua wrote down the other team's strongest point beside her own response. During the debate she answered that point directly.", prompt: "What strategy did Akosua use?", answer: "She anticipated an opposing argument", wrong: ["She ignored the other team", "She changed the debate topic", "She memorised only the title"], explanation: "Identifying a likely opposing point and preparing a response is anticipation of a counterargument.", focus: ["Strategy", "Inference"] },
  { minDifficulty: 2, passage: "The bus normally leaves at 6:30. A notice says roadworks will add about twenty minutes to Monday's journey. Sena has an appointment at the usual arrival time.", prompt: "What is the most sensible plan for Sena?", answer: "Allow extra travel time", wrong: ["Leave later than usual", "Ignore the notice", "Assume the roadworks shorten the trip"], explanation: "The notice predicts a delay, so extra travel time reduces the risk of arriving late.", focus: ["Applying information", "Planning"] },
  { minDifficulty: 2, passage: "A paragraph first describes a blocked drain, then explains how volunteers removed plastic waste, and ends by noting that rainwater flowed freely afterwards.", prompt: "How is the paragraph mainly organised?", answer: "Problem, action, result", wrong: ["Question, joke, recipe", "Alphabetical order", "Two unrelated descriptions"], explanation: "The sequence moves from a problem to an intervention and then its result.", focus: ["Text structure", "Sequence"] },
  { minDifficulty: 3, passage: "An article says a new study corner 'transformed learning overnight.' The same article later reports that exam scores rose gradually over two terms and that several tutoring sessions also began.", prompt: "Why should the phrase 'transformed learning overnight' be treated cautiously?", answer: "Other changes occurred and the improvement was gradual", wrong: ["Exam scores can never change", "Study corners are always harmful", "Two terms means one night"], explanation: "The later evidence shows a gradual change with multiple possible influences, so the dramatic phrase overstates certainty.", focus: ["Author claim", "Evidence quality"] },
  { minDifficulty: 3, passage: "Two witnesses describe the same power outage. One says the lights failed just after heavy rain began; the other says the lights flickered earlier in the evening. Neither saw the cause of the outage.", prompt: "Which statement is best supported?", answer: "The accounts differ about timing and do not prove the cause", wrong: ["Heavy rain certainly caused the outage", "Both witnesses gave identical accounts", "The outage happened before evening"], explanation: "The witnesses provide different timing details and neither directly observed causation.", focus: ["Compare sources", "Evidence limits"] },
  { minDifficulty: 3, passage: "A student survey found that most respondents preferred a later sports period. Only 40 of the school's 600 learners completed the voluntary survey.", prompt: "What limitation should be considered before generalising the result?", answer: "The small voluntary sample may not represent the whole school", wrong: ["Surveys cannot contain numbers", "Sports periods never change", "Six hundred learners answered"], explanation: "A small self-selected group can differ from the wider population.", focus: ["Source evaluation", "Sampling"] },
  { minDifficulty: 3, passage: "The writer describes the old tree as 'a patient guard beside the gate,' then explains that generations of pupils met beneath it before assembly.", prompt: "What effect does the phrase 'patient guard' create?", answer: "It gives the tree a protective, enduring character", wrong: ["It proves the tree can speak", "It shows the gate is new", "It means pupils feared the tree"], explanation: "The figurative description presents the tree as steady and watchful over time.", focus: ["Figurative language", "Author effect"] },
  { minDifficulty: 4, passage: "A proposal argues that extending library hours will improve results because high-performing schools often keep libraries open later. It provides no data showing that the longer hours caused those schools' results.", prompt: "What is the main weakness in the argument?", answer: "It treats an association as proof of cause", wrong: ["It uses the word library", "It compares more than one school", "It mentions academic results"], explanation: "The proposal assumes causation from correlation without evidence that longer hours produced the results.", focus: ["Argument", "Causation"] },
  { minDifficulty: 4, passage: "A news summary says a programme was 'widely successful.' The linked report shows strong gains in two districts, no clear change in three, and does not include four districts that joined late.", prompt: "Which reading of the summary is most defensible?", answer: "The word 'widely' is broader than the available evidence supports", wrong: ["The report proves failure everywhere", "Two districts are the entire programme", "Missing districts must have improved"], explanation: "The evidence is mixed and incomplete, so a broad success claim needs qualification.", focus: ["Synthesis", "Claim strength"] },
  { minDifficulty: 5, passage: "An editorial recommends banning phones during every school activity. Its evidence comes from one classroom where off-task behaviour fell after phones were collected, but the editorial does not examine lessons that intentionally use phones for research or accessibility.", prompt: "Which critique best evaluates the editorial's reasoning?", answer: "Its evidence is too narrow for the universal recommendation", wrong: ["One classroom can never provide useful evidence", "Research activities should always use phones", "Off-task behaviour is unrelated to learning"], explanation: "The evidence may be relevant, but it does not cover all activities addressed by the universal policy claim.", focus: ["Argument scope", "Counterexample"] },
  { minDifficulty: 5, passage: "A historical account written decades later describes a protest as completely peaceful. Contemporary newspaper reports mention several confrontations, while police records from the period are incomplete and may reflect official bias.", prompt: "What is the strongest approach to interpreting these sources?", answer: "Compare the sources while considering each source's limits and perspective", wrong: ["Accept the latest account automatically", "Reject every newspaper report automatically", "Treat incomplete police records as perfectly neutral"], explanation: "Historical interpretation is stronger when multiple sources are compared and their context, gaps and possible bias are considered.", focus: ["Source evaluation", "Perspective"] },
];

function shuffle<T>(values: readonly T[]): T[] {
  const output = [...values];
  for (let index = output.length - 1; index > 0; index -= 1) {
    const swap = randomInt(index + 1);
    [output[index], output[swap]] = [output[swap], output[index]];
  }
  return output;
}

export function createReadingQuestQuestions(difficulty: number, length: number): ReadingQuestQuestion[] {
  const safeDifficulty = Math.max(1, Math.min(5, Math.trunc(difficulty)));
  const desired = Math.max(1, Math.min(15, Math.trunc(length)));
  const eligible = READING_BANK.filter((row) => row.minDifficulty <= Math.min(5, safeDifficulty + 1));
  const selected: ReadingRow[] = [];
  let pool = shuffle(eligible);
  while (selected.length < desired) {
    if (!pool.length) pool = shuffle(eligible);
    selected.push(pool.pop()!);
  }
  return selected.map((row, index) => ({
    id: String(index),
    kind: "path",
    prompt: row.prompt,
    options: shuffle([row.answer, ...row.wrong]),
    answer: row.answer,
    explanation: row.explanation,
    scene: { cue: row.passage, meterLabels: [...row.focus] },
  }));
}
