import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { TenantDb } from "./db";
import { appendSchoolAudit } from "./audit";
import { AppError, ForbiddenError } from "./errors";
import { hasPermission, requirePermission } from "./rbac";
import { enqueueSms } from "./sms-outbox";

type SubjectResult = {
  subject: string;
  ca: number | null;
  exam: number | null;
  total: number;
};

async function reportData(tx: TenantDb, studentId: string, termId: string) {
  const [student, term, settings, school] = await Promise.all([
    tx.student.findUnique({ where: { id: studentId }, include: { class: true } }),
    tx.term.findUnique({ where: { id: termId } }),
    tx.schoolSettings.findFirst(),
    tx.school.findFirst()
  ]);
  if (!student || !term || !settings || !school) {
    throw new AppError("Report-card context is incomplete.", 404, "NOT_FOUND");
  }
  if (!student.classId) throw new AppError("Student has no class assignment.", 409, "NO_CLASS");

  const assessments = await tx.assessment.findMany({
    where: { termId, classId: student.classId },
    include: {
      subject: true,
      scores: { where: { studentId } }
    },
    orderBy: [{ subject: { name: "asc" } }, { type: "asc" }]
  });
  if (assessments.length === 0) {
    throw new AppError("No assessments exist for this report card.", 409, "NO_ASSESSMENTS");
  }
  const missing = assessments.filter((assessment) => assessment.scores.length === 0);
  if (missing.length > 0 && !settings.allowPartialReportCards) {
    throw new AppError(
      "Missing scores block report-card generation. Enable partial reports to override.",
      409,
      "MISSING_SCORES"
    );
  }

  const grouped = new Map<string, typeof assessments>();
  for (const assessment of assessments) {
    grouped.set(assessment.subject.name, [
      ...(grouped.get(assessment.subject.name) ?? []),
      assessment
    ]);
  }
  const results: SubjectResult[] = [];
  for (const [subject, rows] of grouped) {
    const average = (type: string) => {
      const typed = rows.filter((row) => row.type === type && row.scores[0]);
      if (typed.length === 0) return null;
      return typed.reduce(
        (sum, row) => sum + (Number(row.scores[0].value) / Number(row.maxScore)) * 100,
        0
      ) / typed.length;
    };
    const ca = average("ca");
    const exam = average("exam");
    const total =
      (ca ?? 0) * (Number(settings.gradeCaWeight) / 100) +
      (exam ?? 0) * (Number(settings.gradeExamWeight) / 100);
    results.push({ subject, ca, exam, total });
  }
  const attendance = await tx.attendanceEvent.findMany({
    where: {
      studentId,
      type: "in",
      attendanceDate: { gte: term.startDate, lte: term.endDate }
    },
    select: { attendanceDate: true, isLate: true }
  });
  return { student, term, settings, school, results, attendance };
}

async function makePdf(data: Awaited<ReturnType<typeof reportData>>, remarks?: string) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  page.drawText(data.school.name, { x: 50, y: 790, size: 20, font: bold, color: rgb(0.1, 0.2, 0.45) });
  page.drawText("SukuuNova Report Card", { x: 50, y: 765, size: 12, font: regular });
  page.drawText("Student: " + data.student.name, { x: 50, y: 730, size: 11, font: bold });
  page.drawText("Class: " + (data.student.class?.name ?? "Unassigned"), { x: 320, y: 730, size: 11, font: regular });
  page.drawText("Term: " + data.term.name, { x: 50, y: 710, size: 11, font: regular });
  page.drawText("Subject", { x: 50, y: 675, size: 10, font: bold });
  page.drawText("CA", { x: 310, y: 675, size: 10, font: bold });
  page.drawText("Exam", { x: 380, y: 675, size: 10, font: bold });
  page.drawText("Total", { x: 465, y: 675, size: 10, font: bold });
  let y = 653;
  for (const row of data.results.slice(0, 20)) {
    page.drawText(row.subject.slice(0, 36), { x: 50, y, size: 9, font: regular });
    page.drawText(row.ca === null ? "-" : row.ca.toFixed(1), { x: 310, y, size: 9, font: regular });
    page.drawText(row.exam === null ? "-" : row.exam.toFixed(1), { x: 380, y, size: 9, font: regular });
    page.drawText(row.total.toFixed(1), { x: 465, y, size: 9, font: bold });
    y -= 21;
  }
  const presentDays = new Set(data.attendance.map((row) => row.attendanceDate.toISOString().slice(0, 10))).size;
  const lateDays = data.attendance.filter((row) => row.isLate).length;
  page.drawText("Attendance: " + presentDays + " days present; " + lateDays + " late.", {
    x: 50, y: 190, size: 10, font: regular
  });
  page.drawText("Remarks: " + (remarks?.trim() || "—"), { x: 50, y: 165, size: 10, font: regular });
  page.drawText("Generated by SukuuNova", { x: 50, y: 60, size: 8, font: regular, color: rgb(0.4, 0.4, 0.4) });
  return Buffer.from(await pdf.save());
}

export async function generateReportCard(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; studentId: string; termId: string; remarks?: string }
) {
  await requirePermission(tx, input.actorId, "reports:generate");
  const existing = await tx.reportCard.findUnique({
    where: { studentId_termId: { studentId: input.studentId, termId: input.termId } }
  });
  if (existing && existing.status !== "draft") {
    throw new AppError("A submitted report card cannot be regenerated.", 409, "REPORT_LOCKED");
  }
  const data = await reportData(tx, input.studentId, input.termId);
  const pdfData = await makePdf(data, input.remarks);
  const report = await tx.reportCard.upsert({
    where: { studentId_termId: { studentId: input.studentId, termId: input.termId } },
    update: { pdfData, remarks: input.remarks },
    create: {
      schoolId: input.schoolId,
      studentId: input.studentId,
      termId: input.termId,
      pdfData,
      remarks: input.remarks,
      generatedPdfUrl: "/api/mvp/report-cards/pending/pdf"
    }
  });
  await tx.reportCard.update({
    where: { id: report.id },
    data: { generatedPdfUrl: "/api/mvp/report-cards/" + report.id + "/pdf" }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "report_card.generated",
    entityType: "ReportCard",
    entityId: report.id,
    after: { studentId: input.studentId, termId: input.termId }
  });
  return { ...report, generatedPdfUrl: "/api/mvp/report-cards/" + report.id + "/pdf" };
}

export async function submitReportCard(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; reportCardId: string }
) {
  await requirePermission(tx, input.actorId, "report_cards:submit");
  const report = await tx.reportCard.findUnique({
    where: { id: input.reportCardId },
    include: { student: { include: { class: true } } }
  });
  if (!report) throw new AppError("Report card not found.", 404, "NOT_FOUND");
  if (report.status !== "draft") throw new AppError("Only draft reports can be submitted.", 409, "INVALID_STATE");
  if (report.student.class?.classTeacherId !== input.actorId) {
    throw new ForbiddenError("Only the student's class teacher may submit this report.");
  }
  const updated = await tx.reportCard.update({
    where: { id: report.id },
    data: { status: "submitted", submittedBy: input.actorId, submittedAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId, actorId: input.actorId, action: "report_card.submitted",
    entityType: "ReportCard", entityId: report.id, before: { status: report.status }, after: { status: updated.status }
  });
  return updated;
}

export async function approveReportCard(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; reportCardId: string }
) {
  await requirePermission(tx, input.actorId, "report_cards:approve");
  const report = await tx.reportCard.findUnique({ where: { id: input.reportCardId } });
  if (!report) throw new AppError("Report card not found.", 404, "NOT_FOUND");
  if (report.status !== "submitted") throw new AppError("Only submitted reports can be approved.", 409, "INVALID_STATE");
  if (report.submittedBy === input.actorId) throw new ForbiddenError("The submitter cannot approve the same report.");
  const updated = await tx.reportCard.update({
    where: { id: report.id },
    data: { status: "approved", approvedBy: input.actorId, approvedAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId, actorId: input.actorId, action: "report_card.approved",
    entityType: "ReportCard", entityId: report.id, before: { status: report.status }, after: { status: updated.status }
  });
  return updated;
}

export async function sendReportCard(
  tx: TenantDb,
  input: { schoolId: string; actorId: string; reportCardId: string }
) {
  await requirePermission(tx, input.actorId, "report_cards:approve");
  const report = await tx.reportCard.findUnique({
    where: { id: input.reportCardId },
    include: {
      student: { include: { guardians: { where: { isPrimary: true }, include: { guardian: true } } } }
    }
  });
  if (!report) throw new AppError("Report card not found.", 404, "NOT_FOUND");
  if (report.status !== "approved") throw new AppError("Only approved reports can be sent.", 409, "INVALID_STATE");
  for (const link of report.student.guardians) {
    await enqueueSms(tx, {
      schoolId: input.schoolId,
      recipientType: "guardian",
      recipientId: link.guardianId,
      recipientPhone: link.guardian.phone,
      body: "SukuuNova: " + report.student.name + "'s approved report card is now available."
    });
  }
  const updated = await tx.reportCard.update({
    where: { id: report.id },
    data: { status: "sent", sentAt: new Date() }
  });
  await appendSchoolAudit(tx, {
    schoolId: input.schoolId,
    actorId: input.actorId,
    action: "report_card.sent",
    entityType: "ReportCard",
    entityId: report.id,
    before: { status: report.status },
    after: { status: updated.status }
  });
  return updated;
}

export async function getVisibleReportPdf(
  tx: TenantDb,
  input: { actorId: string; reportCardId: string }
) {
  const report = await tx.reportCard.findUnique({
    where: { id: input.reportCardId },
    include: {
      student: { include: { guardians: { include: { guardian: true } } } }
    }
  });
  if (!report?.pdfData) throw new AppError("Report PDF not found.", 404, "NOT_FOUND");
  if (await hasPermission(tx, input.actorId, "report_cards:view")) {
    const isParent = await hasPermission(tx, input.actorId, "parents:read_linked");
    if (!isParent) return report;
    const linked = report.student.guardians.some((link) => link.guardian.userId === input.actorId);
    if (linked && report.status === "sent") return report;
  }
  throw new ForbiddenError("This report card is not visible to this account.");
}
