import type { PermissionKey } from "./default-rbac";

const TEACHING: PermissionKey[] = ["students:read","attendance:record","attendance:view_own","scores:write:assigned","report_cards:submit","report_cards:view","exams:manage","exams:take","calendar:manage","parents:read_linked","offline:sync","risk_flags:view","ai_drafts:accept","payroll:view_own"];
const LEADERSHIP: PermissionKey[] = ["students:read","students:write","users:read","users:write","classes:manage","calendar:manage","attendance:record","attendance:view_own","attendance:pickup_approve","scores:write:all","report_cards:submit","report_cards:approve","report_cards:view","reports:generate","audit:read","visitors:log","templates:manage","transport:manage","transport:view","feeding:manage","exams:manage","exams:take","library:manage","library:borrow","assets:manage","fees:adjust","fees:approve","analytics:view","payroll:view_own","risk_flags:view","ai_drafts:accept"];
const FINANCE: PermissionKey[] = ["students:read","finance:read","finance:write","finance:approve","invoices:create","payments:record","fees:adjust","fees:approve","reports:generate","analytics:view","payroll:view_own"];
const PAYROLL: PermissionKey[] = ["users:read","payroll:view_own","payroll:manage","finance:read","reports:generate","analytics:view"];
const ADMIN: PermissionKey[] = ["students:read","students:write","users:read","users:write","reports:generate","calendar:manage","classes:manage","attendance:record","visitors:log","templates:manage","transport:view","feeding:manage","assets:manage","payroll:view_own"];

const MAP: Record<string, PermissionKey[]> = {
  "Principal / Headteacher": LEADERSHIP,
  "Principal": LEADERSHIP,
  "Vice Principal / Deputy Head": LEADERSHIP,
  "Vice Principal": LEADERSHIP,
  "Assistant Headteacher": ADMIN.concat(["scores:write:all","report_cards:approve","exams:manage","analytics:view"]),
  "Director of Studies / Academic Director": ADMIN.concat(["scores:write:all","report_cards:approve","exams:manage","analytics:view"]),
  "Head of Department": TEACHING.concat(["scores:write:all","report_cards:approve"]),
  "Academic Coordinator": TEACHING.concat(["scores:write:all","report_cards:approve","exams:manage","analytics:view"]),
  "School Operations Manager": ADMIN.concat(["transport:manage","transport:view","feeding:manage","assets:manage"]),
  Teacher: TEACHING,
  "Class Teacher": TEACHING,
  "Subject Teacher": TEACHING,
  "Assistant Teacher": ["students:read","attendance:record","attendance:view_own","parents:read_linked","payroll:view_own"],
  "Teaching Assistant": ["students:read","attendance:view_own","parents:read_linked","payroll:view_own"],
  "Trainee / Student Teacher": ["students:read","attendance:view_own","calendar:manage","payroll:view_own"],
  "Special Education / SEN Teacher": TEACHING,
  "Learning Support Assistant": ["students:read","attendance:view_own","parents:read_linked","risk_flags:view","payroll:view_own"],
  "Early Years / Nursery Teacher": TEACHING,
  "School Counsellor": ["students:read","attendance:view_own","parents:read_linked","risk_flags:view","reports:generate","payroll:view_own"],
  "School Nurse": ["students:read","attendance:view_own","risk_flags:view","reports:generate","payroll:view_own"],
  "Discipline Officer": ["students:read","attendance:view_own","risk_flags:view","reports:generate","payroll:view_own"],
  "Safeguarding / Child Protection Officer": ["students:read","attendance:view_own","risk_flags:view","audit:read","reports:generate","payroll:view_own"],
  Administrator: ADMIN,
  "School Secretary": ["students:read","students:write","users:read","reports:generate","calendar:manage","visitors:log","templates:manage","payroll:view_own"],
  "Receptionist / Front Desk": ["students:read","visitors:log","calendar:manage","templates:manage","payroll:view_own"],
  Registrar: ["students:read","students:write","reports:generate","payroll:view_own"],
  "Admissions Officer": ["students:read","students:write","reports:generate","payroll:view_own"],
  "Records / Data Officer": ["students:read","students:write","reports:generate","audit:read","analytics:view","payroll:view_own"],
  "Procurement Officer": ["finance:read","finance:write","assets:manage","reports:generate","payroll:view_own"],
  "Storekeeper / Stores Officer": ["assets:manage","reports:generate","payroll:view_own"],
  "Accountant / Bursar": FINANCE.concat(["payroll:manage"]),
  Accountant: FINANCE.concat(["payroll:manage"]),
  "Finance Officer": FINANCE,
  Cashier: ["students:read","finance:read","payments:record","invoices:create","payroll:view_own"],
  "Payroll Officer": PAYROLL,
  "Finance Clerk": ["finance:read","invoices:create","payments:record","payroll:view_own"],
  "HR Manager / Officer": PAYROLL.concat(["users:write","recruitment:manage"]),
  "HR Officer": PAYROLL.concat(["users:write","recruitment:manage"]),
  "HR Assistant": ["users:read","recruitment:manage","payroll:view_own"],
  "Recruitment Officer": ["users:read","recruitment:manage","reports:generate","payroll:view_own"],
  "ICT Manager / Coordinator": ["users:read","users:write","assets:manage","audit:read","analytics:view","payroll:view_own"],
  "Systems Administrator": ["users:read","users:write","assets:manage","audit:read","templates:manage","payroll:view_own"],
  "IT Support Technician": ["users:read","assets:manage","payroll:view_own"],
  "ICT / Computing Teacher": TEACHING,
  "Lab Assistant / Technician": ["students:read","assets:manage","calendar:manage","payroll:view_own"],
  Librarian: ["students:read","library:manage","library:borrow","reports:generate","payroll:view_own"],
  "Library Assistant": ["students:read","library:borrow","payroll:view_own"],
  "Resource Centre Coordinator": ["students:read","library:manage","library:borrow","assets:manage","payroll:view_own"],
  "Transport Manager": ["students:read","transport:manage","transport:view","assets:manage","reports:generate","payroll:view_own"],
  "Transport Coordinator": ["students:read","transport:manage","transport:view","reports:generate","payroll:view_own"],
  Driver: ["students:read","transport:view","offline:sync","payroll:view_own"],
  "Bus Attendant / Bus Monitor": ["students:read","transport:view","attendance:view_own","payroll:view_own"],
  "Security Supervisor": ["students:read","visitors:log","attendance:pickup_approve","risk_flags:view","reports:generate","payroll:view_own"],
  "Security Officer / Guard": ["students:read","visitors:log","attendance:pickup_approve","payroll:view_own"],
  "Gate Officer": ["visitors:log","attendance:pickup_approve","payroll:view_own"],
  "Safety / Compliance Officer": ["visitors:log","reports:generate","risk_flags:view","audit:read","payroll:view_own"],
  "Boarding Coordinator": ["students:read","attendance:record","reports:generate","risk_flags:view","payroll:view_own"],
  "House Parent / House Supervisor": ["students:read","attendance:record","risk_flags:view","payroll:view_own"],
  "Boarding Assistant": ["students:read","attendance:view_own","payroll:view_own"],
  "Catering Manager": ["students:read","feeding:manage","assets:manage","reports:generate","payroll:view_own"],
  "Head Cook / Chef": ["feeding:manage","payroll:view_own"],
  "Cook / Kitchen Staff": ["feeding:manage","payroll:view_own"],
  "Dining Hall Attendant": ["feeding:manage","attendance:view_own","payroll:view_own"],
  "Facilities Manager": ["assets:manage","reports:generate","payroll:view_own"],
  "Maintenance Technician": ["assets:manage","payroll:view_own"],
  "Electrician / Plumber / Tradesperson": ["assets:manage","payroll:view_own"],
  "Cleaner / Janitorial Staff": ["payroll:view_own"],
  "Groundskeeper / Compound Worker": ["assets:manage","payroll:view_own"],
  "Laundry / Housekeeping Staff": ["payroll:view_own"],
  "Communications Officer": ["templates:manage","broadcast:emergency_send","calendar:manage","reports:generate","payroll:view_own"],
  "Community / Parent Liaison Officer": ["parents:read_linked","templates:manage","calendar:manage","payroll:view_own"],
  "Events Coordinator": ["calendar:manage","templates:manage","reports:generate","payroll:view_own"]
};

export function staffRolePermissionKeys(roleName: string): readonly PermissionKey[] {
  return MAP[roleName] ?? ["payroll:view_own"];
}
