import { NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { createId } from "@paralleldrive/cuid2";
import { requireSchoolSession } from "@/lib/school-auth";
import { withTenant } from "@/lib/db";
import { hasPermission, requirePermission } from "@/lib/rbac";
import { appendSchoolAudit } from "@/lib/audit";
import { routeError, ForbiddenError, AppError } from "@/lib/errors";

const createSchema=z.object({classId:z.string().min(1),subjectId:z.string().min(1),termId:z.string().min(1).optional(),title:z.string().trim().min(3).max(160),objective:z.string().trim().max(500).optional(),content:z.string().trim().min(10).max(12000),plannedDate:z.coerce.date(),status:z.enum(["draft","submitted"]).default("draft")});
const patchSchema=z.object({id:z.string().min(1),status:z.enum(["draft","submitted","approved","changes_requested","completed"]),reviewNote:z.string().trim().max(2000).optional()});
type PlanRow={id:string;schoolId:string;teacherId:string;teacherName:string;classId:string;className:string;subjectId:string;subjectName:string;termId:string|null;termName:string|null;title:string;objective:string|null;content:string;plannedDate:Date;status:string;reviewNote:string|null;reviewedAt:Date|null;createdAt:Date;updatedAt:Date};

export async function GET(){try{const session=await requireSchoolSession();return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"lesson_plans:review");const manage=await hasPermission(tx,session.userId,"lesson_plans:manage");if(!review&&!manage)throw new ForbiddenError("You do not have access to lesson planning.");const scope=review?Prisma.sql`lp."schoolId" = ${session.schoolId}`:Prisma.sql`lp."schoolId" = ${session.schoolId} AND lp."teacherId" = ${session.userId}`;const rows=await tx.$queryRaw<PlanRow[]>`SELECT lp."id",lp."schoolId",lp."teacherId",u."name" AS "teacherName",lp."classId",c."name" AS "className",lp."subjectId",s."name" AS "subjectName",lp."termId",t."name" AS "termName",lp."title",lp."objective",lp."content",lp."plannedDate",lp."status",lp."reviewNote",lp."reviewedAt",lp."createdAt",lp."updatedAt" FROM "LessonPlan" lp JOIN "User" u ON u."id"=lp."teacherId" AND u."schoolId"=lp."schoolId" JOIN "Class" c ON c."id"=lp."classId" AND c."schoolId"=lp."schoolId" JOIN "Subject" s ON s."id"=lp."subjectId" AND s."schoolId"=lp."schoolId" LEFT JOIN "Term" t ON t."id"=lp."termId" AND t."schoolId"=lp."schoolId" WHERE ${scope} ORDER BY lp."plannedDate" DESC,lp."updatedAt" DESC`;const assignments=manage?await tx.classSubjectTeacher.findMany({where:{teacherId:session.userId},select:{classId:true,subjectId:true,class:{select:{name:true,level:true}},subject:{select:{name:true}}},orderBy:{classId:"asc"}}):[];const terms=await tx.term.findMany({orderBy:{startDate:"desc"},take:12,select:{id:true,name:true,academicYear:{select:{name:true}}}});return{rows,assignments,terms,review,manage};}))}catch(error){return routeError(error)}}

export async function POST(request:Request){try{const session=await requireSchoolSession();const input=createSchema.parse(await request.json());await withTenant(session.schoolId,async tx=>{await requirePermission(tx,session.userId,"lesson_plans:manage");const assignment=await tx.classSubjectTeacher.findFirst({where:{schoolId:session.schoolId,teacherId:session.userId,classId:input.classId,subjectId:input.subjectId}});const classTeacher=await tx.class.findFirst({where:{id:input.classId,schoolId:session.schoolId,classTeacherId:session.userId},select:{id:true}});if(!assignment&&!classTeacher)throw new ForbiddenError("You can only create a lesson plan for a class and subject you teach (including form classes).");if(input.termId){const term=await tx.term.findFirst({where:{id:input.termId,schoolId:session.schoolId}});if(!term)throw new AppError("Selected term was not found in this school.",404,"TERM_NOT_FOUND");if(term.isLocked)throw new AppError("Selected term is locked.",409,"TERM_LOCKED");}const id=createId();await tx.$executeRaw`INSERT INTO "LessonPlan" ("id","schoolId","teacherId","classId","subjectId","termId","title","objective","content","plannedDate","status") VALUES (${id},${session.schoolId},${session.userId},${input.classId},${input.subjectId},${input.termId??null},${input.title},${input.objective??null},${input.content},${input.plannedDate},${input.status})`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"lesson_plan.created",entityType:"LessonPlan",entityId:id,after:{title:input.title,classId:input.classId,subjectId:input.subjectId,status:input.status}});});return NextResponse.json({ok:true},{status:201})}catch(error){return routeError(error)}}

export async function PATCH(request:Request){try{const session=await requireSchoolSession();const input=patchSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"lesson_plans:review");const manage=await hasPermission(tx,session.userId,"lesson_plans:manage");const rows=await tx.$queryRaw<Array<{id:string;teacherId:string;status:string}>>`SELECT "id","teacherId","status" FROM "LessonPlan" WHERE "id"=${input.id} AND "schoolId"=${session.schoolId} LIMIT 1`;const current=rows[0];if(!current)throw new AppError("Lesson plan not found in this school.",404,"NOT_FOUND");const from=current.status;const to=input.status;const isOwner=current.teacherId===session.userId;const isReviewAction=to==="approved"||to==="changes_requested";if(isReviewAction){if(!review)throw new ForbiddenError("Only academic reviewers can approve or request changes.");if(isOwner)throw new ForbiddenError("Reviewers cannot approve their own lesson plan.");const allowed:Record<string,string[]>={submitted:["approved","changes_requested"],changes_requested:["approved","submitted"],approved:["changes_requested","completed"],completed:[]};if(!(allowed[from]??[]).includes(to))throw new AppError("Cannot move a lesson plan from "+from+" to "+to+".",409,"INVALID_TRANSITION");}else{if(!manage||!isOwner)throw new ForbiddenError("You can only update lesson plans you created.");const allowed:Record<string,string[]>={draft:["submitted"],submitted:["draft"],changes_requested:["submitted"]};if(!(allowed[from]??[]).includes(to))throw new AppError("Cannot move a lesson plan from "+from+" to "+to+".",409,"INVALID_TRANSITION");}const reviewed=isReviewAction;await tx.$executeRaw`UPDATE "LessonPlan" SET "status"=${input.status},"reviewNote"=CASE WHEN ${reviewed} THEN ${input.reviewNote??null} ELSE "reviewNote" END,"reviewerId"=CASE WHEN ${reviewed} THEN ${session.userId} ELSE "reviewerId" END,"reviewedAt"=CASE WHEN ${reviewed} THEN CURRENT_TIMESTAMP ELSE "reviewedAt" END,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${input.id} AND "schoolId"=${session.schoolId}`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:reviewed?"lesson_plan.reviewed":"lesson_plan.updated",entityType:"LessonPlan",entityId:input.id,before:{status:from},after:{status:input.status,reviewNote:reviewed?(input.reviewNote??null):undefined}});return{ok:true};}))}catch(error){return routeError(error)}}
