import { NextResponse } from "next/server";
import { z } from "zod";
import { createId } from "@paralleldrive/cuid2";
import { requireSchoolSession } from "@/lib/school-auth";
import { withTenant } from "@/lib/db";
import { hasPermission, requirePermission } from "@/lib/rbac";
import { appendSchoolAudit } from "@/lib/audit";
import { routeError, ForbiddenError, AppError } from "@/lib/errors";

const createSchema=z.object({classId:z.string().min(1),subjectId:z.string().min(1),termId:z.string().min(1).optional(),title:z.string().trim().min(3).max(160),objective:z.string().trim().max(500).optional(),content:z.string().trim().min(10).max(12000),plannedDate:z.coerce.date(),status:z.enum(["draft","submitted"]).default("draft")});
const patchSchema=z.object({id:z.string().min(1),status:z.enum(["draft","submitted","approved","changes_requested","completed"]),reviewNote:z.string().trim().max(2000).optional()});
type PlanRow={id:string;schoolId:string;teacherId:string;teacherName:string;classId:string;className:string;subjectId:string;subjectName:string;termId:string|null;termName:string|null;title:string;objective:string|null;content:string;plannedDate:string;status:string;reviewNote:string|null;reviewedAt:string|null;createdAt:string;updatedAt:string};

export async function GET(){try{const session=await requireSchoolSession();return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"lesson_plans:review");const manage=await hasPermission(tx,session.userId,"lesson_plans:manage");if(!review&&!manage)throw new ForbiddenError("You do not have access to lesson planning.");const where=review?'lp."schoolId" = ${session.schoolId}':'lp."schoolId" = ${session.schoolId} AND lp."teacherId" = ${session.userId}`;const rows=await tx.$queryRaw<PlanRow[]>`SELECT lp."id",lp."schoolId",lp."teacherId",u."name" AS "teacherName",lp."classId",c."name" AS "className",lp."subjectId",s."name" AS "subjectName",lp."termId",t."name" AS "termName",lp."title",lp."objective",lp."content",lp."plannedDate",lp."status",lp."reviewNote",lp."reviewedAt",lp."createdAt",lp."updatedAt" FROM "LessonPlan" lp JOIN "User" u ON u."id"=lp."teacherId" AND u."schoolId"=lp."schoolId" JOIN "Class" c ON c."id"=lp."classId" AND c."schoolId"=lp."schoolId" JOIN "Subject" s ON s."id"=lp."subjectId" AND s."schoolId"=lp."schoolId" LEFT JOIN "Term" t ON t."id"=lp."termId" AND t."schoolId"=lp."schoolId" WHERE ${where} ORDER BY lp."plannedDate" DESC,lp."updatedAt" DESC`;const assignments=manage?await tx.classSubjectTeacher.findMany({where:{teacherId:session.userId},select:{classId:true,subjectId:true,class:{select:{name:true,level:true}},subject:{select:{name:true}}},orderBy:{classId:"asc"}}):[];const terms=await tx.term.findMany({orderBy:{startDate:"desc"},take:12,select:{id:true,name:true,academicYear:{select:{name:true}}}});return{rows,assignments,terms,review,manage};}))}catch(error){return routeError(error)}}

export async function POST(request:Request){try{const session=await requireSchoolSession();const input=createSchema.parse(await request.json());await withTenant(session.schoolId,async tx=>{await requirePermission(tx,session.userId,"lesson_plans:manage");const assignment=await tx.classSubjectTeacher.findFirst({where:{teacherId:session.userId,classId:input.classId,subjectId:input.subjectId}});if(!assignment)throw new ForbiddenError("You can only create a lesson plan for a class and subject assigned to you.");if(input.termId){const term=await tx.term.findUnique({where:{id:input.termId}});if(!term)throw new AppError("Selected term was not found.",404,"TERM_NOT_FOUND");}const id=createId();await tx.$executeRaw`INSERT INTO "LessonPlan" ("id","schoolId","teacherId","classId","subjectId","termId","title","objective","content","plannedDate","status") VALUES (${id},${session.schoolId},${session.userId},${input.classId},${input.subjectId},${input.termId??null},${input.title},${input.objective??null},${input.content},${input.plannedDate},${input.status})`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"lesson_plan.created",entityType:"LessonPlan",entityId:id,after:{title:input.title,classId:input.classId,subjectId:input.subjectId,status:input.status}});});return NextResponse.json({ok:true},{status:201})}catch(error){return routeError(error)}}

export async function PATCH(request:Request){try{const session=await requireSchoolSession();const input=patchSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"lesson_plans:review");const manage=await hasPermission(tx,session.userId,"lesson_plans:manage");const rows=await tx.$queryRaw<Array<{id:string;teacherId:string;status:string}>>`SELECT "id","teacherId","status" FROM "LessonPlan" WHERE "id"=${input.id} AND "schoolId"=${session.schoolId} LIMIT 1`;const current=rows[0];if(!current)throw new AppError("Lesson plan not found.",404,"NOT_FOUND");if(input.status==="approved"||input.status==="changes_requested"){if(!review)throw new ForbiddenError("Only academic reviewers can approve or request changes.");}else if(!manage||current.teacherId!==session.userId)throw new ForbiddenError("You can only update lesson plans you created.");const reviewed=input.status==="approved"||input.status==="changes_requested";await tx.$executeRaw`UPDATE "LessonPlan" SET "status"=${input.status},"reviewNote"=${input.reviewNote??null},"reviewerId"=${reviewed?session.userId:null},"reviewedAt"=${reviewed?new Date():null},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${input.id} AND "schoolId"=${session.schoolId}`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:reviewed?"lesson_plan.reviewed":"lesson_plan.updated",entityType:"LessonPlan",entityId:input.id,after:{status:input.status,reviewNote:input.reviewNote??null}});return{ok:true};}))}catch(error){return routeError(error)}}
