import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { withTenant } from "@/lib/db";
import { requireGuardianSession } from "@/lib/guardian-auth";
import "@/app/globals.css";

export default async function GuardianPortalPage() {
  const session = await requireGuardianSession();
  if (session.needsPasswordChange) redirect("/account/security?required=1");

  const data = await withTenant(session.schoolId, async (tx) => tx.guardian.findFirst({
    where: { id: session.guardianId, schoolId: session.schoolId, userId: session.userId },
    select: {
      name: true,
      students: { include: { student: { include: { class: true, attendanceEvents: true, scores: { include: { assessment: true, subject: true } }, invoices: { include: { payments: true } } } } } }
    }
  }));
  if (!data) redirect("/login/guardian");

  const children = data.students.map((x) => x.student);
  const attendance = children.reduce((n, s) => n + s.attendanceEvents.length, 0);
  const results = children.reduce((n, s) => n + s.scores.length, 0);
  const balance = children.reduce((n, s) => n + s.invoices.reduce((sum, inv) => sum + Number(inv.totalAmount) - inv.payments.reduce((paid, p) => paid + Number(p.amount), 0), 0), 0);

  return <main className="app-shell app-shell-school">
    <aside className="app-sidebar"><Link href="/" className="app-brand"><span className="app-brand-mark">S</span><span><strong>SukuuNova</strong><small>Guardian Portal</small></span></Link><div className="app-school-chip"><span className="app-chip-avatar">{data.name.slice(0,2).toUpperCase()}</span><span><b>{data.name}</b><small>{session.schoolName}</small></span></div><nav className="app-nav" aria-label="Guardian navigation"><div className="app-nav-group"><div className="app-nav-label">Family</div><Link className="app-nav-item is-active" href="/guardian"><span className="app-nav-icon">⌂</span><span>Overview</span></Link><Link className="app-nav-item" href="/guardian/children"><span className="app-nav-icon">♟</span><span>My children</span></Link><Link className="app-nav-item" href="/guardian/attendance"><span className="app-nav-icon">◉</span><span>Attendance</span></Link><Link className="app-nav-item" href="/guardian/academics"><span className="app-nav-icon">◇</span><span>Academics & results</span></Link><Link className="app-nav-item" href="/guardian/assignments"><span className="app-nav-icon">✦</span><span>Homework</span></Link><Link className="app-nav-item" href="/guardian/fees"><span className="app-nav-icon">₵</span><span>Fees & receipts</span></Link><Link className="app-nav-item" href="/guardian/messages"><span className="app-nav-icon">✉</span><span>Messages</span></Link><Link className="app-nav-item" href="/guardian/calendar"><span className="app-nav-icon">◷</span><span>Calendar</span></Link><Link className="app-nav-item" href="/account/security"><span className="app-nav-icon">⚙</span><span>Security</span></Link></div></nav><div className="app-sidebar-bottom"><form action="/api/auth/guardian/logout" method="post"><button className="app-help" type="submit">Sign out</button></form></div></aside>
    <section className="app-main"><header className="app-topbar"><div><div className="app-breadcrumb">SukuuNova <span>›</span> {session.schoolName}</div><h1>Family dashboard</h1><p>Your private window into only the learners your school has linked to you.</p></div><div className="app-top-actions"><Link className="app-search" href="/guardian/children">♟ {children.length} connected</Link></div></header><div className="app-content">
      <section className="app-card" style={{padding:24,marginBottom:16}}><div className="app-card-head"><div><span className="module-overline">Guardian command centre</span><h2>Welcome back, {data.name.split(" ")[0]}.</h2><p>Attendance, academics, homework, fees and messages are scoped to your linked children.</p></div><span className="app-pill">Private family view</span></div></section>
      <div className="app-grid kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Children</span><span className="app-kpi-icon">♟</span></div><div className="app-kpi-value">{children.length}</div><div className="app-kpi-meta">School-linked only</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Attendance activity</span><span className="app-kpi-icon">◉</span></div><div className="app-kpi-value">{attendance}</div><div className="app-kpi-meta">Across your children</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Results recorded</span><span className="app-kpi-icon">◇</span></div><div className="app-kpi-value">{results}</div><div className="app-kpi-meta">Published school records</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Outstanding</span><span className="app-kpi-icon">₵</span></div><div className="app-kpi-value">GH₵{balance.toFixed(2)}</div><div className="app-kpi-meta">Live invoice balances</div></div></div>
      <section className="app-card" style={{padding:18,marginTop:16}}><div className="app-card-head"><div><h2>My children</h2><p>Open a child to see the full family-safe view.</p></div></div><div style={{display:"grid",gap:12,gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))"}}>{children.map((student) => { const latest=student.scores[0]; const childBalance=student.invoices.reduce((n,inv)=>n+Number(inv.totalAmount)-inv.payments.reduce((p,x)=>p+Number(x.amount),0),0); return <article key={student.id} className="app-card" style={{padding:16,background:"linear-gradient(145deg,rgba(21,45,60,.96),rgba(9,22,31,.98))"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{width:58,height:58,borderRadius:18,overflow:"hidden",background:"rgba(255,255,255,.06)",display:"grid",placeItems:"center",flex:"0 0 auto"}}>{student.photoUrl?<Image src={student.photoUrl} alt="" width={58} height={58} unoptimized style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span style={{fontWeight:900}}>{student.name.slice(0,2).toUpperCase()}</span>}</div><div><h3 style={{margin:0}}>{student.name}</h3><p style={{margin:"4px 0 0",color:"#71898e",fontSize:10}}>{student.admissionNo} · {student.class?.level?`${student.class.level} · `:""}{student.class?.name??"Unassigned"}</p></div></div><div className="app-list" style={{marginTop:12}}><div className="app-list-row"><span className="app-list-icon">◇</span><div><b>Latest result</b><span>{latest?`${latest.subject.name} · ${latest.value}`:"No published result"}</span></div></div><div className="app-list-row"><span className="app-list-icon">◉</span><div><b>Attendance</b><span>{student.attendanceEvents.length} recorded event{student.attendanceEvents.length===1?"":"s"}</span></div></div><div className="app-list-row"><span className="app-list-icon">₵</span><div><b>Fees</b><span>GH₵{childBalance.toFixed(2)} outstanding</span></div></div></div><Link href={`/guardian/children/${student.id}`} className="module-hero-button" style={{display:"inline-flex",marginTop:14}}>Open learner →</Link></article>;})}</div></section>
    </div></section>
  </main>;
}
