import type { LearnLane, LearnQuestion, SessionConfig } from "./learn-domain";

export type SpecializedQuestionEntry = {
  lane: LearnLane;
  programId: string;
  levelId: string;
  subjectId: string;
  topicId: string;
  question: LearnQuestion;
};

type BaseQuestion = Omit<LearnQuestion, "id" | "exposureKey">;

function entry(
  lane: LearnLane,
  programId: string,
  levelId: string,
  subjectId: string,
  topicId: string,
  key: string,
  question: BaseQuestion,
): SpecializedQuestionEntry {
  return {
    lane,
    programId,
    levelId,
    subjectId,
    topicId,
    question: {
      ...question,
      id: `specialized-${lane}-${programId}-${subjectId}-${topicId}-${key}`,
      exposureKey: `specialized:${lane}:${programId}:${subjectId}:${topicId}:${key}`,
    },
  };
}

const universityEntries: SpecializedQuestionEntry[] = [
  entry("university", "computer-science", "level-100", "programming", "variables", "boolean-type", {
    kind: "single",
    subject: "Programming",
    topic: "Variables & data types",
    skill: "Choose appropriate data types",
    difficulty: 2,
    prompt: "Which data type is most appropriate for a value that can only be true or false?",
    options: [
      { id: "boolean", label: "Boolean" },
      { id: "integer", label: "Integer" },
      { id: "string", label: "String" },
      { id: "array", label: "Array" },
    ],
    answer: "boolean",
    explanation: "A Boolean represents one of two logical states, commonly true or false.",
  }),
  entry("university", "computer-science", "level-100", "programming", "variables", "assignment", {
    kind: "numeric",
    subject: "Programming",
    topic: "Variables & data types",
    skill: "Trace variable assignment",
    difficulty: 2,
    prompt: "In the pseudocode x ← 7, then x ← x + 5. What is the final value of x?",
    answer: 12,
    acceptedAnswers: ["12"],
    explanation: "The second assignment replaces x with its current value plus 5: 7 + 5 = 12.",
  }),
  entry("university", "computer-science", "level-100", "programming", "variables", "constant", {
    kind: "single",
    subject: "Programming",
    topic: "Variables & data types",
    skill: "Distinguish variables from constants",
    difficulty: 2,
    prompt: "Why would a programmer declare a value as a constant?",
    options: [
      { id: "fixed", label: "To prevent the value from being reassigned after initialization" },
      { id: "faster", label: "To make every program run twice as fast" },
      { id: "loop", label: "To force the value to repeat in a loop" },
      { id: "network", label: "To send the value across a network automatically" },
    ],
    answer: "fixed",
    explanation: "A constant communicates that a value should not be reassigned after it is initialized.",
  }),

  entry("university", "computer-science", "level-100", "programming", "control-flow", "if-else", {
    kind: "single",
    subject: "Programming",
    topic: "Control flow",
    skill: "Apply conditional logic",
    difficulty: 2,
    prompt: "Which control structure chooses between two paths based on a condition?",
    options: [
      { id: "if", label: "if / else" },
      { id: "array", label: "array" },
      { id: "class", label: "class declaration" },
      { id: "comment", label: "comment" },
    ],
    answer: "if",
    explanation: "An if/else statement evaluates a condition and selects which branch to execute.",
  }),
  entry("university", "computer-science", "level-100", "programming", "control-flow", "while", {
    kind: "numeric",
    subject: "Programming",
    topic: "Control flow",
    skill: "Trace loops",
    difficulty: 3,
    prompt: "A loop starts with n = 1 and repeats while n < 10, doubling n each time. How many loop iterations occur?",
    answer: 4,
    acceptedAnswers: ["4"],
    explanation: "The values after each iteration are 2, 4, 8 and 16, so the loop body executes 4 times.",
  }),
  entry("university", "computer-science", "level-100", "programming", "control-flow", "for-loop", {
    kind: "single",
    subject: "Programming",
    topic: "Control flow",
    skill: "Choose iteration structures",
    difficulty: 2,
    prompt: "Which loop is usually clearest when the number of repetitions is known in advance?",
    options: [
      { id: "for", label: "for loop" },
      { id: "if", label: "if statement" },
      { id: "switch", label: "switch statement" },
      { id: "return", label: "return statement" },
    ],
    answer: "for",
    explanation: "A for loop is commonly used when the iteration count or sequence is known.",
  }),

  entry("university", "computer-science", "level-100", "programming", "data-structures", "stack", {
    kind: "single",
    subject: "Programming",
    topic: "Data structures",
    skill: "Select data structures",
    difficulty: 2,
    prompt: "Which principle describes a stack?",
    options: [
      { id: "lifo", label: "Last in, first out" },
      { id: "fifo", label: "First in, first out" },
      { id: "sorted", label: "Always sorted alphabetically" },
      { id: "random", label: "Random in, random out" },
    ],
    answer: "lifo",
    explanation: "A stack removes the most recently added item first, which is last in, first out.",
  }),
  entry("university", "computer-science", "level-100", "programming", "data-structures", "queue", {
    kind: "single",
    subject: "Programming",
    topic: "Data structures",
    skill: "Select data structures",
    difficulty: 2,
    prompt: "A print server should process jobs in the order they arrive. Which structure best matches that requirement?",
    options: [
      { id: "queue", label: "Queue" },
      { id: "stack", label: "Stack" },
      { id: "set", label: "Set" },
      { id: "tree", label: "Binary tree" },
    ],
    answer: "queue",
    explanation: "A queue follows first in, first out, which matches arrival-order processing.",
  }),
  entry("university", "computer-science", "level-100", "programming", "data-structures", "hash-map", {
    kind: "single",
    subject: "Programming",
    topic: "Data structures",
    skill: "Match structures to access patterns",
    difficulty: 3,
    prompt: "Which structure is designed to associate keys with values for direct lookup?",
    options: [
      { id: "map", label: "Hash map / dictionary" },
      { id: "stack", label: "Stack" },
      { id: "queue", label: "Queue" },
      { id: "matrix", label: "Matrix multiplication" },
    ],
    answer: "map",
    explanation: "A hash map or dictionary stores key-value pairs and supports lookup by key.",
  }),

  entry("university", "computer-science", "level-100", "networks", "network-basics", "router", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Network basics",
    skill: "Identify network device roles",
    difficulty: 2,
    prompt: "What is the primary role of a router?",
    options: [
      { id: "route", label: "Forward packets between different networks" },
      { id: "type", label: "Convert text into bold formatting" },
      { id: "compile", label: "Compile source code" },
      { id: "store", label: "Store every file on a computer" },
    ],
    answer: "route",
    explanation: "Routers examine network-layer information and forward packets between networks.",
  }),
  entry("university", "computer-science", "level-100", "networks", "network-basics", "switch", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Network basics",
    skill: "Identify network device roles",
    difficulty: 3,
    prompt: "On a typical Ethernet LAN, a switch mainly forwards frames using which address?",
    options: [
      { id: "mac", label: "MAC address" },
      { id: "url", label: "URL" },
      { id: "email", label: "Email address" },
      { id: "gps", label: "GPS coordinate" },
    ],
    answer: "mac",
    explanation: "Ethernet switches learn and use MAC addresses to forward frames within a local network.",
  }),
  entry("university", "computer-science", "level-100", "networks", "network-basics", "latency", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Network basics",
    skill: "Distinguish network performance measures",
    difficulty: 2,
    prompt: "Which term describes the delay before data begins to arrive across a network?",
    options: [
      { id: "latency", label: "Latency" },
      { id: "bandwidth", label: "Bandwidth" },
      { id: "storage", label: "Storage capacity" },
      { id: "resolution", label: "Screen resolution" },
    ],
    answer: "latency",
    explanation: "Latency measures delay, while bandwidth describes how much data can be transmitted per unit time.",
  }),

  entry("university", "computer-science", "level-100", "networks", "protocols", "dns", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Protocols",
    skill: "Explain common network protocols",
    difficulty: 2,
    prompt: "What does DNS primarily do?",
    options: [
      { id: "resolve", label: "Translate domain names into IP addresses" },
      { id: "encrypt", label: "Encrypt every file on a computer" },
      { id: "compress", label: "Compress images for printing" },
      { id: "compile", label: "Compile web applications" },
    ],
    answer: "resolve",
    explanation: "The Domain Name System resolves human-readable domain names to network addresses.",
  }),
  entry("university", "computer-science", "level-100", "networks", "protocols", "https", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Protocols",
    skill: "Explain common network protocols",
    difficulty: 3,
    prompt: "What is the key security difference between HTTP and HTTPS?",
    options: [
      { id: "tls", label: "HTTPS protects the connection using TLS" },
      { id: "offline", label: "HTTPS only works without internet access" },
      { id: "images", label: "HTTPS cannot transfer images" },
      { id: "ports", label: "HTTPS removes the need for network ports" },
    ],
    answer: "tls",
    explanation: "HTTPS is HTTP carried over a TLS-protected connection, providing encryption and server authentication.",
  }),
  entry("university", "computer-science", "level-100", "networks", "protocols", "tcp", {
    kind: "single",
    subject: "Computer Networks",
    topic: "Protocols",
    skill: "Compare transport protocols",
    difficulty: 3,
    prompt: "Which feature is associated with TCP?",
    options: [
      { id: "ordered", label: "Reliable, ordered byte delivery" },
      { id: "best-effort", label: "No connection state and no delivery checks" },
      { id: "name", label: "Domain-name resolution" },
      { id: "graphics", label: "Image rendering" },
    ],
    answer: "ordered",
    explanation: "TCP provides connection-oriented, reliable and ordered delivery of a byte stream.",
  }),

  entry("university", "nursing", "level-100", "anatomy", "cardiovascular", "left-ventricle", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Cardiovascular system",
    skill: "Identify heart chamber function",
    difficulty: 2,
    prompt: "Which chamber pumps oxygenated blood into the systemic circulation?",
    options: [
      { id: "lv", label: "Left ventricle" },
      { id: "rv", label: "Right ventricle" },
      { id: "ra", label: "Right atrium" },
      { id: "la", label: "Left atrium" },
    ],
    answer: "lv",
    explanation: "The left ventricle pumps oxygenated blood into the aorta and systemic circulation.",
  }),
  entry("university", "nursing", "level-100", "anatomy", "cardiovascular", "mitral", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Cardiovascular system",
    skill: "Identify cardiac valves",
    difficulty: 3,
    prompt: "Which valve lies between the left atrium and left ventricle?",
    options: [
      { id: "mitral", label: "Mitral valve" },
      { id: "tricuspid", label: "Tricuspid valve" },
      { id: "pulmonary", label: "Pulmonary valve" },
      { id: "aortic", label: "Aortic valve" },
    ],
    answer: "mitral",
    explanation: "The mitral, or bicuspid, valve separates the left atrium from the left ventricle.",
  }),
  entry("university", "nursing", "level-100", "anatomy", "cardiovascular", "vena-cava", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Cardiovascular system",
    skill: "Trace blood flow",
    difficulty: 3,
    prompt: "Blood returning from the systemic circulation enters the heart first through which chamber?",
    options: [
      { id: "ra", label: "Right atrium" },
      { id: "la", label: "Left atrium" },
      { id: "lv", label: "Left ventricle" },
      { id: "rv", label: "Right ventricle" },
    ],
    answer: "ra",
    explanation: "The venae cavae return systemic venous blood to the right atrium.",
  }),

  entry("university", "nursing", "level-100", "anatomy", "respiratory", "alveoli", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Respiratory system",
    skill: "Identify gas-exchange structures",
    difficulty: 2,
    prompt: "Where does most gas exchange between air and blood occur in the lungs?",
    options: [
      { id: "alveoli", label: "Alveoli" },
      { id: "trachea", label: "Trachea" },
      { id: "larynx", label: "Larynx" },
      { id: "pleura", label: "Pleural cavity" },
    ],
    answer: "alveoli",
    explanation: "Alveoli provide a thin, large surface for diffusion of oxygen and carbon dioxide.",
  }),
  entry("university", "nursing", "level-100", "anatomy", "respiratory", "diaphragm", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Respiratory system",
    skill: "Explain ventilation",
    difficulty: 3,
    prompt: "During quiet inspiration, what does the diaphragm normally do?",
    options: [
      { id: "contracts", label: "Contracts and moves downward" },
      { id: "relaxes", label: "Relaxes and moves upward" },
      { id: "closes", label: "Closes the trachea" },
      { id: "stops", label: "Stops all thoracic movement" },
    ],
    answer: "contracts",
    explanation: "Diaphragm contraction increases thoracic volume and helps draw air into the lungs.",
  }),
  entry("university", "nursing", "level-100", "anatomy", "respiratory", "diffusion", {
    kind: "single",
    subject: "Anatomy & Physiology",
    topic: "Respiratory system",
    skill: "Explain gas movement",
    difficulty: 3,
    prompt: "Oxygen moves from alveoli into pulmonary capillary blood mainly by which process?",
    options: [
      { id: "diffusion", label: "Diffusion" },
      { id: "filtration", label: "Filtration" },
      { id: "active", label: "Active transport" },
      { id: "osmosis", label: "Osmosis of oxygen molecules" },
    ],
    answer: "diffusion",
    explanation: "Oxygen diffuses down its partial-pressure gradient across the alveolar-capillary membrane.",
  }),

  entry("university", "nursing", "level-100", "fundamentals", "patient-care", "identity", {
    kind: "single",
    subject: "Fundamentals of Nursing",
    topic: "Patient care",
    skill: "Apply patient-safety principles",
    difficulty: 2,
    prompt: "Before a procedure, which action best supports correct patient identification?",
    options: [
      { id: "two", label: "Use at least two approved patient identifiers" },
      { id: "bed", label: "Use only the bed number" },
      { id: "face", label: "Rely only on recognising the patient's face" },
      { id: "room", label: "Use only the room number" },
    ],
    answer: "two",
    explanation: "Using two approved identifiers reduces the risk of matching care to the wrong patient.",
  }),
  entry("university", "nursing", "level-100", "fundamentals", "patient-care", "hand-hygiene", {
    kind: "single",
    subject: "Fundamentals of Nursing",
    topic: "Patient care",
    skill: "Apply infection-prevention principles",
    difficulty: 2,
    prompt: "Which routine action is central to reducing transmission of microorganisms during patient care?",
    options: [
      { id: "hands", label: "Appropriate hand hygiene" },
      { id: "jewellery", label: "Wearing extra jewellery" },
      { id: "notes", label: "Avoiding documentation" },
      { id: "lights", label: "Turning off room lights" },
    ],
    answer: "hands",
    explanation: "Appropriate hand hygiene is a core infection-prevention measure in clinical care.",
  }),
  entry("university", "nursing", "level-100", "fundamentals", "patient-care", "documentation", {
    kind: "single",
    subject: "Fundamentals of Nursing",
    topic: "Patient care",
    skill: "Document care accurately",
    difficulty: 3,
    prompt: "Which note is the best example of objective clinical documentation?",
    options: [
      { id: "objective", label: "Patient walked 20 metres with one-person assistance at 10:15." },
      { id: "vague", label: "Patient did much better today." },
      { id: "judgment", label: "Patient was difficult and uncooperative." },
      { id: "guess", label: "Patient probably slept badly." },
    ],
    answer: "objective",
    explanation: "Objective documentation records observable, measurable facts with relevant context and time.",
  }),

  entry("university", "business", "level-100", "accounting", "double-entry", "asset-debit", {
    kind: "single",
    subject: "Financial Accounting",
    topic: "Double entry",
    skill: "Apply debit and credit rules",
    difficulty: 2,
    prompt: "In basic double-entry accounting, an increase in an asset is normally recorded on which side?",
    options: [
      { id: "debit", label: "Debit" },
      { id: "credit", label: "Credit" },
      { id: "either", label: "Either side with no rule" },
      { id: "memo", label: "Memorandum only" },
    ],
    answer: "debit",
    explanation: "Asset increases are normally debited, while asset decreases are credited.",
  }),
  entry("university", "business", "level-100", "accounting", "double-entry", "liability-credit", {
    kind: "single",
    subject: "Financial Accounting",
    topic: "Double entry",
    skill: "Apply debit and credit rules",
    difficulty: 2,
    prompt: "An increase in a liability is normally recorded as a:",
    options: [
      { id: "credit", label: "Credit" },
      { id: "debit", label: "Debit" },
      { id: "discount", label: "Discount" },
      { id: "contra", label: "Contra entry only" },
    ],
    answer: "credit",
    explanation: "Liability increases are normally credited.",
  }),
  entry("university", "business", "level-100", "accounting", "double-entry", "cash-sale", {
    kind: "multi",
    subject: "Financial Accounting",
    topic: "Double entry",
    skill: "Record simple transactions",
    difficulty: 3,
    prompt: "A business makes a cash sale. Select the two accounts that normally increase.",
    options: [
      { id: "cash", label: "Cash" },
      { id: "sales", label: "Sales revenue" },
      { id: "loan", label: "Loan payable" },
      { id: "capital", label: "Owner drawings" },
    ],
    answer: ["cash", "sales"],
    explanation: "A cash sale increases the cash asset and sales revenue.",
  }),

  entry("university", "business", "level-100", "accounting", "statements", "position", {
    kind: "single",
    subject: "Financial Accounting",
    topic: "Financial statements",
    skill: "Identify financial statements",
    difficulty: 2,
    prompt: "Which statement reports assets, liabilities and equity at a specific date?",
    options: [
      { id: "position", label: "Statement of financial position" },
      { id: "income", label: "Income statement" },
      { id: "cash", label: "Cash flow statement" },
      { id: "invoice", label: "Sales invoice" },
    ],
    answer: "position",
    explanation: "The statement of financial position presents assets, liabilities and equity at a point in time.",
  }),
  entry("university", "business", "level-100", "accounting", "statements", "income", {
    kind: "single",
    subject: "Financial Accounting",
    topic: "Financial statements",
    skill: "Identify financial statements",
    difficulty: 2,
    prompt: "Which statement is mainly used to determine profit or loss for a period?",
    options: [
      { id: "income", label: "Income statement" },
      { id: "position", label: "Statement of financial position" },
      { id: "bank", label: "Bank statement" },
      { id: "inventory", label: "Inventory count sheet" },
    ],
    answer: "income",
    explanation: "The income statement compares income and expenses to report profit or loss for a period.",
  }),
  entry("university", "business", "level-100", "accounting", "statements", "cash-flow", {
    kind: "single",
    subject: "Financial Accounting",
    topic: "Financial statements",
    skill: "Interpret financial statements",
    difficulty: 3,
    prompt: "Which statement groups cash movements into operating, investing and financing activities?",
    options: [
      { id: "cash", label: "Cash flow statement" },
      { id: "income", label: "Income statement" },
      { id: "position", label: "Statement of financial position" },
      { id: "trial", label: "Trial balance" },
    ],
    answer: "cash",
    explanation: "The cash flow statement classifies cash movements by operating, investing and financing activities.",
  }),

  entry("university", "business", "level-100", "management", "functions", "planning", {
    kind: "single",
    subject: "Management",
    topic: "Management functions",
    skill: "Identify management functions",
    difficulty: 2,
    prompt: "A manager sets objectives and decides the actions needed to achieve them. Which function is this?",
    options: [
      { id: "planning", label: "Planning" },
      { id: "controlling", label: "Controlling" },
      { id: "staffing", label: "Staffing only" },
      { id: "auditing", label: "External auditing" },
    ],
    answer: "planning",
    explanation: "Planning involves setting objectives and deciding how to achieve them.",
  }),
  entry("university", "business", "level-100", "management", "functions", "organising", {
    kind: "single",
    subject: "Management",
    topic: "Management functions",
    skill: "Identify management functions",
    difficulty: 2,
    prompt: "Assigning roles, grouping tasks and arranging resources are mainly part of:",
    options: [
      { id: "organising", label: "Organising" },
      { id: "forecast", label: "Forecasting weather" },
      { id: "pricing", label: "Pricing only" },
      { id: "advertising", label: "Advertising only" },
    ],
    answer: "organising",
    explanation: "Organising structures work, responsibilities and resources so plans can be carried out.",
  }),
  entry("university", "business", "level-100", "management", "functions", "controlling", {
    kind: "single",
    subject: "Management",
    topic: "Management functions",
    skill: "Identify management functions",
    difficulty: 3,
    prompt: "Comparing actual performance with targets and correcting significant deviations is mainly:",
    options: [
      { id: "controlling", label: "Controlling" },
      { id: "planning", label: "Planning" },
      { id: "recruiting", label: "Recruiting only" },
      { id: "purchasing", label: "Purchasing only" },
    ],
    answer: "controlling",
    explanation: "Controlling measures performance against standards and supports corrective action when needed.",
  }),
];

const skillEntries: SpecializedQuestionEntry[] = [
  entry("skills", "digital", "core", "productivity", "documents", "styles", {
    kind: "single",
    subject: "Productivity",
    topic: "Documents",
    skill: "Use document styles",
    difficulty: 2,
    prompt: "Why are heading styles better than manually changing font size for every heading in a long document?",
    options: [
      { id: "consistent", label: "They keep structure and formatting consistent and support navigation" },
      { id: "internet", label: "They automatically publish the document online" },
      { id: "password", label: "They encrypt the document" },
      { id: "formula", label: "They calculate spreadsheet formulas" },
    ],
    answer: "consistent",
    explanation: "Styles apply consistent formatting and provide semantic structure that features like navigation and tables of contents can use.",
  }),
  entry("skills", "digital", "core", "productivity", "documents", "find-replace", {
    kind: "single",
    subject: "Productivity",
    topic: "Documents",
    skill: "Edit documents efficiently",
    difficulty: 2,
    prompt: "You need to change the same misspelled word throughout a 30-page document. Which feature is most efficient?",
    options: [
      { id: "replace", label: "Find and Replace" },
      { id: "zoom", label: "Zoom" },
      { id: "print", label: "Print Preview" },
      { id: "crop", label: "Crop" },
    ],
    answer: "replace",
    explanation: "Find and Replace can locate repeated text and update all or selected occurrences efficiently.",
  }),
  entry("skills", "digital", "core", "productivity", "documents", "page-break", {
    kind: "single",
    subject: "Productivity",
    topic: "Documents",
    skill: "Control document layout",
    difficulty: 2,
    prompt: "Which feature should you use to start the next section at the top of a new page without pressing Enter repeatedly?",
    options: [
      { id: "page-break", label: "Page break" },
      { id: "spaces", label: "Spaces" },
      { id: "underline", label: "Underline" },
      { id: "comment", label: "Comment" },
    ],
    answer: "page-break",
    explanation: "A page break starts following content on a new page while keeping layout stable.",
  }),

  entry("skills", "digital", "core", "productivity", "spreadsheets", "sum", {
    kind: "single",
    subject: "Productivity",
    topic: "Spreadsheets",
    skill: "Use spreadsheet formulas",
    difficulty: 2,
    prompt: "Which formula adds the values from cells B2 through B8?",
    options: [
      { id: "sum", label: "=SUM(B2:B8)" },
      { id: "avg", label: "=AVERAGE(B2:B8)" },
      { id: "count", label: "=COUNT(B2:B8)" },
      { id: "text", label: "B2+B8 as plain text" },
    ],
    answer: "sum",
    explanation: "SUM adds all numeric values in the specified range.",
  }),
  entry("skills", "digital", "core", "productivity", "spreadsheets", "absolute", {
    kind: "single",
    subject: "Productivity",
    topic: "Spreadsheets",
    skill: "Use cell references",
    difficulty: 3,
    prompt: "Which reference remains fixed on both column A and row 1 when copied to another cell?",
    options: [
      { id: "absolute", label: "$A$1" },
      { id: "relative", label: "A1" },
      { id: "row", label: "A$1 only fixes the column" },
      { id: "column", label: "$A1 only fixes the row" },
    ],
    answer: "absolute",
    explanation: "$A$1 is an absolute reference, so both the column and row stay fixed when copied.",
  }),
  entry("skills", "digital", "core", "productivity", "spreadsheets", "filter", {
    kind: "single",
    subject: "Productivity",
    topic: "Spreadsheets",
    skill: "Work with tabular data",
    difficulty: 2,
    prompt: "Which feature temporarily shows only rows that meet selected criteria without deleting the other rows?",
    options: [
      { id: "filter", label: "Filter" },
      { id: "merge", label: "Merge cells" },
      { id: "wrap", label: "Wrap text" },
      { id: "freeze", label: "Freeze panes" },
    ],
    answer: "filter",
    explanation: "Filtering limits the displayed rows to those matching chosen conditions while keeping the data intact.",
  }),

  entry("skills", "digital", "core", "safety", "passwords", "unique", {
    kind: "single",
    subject: "Online Safety",
    topic: "Passwords & accounts",
    skill: "Protect online accounts",
    difficulty: 2,
    prompt: "Why is using a different password for each important account safer than reusing one password?",
    options: [
      { id: "contain", label: "A breach of one account is less likely to expose the others" },
      { id: "short", label: "It makes every password shorter" },
      { id: "public", label: "It makes passwords safe to post publicly" },
      { id: "mfa", label: "It removes the need for any other security controls" },
    ],
    answer: "contain",
    explanation: "Unique passwords limit credential-reuse damage if one service is compromised.",
  }),
  entry("skills", "digital", "core", "safety", "passwords", "mfa", {
    kind: "single",
    subject: "Online Safety",
    topic: "Passwords & accounts",
    skill: "Protect online accounts",
    difficulty: 2,
    prompt: "What does multi-factor authentication add to a password login?",
    options: [
      { id: "factor", label: "An additional verification factor" },
      { id: "public", label: "A public copy of the password" },
      { id: "speed", label: "A faster internet connection" },
      { id: "backup", label: "Automatic deletion of account backups" },
    ],
    answer: "factor",
    explanation: "Multi-factor authentication requires another factor beyond the password, which improves account protection.",
  }),
  entry("skills", "digital", "core", "safety", "passwords", "manager", {
    kind: "single",
    subject: "Online Safety",
    topic: "Passwords & accounts",
    skill: "Manage credentials securely",
    difficulty: 3,
    prompt: "What is a key benefit of a reputable password manager?",
    options: [
      { id: "generate", label: "It can generate and store strong unique passwords" },
      { id: "share", label: "It publishes passwords so friends can remember them" },
      { id: "disable", label: "It disables account security checks" },
      { id: "same", label: "It forces every site to use the same password" },
    ],
    answer: "generate",
    explanation: "A password manager can create and securely store unique passwords, reducing reuse and memorisation pressure.",
  }),

  entry("skills", "digital", "core", "safety", "phishing", "urgency", {
    kind: "single",
    subject: "Online Safety",
    topic: "Phishing awareness",
    skill: "Recognise phishing tactics",
    difficulty: 2,
    prompt: "Which message is the strongest phishing warning sign?",
    options: [
      { id: "urgent", label: "An unexpected message demanding immediate login through a link to avoid account closure" },
      { id: "receipt", label: "A receipt you expected from a purchase you just made" },
      { id: "calendar", label: "A calendar reminder you created yourself" },
      { id: "draft", label: "A document saved locally on your device" },
    ],
    answer: "urgent",
    explanation: "Unexpected urgency, threats and login links are common social-engineering signals and should be verified independently.",
  }),
  entry("skills", "digital", "core", "safety", "phishing", "domain", {
    kind: "single",
    subject: "Online Safety",
    topic: "Phishing awareness",
    skill: "Inspect suspicious links",
    difficulty: 3,
    prompt: "Before opening a login link in an unexpected email, what is the safest first check?",
    options: [
      { id: "verify", label: "Verify the real destination/domain and access the service independently if unsure" },
      { id: "click", label: "Click immediately because the logo looks correct" },
      { id: "reply", label: "Reply with your password to confirm identity" },
      { id: "forward", label: "Forward it to everyone in your contacts" },
    ],
    answer: "verify",
    explanation: "Phishing can imitate branding, so verifying the destination and using a known route to the service is safer than trusting the message link.",
  }),
  entry("skills", "digital", "core", "safety", "phishing", "attachment", {
    kind: "boolean",
    subject: "Online Safety",
    topic: "Phishing awareness",
    skill: "Handle unexpected attachments",
    difficulty: 2,
    prompt: "True or false: An unexpected attachment should be opened simply because the sender name looks familiar.",
    answer: false,
    explanation: "Sender names can be spoofed or accounts can be compromised, so unexpected attachments should be verified before opening.",
  }),

  entry("skills", "reasoning", "core", "numerical", "ratios", "scale", {
    kind: "numeric",
    subject: "Numerical Reasoning",
    topic: "Ratios",
    skill: "Scale ratios",
    difficulty: 2,
    prompt: "A team has men and women in the ratio 2:3. If there are 25 people in total, how many are men?",
    answer: 10,
    acceptedAnswers: ["10"],
    explanation: "There are 5 ratio parts. Each part is 25 ÷ 5 = 5, so men = 2 × 5 = 10.",
  }),
  entry("skills", "reasoning", "core", "numerical", "ratios", "equivalent", {
    kind: "single",
    subject: "Numerical Reasoning",
    topic: "Ratios",
    skill: "Recognise equivalent ratios",
    difficulty: 2,
    prompt: "Which ratio is equivalent to 4:6?",
    options: [
      { id: "two-three", label: "2:3" },
      { id: "three-four", label: "3:4" },
      { id: "four-five", label: "4:5" },
      { id: "one-two", label: "1:2" },
    ],
    answer: "two-three",
    explanation: "Dividing both terms of 4:6 by 2 gives 2:3.",
  }),
  entry("skills", "reasoning", "core", "numerical", "ratios", "share", {
    kind: "numeric",
    subject: "Numerical Reasoning",
    topic: "Ratios",
    skill: "Share quantities in a ratio",
    difficulty: 3,
    prompt: "GH₵360 is shared in the ratio 5:4. What is the larger share in Ghana cedis?",
    answer: 200,
    acceptedAnswers: ["200", "GH₵200", "GHS 200"],
    explanation: "There are 9 parts, so each part is 360 ÷ 9 = 40. The larger share is 5 × 40 = 200.",
  }),

  entry("skills", "reasoning", "core", "numerical", "patterns", "arithmetic", {
    kind: "numeric",
    subject: "Numerical Reasoning",
    topic: "Number patterns",
    skill: "Continue arithmetic sequences",
    difficulty: 2,
    prompt: "What is the next number in the sequence 7, 11, 15, 19, ...?",
    answer: 23,
    acceptedAnswers: ["23"],
    explanation: "The sequence increases by 4 each time, so 19 + 4 = 23.",
  }),
  entry("skills", "reasoning", "core", "numerical", "patterns", "multiplicative", {
    kind: "numeric",
    subject: "Numerical Reasoning",
    topic: "Number patterns",
    skill: "Continue multiplicative sequences",
    difficulty: 2,
    prompt: "What is the next number in the sequence 3, 6, 12, 24, ...?",
    answer: 48,
    acceptedAnswers: ["48"],
    explanation: "Each term is double the previous term, so 24 × 2 = 48.",
  }),
  entry("skills", "reasoning", "core", "numerical", "patterns", "difference", {
    kind: "numeric",
    subject: "Numerical Reasoning",
    topic: "Number patterns",
    skill: "Identify changing differences",
    difficulty: 3,
    prompt: "What is the next number in the sequence 2, 5, 10, 17, 26, ...?",
    answer: 37,
    acceptedAnswers: ["37"],
    explanation: "The differences are +3, +5, +7, +9; the next difference is +11, so 26 + 11 = 37.",
  }),

  entry("skills", "reasoning", "core", "verbal", "analogies", "bird", {
    kind: "single",
    subject: "Verbal Reasoning",
    topic: "Analogies",
    skill: "Recognise word relationships",
    difficulty: 2,
    prompt: "Bird is to nest as bee is to:",
    options: [
      { id: "hive", label: "Hive" },
      { id: "web", label: "Web" },
      { id: "den", label: "Den" },
      { id: "stable", label: "Stable" },
    ],
    answer: "hive",
    explanation: "A nest is a typical home for a bird, while a hive is a typical home for bees.",
  }),
  entry("skills", "reasoning", "core", "verbal", "analogies", "author", {
    kind: "single",
    subject: "Verbal Reasoning",
    topic: "Analogies",
    skill: "Recognise producer-product relationships",
    difficulty: 2,
    prompt: "Author is to book as composer is to:",
    options: [
      { id: "music", label: "Music" },
      { id: "camera", label: "Camera" },
      { id: "school", label: "School" },
      { id: "brush", label: "Brush" },
    ],
    answer: "music",
    explanation: "An author creates a book; a composer creates music.",
  }),
  entry("skills", "reasoning", "core", "verbal", "analogies", "thermometer", {
    kind: "single",
    subject: "Verbal Reasoning",
    topic: "Analogies",
    skill: "Recognise tool-function relationships",
    difficulty: 3,
    prompt: "Thermometer is to temperature as scale is to:",
    options: [
      { id: "weight", label: "Weight" },
      { id: "distance", label: "Distance" },
      { id: "time", label: "Time" },
      { id: "sound", label: "Sound" },
    ],
    answer: "weight",
    explanation: "A thermometer measures temperature; a scale measures weight.",
  }),
];

export const SPECIALIZED_QUESTION_ENTRIES: SpecializedQuestionEntry[] = [
  ...universityEntries,
  ...skillEntries,
];

export function specializedQuestionsForSelection(config: SessionConfig): LearnQuestion[] {
  return SPECIALIZED_QUESTION_ENTRIES
    .filter((item) => item.lane === config.lane)
    .filter((item) => item.programId === config.programId)
    .filter((item) => item.levelId === config.levelId)
    .filter((item) => config.subjectId === "all" || item.subjectId === config.subjectId)
    .filter((item) => config.topicId === "all" || item.topicId === config.topicId)
    .map((item) => item.question);
}
