import { auditQuestionPack, releaseQuestion, type FoundryQuestion, type VerificationCheck } from "./question-foundry";
import type { LearnQuestion } from "./learn-domain";

const checks: VerificationCheck[] = [
  "answer-check",
  "ambiguity-check",
  "curriculum-check",
  "duplicate-check",
  "age-check",
];

const source = {
  kind: "original" as const,
  name: "SukuuNova original topic-depth content",
};

function review() {
  return {
    status: "verified" as const,
    checks: [...checks],
    confidence: 0.97,
    reviewer: "SukuuNova content QA",
    reviewedAt: "2026-09-17T00:00:00.000Z",
  };
}

function dna(input: {
  subject: string;
  topic: string;
  objective: string;
  skill: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  cognitiveSkill: "remember" | "understand" | "apply" | "analyse" | "evaluate" | "create";
  estimatedSeconds?: number;
}) {
  return {
    country: "GH",
    framework: "SukuuNova starter alignment",
    frameworkVersion: "2026.1",
    level: "JHS foundation",
    subject: input.subject,
    topic: input.topic,
    objective: input.objective,
    skill: input.skill,
    difficulty: input.difficulty,
    cognitiveSkill: input.cognitiveSkill,
    language: "en-GH",
    estimatedSeconds: input.estimatedSeconds ?? 45,
  };
}

export const DEPTH_FOUNDRY_PACK: FoundryQuestion[] = [
  {
    id: "depth-math-number-002",
    exposureKey: "math-order-operations-002",
    kind: "numeric",
    subject: "Mathematics",
    topic: "Number & operations",
    skill: "Apply order of operations",
    difficulty: 2,
    prompt: "Evaluate 3 + 4 × 2.",
    answer: 11,
    acceptedAnswers: ["11"],
    explanation: "Multiplication comes before addition: 4 × 2 = 8, then 3 + 8 = 11.",
    hint: "Do the multiplication before the addition.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Number & operations", objective: "Apply the conventional order of operations to a short expression", skill: "Apply order of operations", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-math-algebra-002",
    exposureKey: "math-linear-equation-3x5-002",
    kind: "numeric",
    subject: "Mathematics",
    topic: "Algebra",
    skill: "Solve a one-variable linear equation",
    difficulty: 2,
    prompt: "Solve for x: 3x + 5 = 20.",
    answer: 5,
    acceptedAnswers: ["5"],
    explanation: "Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5.",
    hint: "Undo the +5 first, then divide by 3.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Algebra", objective: "Solve a two-step linear equation in one variable", skill: "Solve a one-variable linear equation", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-math-geometry-002",
    exposureKey: "math-triangle-angle-sum-002",
    kind: "numeric",
    subject: "Mathematics",
    topic: "Geometry",
    skill: "Use the angle sum of a triangle",
    difficulty: 2,
    prompt: "Two angles of a triangle are 50° and 60°. What is the third angle in degrees?",
    answer: 70,
    acceptedAnswers: ["70"],
    explanation: "Angles in a triangle add to 180°. So the third angle is 180 − 50 − 60 = 70°.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Geometry", objective: "Find a missing triangle angle using the 180-degree angle sum", skill: "Use the angle sum of a triangle", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-math-statistics-002",
    exposureKey: "math-probability-even-die-002",
    kind: "single",
    subject: "Mathematics",
    topic: "Statistics & probability",
    skill: "Calculate a simple probability",
    difficulty: 2,
    prompt: "A fair six-sided die is rolled once. What is the probability of rolling an even number?",
    options: [
      { id: "half", label: "1/2" },
      { id: "third", label: "1/3" },
      { id: "two-thirds", label: "2/3" },
      { id: "one", label: "1" },
    ],
    answer: "half",
    explanation: "The even outcomes are 2, 4 and 6: three favourable outcomes out of six equally likely outcomes, so 3/6 = 1/2.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Statistics & probability", objective: "Calculate probability from equally likely outcomes", skill: "Calculate a simple probability", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-english-grammar-002",
    exposureKey: "english-subject-verb-list-002",
    kind: "single",
    subject: "English Language",
    topic: "Grammar & concord",
    skill: "Apply subject-verb agreement",
    difficulty: 2,
    prompt: "Choose the correct verb: The list of items ___ on the table.",
    options: [
      { id: "is", label: "is" },
      { id: "are", label: "are" },
      { id: "were", label: "were" },
      { id: "be", label: "be" },
    ],
    answer: "is",
    explanation: "The head noun of the subject is the singular noun ‘list’, so the singular verb ‘is’ agrees with it.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Grammar & concord", objective: "Choose a verb that agrees with the head noun of a subject phrase", skill: "Apply subject-verb agreement", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-english-vocabulary-002",
    exposureKey: "english-synonym-rapid-002",
    kind: "single",
    subject: "English Language",
    topic: "Vocabulary",
    skill: "Recognise a synonym from context-free vocabulary",
    difficulty: 1,
    prompt: "Which word is closest in meaning to ‘rapid’?",
    options: [
      { id: "fast", label: "fast" },
      { id: "silent", label: "silent" },
      { id: "heavy", label: "heavy" },
      { id: "narrow", label: "narrow" },
    ],
    answer: "fast",
    explanation: "‘Rapid’ means happening or moving very quickly, so ‘fast’ is the closest synonym.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Vocabulary", objective: "Identify a common synonym for a familiar adjective", skill: "Recognise a synonym from context-free vocabulary", difficulty: 1, cognitiveSkill: "remember" }),
    source,
    review: review(),
  },
  {
    id: "depth-english-reading-002",
    exposureKey: "english-reading-inference-clouds-002",
    kind: "single",
    subject: "English Language",
    topic: "Reading comprehension",
    skill: "Make a simple inference from details",
    difficulty: 2,
    prompt: "Read: ‘Kojo saw dark clouds gathering before he left home, so he put an umbrella in his bag.’ What can you reasonably infer?",
    options: [
      { id: "rain", label: "Kojo thought rain was possible" },
      { id: "lost", label: "Kojo had lost his school bag" },
      { id: "sun", label: "Kojo expected stronger sunshine" },
      { id: "broken", label: "Kojo knew the umbrella was broken" },
    ],
    answer: "rain",
    explanation: "Dark gathering clouds can signal rain, and taking an umbrella is a sensible preparation for that possibility.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Reading comprehension", objective: "Infer a likely reason for an action using explicit passage details", skill: "Make a simple inference from details", difficulty: 2, cognitiveSkill: "analyse" }),
    source,
    review: review(),
  },
  {
    id: "depth-english-writing-002",
    exposureKey: "english-sequence-transition-002",
    kind: "fill",
    subject: "English Language",
    topic: "Writing",
    skill: "Use a sequence transition",
    difficulty: 2,
    prompt: "Complete the sequence with a suitable final transition: First, wash the fruit. Next, cut it into pieces. ___, serve it in a clean bowl.",
    answer: "finally",
    acceptedAnswers: ["finally", "lastly"],
    explanation: "‘Finally’ or ‘lastly’ clearly signals the last step in a sequence of instructions.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Writing", objective: "Use an appropriate transition to signal the final step in a sequence", skill: "Use a sequence transition", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-science-living-002",
    exposureKey: "science-lungs-gas-exchange-002",
    kind: "single",
    subject: "Science",
    topic: "Living things",
    skill: "Identify an organ involved in gas exchange",
    difficulty: 1,
    prompt: "Which human organ is primarily responsible for exchanging oxygen and carbon dioxide with the air?",
    options: [
      { id: "lungs", label: "Lungs" },
      { id: "kidneys", label: "Kidneys" },
      { id: "stomach", label: "Stomach" },
      { id: "bladder", label: "Bladder" },
    ],
    answer: "lungs",
    explanation: "Gas exchange occurs in the lungs, where oxygen enters the blood and carbon dioxide leaves it.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Living things", objective: "Identify the principal organ of human gas exchange", skill: "Identify an organ involved in gas exchange", difficulty: 1, cognitiveSkill: "remember" }),
    source,
    review: review(),
  },
  {
    id: "depth-science-matter-002",
    exposureKey: "science-evaporation-state-change-002",
    kind: "single",
    subject: "Science",
    topic: "Matter & materials",
    skill: "Identify a change of state",
    difficulty: 1,
    prompt: "What is the change of state called when liquid water changes into water vapour at its surface?",
    options: [
      { id: "evaporation", label: "Evaporation" },
      { id: "freezing", label: "Freezing" },
      { id: "condensation", label: "Condensation" },
      { id: "melting", label: "Melting" },
    ],
    answer: "evaporation",
    explanation: "Evaporation is the change from liquid to gas that occurs at the surface of a liquid.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Matter & materials", objective: "Identify evaporation as a liquid-to-gas change of state", skill: "Identify a change of state", difficulty: 1, cognitiveSkill: "remember" }),
    source,
    review: review(),
  },
  {
    id: "depth-science-energy-002",
    exposureKey: "science-speed-distance-time-002",
    kind: "numeric",
    subject: "Science",
    topic: "Force & energy",
    skill: "Calculate average speed",
    difficulty: 2,
    prompt: "A cyclist travels 120 metres in 20 seconds. What is the average speed in metres per second?",
    answer: 6,
    acceptedAnswers: ["6"],
    explanation: "Average speed = distance ÷ time, so 120 ÷ 20 = 6 m/s.",
    hint: "Divide the distance travelled by the time taken.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Force & energy", objective: "Calculate average speed from distance and time", skill: "Calculate average speed", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-science-environment-002",
    exposureKey: "science-condensation-water-cycle-002",
    kind: "single",
    subject: "Science",
    topic: "Environment",
    skill: "Recognise condensation in the water cycle",
    difficulty: 2,
    prompt: "In the water cycle, what process changes water vapour into tiny liquid water droplets?",
    options: [
      { id: "condensation", label: "Condensation" },
      { id: "evaporation", label: "Evaporation" },
      { id: "infiltration", label: "Infiltration" },
      { id: "transpiration", label: "Transpiration" },
    ],
    answer: "condensation",
    explanation: "Condensation occurs when water vapour cools and changes into liquid droplets, helping clouds form.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Environment", objective: "Identify condensation as a process in the water cycle", skill: "Recognise condensation in the water cycle", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "depth-social-governance-002",
    exposureKey: "social-accountable-governance-002",
    kind: "single",
    subject: "Social Studies",
    topic: "Governance",
    skill: "Recognise a practice that supports accountability",
    difficulty: 2,
    prompt: "Which action best supports accountable public governance?",
    options: [
      { id: "publish", label: "Publishing clear information about how public funds are used" },
      { id: "hide", label: "Keeping all public decisions permanently secret" },
      { id: "ignore", label: "Ignoring established procedures whenever convenient" },
      { id: "exclude", label: "Preventing citizens from receiving any public information" },
    ],
    answer: "publish",
    explanation: "Clear information about public spending supports transparency and makes it easier for institutions and citizens to hold decision-makers accountable.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "Governance", objective: "Identify a transparent practice that supports public accountability", skill: "Recognise a practice that supports accountability", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "depth-social-citizenship-002",
    exposureKey: "social-civic-responsibility-002",
    kind: "multi",
    subject: "Social Studies",
    topic: "Citizenship",
    skill: "Identify constructive civic responsibilities",
    difficulty: 2,
    prompt: "Select every action that demonstrates responsible citizenship in a community.",
    options: [
      { id: "property", label: "Protecting shared public property" },
      { id: "rules", label: "Following lawful community rules" },
      { id: "vandalise", label: "Damaging public facilities for fun" },
      { id: "litter", label: "Throwing rubbish into public drains" },
    ],
    answer: ["property", "rules"],
    explanation: "Protecting shared property and following lawful rules support the community. Vandalism and littering harm shared spaces and other people.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "Citizenship", objective: "Distinguish constructive civic responsibilities from harmful actions", skill: "Identify constructive civic responsibilities", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "depth-social-environment-002",
    exposureKey: "social-vegetation-erosion-002",
    kind: "boolean",
    subject: "Social Studies",
    topic: "People & environment",
    skill: "Relate vegetation cover to soil protection",
    difficulty: 2,
    prompt: "True or false: Maintaining vegetation cover can help reduce soil erosion.",
    answer: true,
    explanation: "Plant roots help hold soil in place, while leaves and ground cover reduce the direct impact of rain and slow surface runoff.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "People & environment", objective: "Explain how vegetation can help protect soil from erosion", skill: "Relate vegetation cover to soil protection", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "depth-social-development-002",
    exposureKey: "social-skilled-workforce-development-002",
    kind: "single",
    subject: "Social Studies",
    topic: "National development",
    skill: "Connect skills development to national development",
    difficulty: 2,
    prompt: "How can investment in education and skills contribute to long-term national development?",
    options: [
      { id: "capacity", label: "It can increase the knowledge and productive capacity of the workforce" },
      { id: "resources", label: "It automatically creates unlimited natural resources" },
      { id: "weather", label: "It guarantees identical weather every year" },
      { id: "distance", label: "It removes all physical distance between towns" },
    ],
    answer: "capacity",
    explanation: "Education and skills can strengthen human capital, helping people perform productive work, adapt to change and contribute new ideas.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "National development", objective: "Explain a way human-capital investment can support development", skill: "Connect skills development to national development", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "depth-computing-safety-002",
    exposureKey: "computing-phishing-signals-002",
    kind: "multi",
    subject: "Computing",
    topic: "Digital safety",
    skill: "Recognise common phishing warning signs",
    difficulty: 2,
    prompt: "Select every sign that should make you more cautious about a message claiming to be from an online service.",
    options: [
      { id: "urgent", label: "It creates unusual urgency and threatens immediate account loss" },
      { id: "password", label: "It asks you to send your password in a reply" },
      { id: "expected", label: "It is an expected message you independently verified in the official app" },
      { id: "known", label: "It appears inside the official service after you opened the app yourself" },
    ],
    answer: ["urgent", "password"],
    explanation: "Artificial urgency and requests for passwords are common phishing warning signs. Independently verified messages in an official app are less suspicious.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Digital safety", objective: "Identify common warning signs of phishing attempts", skill: "Recognise common phishing warning signs", difficulty: 2, cognitiveSkill: "analyse" }),
    source,
    review: review(),
  },
  {
    id: "depth-computing-systems-002",
    exposureKey: "computing-cpu-purpose-002",
    kind: "single",
    subject: "Computing",
    topic: "Computer systems",
    skill: "Recognise the role of the CPU",
    difficulty: 1,
    prompt: "Which description best matches the role of a computer's CPU?",
    options: [
      { id: "instructions", label: "It executes instructions and performs processing operations" },
      { id: "paper", label: "It stores printed paper inside the computer" },
      { id: "sound", label: "It replaces every speaker connected to the computer" },
      { id: "internet", label: "It guarantees an internet connection without networking hardware" },
    ],
    answer: "instructions",
    explanation: "The central processing unit executes program instructions and performs arithmetic, logic and control operations.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Computer systems", objective: "Identify the central processing unit's core processing role", skill: "Recognise the role of the CPU", difficulty: 1, cognitiveSkill: "remember" }),
    source,
    review: review(),
  },
  {
    id: "depth-computing-internet-002",
    exposureKey: "computing-https-meaning-002",
    kind: "single",
    subject: "Computing",
    topic: "Internet & networks",
    skill: "Interpret HTTPS accurately",
    difficulty: 3,
    prompt: "What does HTTPS most directly indicate when you connect to a website?",
    options: [
      { id: "encrypted", label: "The connection between your browser and the site is encrypted using HTTPS" },
      { id: "truth", label: "Every statement on the website is guaranteed to be true" },
      { id: "safe", label: "The website can never contain scams or harmful content" },
      { id: "free", label: "Everything on the website must be free" },
    ],
    answer: "encrypted",
    explanation: "HTTPS protects data in transit between the browser and site using encryption. It does not guarantee that the site's content or intentions are trustworthy.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Internet & networks", objective: "Distinguish transport encryption from a guarantee that website content is trustworthy", skill: "Interpret HTTPS accurately", difficulty: 3, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "depth-computing-coding-002",
    exposureKey: "computing-decomposition-002",
    kind: "single",
    subject: "Computing",
    topic: "Computational thinking",
    skill: "Recognise decomposition",
    difficulty: 2,
    prompt: "In computational thinking, what does decomposition mean?",
    options: [
      { id: "parts", label: "Breaking a complex problem into smaller manageable parts" },
      { id: "guess", label: "Guessing an answer without examining the problem" },
      { id: "repeat", label: "Repeating the same instruction forever" },
      { id: "delete", label: "Deleting every detail before understanding the task" },
    ],
    answer: "parts",
    explanation: "Decomposition makes a complex problem easier to work with by dividing it into smaller parts that can be understood and solved separately.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Computational thinking", objective: "Recognise decomposition as breaking a complex problem into smaller parts", skill: "Recognise decomposition", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
];

export const DEPTH_PACK_AUDIT = auditQuestionPack(DEPTH_FOUNDRY_PACK);

export const VERIFIED_DEPTH_QUESTIONS: LearnQuestion[] = DEPTH_FOUNDRY_PACK
  .map(releaseQuestion)
  .filter((question): question is LearnQuestion => question !== null);
