import { auditQuestionPack, releaseQuestion, type FoundryQuestion, type VerificationCheck } from "./question-foundry";
import type { LearnQuestion } from "./learn-domain";

const checks: VerificationCheck[] = [
  "answer-check",
  "ambiguity-check",
  "curriculum-check",
  "duplicate-check",
  "age-check",
];

const source = {
  kind: "original" as const,
  name: "SukuuNova original balanced expansion content",
};

function review() {
  return {
    status: "verified" as const,
    checks: [...checks],
    confidence: 0.97,
    reviewer: "SukuuNova content QA",
    reviewedAt: "2026-09-17T00:00:00.000Z",
  };
}

function dna(input: {
  subject: string;
  topic: string;
  objective: string;
  skill: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  cognitiveSkill: "remember" | "understand" | "apply" | "analyse" | "evaluate" | "create";
  estimatedSeconds?: number;
}) {
  return {
    country: "GH",
    framework: "SukuuNova starter alignment",
    frameworkVersion: "2026.1",
    level: "JHS foundation",
    subject: input.subject,
    topic: input.topic,
    objective: input.objective,
    skill: input.skill,
    difficulty: input.difficulty,
    cognitiveSkill: input.cognitiveSkill,
    language: "en-GH",
    estimatedSeconds: input.estimatedSeconds ?? 45,
  };
}

export const EXPANSION_FOUNDRY_PACK: FoundryQuestion[] = [
  {
    id: "expand-math-geometry-001",
    exposureKey: "math-rectangle-area-001",
    kind: "numeric",
    subject: "Mathematics",
    topic: "Geometry",
    skill: "Calculate the area of a rectangle",
    difficulty: 2,
    prompt: "A rectangle is 8 cm long and 5 cm wide. What is its area in square centimetres?",
    answer: 40,
    acceptedAnswers: ["40"],
    explanation: "Area of a rectangle is length × width. Therefore 8 × 5 = 40 cm².",
    hint: "Multiply the length by the width.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Geometry", objective: "Calculate the area of a rectangle from given dimensions", skill: "Calculate the area of a rectangle", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-math-statistics-001",
    exposureKey: "math-mean-four-values-001",
    kind: "numeric",
    subject: "Mathematics",
    topic: "Statistics & probability",
    skill: "Calculate an arithmetic mean",
    difficulty: 2,
    prompt: "Find the mean of 4, 6, 8 and 10.",
    answer: 7,
    acceptedAnswers: ["7"],
    explanation: "Add the values to get 28, then divide by the four values: 28 ÷ 4 = 7.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Statistics & probability", objective: "Calculate the arithmetic mean of a small data set", skill: "Calculate an arithmetic mean", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-math-number-001",
    exposureKey: "math-equivalent-fractions-001",
    kind: "multi",
    subject: "Mathematics",
    topic: "Number & operations",
    skill: "Recognise equivalent fractions",
    difficulty: 2,
    prompt: "Select every fraction that is equivalent to one half.",
    options: [
      { id: "two-fourths", label: "2/4" },
      { id: "three-sixths", label: "3/6" },
      { id: "four-eighths", label: "4/8" },
      { id: "three-fifths", label: "3/5" },
    ],
    answer: ["two-fourths", "three-sixths", "four-eighths"],
    explanation: "2/4, 3/6 and 4/8 each simplify to 1/2. The fraction 3/5 does not.",
    version: 1,
    dna: dna({ subject: "Mathematics", topic: "Number & operations", objective: "Identify fractions equivalent to one half", skill: "Recognise equivalent fractions", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-english-reading-001",
    exposureKey: "english-reading-main-idea-001",
    kind: "single",
    subject: "English Language",
    topic: "Reading comprehension",
    skill: "Identify the main idea of a short passage",
    difficulty: 2,
    prompt: "Read: ‘Mina carries a reusable bottle to school each day. She refills it instead of buying disposable plastic bottles.’ What is the main idea?",
    options: [
      { id: "reuse", label: "Mina reduces disposable-bottle use by refilling a reusable bottle" },
      { id: "late", label: "Mina usually arrives late for school" },
      { id: "sport", label: "Mina is preparing for a sports competition" },
      { id: "shop", label: "Mina sells bottled water at school" },
    ],
    answer: "reuse",
    explanation: "Both sentences focus on Mina repeatedly using one bottle instead of buying disposable bottles.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Reading comprehension", objective: "Identify the main idea stated across a short passage", skill: "Identify the main idea of a short passage", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-english-writing-001",
    exposureKey: "english-topic-sentence-001",
    kind: "single",
    subject: "English Language",
    topic: "Writing",
    skill: "Choose a focused topic sentence",
    difficulty: 2,
    prompt: "Which sentence is the best topic sentence for a paragraph about the benefits of regular reading?",
    options: [
      { id: "benefits", label: "Regular reading can strengthen vocabulary, knowledge and concentration." },
      { id: "book", label: "The book on my desk has a blue cover." },
      { id: "yesterday", label: "Yesterday was Tuesday." },
      { id: "pen", label: "My pen stopped working during class." },
    ],
    answer: "benefits",
    explanation: "A topic sentence should introduce the paragraph’s central idea. The first option directly introduces several benefits of regular reading.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Writing", objective: "Select a topic sentence that clearly introduces a paragraph focus", skill: "Choose a focused topic sentence", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-english-grammar-001",
    exposureKey: "english-pronoun-agreement-001",
    kind: "fill",
    subject: "English Language",
    topic: "Grammar & concord",
    skill: "Use plural pronouns accurately",
    difficulty: 2,
    prompt: "Complete the sentence with the correct pronoun: The players packed ___ boots after training.",
    answer: "their",
    acceptedAnswers: ["their"],
    explanation: "‘Players’ is plural, so the possessive determiner ‘their’ agrees with the plural noun.",
    version: 1,
    dna: dna({ subject: "English Language", topic: "Grammar & concord", objective: "Use a pronoun that agrees with a plural antecedent", skill: "Use plural pronouns accurately", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-science-energy-001",
    exposureKey: "science-force-motion-001",
    kind: "single",
    subject: "Science",
    topic: "Force & energy",
    skill: "Relate force to changes in motion",
    difficulty: 2,
    prompt: "Which statement best describes one effect a force can have on a moving object?",
    options: [
      { id: "motion", label: "It can change the object’s speed or direction" },
      { id: "mass", label: "It always changes the object’s mass" },
      { id: "matter", label: "It turns every object into a liquid" },
      { id: "time", label: "It stops time around the object" },
    ],
    answer: "motion",
    explanation: "A force can change an object’s motion by making it speed up, slow down or change direction.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Force & energy", objective: "Recognise how force can change an object's motion", skill: "Relate force to changes in motion", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-science-environment-001",
    exposureKey: "science-renewable-resource-001",
    kind: "single",
    subject: "Science",
    topic: "Environment",
    skill: "Distinguish renewable energy resources",
    difficulty: 2,
    prompt: "Which energy source is renewable because it is naturally replenished on a human timescale?",
    options: [
      { id: "solar", label: "Sunlight" },
      { id: "coal", label: "Coal" },
      { id: "oil", label: "Crude oil" },
      { id: "gas", label: "Natural gas" },
    ],
    answer: "solar",
    explanation: "Sunlight is continually supplied by the Sun, while coal, crude oil and natural gas are finite fossil-fuel resources.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Environment", objective: "Distinguish a renewable energy source from fossil fuels", skill: "Distinguish renewable energy resources", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-science-living-001",
    exposureKey: "science-photosynthesis-light-001",
    kind: "boolean",
    subject: "Science",
    topic: "Living things",
    skill: "Recognise a requirement for photosynthesis",
    difficulty: 2,
    prompt: "True or false: Light provides the energy plants use during photosynthesis.",
    answer: true,
    explanation: "Photosynthesis uses light energy to help convert carbon dioxide and water into glucose, releasing oxygen as a product.",
    version: 1,
    dna: dna({ subject: "Science", topic: "Living things", objective: "Recognise light as an energy input for photosynthesis", skill: "Recognise a requirement for photosynthesis", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-social-environment-001",
    exposureKey: "social-waste-drainage-001",
    kind: "single",
    subject: "Social Studies",
    topic: "People & environment",
    skill: "Connect human behaviour to environmental effects",
    difficulty: 2,
    prompt: "Which is a likely consequence of dumping solid waste into open drains?",
    options: [
      { id: "blockage", label: "Blocked drainage and increased local flooding risk" },
      { id: "rain", label: "More rainfall is automatically created" },
      { id: "soil", label: "Every type of soil becomes more fertile" },
      { id: "traffic", label: "Road traffic immediately disappears" },
    ],
    answer: "blockage",
    explanation: "Solid waste can obstruct drains, reducing water flow and increasing the risk of local flooding when water accumulates.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "People & environment", objective: "Explain an environmental consequence of improper waste disposal", skill: "Connect human behaviour to environmental effects", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-social-development-001",
    exposureKey: "social-development-actions-001",
    kind: "multi",
    subject: "Social Studies",
    topic: "National development",
    skill: "Identify actions that support development",
    difficulty: 2,
    prompt: "Select every action that can support long-term national development.",
    options: [
      { id: "education", label: "Investing in education and skills" },
      { id: "infrastructure", label: "Maintaining useful public infrastructure" },
      { id: "vandalism", label: "Destroying shared public facilities" },
      { id: "waste", label: "Wasting productive resources deliberately" },
    ],
    answer: ["education", "infrastructure"],
    explanation: "Education builds human capacity, while reliable infrastructure supports economic and social activity. Vandalism and deliberate waste weaken development.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "National development", objective: "Identify constructive actions that can support national development", skill: "Identify actions that support development", difficulty: 2, cognitiveSkill: "apply" }),
    source,
    review: review(),
  },
  {
    id: "expand-social-governance-001",
    exposureKey: "social-rule-of-law-001",
    kind: "single",
    subject: "Social Studies",
    topic: "Governance",
    skill: "Understand the rule of law",
    difficulty: 3,
    prompt: "Which statement best describes the idea of the rule of law?",
    options: [
      { id: "law", label: "Public power should be exercised according to established law" },
      { id: "wealth", label: "Only wealthy people must obey laws" },
      { id: "leaders", label: "Leaders may ignore every law whenever they choose" },
      { id: "secret", label: "Laws should always remain secret from citizens" },
    ],
    answer: "law",
    explanation: "The rule of law requires public authority to operate under established legal rules rather than arbitrary personal power.",
    version: 1,
    dna: dna({ subject: "Social Studies", topic: "Governance", objective: "Explain the basic meaning of the rule of law", skill: "Understand the rule of law", difficulty: 3, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-computing-systems-001",
    exposureKey: "computing-ram-purpose-001",
    kind: "single",
    subject: "Computing",
    topic: "Computer systems",
    skill: "Recognise the role of RAM",
    difficulty: 2,
    prompt: "What is a common role of RAM in a computer?",
    options: [
      { id: "working", label: "Temporarily holding data and instructions being actively used" },
      { id: "paper", label: "Printing documents without a printer" },
      { id: "internet", label: "Creating an internet connection by itself" },
      { id: "battery", label: "Replacing the computer’s battery" },
    ],
    answer: "working",
    explanation: "RAM provides fast temporary working storage for data and instructions the computer is actively using.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Computer systems", objective: "Recognise the purpose of random-access memory", skill: "Recognise the role of RAM", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-computing-internet-001",
    exposureKey: "computing-router-role-001",
    kind: "single",
    subject: "Computing",
    topic: "Internet & networks",
    skill: "Recognise the role of a router",
    difficulty: 2,
    prompt: "Which device commonly forwards data between different networks?",
    options: [
      { id: "router", label: "Router" },
      { id: "keyboard", label: "Keyboard" },
      { id: "speaker", label: "Speaker" },
      { id: "scanner", label: "Scanner" },
    ],
    answer: "router",
    explanation: "A router forwards data packets between networks and commonly connects a local network to other networks.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Internet & networks", objective: "Identify a device used to route data between networks", skill: "Recognise the role of a router", difficulty: 2, cognitiveSkill: "understand" }),
    source,
    review: review(),
  },
  {
    id: "expand-computing-coding-001",
    exposureKey: "computing-algorithm-definition-001",
    kind: "short",
    subject: "Computing",
    topic: "Computational thinking",
    skill: "Describe an algorithm",
    difficulty: 2,
    prompt: "What term describes a finite step-by-step procedure for solving a problem or completing a task?",
    answer: "algorithm",
    acceptedAnswers: ["algorithm", "an algorithm"],
    explanation: "An algorithm is a defined sequence of steps used to solve a problem or perform a task.",
    version: 1,
    dna: dna({ subject: "Computing", topic: "Computational thinking", objective: "Recognise the meaning of an algorithm", skill: "Describe an algorithm", difficulty: 2, cognitiveSkill: "remember" }),
    source,
    review: review(),
  },
];

export const EXPANSION_PACK_AUDIT = auditQuestionPack(EXPANSION_FOUNDRY_PACK);

export const VERIFIED_EXPANSION_QUESTIONS: LearnQuestion[] = EXPANSION_FOUNDRY_PACK
  .map(releaseQuestion)
  .filter((question): question is LearnQuestion => question !== null);
