"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Banknote, CheckCircle2, Clock3, FilePlus2, RefreshCw, Search } from "lucide-react";

type Invoice = { id: string; period: string; amount: number; status: string; createdAt: string; paid: number; outstanding: number; overpaid: number; effectiveStatus: string };
type Summary = { school: { id: string; name: string; uniqueCode: string; status: string; subscriptionPlan?: { name: string; price: number | string } | null }; invoices: Invoice[]; payments: Array<{ id: string; amount: string; method: string; reference: string | null; createdAt: string; platformInvoiceId: string }>; totals: { invoiced: number; paid: number; outstanding: number; overpaid: number } };
function money(value: number) { return `₵${value.toLocaleString()}`; }
function aging(period: string) { const [year, month] = period.split("-").map(Number); const due = new Date(year, month, 0); const days = Math.max(0, Math.floor((Date.now() - due.getTime()) / 86400000)); return days <= 30 ? "0–30d" : days <= 60 ? "31–60d" : days <= 90 ? "61–90d" : "90+d"; }

export default function BillingConsole() {
  const [rows, setRows] = useState<Summary[]>([]), [query, setQuery] = useState(""), [selectedSchool, setSelectedSchool] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const [paymentInvoice, setPaymentInvoice] = useState(""), [paymentAmount, setPaymentAmount] = useState(""), [paymentMethod, setPaymentMethod] = useState("momo"), [paymentReference, setPaymentReference] = useState("");

  async function load() { setBusy(true); try { const response = await fetch("/api/platform/billing", { cache: "no-store" }); const data = await response.json() as { schools?: Summary[]; message?: string; error?: string }; if (!response.ok) { setMessage(data.message ?? data.error ?? "Unable to load billing."); return; } setRows(data.schools ?? []); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);

  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return rows.filter((row) => !q || row.school.name.toLowerCase().includes(q) || row.school.uniqueCode.toLowerCase().includes(q)); }, [query, rows]);
  const metrics = useMemo(() => { const invoices = visible.flatMap((row) => row.invoices); const invoiced = invoices.reduce((n, i) => n + i.amount, 0); const paid = invoices.reduce((n, i) => n + i.paid, 0); const outstanding = invoices.reduce((n, i) => n + i.outstanding, 0); const overpaid = invoices.reduce((n, i) => n + i.overpaid, 0); return { invoiced, paid, outstanding, overpaid, collectionRate: invoiced ? Math.round((paid / invoiced) * 100) : 0 }; }, [visible]);
  const selected = rows.find((row) => row.school.id === selectedSchool) ?? null;
  const selectedInvoices = selected?.invoices ?? [];

  async function generate() { if (!selectedSchool || !period) return; setBusy(true); try { const response = await fetch("/api/platform/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "generate", schoolId: selectedSchool, period }) }); const data = await response.json() as { invoice?: { id: string }; message?: string; error?: string }; setMessage(response.ok ? `Invoice generated for ${period}.` : (data.message ?? data.error ?? "Unable to generate invoice.")); if (response.ok) await load(); } finally { setBusy(false); } }
  async function recordPayment() { if (!selectedSchool || !paymentInvoice) return; const amount = Number(paymentAmount); if (!Number.isFinite(amount) || amount <= 0) { setMessage("Enter a valid payment amount."); return; } setBusy(true); try { const response = await fetch("/api/platform/billing", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "record_payment", schoolId: selectedSchool, invoiceId: paymentInvoice, amount, method: paymentMethod, reference: paymentReference || undefined }) }); const data = await response.json() as { message?: string; error?: string }; setMessage(response.ok ? "Payment recorded and reconciled." : (data.message ?? data.error ?? "Unable to record payment.")); if (response.ok) { setPaymentAmount(""); setPaymentReference(""); await load(); } } finally { setBusy(false); } }

  return <div style={{ display: "grid", gap: 18, marginTop: 20 }}>
    {message ? <div className="app-banner" role="status"><div><h3>{message}</h3><p>Billing actions are permission-checked and written to the platform audit trail.</p></div><span className="app-pill">Audited</span></div> : null}
    <div className="app-grid kpis">
      <div className="app-card app-kpi"><span className="app-kpi-label">Invoiced</span><div className="app-kpi-value">{money(metrics.invoiced)}</div><div className="app-kpi-meta">Visible subscription billing</div></div>
      <div className="app-card app-kpi"><span className="app-kpi-label">Collected</span><div className="app-kpi-value">{money(metrics.paid)}</div><div className="app-kpi-meta">{metrics.collectionRate}% collection rate</div></div>
      <div className="app-card app-kpi"><span className="app-kpi-label">Outstanding</span><div className="app-kpi-value">{money(metrics.outstanding)}</div><div className="app-kpi-meta">Requires collection action</div></div>
      <div className="app-card app-kpi"><span className="app-kpi-label">Overpayments</span><div className="app-kpi-value">{money(metrics.overpaid)}</div><div className="app-kpi-meta">Needs reconciliation review</div></div>
    </div>

    <section className="app-card app-panel" style={{ padding: 20 }}>
      <div className="app-card-head"><div><h2>Billing control center</h2><p>Search the network, identify collection pressure, and drill into the school ledger without leaving Platform Control.</p></div><button className="app-pill" onClick={() => void load()} disabled={busy}><RefreshCw size={14}/> Refresh</button></div>
      <label style={{ display: "flex", alignItems: "center", gap: 8, maxWidth: 560, border: "1px solid var(--sn-line)", borderRadius: 12, padding: "10px 12px", background: "var(--sn-surface)" }}><Search size={15} color="var(--sn-muted)"/><input aria-label="Search billing schools" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search school name or code" style={{ border: 0, outline: 0, width: "100%", background: "transparent", font: "inherit" }}/></label>
      <div style={{ overflowX: "auto", marginTop: 14 }}><div style={{ minWidth: 850 }}>
        <div style={{ display: "grid", gridTemplateColumns: "minmax(250px,2fr) 120px 130px 140px 120px 130px", gap: 12, padding: "10px 12px", borderBottom: "1px solid var(--sn-line)", color: "var(--sn-muted)", fontSize: 9, fontWeight: 850, textTransform: "uppercase", letterSpacing: ".08em" }}><span>School</span><span>Plan</span><span>Invoiced</span><span>Outstanding</span><span>Rate</span><span>Action</span></div>
        {visible.map((row) => { const rate = row.totals.invoiced ? Math.round((row.totals.paid / row.totals.invoiced) * 100) : 0; return <button type="button" key={row.school.id} onClick={() => setSelectedSchool(row.school.id)} style={{ width: "100%", border: 0, borderBottom: "1px solid var(--sn-line)", background: selectedSchool === row.school.id ? "var(--sn-surface-2)" : "var(--sn-surface)", textAlign: "left", cursor: "pointer", display: "grid", gridTemplateColumns: "minmax(250px,2fr) 120px 130px 140px 120px 130px", gap: 12, alignItems: "center", padding: "15px 12px" }}><div><b style={{ display: "block", fontSize: 12 }}>{row.school.name}</b><span style={{ display: "block", marginTop: 2, color: "var(--sn-muted)", fontSize: 10 }}>{row.school.uniqueCode} · {row.invoices.filter((i) => i.effectiveStatus !== "paid").length} open invoices</span></div><span style={{ fontSize: 10 }}>{row.school.subscriptionPlan?.name || "No plan"}</span><span>{money(row.totals.invoiced)}</span><span style={{ color: row.totals.outstanding ? "#9a6700" : "#087443", fontWeight: 800 }}>{money(row.totals.outstanding)}</span><span className="app-pill">{rate}%</span><span className="app-action" style={{ justifyContent: "center" }}><strong>Review</strong><ArrowRight size={13}/></span></button>; })}
        {visible.length === 0 ? <div style={{ padding: 35, textAlign: "center", color: "var(--sn-muted)" }}>No billing records match this search.</div> : null}
      </div></div>
    </section>

    {selected ? <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.35fr) minmax(360px,.65fr)", gap: 18 }}>
      <section className="app-card app-panel" style={{ padding: 20 }}>
        <div className="app-card-head"><div><h2>{selected.school.name}</h2><p>{selected.school.uniqueCode} · {selected.school.subscriptionPlan?.name || "No plan assigned"} · {selected.school.subscriptionPlan ? money(Number(selected.school.subscriptionPlan.price)) + " / month" : ""}</p></div><Link href={`/platform/schools/${selected.school.id}`} className="app-pill">School 360</Link></div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 10, marginBottom: 15 }}><div className="app-card" style={{ padding: 13 }}><Clock3 size={15}/><b style={{ display: "block", marginTop: 5 }}>{selected.invoices.filter((i) => i.effectiveStatus !== "paid").length}</b><span style={{ color: "var(--sn-muted)", fontSize: 10 }}>Open invoices</span></div><div className="app-card" style={{ padding: 13 }}><Banknote size={15}/><b style={{ display: "block", marginTop: 5 }}>{money(selected.totals.paid)}</b><span style={{ color: "var(--sn-muted)", fontSize: 10 }}>Paid</span></div><div className="app-card" style={{ padding: 13 }}><AlertTriangle size={15}/><b style={{ display: "block", marginTop: 5 }}>{money(selected.totals.outstanding)}</b><span style={{ color: "var(--sn-muted)", fontSize: 10 }}>Outstanding</span></div></div>
        <div style={{ overflowX: "auto" }}><div style={{ minWidth: 700 }}><div style={{ display: "grid", gridTemplateColumns: "110px 120px 120px 120px 100px", gap: 10, padding: "9px 10px", borderBottom: "1px solid var(--sn-line)", fontSize: 9, color: "var(--sn-muted)", fontWeight: 850, textTransform: "uppercase" }}><span>Period</span><span>Due</span><span>Paid</span><span>Outstanding</span><span>Age</span></div>{selectedInvoices.map((invoice) => <button type="button" key={invoice.id} onClick={() => setPaymentInvoice(invoice.id)} style={{ width: "100%", border: 0, background: paymentInvoice === invoice.id ? "var(--sn-surface-2)" : "var(--sn-surface)", borderBottom: "1px solid var(--sn-line)", display: "grid", gridTemplateColumns: "110px 120px 120px 120px 100px", gap: 10, padding: "12px 10px", textAlign: "left", cursor: "pointer" }}><span><b>{invoice.period}</b><small style={{ display: "block", color: "var(--sn-muted)", marginTop: 2 }}>{invoice.effectiveStatus}</small></span><span>{money(invoice.amount)}</span><span>{money(invoice.paid)}</span><span style={{ color: invoice.outstanding ? "#9a6700" : "#087443", fontWeight: 800 }}>{money(invoice.outstanding)}</span><span className="app-pill">{aging(invoice.period)}</span></button>)}</div></div>
      </section>
      <section className="app-card app-panel" style={{ padding: 20 }}>
        <div className="app-card-head"><div><h2>Ledger actions</h2><p>Generate the recurring invoice, then reconcile payments against a locked invoice.</p></div></div>
        <label style={{ display: "grid", gap: 5, fontSize: 10, fontWeight: 750 }}><span>Invoice period</span><input type="month" value={period} onChange={(event) => setPeriod(event.target.value)}/></label>
        <button className="app-action" onClick={() => void generate()} disabled={busy || !selected.school.subscriptionPlan} style={{ marginTop: 9 }}><FilePlus2 size={14}/><strong>Generate invoice</strong>{selected.school.subscriptionPlan ? `at ${money(Number(selected.school.subscriptionPlan.price))}` : "assign a plan first"}</button>
        <div style={{ margin: "20px 0 12px", borderTop: "1px solid var(--sn-line)" }}/>
        <label style={{ display: "grid", gap: 5, fontSize: 10, fontWeight: 750 }}><span>Invoice to reconcile</span><select value={paymentInvoice} onChange={(event) => setPaymentInvoice(event.target.value)}><option value="">Choose open invoice…</option>{selectedInvoices.filter((invoice) => invoice.outstanding > 0).map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.period} · {money(invoice.outstanding)} outstanding</option>)}</select></label>
        <label style={{ display: "grid", gap: 5, marginTop: 9, fontSize: 10, fontWeight: 750 }}><span>Payment amount</span><input type="number" min="0.01" step="0.01" value={paymentAmount} onChange={(event) => setPaymentAmount(event.target.value)} placeholder="e.g. 250"/></label>
        <label style={{ display: "grid", gap: 5, marginTop: 9, fontSize: 10, fontWeight: 750 }}><span>Method</span><select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)}><option value="momo">Mobile Money</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option></select></label>
        <label style={{ display: "grid", gap: 5, marginTop: 9, fontSize: 10, fontWeight: 750 }}><span>Reference</span><input value={paymentReference} onChange={(event) => setPaymentReference(event.target.value)} placeholder="Optional transaction reference"/></label>
        <button className="app-action" onClick={() => void recordPayment()} disabled={busy || !paymentInvoice || !paymentAmount} style={{ marginTop: 12 }}><CheckCircle2 size={14}/><strong>Record payment</strong>Recalculate invoice status</button>
      </section>
    </div> : null}
  </div>;
}
