-- Restore Phase 3 operational tables that were previously removed by the biometric consolidation migration.
-- This migration is additive and safe for clean test databases. All restored tables carry schoolId and strict tenant RLS.

CREATE TABLE "P3Vehicle" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"registrationNumber" TEXT NOT NULL,"name" TEXT NOT NULL,"capacity" INTEGER NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'active',"driverName" TEXT,"driverPhone" TEXT,"lastComplianceAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3Vehicle_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3BusRoute" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"origin" TEXT,"destination" TEXT,"status" TEXT NOT NULL DEFAULT 'active',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3BusRoute_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3BusStop" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"name" TEXT NOT NULL,"latitude" DECIMAL(10,7) NOT NULL,"longitude" DECIMAL(10,7) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3BusStop_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3RouteStop" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"routeId" TEXT NOT NULL,"stopId" TEXT NOT NULL,"sequence" INTEGER NOT NULL,"etaMinutes" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "P3RouteStop_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3VehicleLocation" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"vehicleId" TEXT NOT NULL,"routeId" TEXT,"latitude" DECIMAL(10,7) NOT NULL,"longitude" DECIMAL(10,7) NOT NULL,"speedKph" DECIMAL(8,2) NOT NULL DEFAULT 0,"heading" DECIMAL(8,2),"reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"source" TEXT NOT NULL DEFAULT 'gps',CONSTRAINT "P3VehicleLocation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3ParentLocation" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"guardianId" TEXT NOT NULL,"routeId" TEXT,"latitude" DECIMAL(10,7) NOT NULL,"longitude" DECIMAL(10,7) NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3ParentLocation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3BoardingEvent" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"vehicleId" TEXT NOT NULL,"routeId" TEXT,"studentId" TEXT NOT NULL,"type" TEXT NOT NULL,"stopId" TEXT,"eventAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"alertQueued" BOOLEAN NOT NULL DEFAULT false,"createdBy" TEXT NOT NULL,CONSTRAINT "P3BoardingEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3VehicleComplianceReminder" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"vehicleId" TEXT NOT NULL,"kind" TEXT NOT NULL,"dueAt" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"notes" TEXT,"completedAt" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3VehicleComplianceReminder_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3FeedingBudget" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"name" TEXT NOT NULL,"periodStart" TIMESTAMP(3) NOT NULL,"periodEnd" TIMESTAMP(3) NOT NULL,"plannedAmount" DECIMAL(14,2) NOT NULL,"status" TEXT NOT NULL DEFAULT 'active',"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3FeedingBudget_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3FeedingMenu" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"menuDate" TIMESTAMP(3) NOT NULL,"meal" TEXT NOT NULL,"items" JSONB NOT NULL,"plannedCost" DECIMAL(14,2) NOT NULL DEFAULT 0,"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3FeedingMenu_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3FeedingLog" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"menuId" TEXT,"logDate" TIMESTAMP(3) NOT NULL,"meal" TEXT NOT NULL,"servedCount" INTEGER NOT NULL DEFAULT 0,"actualCost" DECIMAL(14,2) NOT NULL DEFAULT 0,"notes" TEXT,"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3FeedingLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3FeedingInvoiceItem" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"description" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"status" TEXT NOT NULL DEFAULT 'optional',"approvedBy" TEXT,"approvedAt" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3FeedingInvoiceItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3Exam" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"durationSeconds" INTEGER NOT NULL,"opensAt" TIMESTAMP(3),"closesAt" TIMESTAMP(3),"status" TEXT NOT NULL DEFAULT 'draft',"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3Exam_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3ExamQuestion" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"examId" TEXT NOT NULL,"prompt" TEXT NOT NULL,"options" JSONB NOT NULL,"correctOptionIndex" INTEGER NOT NULL,"points" DECIMAL(10,2) NOT NULL DEFAULT 1,"orderIndex" INTEGER NOT NULL,CONSTRAINT "P3ExamQuestion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3ExamAttempt" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"examId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"submittedAt" TIMESTAMP(3),"status" TEXT NOT NULL DEFAULT 'in_progress',"score" DECIMAL(14,2) NOT NULL DEFAULT 0,"answers" JSONB NOT NULL DEFAULT '{}',CONSTRAINT "P3ExamAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3LibraryBook" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"isbn" TEXT,"title" TEXT NOT NULL,"author" TEXT,"category" TEXT,"copies" INTEGER NOT NULL DEFAULT 1,"availableCopies" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3LibraryBook_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3LibraryLoan" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"bookId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"borrowedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"dueAt" TIMESTAMP(3) NOT NULL,"returnedAt" TIMESTAMP(3),"status" TEXT NOT NULL DEFAULT 'borrowed',"issuedBy" TEXT NOT NULL,"returnedBy" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3LibraryLoan_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3Asset" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"assetTag" TEXT NOT NULL,"name" TEXT NOT NULL,"category" TEXT,"serialNumber" TEXT,"location" TEXT,"condition" TEXT NOT NULL DEFAULT 'good',"status" TEXT NOT NULL DEFAULT 'active',"purchaseDate" TIMESTAMP(3),"purchaseCost" DECIMAL(14,2),"assignedToUserId" TEXT,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3Asset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3FinanceAdjustment" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"invoiceId" TEXT,"kind" TEXT NOT NULL,"mode" TEXT NOT NULL,"value" DECIMAL(14,2) NOT NULL,"siblingGroupKey" TEXT,"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"requestedBy" TEXT NOT NULL,"approvedBy" TEXT,"approvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3FinanceAdjustment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3RecruitmentPosting" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"title" TEXT NOT NULL,"department" TEXT,"employmentType" TEXT,"description" TEXT,"status" TEXT NOT NULL DEFAULT 'open',"closingDate" TIMESTAMP(3),"createdBy" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3RecruitmentPosting_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3Applicant" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"postingId" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"phone" TEXT,"resumeUrl" TEXT,"status" TEXT NOT NULL DEFAULT 'applied',"notes" TEXT,"staffUserId" TEXT,"convertedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "P3Applicant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "P3OfflineSyncQueue" ("id" TEXT NOT NULL,"schoolId" TEXT NOT NULL,"clientGeneratedId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"payload" JSONB NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"entityId" TEXT,"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"processedAt" TIMESTAMP(3),CONSTRAINT "P3OfflineSyncQueue_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "P3Vehicle_id_schoolId_key" ON "P3Vehicle"("id","schoolId"); CREATE UNIQUE INDEX "P3Vehicle_schoolId_registrationNumber_key" ON "P3Vehicle"("schoolId","registrationNumber");
CREATE UNIQUE INDEX "P3BusRoute_id_schoolId_key" ON "P3BusRoute"("id","schoolId"); CREATE UNIQUE INDEX "P3BusRoute_schoolId_code_key" ON "P3BusRoute"("schoolId","code");
CREATE UNIQUE INDEX "P3BusStop_id_schoolId_key" ON "P3BusStop"("id","schoolId"); CREATE UNIQUE INDEX "P3RouteStop_id_schoolId_key" ON "P3RouteStop"("id","schoolId");
CREATE UNIQUE INDEX "P3VehicleLocation_id_schoolId_key" ON "P3VehicleLocation"("id","schoolId"); CREATE UNIQUE INDEX "P3ParentLocation_id_schoolId_key" ON "P3ParentLocation"("id","schoolId"); CREATE UNIQUE INDEX "P3ParentLocation_schoolId_guardianId_key" ON "P3ParentLocation"("schoolId","guardianId");
CREATE UNIQUE INDEX "P3BoardingEvent_id_schoolId_key" ON "P3BoardingEvent"("id","schoolId"); CREATE UNIQUE INDEX "P3VehicleComplianceReminder_id_schoolId_key" ON "P3VehicleComplianceReminder"("id","schoolId");
CREATE UNIQUE INDEX "P3FeedingBudget_id_schoolId_key" ON "P3FeedingBudget"("id","schoolId"); CREATE UNIQUE INDEX "P3FeedingMenu_id_schoolId_key" ON "P3FeedingMenu"("id","schoolId"); CREATE UNIQUE INDEX "P3FeedingLog_id_schoolId_key" ON "P3FeedingLog"("id","schoolId"); CREATE UNIQUE INDEX "P3FeedingInvoiceItem_id_schoolId_key" ON "P3FeedingInvoiceItem"("id","schoolId");
CREATE UNIQUE INDEX "P3Exam_id_schoolId_key" ON "P3Exam"("id","schoolId"); CREATE UNIQUE INDEX "P3Exam_schoolId_title_key" ON "P3Exam"("schoolId","title"); CREATE UNIQUE INDEX "P3ExamQuestion_id_schoolId_key" ON "P3ExamQuestion"("id","schoolId"); CREATE UNIQUE INDEX "P3ExamAttempt_id_schoolId_key" ON "P3ExamAttempt"("id","schoolId"); CREATE UNIQUE INDEX "P3ExamAttempt_schoolId_examId_studentId_key" ON "P3ExamAttempt"("schoolId","examId","studentId");
CREATE UNIQUE INDEX "P3LibraryBook_id_schoolId_key" ON "P3LibraryBook"("id","schoolId"); CREATE UNIQUE INDEX "P3LibraryBook_schoolId_isbn_key" ON "P3LibraryBook"("schoolId","isbn"); CREATE UNIQUE INDEX "P3LibraryLoan_id_schoolId_key" ON "P3LibraryLoan"("id","schoolId");
CREATE UNIQUE INDEX "P3Asset_id_schoolId_key" ON "P3Asset"("id","schoolId"); CREATE UNIQUE INDEX "P3Asset_schoolId_assetTag_key" ON "P3Asset"("schoolId","assetTag"); CREATE UNIQUE INDEX "P3FinanceAdjustment_id_schoolId_key" ON "P3FinanceAdjustment"("id","schoolId");
CREATE UNIQUE INDEX "P3RecruitmentPosting_id_schoolId_key" ON "P3RecruitmentPosting"("id","schoolId"); CREATE UNIQUE INDEX "P3RecruitmentPosting_schoolId_title_key" ON "P3RecruitmentPosting"("schoolId","title"); CREATE UNIQUE INDEX "P3Applicant_id_schoolId_key" ON "P3Applicant"("id","schoolId"); CREATE UNIQUE INDEX "P3OfflineSyncQueue_schoolId_clientGeneratedId_key" ON "P3OfflineSyncQueue"("schoolId","clientGeneratedId");

CREATE INDEX "P3RouteStop_schoolId_routeId_sequence_idx" ON "P3RouteStop"("schoolId","routeId","sequence"); CREATE INDEX "P3VehicleLocation_schoolId_vehicleId_reportedAt_idx" ON "P3VehicleLocation"("schoolId","vehicleId","reportedAt"); CREATE INDEX "P3BoardingEvent_schoolId_studentId_eventAt_idx" ON "P3BoardingEvent"("schoolId","studentId","eventAt"); CREATE INDEX "P3VehicleComplianceReminder_schoolId_vehicleId_dueAt_idx" ON "P3VehicleComplianceReminder"("schoolId","vehicleId","dueAt");
CREATE INDEX "P3FeedingBudget_schoolId_period_idx" ON "P3FeedingBudget"("schoolId","periodStart","periodEnd"); CREATE INDEX "P3FeedingMenu_schoolId_menuDate_idx" ON "P3FeedingMenu"("schoolId","menuDate"); CREATE INDEX "P3FeedingLog_schoolId_logDate_idx" ON "P3FeedingLog"("schoolId","logDate"); CREATE INDEX "P3FeedingInvoiceItem_schoolId_invoiceId_idx" ON "P3FeedingInvoiceItem"("schoolId","invoiceId");
CREATE INDEX "P3ExamQuestion_schoolId_examId_orderIndex_idx" ON "P3ExamQuestion"("schoolId","examId","orderIndex"); CREATE INDEX "P3ExamAttempt_schoolId_status_idx" ON "P3ExamAttempt"("schoolId","status"); CREATE INDEX "P3LibraryBook_schoolId_title_idx" ON "P3LibraryBook"("schoolId","title"); CREATE INDEX "P3LibraryLoan_schoolId_studentId_status_idx" ON "P3LibraryLoan"("schoolId","studentId","status"); CREATE INDEX "P3LibraryLoan_schoolId_dueAt_idx" ON "P3LibraryLoan"("schoolId","dueAt");
CREATE INDEX "P3Asset_schoolId_status_idx" ON "P3Asset"("schoolId","status"); CREATE INDEX "P3FinanceAdjustment_schoolId_status_idx" ON "P3FinanceAdjustment"("schoolId","status"); CREATE INDEX "P3FinanceAdjustment_schoolId_invoiceId_idx" ON "P3FinanceAdjustment"("schoolId","invoiceId"); CREATE INDEX "P3FinanceAdjustment_schoolId_studentId_idx" ON "P3FinanceAdjustment"("schoolId","studentId");
CREATE INDEX "P3RecruitmentPosting_schoolId_status_idx" ON "P3RecruitmentPosting"("schoolId","status"); CREATE INDEX "P3Applicant_schoolId_postingId_status_idx" ON "P3Applicant"("schoolId","postingId","status"); CREATE INDEX "P3OfflineSyncQueue_schoolId_status_idx" ON "P3OfflineSyncQueue"("schoolId","status");

ALTER TABLE "P3RouteStop" ADD CONSTRAINT "P3RouteStop_route_fkey" FOREIGN KEY ("routeId","schoolId") REFERENCES "P3BusRoute"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3RouteStop" ADD CONSTRAINT "P3RouteStop_stop_fkey" FOREIGN KEY ("stopId","schoolId") REFERENCES "P3BusStop"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3VehicleLocation" ADD CONSTRAINT "P3VehicleLocation_vehicle_fkey" FOREIGN KEY ("vehicleId","schoolId") REFERENCES "P3Vehicle"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3VehicleLocation" ADD CONSTRAINT "P3VehicleLocation_route_fkey" FOREIGN KEY ("routeId","schoolId") REFERENCES "P3BusRoute"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "P3ParentLocation" ADD CONSTRAINT "P3ParentLocation_guardian_fkey" FOREIGN KEY ("guardianId","schoolId") REFERENCES "Guardian"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3ParentLocation" ADD CONSTRAINT "P3ParentLocation_route_fkey" FOREIGN KEY ("routeId","schoolId") REFERENCES "P3BusRoute"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "P3BoardingEvent" ADD CONSTRAINT "P3BoardingEvent_vehicle_fkey" FOREIGN KEY ("vehicleId","schoolId") REFERENCES "P3Vehicle"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3BoardingEvent" ADD CONSTRAINT "P3BoardingEvent_route_fkey" FOREIGN KEY ("routeId","schoolId") REFERENCES "P3BusRoute"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "P3BoardingEvent" ADD CONSTRAINT "P3BoardingEvent_student_fkey" FOREIGN KEY ("studentId","schoolId") REFERENCES "Student"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "P3BoardingEvent" ADD CONSTRAINT "P3BoardingEvent_stop_fkey" FOREIGN KEY ("stopId","schoolId") REFERENCES "P3BusStop"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "P3BoardingEvent" ADD CONSTRAINT "P3BoardingEvent_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3VehicleComplianceReminder" ADD CONSTRAINT "P3VehicleComplianceReminder_vehicle_fkey" FOREIGN KEY ("vehicleId","schoolId") REFERENCES "P3Vehicle"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3VehicleComplianceReminder" ADD CONSTRAINT "P3VehicleComplianceReminder_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3FeedingBudget" ADD CONSTRAINT "P3FeedingBudget_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3FeedingMenu" ADD CONSTRAINT "P3FeedingMenu_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3FeedingLog" ADD CONSTRAINT "P3FeedingLog_menu_fkey" FOREIGN KEY ("menuId","schoolId") REFERENCES "P3FeedingMenu"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "P3FeedingLog" ADD CONSTRAINT "P3FeedingLog_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3FeedingInvoiceItem" ADD CONSTRAINT "P3FeedingInvoiceItem_invoice_fkey" FOREIGN KEY ("invoiceId","schoolId") REFERENCES "Invoice"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3FeedingInvoiceItem" ADD CONSTRAINT "P3FeedingInvoiceItem_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3ExamQuestion" ADD CONSTRAINT "P3ExamQuestion_exam_fkey" FOREIGN KEY ("examId","schoolId") REFERENCES "P3Exam"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3Exam" ADD CONSTRAINT "P3Exam_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3ExamAttempt" ADD CONSTRAINT "P3ExamAttempt_exam_fkey" FOREIGN KEY ("examId","schoolId") REFERENCES "P3Exam"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3ExamAttempt" ADD CONSTRAINT "P3ExamAttempt_student_fkey" FOREIGN KEY ("studentId","schoolId") REFERENCES "Student"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "P3LibraryLoan" ADD CONSTRAINT "P3LibraryLoan_book_fkey" FOREIGN KEY ("bookId","schoolId") REFERENCES "P3LibraryBook"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3LibraryLoan" ADD CONSTRAINT "P3LibraryLoan_student_fkey" FOREIGN KEY ("studentId","schoolId") REFERENCES "Student"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3LibraryLoan" ADD CONSTRAINT "P3LibraryLoan_issuer_fkey" FOREIGN KEY ("issuedBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3LibraryLoan" ADD CONSTRAINT "P3LibraryLoan_returner_fkey" FOREIGN KEY ("returnedBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "P3Asset" ADD CONSTRAINT "P3Asset_school_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3Asset" ADD CONSTRAINT "P3Asset_user_fkey" FOREIGN KEY ("assignedToUserId","schoolId") REFERENCES "User"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "P3FinanceAdjustment" ADD CONSTRAINT "P3FinanceAdjustment_student_fkey" FOREIGN KEY ("studentId","schoolId") REFERENCES "Student"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3FinanceAdjustment" ADD CONSTRAINT "P3FinanceAdjustment_invoice_fkey" FOREIGN KEY ("invoiceId","schoolId") REFERENCES "Invoice"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "P3FinanceAdjustment" ADD CONSTRAINT "P3FinanceAdjustment_requester_fkey" FOREIGN KEY ("requestedBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "P3RecruitmentPosting" ADD CONSTRAINT "P3RecruitmentPosting_creator_fkey" FOREIGN KEY ("createdBy","schoolId") REFERENCES "User"("id","schoolId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "P3Applicant" ADD CONSTRAINT "P3Applicant_posting_fkey" FOREIGN KEY ("postingId","schoolId") REFERENCES "P3RecruitmentPosting"("id","schoolId") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "P3Applicant" ADD CONSTRAINT "P3Applicant_staff_fkey" FOREIGN KEY ("staffUserId","schoolId") REFERENCES "User"("id","schoolId") ON DELETE SET NULL ON UPDATE CASCADE;

DO $$ DECLARE r RECORD; BEGIN FOR r IN SELECT unnest(ARRAY['P3Vehicle','P3BusRoute','P3BusStop','P3RouteStop','P3VehicleLocation','P3ParentLocation','P3BoardingEvent','P3VehicleComplianceReminder','P3FeedingBudget','P3FeedingMenu','P3FeedingLog','P3FeedingInvoiceItem','P3Exam','P3ExamQuestion','P3ExamAttempt','P3LibraryBook','P3LibraryLoan','P3Asset','P3FinanceAdjustment','P3RecruitmentPosting','P3Applicant','P3OfflineSyncQueue']) AS table_name LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',r.table_name); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',r.table_name); EXECUTE format('CREATE POLICY %I ON %I USING ("schoolId" = sukuunova_current_school_id()) WITH CHECK ("schoolId" = sukuunova_current_school_id())',r.table_name || '_tenant_isolation',r.table_name); END LOOP; END $$;
