import { NextResponse } from "next/server";
import { z } from "zod";
import { IMPERSONATION_SECONDS, SCHOOL_COOKIE, createSchoolSessionToken, requirePlatformSession, sessionCookieOptions } from "@/lib/auth";
import { routeError, UnauthorizedError } from "@/lib/errors";
import { parseJson } from "@/lib/http";
import { requirePlatformPermission } from "@/lib/platform-permissions";
import { requireSchoolScope } from "@/lib/platform-school-scope";
import { createPlatformSchool, suspendPlatformSchool, searchCrossSchool, listPlans, createPlan, assignPlan, generatePlatformInvoice, recordPlatformPayment, listBilling, updateSupportTicket, impersonateUser, listPlatformSchools } from "@/lib/phase4-service";
import { listSupportTicketsForPlatform } from "@/lib/phase4-platform-support";
const postSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("createSchool"),uniqueCode:z.string().min(3).max(40),schoolName:z.string().min(2).max(160),ownerName:z.string().min(2).max(160),ownerEmail:z.string().email(),ownerPassword:z.string().min(12).max(256)}),
 z.object({action:z.literal("suspendSchool"),schoolId:z.string(),suspended:z.boolean()}),
 z.object({action:z.literal("search"),q:z.string().min(1).max(120)}),
 z.object({action:z.literal("createPlan"),name:z.string().min(2).max(80),price:z.number().positive(),featureFlags:z.array(z.string().max(80)).max(30)}),
 z.object({action:z.literal("assignPlan"),schoolId:z.string(),planId:z.string()}),
 z.object({action:z.literal("generateInvoice"),schoolId:z.string(),period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}),
 z.object({action:z.literal("recordPayment"),schoolId:z.string(),invoiceId:z.string(),amount:z.number().positive(),method:z.string().min(1).max(40),reference:z.string().max(120).optional()}),
 z.object({action:z.literal("supportUpdate"),schoolId:z.string(),ticketId:z.string(),status:z.enum(["open","in_progress","resolved"]),body:z.string().max(5000).optional()}),
 z.object({action:z.literal("impersonate"),schoolId:z.string(),userId:z.string(),reason:z.string().min(5).max(500)})
]);
const postPermission:Record<z.infer<typeof postSchema>["action"],string>={createSchool:"schools.manage",suspendSchool:"schools.manage",search:"schools.view",createPlan:"plans.manage",assignPlan:"plans.manage",generateInvoice:"billing.manage",recordPayment:"billing.manage",supportUpdate:"support.manage",impersonate:"schools.impersonate"};
export async function GET(request:Request){try{const session=await requirePlatformSession();const url=new URL(request.url),view=url.searchParams.get("view")||"schools",schoolId=url.searchParams.get("schoolId")||"";if(view==="schools"){await requirePlatformPermission(session,"schools.view");return NextResponse.json({schools:await listPlatformSchools()});}if(view==="plans"){await requirePlatformPermission(session,"plans.manage");return NextResponse.json({plans:await listPlans(session.role)});}if(view==="billing"){await requirePlatformPermission(session,"billing.view");if(!schoolId)throw new UnauthorizedError("schoolId is required");await requireSchoolScope(session,schoolId);return NextResponse.json(await listBilling(session.role,schoolId));}if(view==="support"){await requirePlatformPermission(session,"support.view");if(!schoolId)throw new UnauthorizedError("schoolId is required");await requireSchoolScope(session,schoolId);return NextResponse.json({tickets:await listSupportTicketsForPlatform(session.adminId,session.role,schoolId)});}throw new UnauthorizedError("Unknown platform view");}catch(error){return routeError(error);}}
export async function POST(request:Request){try{const session=await requirePlatformSession();const input=await parseJson(request,postSchema);await requirePlatformPermission(session,postPermission[input.action]);switch(input.action){case"createSchool":return NextResponse.json({ok:true,result:await createPlatformSchool({adminId:session.adminId,adminRole:session.role,...input})},{status:201});case"suspendSchool":await requireSchoolScope(session,input.schoolId);return NextResponse.json({ok:true,result:await suspendPlatformSchool(session.adminId,session.role,input.schoolId,input.suspended)});case"search":return NextResponse.json({results:await searchCrossSchool(session.adminId,session.role,input.q)});case"createPlan":return NextResponse.json({ok:true,result:await createPlan({adminId:session.adminId,adminRole:session.role,...input})},{status:201});case"assignPlan":await requireSchoolScope(session,input.schoolId);return NextResponse.json({ok:true,result:await assignPlan({adminId:session.adminId,adminRole:session.role,...input})});case"generateInvoice":await requireSchoolScope(session,input.schoolId);return NextResponse.json({ok:true,result:await generatePlatformInvoice({adminId:session.adminId,adminRole:session.role,...input})},{status:201});case"recordPayment":await requireSchoolScope(session,input.schoolId);return NextResponse.json({ok:true,result:await recordPlatformPayment({adminId:session.adminId,adminRole:session.role,...input})});case"supportUpdate":await requireSchoolScope(session,input.schoolId);return NextResponse.json({ok:true,result:await updateSupportTicket({adminId:session.adminId,adminRole:session.role,...input})});case"impersonate":{await requireSchoolScope(session,input.schoolId);const result=await impersonateUser({adminId:session.adminId,adminRole:session.role,...input});const token=await createSchoolSessionToken({kind:"school",userId:result.userId,schoolId:input.schoolId,name:result.userName,impersonationId:result.id,impersonatedByAdminId:session.adminId},IMPERSONATION_SECONDS);const response=NextResponse.json({ok:true,result,expiresInSeconds:IMPERSONATION_SECONDS});response.cookies.set(SCHOOL_COOKIE,token,sessionCookieOptions(IMPERSONATION_SECONDS));return response;}}}catch(error){return routeError(error);}}