"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import "./access-workspace.css";

type Role={id:string;name:string;key:string|null;isSystem:boolean;rolePermissions?:Array<{permission:{key:string}}>};
type Override={granted:boolean;permission:{key:string;description:string|null}};
type User={id:string;name:string;email:string|null;phone:string|null;status:string;createdAt:string;userRoles:Array<{role:Role}>;permissionOverrides:Override[]};
type Permission={id:string;key:string;description:string|null};
type Data={users:User[];roles:Role[];permissions:Permission[];me:string;canManage:boolean;canControlRoles:boolean};
const empty={name:"",email:"",phone:"",password:""};
const rolePurpose:Record<string,string>={Owner:"Full school control and oversight.",Principal:"School leadership, oversight and academic/operational approvals.","Vice Principal":"Deputy leadership, academic monitoring and operational support.","Academic Coordinator":"Owns academic quality checks, review and coordination.","Department Head":"Reviews department delivery, results and teaching quality.","Class Teacher":"Runs assigned classes and classroom workflows.","Subject Teacher":"Delivers assigned subjects and classroom work.",Accountant:"Finance, collections, billing and financial approvals.","HR Officer":"Staff, recruitment, payroll and workforce administration.","Admissions Officer":"Admissions pipeline and student intake.","Front Desk/Gate Security":"Front desk, visitors and authorised pickup workflow.","Transport Officer":"Transport routes, drivers and operational assignments.",Parent:"Linked child/family access only.",Student:"Learner access only."};
const groups:Record<string,string>={lesson_plans:"Lesson planning",homework:"Homework",scores:"Results & gradebook",report_cards:"Report cards",exams:"Exams & assessments",classes:"Classes & curriculum",attendance:"Attendance",analytics:"Analytics",reports:"Reports",students:"Students",finance:"Finance",fees:"Fees",payroll:"Payroll",users:"Accounts",settings:"Settings",roles:"Roles",calendar:"Calendar",library:"Library",transport:"Transport",feeding:"Feeding",assets:"Assets",recruitment:"Recruitment",risk_flags:"Safeguarding",ai_drafts:"AI assistance",offline:"Offline",parents:"Family links",templates:"Templates",visitors:"Visitors",broadcast:"Broadcasts"};
function permissionGroup(key:string){const prefix=key.split(":")[0];return groups[prefix]??prefix;}
export default function AccessPage(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState(empty),[roleNames,setRoleNames]=useState<string[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[selectedId,setSelectedId]=useState(""),[draftRoles,setDraftRoles]=useState<string[]>([]),[grantKeys,setGrantKeys]=useState<string[]>([]),[denyKeys,setDenyKeys]=useState<string[]>([]),[search,setSearch]=useState("");
 const load=()=>fetch("/api/school/access").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load access settings.");return d as Data}).then(d=>{setData(d);}).catch(e=>setMessage(e instanceof Error?e.message:"Could not load access settings."));
 useEffect(()=>{void load()},[]);
 const selected=data?.users.find((u)=>u.id===selectedId); const filteredPermissions=useMemo(()=>{const q=search.trim().toLowerCase();return (data?.permissions??[]).filter((p)=>!q||p.key.toLowerCase().includes(q)||(p.description??"").toLowerCase().includes(q));},[data,search]);
 const openUser=(u:User)=>{setSelectedId(u.id);setDraftRoles(u.userRoles.map((r)=>r.role.name));setGrantKeys(u.permissionOverrides.filter((o)=>o.granted).map((o)=>o.permission.key));setDenyKeys(u.permissionOverrides.filter((o)=>!o.granted).map((o)=>o.permission.key));setSearch("");};
 const toggleRole=(name:string)=>setRoleNames((items)=>items.includes(name)?items.filter((x)=>x!==name):[...items,name]);
 const create=async()=>{if(!roleNames.length){setMessage("Choose at least one role.");return}setSaving(true);setMessage("");try{const r=await fetch("/api/school/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,roleNames})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create account.");setMessage(`Account for ${d.name} created with ${roleNames.join(" + ")}.`);setForm(empty);setRoleNames([]);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not create account.")}finally{setSaving(false)}};
 const setPermission=(key:string,kind:"grant"|"deny")=>{setGrantKeys((items)=>kind==="grant"?(items.includes(key)?items.filter((x)=>x!==key):[...items,key]):items.filter((x)=>x!==key));setDenyKeys((items)=>kind==="deny"?(items.includes(key)?items.filter((x)=>x!==key):[...items,key]):items.filter((x)=>x!==key));};
 const saveUser=async()=>{if(!selected||!data?.canControlRoles)return;setSaving(true);setMessage("");try{const r=await fetch("/api/school/access",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId:selected.id,status:selected.status,roleNames:draftRoles,grantedPermissionKeys:grantKeys,deniedPermissionKeys:denyKeys,clearPermissionOverrides:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update account.");setMessage(`${selected.name}'s role and direct permission profile was updated.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not update account.")}finally{setSaving(false)}};
 const changeStatus=async(u:User)=>{setSaving(true);const next=u.status==="suspended"?"active":"suspended";try{const r=await fetch("/api/school/access",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId:u.id,status:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update status.");setMessage(`${u.name} is now ${next}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not update status.")}finally{setSaving(false)}};
 return <AppShell universe="school" title="People, Roles & Access" subtitle="Give every account the right default responsibilities, then add extra roles or direct rights only where the school needs them." active="Roles & Permissions">
  <div className="access-shell">
   <section className="access-hero"><div><span className="access-kicker">SCHOOL ACCESS CONTROL</span><h2>Everyone gets a job, not a copy of the owner.</h2><p>Teaching accounts work inside assigned classes and subjects. Leaders monitor and verify. Owners retain full control and can extend an individual account without changing the baseline role for everyone else.</p></div><div className="access-hero-stat"><strong>{data?.users.length??0}</strong><span>school accounts</span><small>{data?.roles.length??0} roles available</small></div></section>
   <section className="access-model"><div><span className="model-badge owner">O</span><div><b>Owner</b><small>Oversight, governance, approvals, reporting and account control. Full rights remain available, but teaching work is not the default dashboard.</small></div></div><div><span className="model-badge lead">P</span><div><b>Principal / academic leadership</b><small>Monitor school delivery, review teachers, verify plans and results, approve reporting and see cross-school performance.</small></div></div><div><span className="model-badge teacher">T</span><div><b>Teacher / class teacher</b><small>Teach assigned classes, create lesson plans and homework, take attendance, enter marks and submit work for review.</small></div></div></section>
   <div className="access-grid"><section className="access-card"><div className="access-card-head"><div><span className="access-kicker">NEW ACCOUNT</span><h3>Create a staff login</h3><p>Assign one role or a deliberate combination such as Subject Teacher + Department Head.</p></div></div>{!data?.canManage?<div className="access-note">Your account cannot create or change school users.</div>:<div className="access-form"><label>Full name<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} placeholder="e.g. Ama Mensah"/></label><label>Email<input value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} placeholder="name@school.com"/></label><label>Phone / WhatsApp<input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})} placeholder="Optional"/></label><label>Temporary password<input type="password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} placeholder="12+ characters"/></label><div><b className="field-label">Default role bundle</b><div className="role-picker">{data?.roles.map((role)=><button type="button" key={role.id} onClick={()=>toggleRole(role.name)} className={roleNames.includes(role.name)?"chosen":""}><strong>{role.name}</strong><span>{rolePurpose[role.name]??"School-defined responsibility."}</span></button>)}</div></div><button className="access-primary" disabled={saving} onClick={()=>void create()}>{saving?"Creating account…":"Create account"}</button></div>}</section>
   <section className="access-card"><div className="access-card-head"><div><span className="access-kicker">ACCOUNT DIRECTORY</span><h3>Who can do what</h3><p>Open any user to combine roles and add or deny direct permissions without altering the role definition.</p></div><span className="access-count">{data?.users.length??0}</span></div><div className="user-list">{data?.users.map((u)=><button className={`user-row ${selectedId===u.id?"selected":""}`} key={u.id} onClick={()=>openUser(u)}><span className="user-avatar">{u.name.split(/\s+/).map((x)=>x[0]).slice(0,2).join("")}</span><span className="user-copy"><b>{u.name}{u.id===data.me?" · You":""}</b><small>{u.email||u.phone||"No contact"}</small><span>{u.userRoles.map((r)=>r.role.name).join(" + ")||"No role"}</span></span><span className={`status-dot ${u.status}`}/></button>)}</div></section></div>
   {selected&&<section className="access-card access-editor"><div className="access-card-head"><div><span className="access-kicker">ACCOUNT PROFILE</span><h3>{selected.name}</h3><p>{selected.email||selected.phone||"No contact"} · {selected.status}</p></div><div className="editor-actions"><button className="access-secondary" onClick={()=>void changeStatus(selected)} disabled={saving}>{selected.status==="suspended"?"Reactivate":"Suspend"}</button>{data?.canControlRoles&&<button className="access-primary compact" onClick={()=>void saveUser()} disabled={saving}>{saving?"Saving…":"Save profile"}</button>}</div></div><div className="editor-grid"><div><b className="field-label">Roles assigned to this account</b><div className="role-picker compact-grid">{data?.roles.map((role)=><button type="button" key={role.id} onClick={()=>data.canControlRoles&&setDraftRoles((items)=>items.includes(role.name)?items.filter((x)=>x!==role.name):[...items,role.name])} className={draftRoles.includes(role.name)?"chosen":""} disabled={!data.canControlRoles}><strong>{role.name}</strong><span>{rolePurpose[role.name]??"School-defined responsibility."}</span></button>)}</div></div><div><div className="permission-toolbar"><div><b className="field-label">Direct permissions for {selected.name}</b><small>Grant adds a right. Deny overrides an inherited role. Leave both empty for role-only access.</small></div><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Filter permissions…"/></div><div className="permission-list">{Object.entries(filteredPermissions.reduce<Record<string,Permission[]>>((acc,p)=>{const group=permissionGroup(p.key);(acc[group]??=[]).push(p);return acc;},{})).map(([group,items])=><div className="permission-group" key={group}><b>{group}</b>{items.map((p)=><div className="permission-row" key={p.key}><span><strong>{p.key}</strong><small>{p.description||"School permission"}</small></span><button type="button" className={grantKeys.includes(p.key)?"on grant":""} onClick={()=>data?.canControlRoles&&setPermission(p.key,"grant")} disabled={!data?.canControlRoles}>Grant</button><button type="button" className={denyKeys.includes(p.key)?"on deny":""} onClick={()=>data?.canControlRoles&&setPermission(p.key,"deny")} disabled={!data?.canControlRoles}>Deny</button></div>)}</div>)}</div></div></div></section>}
   {message&&<div className="access-message">{message}</div>}
   <section className="access-footer"><div><span className="access-kicker">ROLE DESIGN</span><h3>Need a new job without changing the system defaults?</h3><p>Create a custom role, give it exactly the permissions it needs, then combine it with another role on one user.</p></div><a className="access-secondary link-button" href="/school/settings/roles">Open Role Designer →</a></section>
  </div>
 </AppShell>;
}
