"use client";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";

type Role={id:string;name:string;key:string|null;isSystem:boolean};
type User={id:string;name:string;email:string|null;phone:string|null;status:string;createdAt:string;userRoles:Array<{role:Role}>};
type Data={users:User[];roles:Role[];me:string;canManage:boolean};
const empty={name:"",email:"",phone:"",password:"",roleName:""};
export default function AccessPage(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState(empty),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>fetch("/api/school/access").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load access settings.");return d as Data}).then(setData).catch(e=>setMessage(e instanceof Error?e.message:"Could not load access settings."));
 useEffect(()=>{void load()},[]);
 const create=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/api/school/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create account.");setMessage(`Sub-account for ${d.name} created successfully.`);setForm(empty);await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not create account.")}finally{setSaving(false)}};
 const change=async(userId:string,status:string,roleName?:string)=>{const r=await fetch("/api/school/access",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,status,roleName})});const d=await r.json();setMessage(r.ok?"Account access updated and recorded.":d.error||"Could not update account.");if(r.ok)void load()};
 return <AppShell universe="school" title="Access & sub-accounts" subtitle="Manage school accounts without losing role boundaries, audit history or control over who can enter the workspace." active="Roles & Permissions"><div className="app-dashboard-grid"><section className="app-card app-panel"><div className="app-card-head"><div><h2>Create a sub-account</h2><p>Give a colleague a dedicated login instead of sharing the school owner account.</p></div></div>{!data?.canManage?<div className="app-banner"><div><h3>Access is read-only</h3><p>Your current role does not have permission to create or change school accounts.</p></div></div>:<div style={{display:"grid",gap:9}}><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Phone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Temporary password (12+ chars)" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.roleName} onChange={e=>setForm({...form,roleName:e.target.value})}><option value="">Choose a role…</option>{data?.roles.map(r=><option key={r.id} value={r.name}>{r.name}</option>)}</select><button className="app-action" disabled={saving} onClick={()=>void create()}><strong>{saving?"Creating…":"Create sub-account"}</strong>Assign school role</button></div>}</section><section className="app-card app-panel"><div className="app-card-head"><div><h2>School accounts</h2><p>See who can sign in, what role they hold and whether their access is active.</p></div><span className="app-pill">{data?.users.length??0} accounts</span></div><div className="app-list">{data?.users.map(u=><div className="app-list-row" key={u.id}><div style={{flex:1}}><b>{u.name}{u.id===data.me?" · You":""}</b><span>{u.email||u.phone||"No contact"} · {u.userRoles.map(r=>r.role.name).join(", ")||"No role"} · {u.status}</span></div>{u.id!==data.me&&data.canManage&&<div style={{display:"flex",gap:6}}><button className="app-pill" onClick={()=>void change(u.id,u.status==="suspended"?"active":"suspended")}>{u.status==="suspended"?"Reactivate":"Suspend"}</button><select defaultValue={u.userRoles[0]?.role.name||""} onChange={e=>e.target.value&&void change(u.id,u.status,e.target.value)}><option value="">Change role</option>{data.roles.map(r=><option key={r.id} value={r.name}>{r.name}</option>)}</select></div>}</div>)}</div>{message&&<div className="app-banner" style={{marginTop:12}}><div><h3>{message}</h3><p>Changes are recorded in the school audit trail.</p></div></div>}</section></div></AppShell>;
}
