import { NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { createId } from "@paralleldrive/cuid2";
import { requireSchoolSession } from "@/lib/school-auth";
import { withTenant } from "@/lib/db";
import { hasPermission, requirePermission } from "@/lib/rbac";
import { appendSchoolAudit } from "@/lib/audit";
import { routeError, ForbiddenError, AppError } from "@/lib/errors";

const createSchema=z.object({classId:z.string().min(1).max(100),subjectId:z.string().min(1).max(100),termId:z.string().min(1).max(100).optional(),title:z.string().trim().min(3).max(160),instructions:z.string().trim().min(5).max(12000),dueDate:z.coerce.date(),points:z.coerce.number().min(1).max(10000).optional(),assignmentStatus:z.enum(["draft","assigned"]).default("draft")});
const patchSchema=z.object({id:z.string().min(1).max(100),assignmentStatus:z.enum(["draft","assigned","closed"]).optional(),reviewStatus:z.enum(["not_reviewed","approved","changes_requested"]).optional(),reviewNote:z.string().trim().max(2000).optional()}).refine((v)=>v.assignmentStatus!==undefined||v.reviewStatus!==undefined,{message:"Nothing to update."});
type HomeworkRow={id:string;schoolId:string;teacherId:string;teacherName:string;classId:string;className:string;subjectId:string;subjectName:string;termId:string|null;termName:string|null;title:string;instructions:string;dueDate:Date;points:number|null;assignmentStatus:string;reviewStatus:string;reviewNote:string|null;reviewedAt:Date|null;createdAt:Date;updatedAt:Date};

export async function GET(){try{const session=await requireSchoolSession();return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"homework:review");const manage=await hasPermission(tx,session.userId,"homework:manage_assigned");if(!review&&!manage)throw new ForbiddenError("You do not have access to homework workflows.");const scope=review?Prisma.sql`hw."schoolId" = ${session.schoolId}`:Prisma.sql`hw."schoolId" = ${session.schoolId} AND hw."teacherId" = ${session.userId}`;const rows=await tx.$queryRaw<HomeworkRow[]>`SELECT hw."id",hw."schoolId",hw."teacherId",u."name" AS "teacherName",hw."classId",c."name" AS "className",hw."subjectId",s."name" AS "subjectName",hw."termId",t."name" AS "termName",hw."title",hw."instructions",hw."dueDate",CAST(hw."points" AS DOUBLE PRECISION) AS "points",hw."assignmentStatus",hw."reviewStatus",hw."reviewNote",hw."reviewedAt",hw."createdAt",hw."updatedAt" FROM "Homework" hw JOIN "User" u ON u."id"=hw."teacherId" AND u."schoolId"=hw."schoolId" JOIN "Class" c ON c."id"=hw."classId" AND c."schoolId"=hw."schoolId" JOIN "Subject" s ON s."id"=hw."subjectId" AND s."schoolId"=hw."schoolId" LEFT JOIN "Term" t ON t."id"=hw."termId" AND t."schoolId"=hw."schoolId" WHERE ${scope} ORDER BY hw."dueDate" ASC,hw."updatedAt" DESC`;const assignments=manage?await tx.classSubjectTeacher.findMany({where:{teacherId:session.userId},select:{classId:true,subjectId:true,class:{select:{name:true,level:true}},subject:{select:{name:true}}},orderBy:{classId:"asc"}}):[];const terms=await tx.term.findMany({orderBy:{startDate:"desc"},take:12,select:{id:true,name:true,academicYear:{select:{name:true}}}});return{rows,assignments,terms,review,manage};}))}catch(error){return routeError(error)}}

export async function POST(request:Request){try{const session=await requireSchoolSession();const input=createSchema.parse(await request.json());await withTenant(session.schoolId,async tx=>{await requirePermission(tx,session.userId,"homework:manage_assigned");const assignment=await tx.classSubjectTeacher.findFirst({where:{schoolId:session.schoolId,teacherId:session.userId,classId:input.classId,subjectId:input.subjectId}});const classTeacher=await tx.class.findFirst({where:{id:input.classId,schoolId:session.schoolId,classTeacherId:session.userId},select:{id:true}});if(!assignment&&!classTeacher)throw new ForbiddenError("You can only create homework for a class and subject you teach (including form classes).");if(input.termId){const term=await tx.term.findFirst({where:{id:input.termId,schoolId:session.schoolId}});if(!term)throw new AppError("Selected term was not found in this school.",404,"TERM_NOT_FOUND");if(term.isLocked)throw new AppError("Selected term is locked.",409,"TERM_LOCKED");}const id=createId();await tx.$executeRaw`INSERT INTO "Homework" ("id","schoolId","teacherId","classId","subjectId","termId","title","instructions","dueDate","points","assignmentStatus") VALUES (${id},${session.schoolId},${session.userId},${input.classId},${input.subjectId},${input.termId??null},${input.title},${input.instructions},${input.dueDate},${input.points??null},${input.assignmentStatus})`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"homework.created",entityType:"Homework",entityId:id,after:{title:input.title,classId:input.classId,subjectId:input.subjectId,assignmentStatus:input.assignmentStatus}});});return NextResponse.json({ok:true},{status:201})}catch(error){return routeError(error)}}

export async function PATCH(request:Request){try{const session=await requireSchoolSession();const input=patchSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{const review=await hasPermission(tx,session.userId,"homework:review");const manage=await hasPermission(tx,session.userId,"homework:manage_assigned");const rows=await tx.$queryRaw<Array<{id:string;teacherId:string;assignmentStatus:string;reviewStatus:string}>>`SELECT "id","teacherId","assignmentStatus","reviewStatus" FROM "Homework" WHERE "id"=${input.id} AND "schoolId"=${session.schoolId} LIMIT 1`;const current=rows[0];if(!current)throw new AppError("Homework item not found in this school.",404,"NOT_FOUND");const reviewChange=Boolean(input.reviewStatus);const ownerChange=Boolean(input.assignmentStatus);if(reviewChange&&!review)throw new ForbiddenError("Only academic reviewers can review homework.");if(ownerChange&&(!manage||current.teacherId!==session.userId))throw new ForbiddenError("You can only change the delivery state of homework you created.");if(reviewChange&&ownerChange&&current.teacherId===session.userId)throw new ForbiddenError("Assign and review must be separate actions by different people.");if(ownerChange){const allowed:Record<string,string[]>={draft:["assigned"],assigned:["closed"],closed:[]};if(!(allowed[current.assignmentStatus]??[]).includes(input.assignmentStatus as string))throw new AppError("Cannot move homework from "+current.assignmentStatus+" to "+input.assignmentStatus+".",409,"INVALID_TRANSITION");}if(reviewChange){if(current.teacherId===session.userId)throw new ForbiddenError("Reviewers cannot review their own homework.");const allowed:Record<string,string[]>={not_reviewed:["approved","changes_requested"],changes_requested:["approved"],approved:["changes_requested"]};if(!(allowed[current.reviewStatus]??[]).includes(input.reviewStatus as string))throw new AppError("Cannot move homework review from "+current.reviewStatus+" to "+input.reviewStatus+".",409,"INVALID_TRANSITION");}await tx.$executeRaw`UPDATE "Homework" SET "assignmentStatus"=COALESCE(${input.assignmentStatus??null},"assignmentStatus"),"reviewStatus"=COALESCE(${input.reviewStatus??null},"reviewStatus"),"reviewNote"=CASE WHEN ${input.reviewStatus??null} IS NULL THEN "reviewNote" ELSE ${input.reviewNote??null} END,"reviewerId"=CASE WHEN ${reviewChange} THEN ${session.userId} ELSE "reviewerId" END,"reviewedAt"=CASE WHEN ${reviewChange} THEN CURRENT_TIMESTAMP ELSE "reviewedAt" END,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${input.id} AND "schoolId"=${session.schoolId}`;await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:reviewChange?"homework.reviewed":"homework.updated",entityType:"Homework",entityId:input.id,after:{assignmentStatus:input.assignmentStatus,reviewStatus:input.reviewStatus,reviewNote:input.reviewNote??null}});return{ok:true};}))}catch(error){return routeError(error)}}
