import type { GameCatalogEntry } from "./types";

export const SUKUUNOVA_GAME_CATALOG: GameCatalogEntry[] = [
  {
    dna: {
      id: "blackout-protocol",
      title: "Blackout Protocol",
      category: "simulation",
      genre: "real-time systems crisis",
      setting: "connected city control centre",
      playerRole: "emergency systems controller",
      primaryMechanic: "systems triage",
      secondaryMechanics: ["network inspection", "resource allocation", "incident containment"],
      interactionStyle: "dashboards maps logs and timed commands",
      storyStructure: "branching crisis",
      pacing: "high",
      failureModel: "partial",
      endingModel: "multiple",
      sessionLength: "medium",
      movementProfileId: "strategy-cursor",
      cameraProfileId: "strategy-top-down",
      academicDomains: ["ICT", "Computer Science", "Networking", "Electricity"],
    },
    summary: "Keep a city functioning while electrical and cyber failures cascade across connected systems.",
    coreLoop: ["Detect abnormal systems", "Prioritise limited teams", "Contain failures", "Reassess the changing city"],
    learningThroughAction: ["Configure protection instead of defining it", "Trace incidents through logs", "Balance electrical load and service priority"],
    replayDrivers: ["Different failure origins", "Changing affected systems", "Resource constraints", "Multiple endings"],
  },
  {
    dna: {
      id: "nova-run",
      title: "Nova Run",
      category: "runner",
      genre: "endless skill runner",
      setting: "changing learning districts",
      playerRole: "courier",
      primaryMechanic: "lane traversal",
      secondaryMechanics: ["jump", "slide", "route choice", "pickup use"],
      interactionStyle: "swipe keyboard or controller reflex movement",
      storyStructure: "minimal",
      pacing: "high",
      failureModel: "score-only",
      endingModel: "endless",
      sessionLength: "quick",
      movementProfileId: "arcade-runner",
      cameraProfileId: "runner-forward",
      academicDomains: ["Cross-curricular"],
    },
    summary: "A fast runner where knowledge changes routes, tools and environmental interactions rather than pausing for question screens.",
    coreLoop: ["Read the route", "Move early", "Use environmental knowledge", "Chain clean traversal", "Choose riskier reward paths"],
    learningThroughAction: ["Symbols alter safe routes", "Patterns predict obstacle cycles", "Subject mechanics unlock shortcuts"],
    replayDrivers: ["Procedural chunks", "District modifiers", "Route branches", "Score mastery"],
  },
  {
    dna: {
      id: "field-expedition",
      title: "Field Expedition",
      category: "open-world",
      genre: "exploration adventure",
      setting: "connected town farms rivers and research sites",
      playerRole: "student field researcher",
      primaryMechanic: "free exploration",
      secondaryMechanics: ["contextual interaction", "navigation", "collection", "light traversal"],
      interactionStyle: "camera-relative third-person movement",
      storyStructure: "mission web",
      pacing: "variable",
      failureModel: "recoverable",
      endingModel: "multiple",
      sessionLength: "persistent",
      movementProfileId: "open-world-exploration",
      cameraProfileId: "open-world-orbit",
      academicDomains: ["Science", "Geography", "Social Studies", "Agriculture"],
    },
    summary: "A non-violent open learning world inspired by the freedom and mission layering of modern sandbox games.",
    coreLoop: ["Explore freely", "Discover local problems", "Accept or ignore missions", "Use knowledge in the world", "Unlock new districts and transport"],
    learningThroughAction: ["Survey real spatial relationships", "Run field experiments", "Plan routes and logistics", "Interview characters and compare evidence"],
    replayDrivers: ["Mission order freedom", "Optional discoveries", "World-state consequences", "Different transport and solution choices"],
  },
  {
    dna: {
      id: "geometry-forge",
      title: "Geometry Forge",
      category: "construction",
      genre: "spatial construction puzzle",
      setting: "abstract design workshop",
      playerRole: "designer",
      primaryMechanic: "shape construction",
      secondaryMechanics: ["measure", "rotate", "cut", "combine", "simulate"],
      interactionStyle: "direct manipulation tools",
      storyStructure: "none",
      pacing: "relaxed",
      failureModel: "score-only",
      endingModel: "score-attack",
      sessionLength: "quick",
      movementProfileId: "physics-builder",
      cameraProfileId: "builder-static",
      academicDomains: ["Mathematics"],
    },
    summary: "Solve geometry by constructing, measuring and testing designs rather than selecting answers.",
    coreLoop: ["Read constraint", "Construct", "Measure", "Test", "Refine for efficiency"],
    learningThroughAction: ["Area and perimeter emerge from the build", "Angles are manipulated directly", "Efficiency creates optimisation problems"],
    replayDrivers: ["Multiple valid designs", "Material limits", "Precision scoring", "Challenge modifiers"],
  },
  {
    dna: {
      id: "failure-point",
      title: "Engineer: Failure Point",
      category: "construction",
      genre: "physics engineering sandbox",
      setting: "engineering test range",
      playerRole: "structural engineer",
      primaryMechanic: "build and simulate",
      secondaryMechanics: ["load placement", "material selection", "force inspection", "redesign"],
      interactionStyle: "direct construction plus physics simulation",
      storyStructure: "challenge series",
      pacing: "steady",
      failureModel: "recoverable",
      endingModel: "score-attack",
      sessionLength: "medium",
      movementProfileId: "physics-builder",
      cameraProfileId: "builder-static",
      academicDomains: ["Physics", "Mathematics", "Engineering"],
    },
    summary: "Build structures, stress them until they fail, inspect the failure and redesign.",
    coreLoop: ["Build", "Apply load", "Watch physical response", "Inspect force visualisation", "Redesign"],
    learningThroughAction: ["Failure communicates structural mistakes", "Forces become visible", "Material and geometry choices change outcomes"],
    replayDrivers: ["Different loads", "Cost constraints", "Weather modifiers", "Alternative structural solutions"],
  },
  {
    dna: {
      id: "the-archive",
      title: "The Archive",
      category: "investigation",
      genre: "historical investigation",
      setting: "archive and reconstructed locations",
      playerRole: "historian",
      primaryMechanic: "evidence analysis",
      secondaryMechanics: ["exploration", "timeline building", "source comparison", "interview"],
      interactionStyle: "third-person investigation and document workbench",
      storyStructure: "evidence mystery",
      pacing: "relaxed",
      failureModel: "branching",
      endingModel: "multiple",
      sessionLength: "long",
      movementProfileId: "investigation-walk",
      cameraProfileId: "investigation-orbit",
      academicDomains: ["History", "English", "Social Studies"],
    },
    summary: "Reconstruct historical events from conflicting sources and environmental evidence.",
    coreLoop: ["Explore", "Collect sources", "Test reliability", "Build timeline", "Defend interpretation"],
    learningThroughAction: ["Bias is discovered by comparison", "Chronology is constructed", "Claims require evidence chains"],
    replayDrivers: ["Optional sources", "Different evidence order", "Competing interpretations", "Hidden archive material"],
  },
  {
    dna: {
      id: "last-harvest",
      title: "The Last Harvest",
      category: "strategy",
      genre: "seasonal survival strategy",
      setting: "farming community",
      playerRole: "farm manager",
      primaryMechanic: "resource planning",
      secondaryMechanics: ["crop experiments", "weather response", "soil management", "budgeting"],
      interactionStyle: "top-down planning and field simulation",
      storyStructure: "emergent seasons",
      pacing: "variable",
      failureModel: "partial",
      endingModel: "seasonal",
      sessionLength: "long",
      movementProfileId: "strategy-cursor",
      cameraProfileId: "strategy-top-down",
      academicDomains: ["Biology", "Agriculture", "Environmental Science", "Mathematics"],
    },
    summary: "Manage a farm as weather, biology and economics interact across multiple seasons.",
    coreLoop: ["Plan season", "Allocate resources", "Observe growth", "Run experiments", "Respond to events", "Harvest and reinvest"],
    learningThroughAction: ["Plant conditions affect yields", "Experimental plots reveal causal relationships", "Budgets force mathematical trade-offs"],
    replayDrivers: ["Weather variation", "Crop strategies", "Long-term soil consequences", "Different investment paths"],
  },
  {
    dna: {
      id: "argument-arena",
      title: "Argument Arena",
      category: "debate",
      genre: "competitive persuasion",
      setting: "debate arena",
      playerRole: "advocate",
      primaryMechanic: "argument construction",
      secondaryMechanics: ["evidence selection", "rebuttal", "cross-examination", "audience adaptation"],
      interactionStyle: "structured language composition",
      storyStructure: "match",
      pacing: "steady",
      failureModel: "score-only",
      endingModel: "score-attack",
      sessionLength: "quick",
      movementProfileId: "strategy-cursor",
      cameraProfileId: "strategy-top-down",
      academicDomains: ["English", "Communication", "Social Studies"],
    },
    summary: "Build and defend arguments against an adaptive opponent; quality is judged by reasoning rather than a single correct option.",
    coreLoop: ["Build claim", "Attach evidence", "Explain reasoning", "Hear challenge", "Rebut", "Adapt"],
    learningThroughAction: ["Weak evidence is exposed in cross-examination", "Contradictions have consequences", "Clear reasoning strengthens persuasion"],
    replayDrivers: ["Opponent strategies", "Different positions", "Evidence pools", "Tournament play"],
  },
];

export function gameCatalogById(id: string) {
  return SUKUUNOVA_GAME_CATALOG.find((entry) => entry.dna.id === id) ?? null;
}
