"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { AppShell } from "@/components/AppShell";
import "./lessons-workspace.css";

type Assignment={classId:string;subjectId:string;class:{name:string;level:string|null};subject:{name:string}};
type Resource={label:string;url:string};
type Row={
 id:string;updatedAt:string;termId:string|null;teacherId:string;teacherName:string;classId:string;className:string;subjectId:string;subjectName:string;termName:string|null;
 title:string;objective:string|null;content:string;topic:string|null;subTopic:string|null;curriculumObjective:string|null;learningOutcomes:string|null;priorKnowledge:string|null;
 materials:string|null;introduction:string|null;development:string|null;differentiatedActivities:string|null;assessment:string|null;conclusion:string|null;homework:string|null;reflection:string|null;
 resources:unknown;plannedDate:string;status:string;reviewNote:string|null;reviewedAt:string|null;submittedAt:string|null;completedAt:string|null;archivedAt:string|null
};
type Review={id:string;lessonPlanId:string;reviewerId:string;reviewerName:string;decision:string;reasonCode:string|null;note:string|null;createdAt:string};
type Term={id:string;name:string;academicYear:{name:string}};
type Data={rows:Row[];reviews:Review[];assignments:Assignment[];terms:Term[];review:boolean;manage:boolean;me:string};
type FormState={
 classId:string;subjectId:string;termId:string;title:string;objective:string;content:string;plannedDate:string;status:"draft"|"submitted";
 topic:string;subTopic:string;curriculumObjective:string;learningOutcomes:string;priorKnowledge:string;materials:string;introduction:string;development:string;
 differentiatedActivities:string;assessment:string;conclusion:string;homework:string;resourcesText:string
};

const today=new Date().toISOString().slice(0,10);
const emptyForm=():FormState=>({classId:"",subjectId:"",termId:"",title:"",objective:"",content:"",plannedDate:today,status:"draft",topic:"",subTopic:"",curriculumObjective:"",learningOutcomes:"",priorKnowledge:"",materials:"",introduction:"",development:"",differentiatedActivities:"",assessment:"",conclusion:"",homework:"",resourcesText:""});
const REVIEW_REASONS=[
 ["curriculum_alignment","Curriculum alignment"],["learning_outcomes","Learning outcomes"],["assessment","Assessment evidence"],["differentiation","Differentiation"],
 ["resources","Resources / materials"],["clarity","Clarity / sequencing"],["timing","Timing / pacing"],["other","Other"]
] as const;
function statusLabel(status:string){return status==="changes_requested"?"Needs revision":status.charAt(0).toUpperCase()+status.slice(1).replaceAll("_"," ");}
function reasonLabel(reason:string|null){return REVIEW_REASONS.find(([value])=>value===reason)?.[1]??(reason?reason.replaceAll("_"," "):"");}
function resourcesOf(value:unknown):Resource[]{return Array.isArray(value)?value.filter((item):item is Resource=>!!item&&typeof item==="object"&&typeof (item as Resource).label==="string"&&typeof (item as Resource).url==="string"):[];}
function resourcesText(value:unknown){return resourcesOf(value).map(item=>`${item.label} | ${item.url}`).join("\n");}
function parseResources(value:string):Resource[]{
 const lines=value.split("\n").map(line=>line.trim()).filter(Boolean);
 return lines.map((line,index)=>{
  const divider=line.indexOf("|");
  if(divider<1)throw new Error(`Resource line ${index+1} must use: Label | https://example.com/file`);
  const label=line.slice(0,divider).trim(),url=line.slice(divider+1).trim();
  if(!label||!url)throw new Error(`Resource line ${index+1} is incomplete.`);
  try{const parsed=new URL(url);if(!["http:","https:"].includes(parsed.protocol))throw new Error();}catch{throw new Error(`Resource line ${index+1} needs a valid http/https URL.`);}
  return{label,url};
 });
}
function formFromRow(row:Row):FormState{return{classId:row.classId,subjectId:row.subjectId,termId:row.termId??"",title:row.title,objective:row.objective??"",content:row.content,plannedDate:row.plannedDate.slice(0,10),status:"draft",topic:row.topic??"",subTopic:row.subTopic??"",curriculumObjective:row.curriculumObjective??"",learningOutcomes:row.learningOutcomes??"",priorKnowledge:row.priorKnowledge??"",materials:row.materials??"",introduction:row.introduction??"",development:row.development??"",differentiatedActivities:row.differentiatedActivities??"",assessment:row.assessment??"",conclusion:row.conclusion??"",homework:row.homework??"",resourcesText:resourcesText(row.resources)};}

export default function LessonsPage(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("all"),[message,setMessage]=useState(""),[open,setOpen]=useState(false),[selected,setSelected]=useState<Row|null>(null),[saving,setSaving]=useState(false);
 const [editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState<FormState>(emptyForm());
 const [reviewReason,setReviewReason]=useState("curriculum_alignment"),[reviewNote,setReviewNote]=useState(""),[reflection,setReflection]=useState("");
 const load=()=>fetch("/api/school/lesson-plans",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"Unable to load lesson plans");return d as Data}).then(setData).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load lesson plans."));
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const rows=data?.rows??[];return tab==="all"?rows:tab==="review"?rows.filter(r=>r.status==="submitted"):rows.filter(r=>r.status===tab)},[data,tab]);
 const counts={all:data?.rows.length??0,draft:data?.rows.filter(r=>r.status==="draft").length??0,submitted:data?.rows.filter(r=>r.status==="submitted").length??0,approved:data?.rows.filter(r=>r.status==="approved").length??0,changes:data?.rows.filter(r=>r.status==="changes_requested").length??0,completed:data?.rows.filter(r=>r.status==="completed").length??0,archived:data?.rows.filter(r=>r.status==="archived").length??0,review:data?.rows.filter(r=>r.status==="submitted").length??0};
 const selectedReviews=useMemo(()=>data?.reviews.filter(item=>item.lessonPlanId===selected?.id)??[],[data,selected]);
 const openPlan=(row:Row)=>{setSelected(row);setReviewNote("");setReviewReason("curriculum_alignment");setReflection(row.reflection??"");setMessage("");};
 const startNew=()=>{setEditing(null);setSelected(null);setForm(emptyForm());setOpen(true);};
 const save=async(nextStatus:"draft"|"submitted")=>{setSaving(true);setMessage("");try{
  const resources=parseResources(form.resourcesText);
  const body={...form,status:nextStatus,resources,termId:form.termId||undefined,...(editing?{id:editing.id,expectedUpdatedAt:editing.updatedAt}:{})};
  const r=await fetch("/api/school/lesson-plans",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"Could not save lesson plan.");
  setMessage(nextStatus==="submitted"?"Lesson plan submitted for academic review.":"Lesson plan saved as draft.");setOpen(false);setEditing(null);setForm(emptyForm());await load();
 }catch(e){setMessage(e instanceof Error?e.message:"Could not save lesson plan")}finally{setSaving(false)}};
 const edit=(row:Row)=>{setEditing(row);setSelected(null);setForm(formFromRow(row));setOpen(true);setMessage("");};
 const transition=async(row:Row,status:"completed"|"archived")=>{setSaving(true);setMessage("");try{
  const payload=status==="completed"?{id:row.id,status,reflection}:{id:row.id,status};
  const r=await fetch("/api/school/lesson-plans",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"Could not update the lesson.");
  setMessage(status==="completed"?"Lesson completed and reflection recorded.":"Lesson plan archived.");setSelected(null);await load();
 }catch(error){setMessage(error instanceof Error?error.message:"Could not update the lesson.")}finally{setSaving(false)}};
 const reviewAction=async(row:Row,status:"approved"|"changes_requested")=>{if(status==="changes_requested"&&!reviewNote.trim()){setMessage("Explain what the teacher should revise before requesting changes.");return;}setSaving(true);setMessage("");try{
  const payload={id:row.id,status,reviewNote:reviewNote.trim()||undefined,...(status==="changes_requested"?{reviewReason}: {})};
  const r=await fetch("/api/school/lesson-plans",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"Could not review lesson plan.");
  setMessage(status==="approved"?"Lesson plan approved.":"Changes requested from the teacher.");setSelected(null);await load();
 }catch(e){setMessage(e instanceof Error?e.message:"Review failed")}finally{setSaving(false)}};
 const detailSections=(row:Row)=>[
  ["Topic",[row.topic,row.subTopic].filter(Boolean).join(" · ")],["Curriculum objective",row.curriculumObjective],["Learning outcomes",row.learningOutcomes],["Prior knowledge",row.priorKnowledge],
  ["Teaching & learning materials",row.materials],["Introduction",row.introduction],["Development / learning activities",row.development],["Differentiated activities",row.differentiatedActivities],
  ["Assessment / evidence",row.assessment],["Conclusion",row.conclusion],["Homework / extension",row.homework],["Lesson overview / notes",row.content]
 ].filter(([,value])=>String(value??"").trim());
 return <AppShell universe="school" title="Lessons & Planning" subtitle="Structured lesson planning, academic review and teaching reflection." active="Lessons & Planning">
  <div className="lessons-shell"><section className="lessons-hero"><div><span className="lessons-kicker">TEACHING OPERATIONS</span><h2>{data?.review&&!data.manage?"Academic lesson-plan review":"Plan, review and improve every lesson"}</h2><p>Build curriculum-aligned plans, submit them for human academic review, record revisions, teach, reflect and preserve the completed evidence.</p><div className="lessons-pills"><span>{data?.manage?"Teacher authoring enabled":"Review access"}</span><span>{data?.review?"Academic review enabled":"Assignment-scoped workspace"}</span><span>Review history preserved</span></div></div>{data?.manage?<button className="lessons-primary" onClick={startNew}>＋ New lesson plan</button>:null}</section>
   <section className="lessons-kpis"><article><span>Total plans</span><strong>{counts.all}</strong><small>Visible to this account</small></article><article><span>Awaiting review</span><strong>{counts.submitted}</strong><small>Submitted plans</small></article><article><span>Needs revision</span><strong>{counts.changes}</strong><small>Returned to teachers</small></article><article><span>Approved / completed</span><strong>{counts.approved+counts.completed}</strong><small>Quality-checked lessons</small></article></section>
   <section className="lessons-card"><div className="lessons-tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>All <b>{counts.all}</b></button><button className={tab==="draft"?"active":""} onClick={()=>setTab("draft")}>Drafts <b>{counts.draft}</b></button><button className={tab==="submitted"?"active":""} onClick={()=>setTab("submitted")}>Submitted <b>{counts.submitted}</b></button><button className={tab==="changes_requested"?"active":""} onClick={()=>setTab("changes_requested")}>Needs revision <b>{counts.changes}</b></button><button className={tab==="approved"?"active":""} onClick={()=>setTab("approved")}>Approved <b>{counts.approved}</b></button><button className={tab==="completed"?"active":""} onClick={()=>setTab("completed")}>Completed <b>{counts.completed}</b></button><button className={tab==="archived"?"active":""} onClick={()=>setTab("archived")}>Archived <b>{counts.archived}</b></button>{data?.review?<button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>Review queue <b>{counts.review}</b></button>:null}</div><div className="lesson-list">{filtered.length===0?<div className="lesson-empty"><h3>No lesson plans in this view</h3><p>The plans matching this stage will appear here.</p></div>:filtered.map(row=><article className="lesson-row" key={row.id} onClick={()=>openPlan(row)}><button className="lessons-secondary" onClick={(event)=>{event.stopPropagation();openPlan(row)}}>Open plan</button><div className="lesson-main"><span>{row.className} · {row.subjectName}{row.topic?` · ${row.topic}`:""}</span><h3>{row.title}</h3><p>{row.learningOutcomes||row.objective||row.content.slice(0,150)}</p><small>{row.teacherName} · {row.termName||"No term"} · {new Date(row.plannedDate).toLocaleDateString("en-GB")}</small></div><div className="lesson-row-side"><span className={`lesson-status ${row.status}`}>{statusLabel(row.status)}</span></div></article>)}</div></section>
   <section className="lessons-card lessons-chain"><div><span className="lessons-kicker">CONNECTED WORKFLOW</span><h3>Assignment → lesson plan → review → teaching → reflection</h3><p>Academic planning stays connected to the classes, timetable, homework and gradebook teachers already use.</p></div><div className="lessons-chain-links"><Link href="/school/classes">Assignments <span>→</span></Link><Link href="/school/timetable">Timetable <span>→</span></Link><Link href="/school/homework">Homework <span>→</span></Link><Link href="/school/gradebook/studio">Gradebook <span>→</span></Link></div></section>
   {open&&<div className="lesson-modal-backdrop"><section className="lesson-modal lesson-modal-wide"><div className="lesson-modal-head"><div><span className="lessons-kicker">{editing?"EDIT LESSON PLAN":"NEW LESSON PLAN"}</span><h3>Prepare a structured lesson for an assigned class</h3><p>Drafts may be incomplete. Submission requires topic, learning outcomes, development activities and assessment.</p></div><button onClick={()=>setOpen(false)} aria-label="Close editor" disabled={saving}>×</button></div>
    <div className="lesson-form-section"><h4>1. Lesson context</h4><div className="lesson-form-grid"><label>Class<select disabled={Boolean(editing)} value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,subjectId:""})}><option value="">Choose class…</option>{data?.assignments.filter((a,i,self)=>self.findIndex(x=>x.classId===a.classId)===i).map(a=><option key={a.classId} value={a.classId}>{a.class.level?`${a.class.level} · `:""}{a.class.name}</option>)}</select></label><label>Subject<select disabled={Boolean(editing)} value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Choose subject…</option>{data?.assignments.filter(a=>!form.classId||a.classId===form.classId).map(a=><option key={`${a.classId}:${a.subjectId}`} value={a.subjectId}>{a.subject.name}</option>)}</select></label><label>Term<select disabled={Boolean(editing)} value={form.termId} onChange={e=>setForm({...form,termId:e.target.value})}><option value="">No term selected</option>{data?.terms.map(t=><option key={t.id} value={t.id}>{t.name} · {t.academicYear.name}</option>)}</select></label><label>Planned date<input type="date" value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label><label className="wide">Lesson title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Fractions on a number line"/></label><label>Topic <span className="lesson-required">required to submit</span><input value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} placeholder="Main curriculum topic"/></label><label>Sub-topic<input value={form.subTopic} onChange={e=>setForm({...form,subTopic:e.target.value})} placeholder="Specific focus"/></label></div></div>
    <div className="lesson-form-section"><h4>2. Curriculum & outcomes</h4><div className="lesson-form-grid"><label className="wide">Curriculum objective<textarea rows={3} value={form.curriculumObjective} onChange={e=>setForm({...form,curriculumObjective:e.target.value})} placeholder="Curriculum standard, indicator or objective"/></label><label className="wide">Learning outcomes <span className="lesson-required">required to submit</span><textarea rows={3} value={form.learningOutcomes} onChange={e=>setForm({...form,learningOutcomes:e.target.value})} placeholder="What should learners know or be able to do by the end?"/></label><label className="wide">Prior knowledge<textarea rows={2} value={form.priorKnowledge} onChange={e=>setForm({...form,priorKnowledge:e.target.value})} placeholder="Relevant prior learning or prerequisite knowledge"/></label><label className="wide">Learning objective / summary<input value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})} placeholder="A concise lesson objective"/></label></div></div>
    <div className="lesson-form-section"><h4>3. Preparation & teaching sequence</h4><div className="lesson-form-grid"><label className="wide">Teaching / learning materials<textarea rows={2} value={form.materials} onChange={e=>setForm({...form,materials:e.target.value})} placeholder="TLMs, equipment, texts or digital resources"/></label><label className="wide">Introduction / starter<textarea rows={3} value={form.introduction} onChange={e=>setForm({...form,introduction:e.target.value})} placeholder="How will you activate prior knowledge and introduce the lesson?"/></label><label className="wide">Development / learning activities <span className="lesson-required">required to submit</span><textarea rows={7} value={form.development} onChange={e=>setForm({...form,development:e.target.value})} placeholder="Stage the lesson clearly: teacher activity, learner activity, guided practice, independent practice…"/></label><label className="wide">Differentiated activities<textarea rows={3} value={form.differentiatedActivities} onChange={e=>setForm({...form,differentiatedActivities:e.target.value})} placeholder="Support, extension and adaptations for different learners"/></label></div></div>
    <div className="lesson-form-section"><h4>4. Evidence, closure & extension</h4><div className="lesson-form-grid"><label className="wide">Assessment / evidence of learning <span className="lesson-required">required to submit</span><textarea rows={4} value={form.assessment} onChange={e=>setForm({...form,assessment:e.target.value})} placeholder="How will you check learning during and at the end of the lesson?"/></label><label className="wide">Conclusion / plenary<textarea rows={3} value={form.conclusion} onChange={e=>setForm({...form,conclusion:e.target.value})} placeholder="How will the class consolidate the learning?"/></label><label className="wide">Homework / extension<textarea rows={3} value={form.homework} onChange={e=>setForm({...form,homework:e.target.value})} placeholder="Optional follow-up task or extension"/></label><label className="wide">Lesson overview / additional teaching notes<textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} rows={5} placeholder="Keep a concise overview, pacing notes, key vocabulary or other teaching notes…"/></label><label className="wide">Resources / attachments<textarea rows={4} value={form.resourcesText} onChange={e=>setForm({...form,resourcesText:e.target.value})} placeholder={"One per line: Label | https://example.com/resource\nWorksheet | https://school.example/worksheet.pdf"}/><small className="lesson-resource-help">Use school-approved http/https links. Resource history stays with the plan.</small></label></div></div>
    <div className="lesson-modal-actions"><button className="lessons-secondary" onClick={()=>void save("draft")} disabled={saving}>Save draft</button><button className="lessons-primary" onClick={()=>void save("submitted")} disabled={saving}>Submit for review</button></div></section></div>}
   {selected&&<div className="lesson-modal-backdrop" onClick={()=>setSelected(null)}><section className="lesson-modal lesson-modal-wide" onClick={e=>e.stopPropagation()}><div className="lesson-modal-head"><div><span className="lessons-kicker">LESSON PLAN · {statusLabel(selected.status).toUpperCase()}</span><h3>{selected.title}</h3><p>{selected.teacherName} · {selected.className} · {selected.subjectName} · {new Date(selected.plannedDate).toLocaleDateString("en-GB")}</p></div><button onClick={()=>setSelected(null)} aria-label="Close lesson plan">×</button></div>
    <div className="lesson-detail-grid">{detailSections(selected).map(([label,value])=><div key={String(label)}><b>{label}</b><p className="prewrap">{String(value)}</p></div>)}</div>
    {resourcesOf(selected.resources).length?<div className="lesson-detail lesson-resources"><div><b>Resources & attachments</b><div className="lesson-resource-list">{resourcesOf(selected.resources).map((resource,index)=><a key={`${resource.url}-${index}`} href={resource.url} target="_blank" rel="noreferrer">{resource.label}<span>↗</span></a>)}</div></div></div>:null}
    {selected.reviewNote?<div className="lesson-detail"><div className="lesson-note"><b>Latest reviewer note</b><p>{selected.reviewNote}</p></div></div>:null}
    {selectedReviews.length?<section className="lesson-history"><div><span className="lessons-kicker">REVIEW HISTORY</span><h4>{selectedReviews.length} academic decision{selectedReviews.length===1?"":"s"}</h4></div>{selectedReviews.map(item=><article key={item.id}><div><strong>{item.decision==="changes_requested"?"Changes requested":"Approved"}</strong>{item.reasonCode?<span>{reasonLabel(item.reasonCode)}</span>:null}</div><p>{item.note||"No additional reviewer note."}</p><small>{item.reviewerName} · {new Date(item.createdAt).toLocaleString("en-GB")}</small></article>)}</section>:null}
    {selected.reflection?<div className="lesson-detail"><div><b>Teacher reflection</b><p className="prewrap">{selected.reflection}</p></div></div>:null}
    {data?.manage&&selected.teacherId===data.me&&["draft","changes_requested"].includes(selected.status)?<div className="lesson-modal-actions"><button className="lessons-primary" onClick={()=>edit(selected)} disabled={saving}>{selected.status==="changes_requested"?"Edit & resubmit":"Edit plan"}</button></div>:null}
    {data?.manage&&selected.teacherId===data.me&&selected.status==="approved"?<section className="lesson-review-panel"><div><span className="lessons-kicker">POST-LESSON REFLECTION</span><h4>Close the teaching loop</h4><p>Record what worked, what learners struggled with, and what you will adjust next time.</p></div><textarea rows={4} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Reflection after teaching this lesson…" disabled={saving}/><div className="lesson-modal-actions"><button className="lessons-primary" onClick={()=>void transition(selected,"completed")} disabled={saving||reflection.trim().length<10}>Mark lesson completed</button></div></section>:null}
    {data?.manage&&selected.teacherId===data.me&&selected.status==="completed"?<div className="lesson-modal-actions"><button className="lessons-secondary" onClick={()=>void transition(selected,"archived")} disabled={saving}>Archive completed plan</button></div>:null}
    {data?.review&&selected.teacherId!==data.me&&selected.status==="submitted"?<section className="lesson-review-panel"><div><span className="lessons-kicker">ACADEMIC REVIEW</span><h4>Review against the lesson evidence</h4><p>Approvals and revision requests are preserved in history. Returned plans must be edited and resubmitted before another decision.</p></div><label>Revision reason<select value={reviewReason} onChange={e=>setReviewReason(e.target.value)} disabled={saving}>{REVIEW_REASONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Reviewer note<textarea rows={4} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Explain strengths, concerns or required corrections…" disabled={saving}/></label><div className="lesson-modal-actions"><button className="lessons-secondary" onClick={()=>void reviewAction(selected,"changes_requested")} disabled={saving||!reviewNote.trim()}>Request changes</button><button className="lessons-primary" onClick={()=>void reviewAction(selected,"approved")} disabled={saving}>Approve plan</button></div></section>:null}
   </section></div>}
   {message?<div className="lessons-message" role="status">{message}</div>:null}
  </div></AppShell>;
}
