"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { AppShell } from "@/components/AppShell";
import "./lessons-workspace.css";

type Assignment={classId:string;subjectId:string;class:{name:string;level:string|null};subject:{name:string}};
type Row={id:string;teacherId:string;teacherName:string;classId:string;className:string;subjectId:string;subjectName:string;termName:string|null;title:string;objective:string|null;content:string;plannedDate:string;status:string;reviewNote:string|null};
type Term={id:string;name:string;academicYear:{name:string}};
type Data={rows:Row[];assignments:Assignment[];terms:Term[];review:boolean;manage:boolean};
export default function LessonsPage(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("all"),[message,setMessage]=useState(""),[open,setOpen]=useState(false),[selected,setSelected]=useState<Row|null>(null),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({classId:"",subjectId:"",termId:"",title:"",objective:"",content:"",plannedDate:new Date().toISOString().slice(0,10),status:"draft"});
 const load=()=>fetch("/api/school/lesson-plans").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load lesson plans");return d as Data}).then(setData).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load lesson plans."));
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const rows=data?.rows??[];return tab==="all"?rows:tab==="review"?rows.filter(r=>r.status==="submitted"):rows.filter(r=>r.status===tab)},[data,tab]);
 const counts={all:data?.rows.length??0,draft:data?.rows.filter(r=>r.status==="draft").length??0,submitted:data?.rows.filter(r=>r.status==="submitted").length??0,approved:data?.rows.filter(r=>r.status==="approved").length??0,review:data?.rows.filter(r=>r.status==="submitted").length??0};
 const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/api/school/lesson-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save lesson plan.");setMessage(form.status==="submitted"?"Lesson plan submitted for academic review.":"Lesson plan saved as draft.");setOpen(false);setForm({...form,title:"",objective:"",content:""});await load()}catch(e){setMessage(e instanceof Error?e.message:"Could not save lesson plan.")}finally{setSaving(false)}};
 const review=async(id:string,status:"approved"|"changes_requested")=>{setSaving(true);try{const note=status==="changes_requested"?window.prompt("What should the teacher correct?","")||"Please revise this plan.":"Plan verified against the academic expectations.";const r=await fetch("/api/school/lesson-plans",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,reviewNote:note})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not review lesson plan.");setMessage(status==="approved"?"Lesson plan approved.":"Changes requested from the teacher.");setSelected(null);await load()}catch(e){setMessage(e instanceof Error?e.message:"Review failed")}finally{setSaving(false)}};
 return <AppShell universe="school" title="Lessons & Planning" subtitle="Teachers plan instruction inside their assigned classes and subjects; academic leaders review quality and give feedback." active="Lessons & Planning">
  <div className="lessons-shell"><section className="lessons-hero"><div><span className="lessons-kicker">TEACHING OPERATIONS</span><h2>{data?.review&&!data.manage?"Academic lesson-plan review":"Plan better lessons, in the right class"}</h2><p>{data?.review&&!data.manage?"Review submitted plans, verify objectives and content against the school programme, and send precise feedback back to the teacher.":"Your lesson plans stay attached to the class, subject and term assignment you actually teach."}</p><div className="lessons-pills"><span>{data?.manage?"Teacher authoring enabled":"Review access"}</span><span>{data?.review?"Academic review enabled":"Assignment-scoped workspace"}</span></div></div>{data?.manage?<button className="lessons-primary" onClick={()=>setOpen(true)}>＋ New lesson plan</button>:null}</section>
   <section className="lessons-kpis"><article><span>Total plans</span><strong>{counts.all}</strong><small>Visible to this account</small></article><article><span>Drafts</span><strong>{counts.draft}</strong><small>Not submitted</small></article><article><span>Awaiting review</span><strong>{counts.submitted}</strong><small>Submitted plans</small></article><article><span>Approved</span><strong>{counts.approved}</strong><small>Quality verified</small></article></section>
   <section className="lessons-card"><div className="lessons-tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>All <b>{counts.all}</b></button><button className={tab==="draft"?"active":""} onClick={()=>setTab("draft")}>Drafts <b>{counts.draft}</b></button><button className={tab==="submitted"?"active":""} onClick={()=>setTab("submitted")}>Submitted <b>{counts.submitted}</b></button><button className={tab==="approved"?"active":""} onClick={()=>setTab("approved")}>Approved <b>{counts.approved}</b></button>{data?.review?<button className={tab==="review"?"active":""} onClick={()=>setTab("review")}>Review queue <b>{counts.review}</b></button>:null}</div><div className="lesson-list">{filtered.length===0?<div className="lesson-empty"><h3>No lesson plans in this view</h3><p>{data?.manage?"Start with a class and subject from your assigned teaching load.":"Submitted teacher plans will appear here when they are ready for verification."}</p></div>:filtered.map(row=><article className="lesson-row" key={row.id} onClick={()=>setSelected(row)}><div className="lesson-main"><span>{row.className} · {row.subjectName}</span><h3>{row.title}</h3><p>{row.objective||row.content.slice(0,150)}</p><small>{row.teacherName} · {row.termName||"No term"} · {new Date(row.plannedDate).toLocaleDateString("en-GB")}</small></div><div className="lesson-row-side"><span className={`lesson-status ${row.status}`}>{row.status.replace("_"," ")}</span>{data?.review&&row.status==="submitted"?<div className="lesson-review-buttons"><button onClick={(e)=>{e.stopPropagation();void review(row.id,"approved")}} disabled={saving}>Approve</button><button onClick={(e)=>{e.stopPropagation();void review(row.id,"changes_requested")}} disabled={saving}>Changes</button></div>:null}</div></article>)}</div></section>
   <section className="lessons-card lessons-chain"><div><span className="lessons-kicker">CONNECTED WORKFLOW</span><h3>Assignment → lesson plan → review → teaching → evidence</h3><p>The planning page is deliberately tied to teacher assignments, so a teacher does not create plans for classes they were never assigned.</p></div><div className="lessons-chain-links"><Link href="/school/classes">Assignments <span>→</span></Link><Link href="/school/timetable">Timetable <span>→</span></Link><Link href="/school/homework">Homework <span>→</span></Link><Link href="/school/gradebook/studio">Gradebook <span>→</span></Link></div></section>
   {open&&<div className="lesson-modal-backdrop"><section className="lesson-modal"><div className="lesson-modal-head"><div><span className="lessons-kicker">NEW LESSON PLAN</span><h3>Prepare instruction for an assigned class</h3></div><button onClick={()=>setOpen(false)}>×</button></div><div className="lesson-form-grid"><label>Class<select value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,subjectId:""})}><option value="">Choose class…</option>{data?.assignments.filter((a,i,self)=>self.findIndex(x=>x.classId===a.classId)===i).map(a=><option key={a.classId} value={a.classId}>{a.class.level?`${a.class.level} · `:""}{a.class.name}</option>)}</select></label><label>Subject<select value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Choose subject…</option>{data?.assignments.filter(a=>!form.classId||a.classId===form.classId).map(a=><option key={`${a.classId}:${a.subjectId}`} value={a.subjectId}>{a.subject.name}</option>)}</select></label><label>Term<select value={form.termId} onChange={e=>setForm({...form,termId:e.target.value})}><option value="">No term selected</option>{data?.terms.map(t=><option key={t.id} value={t.id}>{t.name} · {t.academicYear.name}</option>)}</select></label><label>Planned date<input type="date" value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label><label className="wide">Lesson title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Fractions on a number line"/></label><label className="wide">Learning objective<input value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})} placeholder="What should learners be able to do?"/></label><label className="wide">Plan / teaching notes<textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} rows={8} placeholder="Starter, explanation, guided practice, independent work, evidence of learning…"/></label></div><div className="lesson-modal-actions"><button className="lessons-secondary" onClick={()=>{setForm({...form,status:"draft"});void save()}} disabled={saving}>Save draft</button><button className="lessons-primary" onClick={()=>{setForm({...form,status:"submitted"});setTimeout(()=>void save(),0)}} disabled={saving}>Submit for review</button></div></section></div>}
   {selected&&<div className="lesson-modal-backdrop" onClick={()=>setSelected(null)}><section className="lesson-modal" onClick={e=>e.stopPropagation()}><div className="lesson-modal-head"><div><span className="lessons-kicker">LESSON PLAN</span><h3>{selected.title}</h3><p>{selected.teacherName} · {selected.className} · {selected.subjectName}</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="lesson-detail"><div><b>Objective</b><p>{selected.objective||"Not specified"}</p></div><div><b>Teaching plan</b><p className="prewrap">{selected.content}</p></div>{selected.reviewNote?<div className="lesson-note"><b>Reviewer note</b><p>{selected.reviewNote}</p></div>:null}</div>{data?.review&&selected.status==="submitted"?<div className="lesson-modal-actions"><button className="lessons-secondary" onClick={()=>void review(selected.id,"changes_requested")} disabled={saving}>Request changes</button><button className="lessons-primary" onClick={()=>void review(selected.id,"approved")} disabled={saving}>Approve plan</button></div>:null}</section></div>}
   {message?<div className="lessons-message">{message}</div>:null}
  </div></AppShell>;
}
