import { NextResponse } from "next/server";
import { z } from "zod";
import { getPlatformSession } from "@/lib/auth";
import { routeError, UnauthorizedError } from "@/lib/errors";
import { getPlatformOverview, listPlatformAdmins, createPlatformAdmin, updatePlatformAdmin, listPlatformAudit, getPlatformHealth, getSchoolSnapshot, ADMIN_PERMISSIONS } from "@/lib/platform-admin-service";
const schema=z.discriminatedUnion("action",[
 z.object({action:z.literal("createWorker"),name:z.string().min(2).max(160),email:z.string().email(),password:z.string().min(12).max(256),role:z.enum(["platform_admin","support_admin","billing_admin","analytics_admin"]),permissions:z.array(z.string()).max(30)}),
 z.object({action:z.literal("updateWorker"),adminId:z.string(),status:z.enum(["active","suspended"]),role:z.enum(["super_admin","platform_admin","support_admin","billing_admin","analytics_admin"]).optional(),permissions:z.array(z.string()).max(30).optional()})
]);
export async function GET(request:Request){try{const session=await getPlatformSession();if(!session)throw new UnauthorizedError();const u=new URL(request.url),view=u.searchParams.get("view")||"overview",schoolId=u.searchParams.get("schoolId")||"";if(view==="overview")return NextResponse.json(await getPlatformOverview());if(view==="admins")return NextResponse.json({admins:await listPlatformAdmins(session.role),permissions:ADMIN_PERMISSIONS});if(view==="audit")return NextResponse.json({events:await listPlatformAudit(session.role,Number(u.searchParams.get("limit")||100))});if(view==="health")return NextResponse.json(await getPlatformHealth());if(view==="school"){if(!schoolId)throw new UnauthorizedError("schoolId is required");return NextResponse.json(await getSchoolSnapshot(session.role,schoolId));}throw new UnauthorizedError("Unknown admin view");}catch(e){return routeError(e);}}
export async function POST(request:Request){try{const session=await getPlatformSession();if(!session)throw new UnauthorizedError();const input=await request.json();const parsed=schema.parse(input);if(parsed.action==="createWorker")return NextResponse.json({ok:true,worker:await createPlatformAdmin({actorId:session.adminId,actorRole:session.role,...parsed})},{status:201});return NextResponse.json({ok:true,worker:await updatePlatformAdmin({actorId:session.adminId,actorRole:session.role,...parsed})});}catch(e){return routeError(e);}}
