"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import "./terms.css";

type Term={id:string;name:string;startDate:string;endDate:string;status:"upcoming"|"current"|"completed";academicYear:{id:string;name:string;startDate:string;endDate:string}};
type Summary={students:number;assessments:number;scores:number;scorePct:number|null;reportCards:number;attendance:{records:number;present:number;late:number;absent:number};finance:{invoiceCount:number;invoiced:number;collected:number;outstanding:number}};

auto constDate=(value:string)=>value.slice(0,10);
const humanDate=(s:string)=>new Date(s).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});
const daysBetween=(a:string,b:string)=>Math.max(1,Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000));

export default function TermsPage(){
 const [terms,setTerms]=useState<Term[]>([]);const [selected,setSelected]=useState("");const [summary,setSummary]=useState<Summary|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [editor,setEditor]=useState<"create"|"edit"|null>(null);
 const [form,setForm]=useState({academicYearName:"",academicYearStart:"",academicYearEnd:"",name:"",startDate:"",endDate:""});
 const active=useMemo(()=>terms.find(t=>t.id===selected)??null,[terms,selected]);
 const years=useMemo(()=>Array.from(new Map(terms.map(t=>[t.academicYear.id,t.academicYear])).values()).sort((a,b)=>new Date(b.startDate).getTime()-new Date(a.startDate).getTime()),[terms]);
 const currentYear=useMemo(()=>active?.academicYear??years[0]??null,[active,years]);
 const yearTerms=useMemo(()=>currentYear?terms.filter(t=>t.academicYear.id===currentYear.id).sort((a,b)=>new Date(a.startDate).getTime()-new Date(b.startDate).getTime()):[],[terms,currentYear]);
 const yearDuration=currentYear?daysBetween(currentYear.startDate,currentYear.endDate):1;
 const elapsed=currentYear?Math.min(yearDuration,Math.max(0,daysBetween(currentYear.startDate,new Date().toISOString()))):0;

 const loadTerms=async()=>{setError("");const r=await fetch("/api/school/terms");const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to load academic calendar.");setTerms(j.terms);const next=j.terms.find((t:Term)=>t.status==="current")??j.terms[0];if(next)setSelected(next.id);};
 useEffect(()=>{void loadTerms().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!selected){setSummary(null);return;}fetch(`/api/school/terms/${selected}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to load term summary.");setSummary(j);}).catch(e=>setError(e.message));},[selected]);

 const beginCreate=()=>{const y=currentYear??{name:"",startDate:"",endDate:""};setForm({academicYearName:y.name??"",academicYearStart:auto constDate(y.startDate??""),academicYearEnd:auto constDate(y.endDate??""),name:"New Term",startDate:"",endDate:""});setEditor("create");setNotice("");};
 const beginEdit=()=>{if(!active)return;setForm({academicYearName:active.academicYear.name,academicYearStart:auto constDate(active.academicYear.startDate),academicYearEnd:auto constDate(active.academicYear.endDate),name:active.name,startDate:auto constDate(active.startDate),endDate:auto constDate(active.endDate)});setEditor("edit");setNotice("");};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setNotice("");try{const url=editor==="edit"?`/api/school/terms/${active?.id}`:"/api/school/terms";const body=editor==="edit"?{name:form.name,startDate:form.startDate,endDate:form.endDate}:form;const r=await fetch(url,{method:editor==="edit"?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error??"Could not save term.");setEditor(null);setNotice(editor==="edit"?"Term dates updated successfully.":"Academic year and term created successfully.");await loadTerms();if(j.term?.id)setSelected(j.term.id);}catch(err){setError(err instanceof Error?err.message:"Could not save term.");}finally{setBusy(false)}};

 return <AppShell universe="school" title="Terms & Academic Calendar" subtitle="Own the academic year from one place: create and edit terms, understand where the school is in its cycle, and hand the correct period context to every academic workflow." active="Terms & Calendar">
  <div className="terms-workspace">
   <header className="terms-hero"><div><span className="terms-kicker">ACADEMIC TIMELINE</span><h2>{currentYear?.name??"Build your academic calendar"}</h2><p>{currentYear?`${humanDate(currentYear.startDate)} → ${humanDate(currentYear.endDate)} · ${yearTerms.length} term${yearTerms.length===1?"":"s"}`:"Create your first academic year and terms here. This becomes the shared time context for results, attendance, reports and finance."}</p></div><div className="terms-hero-actions"><Link href="/school/academics/setup" className="terms-btn secondary">Academic Setup</Link><Link href="/school/academics/health" className="terms-btn secondary">Readiness</Link><button className="terms-btn primary" onClick={beginCreate}>+ New term</button></div></header>
   {error&&<div className="terms-alert error">{error}</div>}{notice&&<div className="terms-alert success">{notice}</div>}

   <section className="calendar-overview">
    <div className="calendar-card year-card"><div className="calendar-heading"><div><span className="terms-kicker">ACADEMIC YEAR</span><h3>{currentYear?.name??"No academic year yet"}</h3></div>{currentYear&&<button className="terms-icon-btn" onClick={()=>{setForm({academicYearName:currentYear.name,academicYearStart:auto constDate(currentYear.startDate),academicYearEnd:auto constDate(currentYear.endDate),name:"New Term",startDate:"",endDate:""});setEditor("create");}}>Edit year</button>}</div>{currentYear?<><div className="year-dates"><span>{humanDate(currentYear.startDate)}</span><b>→</b><span>{humanDate(currentYear.endDate)}</span></div><div className="year-track"><i style={{width:`${Math.round((elapsed/yearDuration)*100)}%`}}/><div className="term-marks">{yearTerms.map(t=>{const left=Math.max(0,Math.min(100,(daysBetween(currentYear.startDate,t.startDate)/yearDuration)*100));return <button key={t.id} style={{left:`${left}%`}} onClick={()=>setSelected(t.id)} title={`${t.name}: ${humanDate(t.startDate)} → ${humanDate(t.endDate)}`}><span>{t.name}</span></button>;})}</div></div><div className="calendar-legend"><span><i className="legend-dot current"/>Today</span><span><i className="legend-line"/>Term boundaries</span><span><i className="legend-dot"/>Completed / upcoming</span></div></>:<button className="empty-create" onClick={beginCreate}>+ Create academic year</button>}</div>
    <div className="calendar-card year-list"><div className="calendar-heading"><div><span className="terms-kicker">YEAR HISTORY</span><h3>Academic years</h3></div></div>{years.length?<div className="year-list-items">{years.map(y=><button key={y.id} className={`year-list-item ${currentYear?.id===y.id?"active":""}`} onClick={()=>{const t=terms.find(x=>x.academicYear.id===y.id);if(t)setSelected(t.id);}}><div><b>{y.name}</b><span>{humanDate(y.startDate)} → {humanDate(y.endDate)}</span></div><strong>{terms.filter(t=>t.academicYear.id===y.id).length}</strong></button>)}</div>:<p className="muted">No academic years recorded yet.</p>}</div>
   </section>

   <section className="term-manager">
    <div className="term-list-card calendar-card"><div className="calendar-heading"><div><span className="terms-kicker">TERM MANAGER</span><h3>{currentYear?`${currentYear.name} terms`:"Terms"}</h3><p>Choose a term to see its live connected records and edit its dates.</p></div><button className="terms-icon-btn" onClick={beginCreate}>+ Add term</button></div><div className="term-manager-list">{yearTerms.length?yearTerms.map((t,i)=><button key={t.id} onClick={()=>setSelected(t.id)} className={`term-manager-item ${selected===t.id?"selected":""}`}><div className="term-order">0{i+1}</div><div className="term-main"><div><b>{t.name}</b><span className={`term-status ${t.status}`}>{t.status}</span></div><p>{humanDate(t.startDate)} → {humanDate(t.endDate)}</p></div><div className="term-duration">{daysBetween(t.startDate,t.endDate)}<span>days</span></div><span className="term-arrow">→</span></button>):<div className="empty-state">No terms exist for this academic year. Start the cycle with your first term.</div>}</div></div>

    <div className="term-detail-card calendar-card">{active&&summary?<><div className="calendar-heading"><div><span className="terms-kicker">SELECTED TERM</span><h3>{active.name}</h3><p>{active.academicYear.name} · {humanDate(active.startDate)} → {humanDate(active.endDate)}</p></div><div className="detail-actions"><button className="terms-icon-btn" onClick={beginEdit}>Edit term</button></div></div><div className="term-status-banner"><span className={`term-status ${active.status}`}>{active.status}</span><div><b>{active.status==="current"?"This term is active now.":active.status==="upcoming"?"This term is scheduled next.":"This term is complete."}</b><small>{active.status==="completed"?"Historical records remain connected for review and reporting.":"Academic pages should use this term as their working context when appropriate."}</small></div></div><div className="connected-grid"><div><b>{summary.students}</b><span>Active students</span></div><div><b>{summary.assessments}</b><span>Assessments</span></div><div><b>{summary.scores}</b><span>Scores</span></div><div><b>{summary.scorePct==null?"—":`${summary.scorePct.toFixed(1)}%`}</b><span>Average score</span></div><div><b>{summary.attendance.records}</b><span>Attendance records</span></div><div><b>{summary.reportCards}</b><span>Report cards</span></div><div><b>₵{summary.finance.collected.toFixed(2)}</b><span>Collected</span></div><div><b>₵{summary.finance.outstanding.toFixed(2)}</b><span>Outstanding</span></div></div><div className="workflow-handoff"><div><span className="terms-kicker">CONNECTED WORKFLOWS</span><h4>Continue with this term</h4></div><div className="handoff-grid"><Link href="/school/academics/health"><span>✓</span><b>Academic Readiness</b><small>Check setup gaps</small><em>→</em></Link><Link href="/school/timetable"><span>◷</span><b>Timetable</b><small>Plan teaching time</small><em>→</em></Link><Link href="/school/gradebook"><span>▥</span><b>Gradebook</b><small>Enter term results</small><em>→</em></Link><Link href="/school/attendance"><span>◉</span><b>Attendance</b><small>Track this period</small><em>→</em></Link><Link href="/school/report-cards"><span>▤</span><b>Report Cards</b><small>Publish term reports</small><em>→</em></Link><Link href="/school/fees"><span>₵</span><b>Finance</b><small>Review term balances</small><em>→</em></Link></div></div></>:<div className="term-detail-empty"><span>◫</span><h3>Choose a term</h3><p>Select a term from the list to see its connected academic, attendance, reporting and finance activity.</p></div>}</div>
   </section>
  </div>

  {editor&&<div className="term-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target&&!busy)setEditor(null)}}><form className="term-modal" onSubmit={submit}><div className="modal-head"><div><span className="terms-kicker">{editor==="edit"?"EDIT TERM":"CREATE ACADEMIC PERIOD"}</span><h3>{editor==="edit"?"Update this term":"Create academic year + term"}</h3><p>{editor==="edit"?"Change the term name or dates without losing connected records.":"Define the academic year window first, then place the term inside it."}</p></div><button type="button" className="terms-icon-btn" onClick={()=>setEditor(null)}>×</button></div><div className="form-grid">{editor==="create"&&<><label>Academic year name<input required value={form.academicYearName} onChange={e=>setForm({...form,academicYearName:e.target.value})} placeholder="2026/2027"/></label><label>Academic year starts<input required type="date" value={form.academicYearStart} onChange={e=>setForm({...form,academicYearStart:e.target.value})}/></label><label>Academic year ends<input required type="date" value={form.academicYearEnd} onChange={e=>setForm({...form,academicYearEnd:e.target.value})}/></label></>}<label>Term name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="First Term"/></label><label>Term starts<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Term ends<input required type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><div className="modal-note"><b>Validation is built in.</b><span>Terms cannot end before they start, cannot overlap another term in the same academic year, and must remain inside the academic-year window.</span></div><div className="modal-actions"><button type="button" className="terms-btn secondary" onClick={()=>setEditor(null)}>Cancel</button><button type="submit" className="terms-btn primary" disabled={busy}>{busy?"Saving…":editor==="edit"?"Save term":"Create term"}</button></div></form></div>}
 </AppShell>;
}
