import { NextResponse } from "next/server";
import { z } from "zod";
import { hash } from "bcryptjs";
import { getSchoolSession } from "@/lib/auth";
import { withTenant } from "@/lib/db";
import { requirePermission } from "@/lib/rbac";
import { appendSchoolAudit } from "@/lib/audit";
import { routeError, UnauthorizedError, ForbiddenError } from "@/lib/errors";

const createSchema = z.object({name:z.string().min(2).max(160),email:z.string().email(),phone:z.string().max(40).optional(),password:z.string().min(12).max(256),roleName:z.string().min(2).max(80)});
const updateSchema = z.object({userId:z.string().min(1),status:z.enum(["active","suspended"]),roleName:z.string().min(2).max(80).optional()});
async function canManage(tx:Parameters<typeof requirePermission>[0],userId:string){try{await requirePermission(tx,userId,"users:write");return true}catch{return false}}
export async function GET(){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();return NextResponse.json(await withTenant(session.schoolId,async tx=>{const users=await tx.user.findMany({orderBy:{name:"asc"},select:{id:true,name:true,email:true,phone:true,status:true,createdAt:true,userRoles:{select:{role:{select:{id:true,name:true,key:true,isSystem:true}}}}}});const roles=await tx.role.findMany({orderBy:{name:"asc"},select:{id:true,name:true,key:true,isSystem:true}});return{users,roles,me:session.userId,canManage:await canManage(tx,session.userId)};}))}catch(error){return routeError(error)}}
export async function POST(request:Request){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();const input=createSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{if(!(await canManage(tx,session.userId)))throw new ForbiddenError("You do not have permission to manage sub-accounts.");const role=await tx.role.findUnique({where:{schoolId_name:{schoolId:session.schoolId,name:input.roleName}}});if(!role)throw new ForbiddenError("That role is not available in this school.");const user=await tx.user.create({data:{school:{connect:{id:session.schoolId}},name:input.name.trim(),email:input.email.trim().toLowerCase(),phone:input.phone?.trim()||undefined,passwordHash:await hash(input.password,12),status:"active"},select:{id:true,name:true,email:true,phone:true,status:true}});await tx.userRole.create({data:{schoolId:session.schoolId,userId:user.id,roleId:role.id}});await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"user.subaccount_created",entityType:"User",entityId:user.id,after:{roleName:role.name,email:user.email}});return user;}),{status:201})}catch(error){return routeError(error)}}
export async function PATCH(request:Request){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();const input=updateSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{if(!(await canManage(tx,session.userId)))throw new ForbiddenError("You do not have permission to manage sub-accounts.");if(input.userId===session.userId&&input.status==="suspended")throw new ForbiddenError("You cannot suspend your own account.");const target=await tx.user.findUnique({where:{id:input.userId},select:{id:true,status:true}});if(!target)throw new UnauthorizedError("Account not found.");const user=await tx.user.update({where:{id:input.userId},data:{status:input.status}});if(input.roleName){const role=await tx.role.findUnique({where:{schoolId_name:{schoolId:session.schoolId,name:input.roleName}}});if(!role)throw new ForbiddenError("That role is not available in this school.");await tx.userRole.deleteMany({where:{userId:input.userId,schoolId:session.schoolId}});await tx.userRole.create({data:{schoolId:session.schoolId,userId:input.userId,roleId:role.id}})}await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"user.subaccount_updated",entityType:"User",entityId:user.id,after:{status:user.status,roleName:input.roleName}});return user;}))}catch(error){return routeError(error)}}
