import { NextResponse } from "next/server";
import { z } from "zod";
import { hash } from "bcryptjs";
import { getSchoolSession } from "@/lib/auth";
import { withTenant } from "@/lib/db";
import { requirePermission } from "@/lib/rbac";
import { appendSchoolAudit } from "@/lib/audit";
import { routeError, UnauthorizedError, ForbiddenError, AppError } from "@/lib/errors";
import { syncDefaultRbac } from "@/lib/role-builder-service";

const createSchema = z.object({ name:z.string().min(2).max(160), email:z.string().email(), phone:z.string().max(40).optional(), password:z.string().min(12).max(256), roleNames:z.array(z.string().min(2).max(80)).min(1).max(12).optional(), roleName:z.string().min(2).max(80).optional() }).refine((x)=>Boolean(x.roleNames?.length||x.roleName),{message:"At least one role is required."});
const updateSchema = z.object({ userId:z.string().min(1), status:z.enum(["active","suspended","pending"]), password:z.string().min(12).max(256).optional(), roleNames:z.array(z.string().min(2).max(80)).min(1).max(12).optional(), roleName:z.string().min(2).max(80).optional(), grantedPermissionKeys:z.array(z.string()).max(100).optional(), deniedPermissionKeys:z.array(z.string()).max(100).optional(), clearPermissionOverrides:z.boolean().optional() });
async function canManage(tx:Parameters<typeof requirePermission>[0],userId:string){try{await requirePermission(tx,userId,"users:write");return true}catch{return false}}
async function canControlRoles(tx:Parameters<typeof requirePermission>[0],userId:string){try{await requirePermission(tx,userId,"roles:create_custom");return true}catch{return false}}
async function roleIdsForNames(tx:Parameters<typeof requirePermission>[0],schoolId:string,names:string[]){const unique=[...new Set(names.map((n)=>n.trim()).filter(Boolean))];const roles=await tx.role.findMany({where:{schoolId,name:{in:unique}}});if(roles.length!==unique.length)throw new ForbiddenError("One or more selected roles are not available in this school.");return roles;}
async function permissionIdsForKeys(tx:Parameters<typeof requirePermission>[0],keys:string[]){const unique=[...new Set(keys)];const rows=await tx.permission.findMany({where:{key:{in:unique}}});if(rows.length!==unique.length)throw new AppError("One or more permission keys are invalid.",400,"INVALID_PERMISSION");return new Map(rows.map((row)=>[row.key,row.id]));}
function isTeachingRole(name:string){return /teacher|class teacher|subject teacher/i.test(name)}
function validateRoleBundle(roleNames:string[]){const normalized=roleNames.map((name)=>name.trim().toLowerCase());if(normalized.includes("owner")&&normalized.some((name)=>/teacher|class teacher|subject teacher/i.test(name)))throw new ForbiddenError("A teacher cannot be assigned the Owner role. Keep school ownership separate from teaching access.");}

export async function GET(){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();return NextResponse.json(await withTenant(session.schoolId,async tx=>{await syncDefaultRbac(tx,session.schoolId);const users=await tx.user.findMany({orderBy:{name:"asc"},select:{id:true,name:true,email:true,phone:true,status:true,createdAt:true,userRoles:{select:{role:{select:{id:true,name:true,key:true,isSystem:true}}}},permissionOverrides:{select:{granted:true,permission:{select:{key:true,description:true}}}}}});const roles=await tx.role.findMany({where:{schoolId:session.schoolId},orderBy:[{isSystem:"desc"},{name:"asc"}],select:{id:true,name:true,key:true,isSystem:true,rolePermissions:{select:{permission:{select:{key:true}}}}}});const permissions=await tx.permission.findMany({orderBy:{key:"asc"},select:{id:true,key:true,description:true}});return{users,roles,permissions,me:session.userId,canManage:await canManage(tx,session.userId),canControlRoles:await canControlRoles(tx,session.userId)};}))}catch(error){return routeError(error)}}

export async function POST(request:Request){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();const input=createSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{if(!(await canManage(tx,session.userId)))throw new ForbiddenError("You do not have permission to manage sub-accounts.");await syncDefaultRbac(tx,session.schoolId);const roleNames=input.roleNames?.length?input.roleNames:[input.roleName!];validateRoleBundle(roleNames);if(roleNames.some(isTeachingRole))throw new ForbiddenError("Create the teacher in Staff & Teachers first, then activate the teacher's login from Sub-accounts & Access.");const roles=await roleIdsForNames(tx,session.schoolId,roleNames);const user=await tx.user.create({data:{school:{connect:{id:session.schoolId}},name:input.name.trim(),email:input.email.trim().toLowerCase(),phone:input.phone?.trim()||undefined,passwordHash:await hash(input.password,12),status:"active"},select:{id:true,name:true,email:true,phone:true,status:true}});await tx.userRole.createMany({data:roles.map((role)=>({schoolId:session.schoolId,userId:user.id,roleId:role.id}))});await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"user.subaccount_created",entityType:"User",entityId:user.id,after:{roleNames:roles.map((role)=>role.name),email:user.email}});return user;}),{status:201})}catch(error){return routeError(error)}}

export async function PATCH(request:Request){try{const session=await getSchoolSession();if(!session)throw new UnauthorizedError();const input=updateSchema.parse(await request.json());return NextResponse.json(await withTenant(session.schoolId,async tx=>{if(!(await canManage(tx,session.userId)))throw new ForbiddenError("You do not have permission to manage sub-accounts.");await syncDefaultRbac(tx,session.schoolId);if(input.userId===session.userId&&input.status==="suspended")throw new ForbiddenError("You cannot suspend your own account.");const target=await tx.user.findUnique({where:{id:input.userId},select:{id:true,name:true,status:true,email:true,phone:true,passwordHash:true}});if(!target)throw new UnauthorizedError("Account not found.");
 const activatingPending = target.status === "pending" && input.status === "active";
 if(activatingPending && !input.password)throw new AppError("Set a login password before activating this staff member.",400,"PASSWORD_REQUIRED");
 const roleControlRequested=Boolean(input.roleNames?.length||input.roleName||input.grantedPermissionKeys||input.deniedPermissionKeys||input.clearPermissionOverrides);if(roleControlRequested&&!(await canControlRoles(tx,session.userId)))throw new ForbiddenError("Only an account with role-control permission can change roles or direct permissions.");
 if(input.roleNames?.length||input.roleName){const roleNames=input.roleNames?.length?input.roleNames:[input.roleName!];validateRoleBundle(roleNames);const roles=await roleIdsForNames(tx,session.schoolId,roleNames);await tx.userRole.deleteMany({where:{userId:input.userId,schoolId:session.schoolId}});await tx.userRole.createMany({data:roles.map((role)=>({schoolId:session.schoolId,userId:input.userId,roleId:role.id}))});}
 const user=await tx.user.update({where:{id:input.userId},data:{status:input.status,...(input.password?{passwordHash:await hash(input.password,12)}:{})}});
 if(input.clearPermissionOverrides) await tx.userPermissionOverride.deleteMany({where:{userId:input.userId,schoolId:session.schoolId}});
 const grants=input.grantedPermissionKeys??[];const denies=input.deniedPermissionKeys??[];if(grants.length||denies.length){const all=[...new Set([...grants,...denies])];const ids=await permissionIdsForKeys(tx,all);for(const key of grants)await tx.userPermissionOverride.upsert({where:{userId_permissionId:{userId:input.userId,permissionId:ids.get(key)!}},update:{schoolId:session.schoolId,granted:true},create:{schoolId:session.schoolId,userId:input.userId,permissionId:ids.get(key)!,granted:true}});for(const key of denies)await tx.userPermissionOverride.upsert({where:{userId_permissionId:{userId:input.userId,permissionId:ids.get(key)!}},update:{schoolId:session.schoolId,granted:false},create:{schoolId:session.schoolId,userId:input.userId,permissionId:ids.get(key)!,granted:false}});}
 await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:activatingPending?"user.staff_login_activated":"user.subaccount_updated",entityType:"User",entityId:user.id,after:{status:user.status,roleNames:input.roleNames??(input.roleName?[input.roleName]:undefined),grants,denies,overridesCleared:Boolean(input.clearPermissionOverrides),loginActivated:activatingPending}});return user;}))}catch(error){return routeError(error)}}
