import Link from "next/link";
import "./home.css";

const modules = [
  ["Students", "Admissions, records, guardians and learner journeys", "01", "/school/students"],
  ["Academics", "Classes, subjects, timetable, homework and results", "02", "/school/subjects"],
  ["Attendance", "Daily registers, lateness, absence and alerts", "03", "/school/attendance"],
  ["Fees & finance", "Invoices, receipts, balances and collections", "04", "/school/fees"],
  ["Communication", "Guardians, announcements, SMS, WhatsApp and events", "05", "/school/communications/announcements"],
  ["People & HR", "Teachers, staff, roles, leave and payroll", "06", "/school/staff"],
];

export default function HomePage() {
  return <main className="home-shell"><div className="home-glow home-glow-a" /><div className="home-glow home-glow-b" /><div className="home-wrap"><header className="topbar"><Link href="/" className="brand" aria-label="SukuuNova home"><img className="brand-logo" src="/brand/sukuunova-logo.svg" alt="SukuuNova" /><span className="sr-only">SukuuNova</span></Link><nav className="topnav" aria-label="Primary navigation"><a href="#platform">Platform</a><a href="#modules">What it manages</a><a href="#schools">For schools</a></nav><div className="top-actions"><Link className="top-link" href="/login/platform">Platform</Link><Link className="top-button" href="/login/school">Enter your school <span>↗</span></Link></div></header>
    <section className="hero" id="platform"><div className="hero-copy-wrap"><div className="eyebrow"><span className="eyebrow-dot" /> Built for modern African schools</div><h1>One beautiful system for <span>the whole school.</span></h1><p className="hero-copy">SukuuNova brings administrators, teachers, finance teams, students and families into one calm, connected workspace built around the real school day.</p><div className="hero-actions"><Link className="primary-cta" href="/login/school">Enter your school <span>→</span></Link></div><div className="hero-proof"><img className="proof-logo" src="/icon.svg" alt="" /><div><strong>One school gateway.</strong><span>Enter your school code, choose Staff or Guardian, and continue securely.</span></div></div></div>
      <div className="hero-product" aria-hidden="true"><div className="dashboard-window"><div className="window-top"><div className="window-dots"><i /><i /><i /></div><span>SukuuNova / Overview</span><b>Connected school workspace</b></div><div className="window-body"><aside className="window-side"><img className="side-logo-image" src="/icon.svg" alt="" /><span className="side-active">⌂</span><span>♟</span><span>▣</span><span>✓</span><span>₵</span><span>✉</span><span>⚙</span></aside><div className="window-main"><div className="window-heading"><div><small>School command centre</small><h3>Good morning, School Team</h3></div><span className="live-dot">● Live</span></div><div className="window-kpis"><div><small>Students</small><strong>Live</strong><span>Real school records</span></div><div><small>Attendance</small><strong>Today</strong><span>Register & exceptions</span></div><div><small>Finance</small><strong>₵</strong><span>Fees & collections</span></div></div><div className="window-content-row"><div className="fake-chart"><div className="fake-head"><strong>Connected workflows</strong><span>School day</span></div><div className="fake-bars">{[42,55,49,68,61,82,72,88].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div><div className="fake-list"><div className="fake-head"><strong>Today</strong><span>View all</span></div><div><b>Admissions</b><small>Enquiries → applications → enrolment</small></div><div><b>Academics</b><small>Classes → lessons → marks → report cards</small></div><div><b>Families</b><small>Announcements, messages & alerts</small></div></div></div></div></div></div><div className="hero-float float-one"><span className="float-icon">✦</span><div><small>Built around workflows</small><strong>One connected school</strong></div><em>Ready</em></div><div className="hero-float float-two"><span className="float-icon">✓</span><div><small>Access control</small><strong>Role based</strong></div><em>Protected</em></div></div>
    </section>
    <section className="stats-strip" id="schools"><div><strong>One connected record</strong><span>students, families, staff and operations</span></div><div><strong>GHS-ready finance</strong><span>fees, invoices, receipts and balances</span></div><div><strong>Internal communication</strong><span>announcements before SMS and WhatsApp</span></div><div><strong>Role-based portals</strong><span>the right tools for every school user</span></div></section>
    <section className="modules" id="modules"><div className="section-kicker">THE SCHOOL, IN ONE PLACE</div><div className="section-head"><h2>Everything your school actually manages.</h2><p>Explore the real workspaces. Each area opens into the authenticated school environment.</p></div><div className="module-grid">{modules.map(([title,copy,num,href])=><Link className="module-card" href={href} key={title}><span className="module-num">{num}</span><h3>{title}</h3><p>{copy}</p><span className="module-arrow">→</span></Link>)}</div></section>
    <section className="closing-cta"><div><span className="section-kicker">READY FOR THE SCHOOL DAY</span><h2>Less chasing. More control.</h2><p>A school platform should feel like a command centre, not a collection of disconnected screens.</p></div><Link className="primary-cta" href="/login/school">Enter your school <span>→</span></Link></section>
    <footer className="footer"><span>© 2026 SukuuNova</span><span>Secure school software · Ghana and beyond</span><span><Link href="/login/school">School access</Link> · <Link href="/login/platform">Platform access</Link></span></footer></div></main>;
}
