import Link from "next/link";
import "./home.css";

const modules = [
  ["Students", "Admissions, records, guardians and learner journeys", "01"],
  ["Academics", "Classes, subjects, timetable, homework and results", "02"],
  ["Attendance", "Daily registers, lateness, absence and alerts", "03"],
  ["Fees & finance", "Invoices, receipts, balances and collections", "04"],
  ["Communication", "Guardians, announcements, SMS, WhatsApp and events", "05"],
  ["People & HR", "Teachers, staff, roles, leave and payroll", "06"],
];

export default function HomePage() {
  return <main className="home-shell"><div className="home-glow home-glow-a" /><div className="home-glow home-glow-b" /><div className="home-wrap"><header className="topbar"><Link href="/" className="brand" aria-label="SukuuNova home"><img className="brand-logo" src="/brand/sukuunova-logo.svg" alt="SukuuNova" /><span className="sr-only">SukuuNova</span></Link><nav className="topnav" aria-label="Primary navigation"><a href="#platform">Platform</a><a href="#modules">What it manages</a><a href="#schools">For schools</a></nav><div className="top-actions"><Link className="top-link" href="/login/platform">Platform</Link><Link className="top-button" href="/login/school">Enter your school <span>↗</span></Link></div></header>
    <section className="hero" id="platform"><div className="hero-copy-wrap"><div className="eyebrow"><span className="eyebrow-dot" /> Built for modern African schools</div><h1>One beautiful system for <span>the whole school.</span></h1><p className="hero-copy">SukuuNova brings the work of administrators, teachers, finance teams, students and families into one calm, connected workspace.</p><div className="hero-actions"><Link className="primary-cta" href="/login/school">Enter your school <span>→</span></Link></div><div className="hero-proof"><img className="proof-logo" src="/icon.svg" alt="" /><div><strong>One school gateway.</strong><span>Enter your school code, choose Staff or Guardian, and continue securely.</span></div></div></div>
      <div className="hero-product" aria-hidden="true"><div className="dashboard-window"><div className="window-top"><div className="window-dots"><i /><i /><i /></div><span>SukuuNova / Overview</span><b>Term 1 · 2026/27</b></div><div className="window-body"><aside className="window-side"><img className="side-logo-image" src="/icon.svg" alt="" /><span className="side-active">⌂</span><span>♟</span><span>▣</span><span>✓</span><span>₵</span><span>✉</span><span>⚙</span></aside><div className="window-main"><div className="window-heading"><div><small>Tuesday, 28 August</small><h3>Good morning, School Team</h3></div><span className="live-dot">● Live</span></div><div className="window-kpis"><div><small>Students</small><strong>1,247</strong><span>+12 this term</span></div><div><small>Attendance</small><strong>94.5%</strong><span>+2.1% today</span></div><div><small>Fees collected</small><strong>GH₵125k</strong><span>+8% this month</span></div></div><div className="window-content-row"><div className="fake-chart"><div className="fake-head"><strong>School performance</strong><span>Last 6 months</span></div><div className="fake-bars">{[42,55,49,68,61,82,72,88].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div><div className="fake-list"><div className="fake-head"><strong>Today</strong><span>View all</span></div><div><b>Fee balance review</b><small>12 families need follow-up</small></div><div><b>Admissions</b><small>7 applications awaiting approval</small></div><div><b>Attendance</b><small>3 classes incomplete</small></div></div></div></div></div></div><div className="hero-float float-one"><span className="float-icon">₵</span><div><small>Fees collected</small><strong>GH₵125,430</strong></div><em>+8.2%</em></div><div className="hero-float float-two"><span className="float-icon">✓</span><div><small>Attendance today</small><strong>94.5%</strong></div><em>Excellent</em></div></div>
    </section>
    <section className="stats-strip" id="schools"><div><strong>Every school function</strong><span>designed as one connected workflow</span></div><div><strong>GHS-ready finance</strong><span>fees, receipts, balances and collections</span></div><div><strong>Family-first communication</strong><span>clear updates without the usual chasing</span></div><div><strong>Role-based access</strong><span>the right tools for every school user</span></div></section>
    <section className="modules" id="modules"><div className="section-kicker">THE SCHOOL, IN ONE PLACE</div><div className="section-head"><h2>Everything your school actually manages.</h2><p>Stop thinking in software “phases”. SukuuNova is organised around the real work happening every day.</p></div><div className="module-grid">{modules.map(([title,copy,num])=><article className="module-card" key={title}><span className="module-num">{num}</span><h3>{title}</h3><p>{copy}</p><span className="module-arrow">→</span></article>)}</div></section>
    <section className="closing-cta"><div><span className="section-kicker">READY FOR THE SCHOOL DAY</span><h2>Less chasing. More control.</h2><p>A school platform should feel like a command centre, not a collection of disconnected screens.</p></div><Link className="primary-cta" href="/login/school">Enter your school <span>→</span></Link></section>
    <footer className="footer"><span>© 2026 SukuuNova</span><span>Secure school software · Ghana and beyond</span><span><Link href="/login/school">School access</Link> · <Link href="/login/platform">Platform access</Link></span></footer></div></main>;
}
