import Link from "next/link";
import { ArrowLeft, ReceiptText, ShieldCheck } from "lucide-react";
import OperationsPrintActions from "@/components/OperationsPrintActions";
import { requireSchoolSession } from "@/lib/auth";
import { withTenant } from "@/lib/db";
import { schoolStoreExportRows } from "@/lib/school-store-service";
import "./store-history-print.css";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS", maximumFractionDigits: 2 });
const when = new Intl.DateTimeFormat("en-GH", { dateStyle: "medium", timeStyle: "short" });

export default async function StoreHistoryPrintPage() {
  const session = await requireSchoolSession();
  const data = await withTenant(session.schoolId, async (tx) => {
    const [school, rows] = await Promise.all([
      tx.school.findUnique({ where: { id: session.schoolId }, select: { name: true, uniqueCode: true, logoUrl: true } }),
      schoolStoreExportRows(tx, session.schoolId, session.userId),
    ]);
    return { school, rows };
  });
  if (!data.school) return null;
  const completed = data.rows.filter((row) => row.status === "completed");
  const total = completed.reduce((sum, row) => sum + Number(row.total ?? 0), 0);

  return <main className="store-history-print-page">
    <div className="store-history-toolbar"><Link href="/school/store"><ArrowLeft size={15}/>Back to School Store</Link><OperationsPrintActions/></div>
    <article className="store-history-sheet">
      <header><div className="store-history-brand">{data.school.logoUrl ? <img src={data.school.logoUrl} alt=""/> : <span>{data.school.name.split(/\s+/).map((part)=>part[0]).slice(0,2).join("").toUpperCase()}</span>}<div><small>SUKUUNOVA SCHOOL STORE</small><h1>{data.school.name}</h1><p>Sales history · School code {data.school.uniqueCode}</p></div></div><div className="store-history-generated"><ReceiptText size={18}/><span><small>Generated</small><strong>{when.format(new Date())}</strong></span></div></header>
      <section className="store-history-summary"><div><small>Total records</small><strong>{data.rows.length}</strong></div><div><small>Completed</small><strong>{completed.length}</strong></div><div><small>Voided</small><strong>{data.rows.length-completed.length}</strong></div><div><small>Completed sales value</small><strong>{money.format(total)}</strong></div></section>
      <section className="store-history-table"><table><thead><tr><th>Date / receipt</th><th>Customer</th><th>Items</th><th>Payment</th><th>Total</th><th>Status</th></tr></thead><tbody>{data.rows.map((row) => <tr key={String(row.receiptNo)}><td><strong>{String(row.receiptNo)}</strong><small>{when.format(new Date(String(row.createdAt)))}</small></td><td><strong>{String(row.customerName)}</strong><small>{String(row.customerType)}{row.customerPhone ? ` · ${String(row.customerPhone)}` : ""}</small></td><td>{String(row.items || "—")}</td><td><strong>{String(row.paymentMethod)}</strong><small>{row.paymentReference ? String(row.paymentReference) : "No reference"}</small></td><td>{money.format(Number(row.total ?? 0))}</td><td>{String(row.status)}</td></tr>)}</tbody></table></section>
      <footer><span><ShieldCheck size={14}/>Tenant-scoped school record generated by SukuuNova.</span><small>Voided transactions remain in this report for audit continuity.</small></footer>
    </article>
  </main>;
}
