import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { requirePlatformSession } from "@/lib/auth";
import { requirePlatformPermission, getPlatformSchoolScope } from "@/lib/platform-permissions";
import { db, withTenant } from "@/lib/db";
import { routeError, ForbiddenError, AppError } from "@/lib/errors";
import { appendPlatformAudit } from "@/lib/audit";
import { z } from "zod";

const PAGE_SIZE=1000;
const teacherKeys=["teacher","class_teacher","subject_teacher","academic_coordinator","department_head"];
const schema=z.object({action:z.literal("send"),requestId:z.string().trim().min(8).max(120).optional(),schoolIds:z.array(z.string().min(1)).min(1).max(200),audience:z.enum(["individual","guardians","teachers","staff","all"]),userIds:z.array(z.string().min(1)).max(PAGE_SIZE).optional(),channel:z.enum(["in_app","sms","whatsapp"]),title:z.string().trim().min(2).max(160),body:z.string().trim().min(1).max(5000),mediaUrl:z.string().url().max(2000).optional()});
function requireProvider(channel:"sms"|"whatsapp"){if(channel==="sms"&&(!process.env.SMS_PROVIDER_URL||!process.env.SMS_PROVIDER_TOKEN))throw new Error("SMS is not configured on the SukuuNova platform.");if(channel==="whatsapp"&&(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!process.env.TWILIO_WHATSAPP_FROM))throw new Error("WhatsApp is not configured on the SukuuNova platform.");}
function metadata(title:string,session:{adminId:string;name:string}){return JSON.parse(JSON.stringify({title,senderType:"platform_admin",senderId:session.adminId,senderName:session.name,attachments:[]}));}
async function audienceWhere(schoolId:string,audience:z.infer<typeof schema>["audience"]){switch(audience){case"guardians":return{schoolId,status:"active",guardianProfiles:{some:{schoolId}}};case"teachers":return{schoolId,status:"active",userRoles:{some:{role:{key:{in:teacherKeys}}}}};case"staff":return{schoolId,status:"active",guardianProfiles:{none:{schoolId}}};case"all":return{schoolId,status:"active"};default:return{schoolId,status:"active"};}}
async function listRecipients(tx:any,schoolId:string,audience:z.infer<typeof schema>["audience"],userIds?:string[]){if(audience==="individual")return tx.user.findMany({where:{schoolId,status:"active",id:{in:userIds||[]}},select:{id:true,name:true,phone:true}});const where=await audienceWhere(schoolId,audience);return tx.user.findMany({where,select:{id:true,name:true,phone:true},orderBy:{id:"asc"},take:PAGE_SIZE});}

export async function GET(request:Request){try{const session=await requirePlatformSession();await requirePlatformPermission(session,"support.manage");const scope=await getPlatformSchoolScope(session);const url=new URL(request.url);const requested=url.searchParams.get("schoolIds")?.split(",").map(v=>v.trim()).filter(Boolean)||[];if(session.role!=="super_admin"&&requested.some(id=>!scope?.includes(id)))throw new ForbiddenError("One or more selected schools are outside your platform assignment.");const schools=session.role==="super_admin"?await db.school.findMany({where:{status:"active"},select:{id:true,name:true,uniqueCode:true},orderBy:{name:"asc"},take:200}):await db.school.findMany({where:{id:{in:scope||[]},status:"active"},select:{id:true,name:true,uniqueCode:true},orderBy:{name:"asc"}});const selected=requested.length?schools.filter(s=>requested.includes(s.id)):schools;const recipients=[] as Array<{id:string;name:string;schoolId:string;schoolName:string;phone:string|null;email:string|null;roles:string[];isGuardian:boolean}>;for(const school of selected){const people=await withTenant(school.id,tx=>tx.user.findMany({where:{schoolId:school.id,status:"active"},orderBy:{name:"asc"},take:PAGE_SIZE,select:{id:true,name:true,phone:true,email:true,guardianProfiles:{select:{id:true}},userRoles:{select:{role:{select:{name:true,key:true}}}}}}));for(const person of people)recipients.push({id:person.id,name:person.name,schoolId:school.id,schoolName:school.name,phone:person.phone,email:person.email,roles:person.userRoles.map(r=>r.role.key||r.role.name),isGuardian:person.guardianProfiles.length>0});}return NextResponse.json({schools:selected,recipients});}catch(error){return routeError(error);}}

export async function POST(request:Request){try{const session=await requirePlatformSession();await requirePlatformPermission(session,"support.manage");const input=schema.parse(await request.json());const scope=await getPlatformSchoolScope(session);if(session.role!=="super_admin"&&input.schoolIds.some(id=>!scope?.includes(id)))throw new ForbiddenError("One or more selected schools are outside your platform assignment.");if(input.channel!=="in_app")requireProvider(input.channel);if(input.audience==="individual"&&!input.userIds?.length)return NextResponse.json({error:"INVALID_INPUT",message:"Choose at least one recipient."},{status:400});const requestId=input.requestId||randomUUID();
    // Preflight every school before creating any messages. This prevents one
    // school succeeding and a later school failing because its audience is too large.
    for(const schoolId of input.schoolIds){await withTenant(schoolId,async tx=>{const count=input.audience==="individual"?await tx.user.count({where:{schoolId,status:"active",id:{in:input.userIds||[]}}}):await tx.user.count({where:await audienceWhere(schoolId,input.audience)});if(count>PAGE_SIZE)throw new AppError(`The selected audience in ${schoolId} contains ${count} active recipients. Narrow the audience to ${PAGE_SIZE} or fewer for one platform send.`,413,"AUDIENCE_TOO_LARGE");});}
    let delivered=0,queued=0,matched=0,duplicates=0;
    for(const schoolId of input.schoolIds){const result=await withTenant(schoolId,async tx=>{const recipients=await listRecipients(tx,schoolId,input.audience,input.userIds);matched+=recipients.length;const keys=recipients.map(r=>`platform:${requestId}:${schoolId}:${r.id}:${input.channel}`);const existing=await tx.message.findMany({where:{schoolId,idempotencyKey:{in:keys}},select:{idempotencyKey:true}});const existingKeys=new Set(existing.map(m=>m.idempotencyKey));let localDelivered=0,localQueued=0,localDuplicates=0;for(let i=0;i<recipients.length;i++){const recipient=recipients[i];const idempotencyKey=keys[i];if(existingKeys.has(idempotencyKey)){localDuplicates++;continue;}const common={schoolId,channel:input.channel,recipientType:"user",recipientId:recipient.id,recipientPhone:recipient.phone||"",body:`${input.title}\n\n${input.body}`,templateKey:input.channel==="whatsapp"?"school_announcement":null,templateVariables:metadata(input.title,session),mediaUrl:input.mediaUrl||null,idempotencyKey};await tx.message.create({data:{...common,status:input.channel==="in_app"?"delivered":"queued",attempts:input.channel==="in_app"?1:0,sentAt:input.channel==="in_app"?new Date():null,nextAttemptAt:new Date()}});if(input.channel==="in_app")localDelivered++;else localQueued++;}return{localDelivered,localQueued,localDuplicates};});delivered+=result.localDelivered;queued+=result.localQueued;duplicates+=result.localDuplicates;await appendPlatformAudit({actorId:session.adminId,action:"platform.message.sent",targetSchoolId:schoolId,targetEntity:"MessageBatch",meta:{requestId,audience:input.audience,channel:input.channel,matched:matched,delivered:result.localDelivered,queued:result.localQueued,duplicates:result.localDuplicates}});}
    return NextResponse.json({ok:true,requestId,matched,delivered,queued,duplicates,message:input.channel==="in_app"?`Delivered ${delivered} platform message${delivered===1?"":"s"}.`: `Queued ${queued} ${input.channel.toUpperCase()} ${queued===1?"delivery":"deliveries"}.`});
  }catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"INVALID_INPUT",message:"Check the schools, audience, channel and message."},{status:400});if(error instanceof ForbiddenError)return NextResponse.json({error:error.code,message:error.message},{status:error.status});if(error instanceof AppError)return NextResponse.json({error:error.code,message:error.message},{status:error.status});if(error instanceof Error&&/not configured/i.test(error.message))return NextResponse.json({error:"NOTIFICATION_PROVIDER_UNAVAILABLE",message:error.message},{status:503});return routeError(error);}}
