"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Period={period:number;start:string;end:string};
type Day={dayOfWeek:number;name:string;enabled:boolean;start:string;end:string;periods?:Period[]};
type Break={name:string;start:string;end:string};
type Assessment={name:string;weight:number};
type Data={timetable:{days:Day[];periodMinutes:number;breaks:Break[];periodsPerDay:number;periods?:Period[];published:boolean};assessment:{categories:Assessment[];rounding:"nearest"|"down"|"up";missingScorePolicy:"blank"|"zero";allowTeacherOverride:boolean};reportCard:Record<string,boolean|string>;classes?:Array<{id:string;name:string;level:string|null}>};

const dayNames=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,Number.isFinite(n)?n:min));
function mins(v:string){const [h,m]=v.split(":").map(Number);return (h||0)*60+(m||0);}
function clock(v:number){const safe=((Math.round(v)%1440)+1440)%1440;return `${String(Math.floor(safe/60)).padStart(2,"0")}:${String(safe%60).padStart(2,"0")}`;}
function buildPeriods(day:Day,minutes:number,breaks:Break[],count:number){const start=mins(day.start),end=mins(day.end),out:Period[]=[];let cursor=start;for(let p=1;p<=count&&cursor+minutes<=end;p++){const next=cursor+minutes;const crossing=breaks.map(b=>({s:mins(b.start),e:mins(b.end)})).find(b=>cursor<b.e&&next>b.s);if(crossing){cursor=crossing.e;p--;continue;}out.push({period:p,start:clock(cursor),end:clock(next)});cursor=next;}return out;}
function formatDuration(total:number){const h=Math.floor(total/60);const m=total%60;return `${h?`${h} hr${h===1?"":"s"} `:""}${m?`${m} min${m===1?"":"s"}`:h?"": "0 min"}`.trim();}

export function AcademicSetupConsole(){
 const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [activeSection,setActiveSection]=useState("schedule");
 const [genScope,setGenScope]=useState<string[]|null>(null);const [replaceExisting,setReplaceExisting]=useState(true);
 useEffect(()=>{fetch("/api/school/academic-engine").then(r=>r.json()).then((d:Data)=>{const next={...d,timetable:{...d.timetable,days:d.timetable.days.map(day=>({...day,periods:day.periods?.length?day.periods:buildPeriods(day,d.timetable.periodMinutes,d.timetable.breaks,d.timetable.periodsPerDay)}))}};setData(next);}).catch(()=>setMessage("We could not load academic setup."));},[]);
 const totalWeight=useMemo(()=>data?.assessment.categories.reduce((n,c)=>n+Number(c.weight),0)??0,[data]);
 const durationHours=data?Math.floor(data.timetable.periodMinutes/60):0;const durationMinutes=data?data.timetable.periodMinutes%60:0;
 if(!data)return <div className="academic-setup-loading">Loading your academic control centre…</div>;
 const updateDay=(dayOfWeek:number,patch:Partial<Day>)=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(d=>d.dayOfWeek===dayOfWeek?{...d,...patch}:d)}});
 const updatePeriod=(dayOfWeek:number,index:number,patch:Partial<Period>)=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(d=>d.dayOfWeek===dayOfWeek?{...d,periods:(d.periods??[]).map((p,i)=>i===index?{...p,...patch}:p)}:d)}});
 const rebuildAll=()=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(d=>({...d,periods:buildPeriods(d,data.timetable.periodMinutes,data.timetable.breaks,data.timetable.periodsPerDay)}))}});
 const setDefaultDuration=(hours:number,minutes:number)=>{const total=clamp(hours*60+minutes,20,480);setData({...data,timetable:{...data.timetable,periodMinutes:total}});};
 const addPeriod=(dayOfWeek:number)=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(d=>{if(d.dayOfWeek!==dayOfWeek)return d;const periods=d.periods??[];const last=periods[periods.length-1];const start=last?mins(last.end):mins(d.start),end=start+data.timetable.periodMinutes;return {...d,periods:[...periods,{period:periods.length+1,start:clock(start),end:clock(end)}]};})}});
 const removePeriod=(dayOfWeek:number,index:number)=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(d=>d.dayOfWeek===dayOfWeek?{...d,periods:(d.periods??[]).filter((_,i)=>i!==index).map((p,i)=>({...p,period:i+1}))}:d)}});
 const updateBreak=(index:number,patch:Partial<Break>)=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.map((b,i)=>i===index?{...b,...patch}:b)}});
 const addBreak=()=>setData({...data,timetable:{...data.timetable,breaks:[...data.timetable.breaks,{name:"Break",start:"10:00",end:"10:20"}]}});
 const save=async()=>{setBusy(true);setMessage("");try{if(Math.abs(totalWeight-100)>0.01)throw new Error("Assessment weights must total 100%.");const r=await fetch("/api/school/academic-engine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",...data})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save setup.");setData({...d,timetable:{...d.timetable,days:d.timetable.days.map((day:Day)=>({...day,periods:day.periods??[]}))}});setMessage("Academic rules, lesson times and reporting settings saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save setup.");}finally{setBusy(false)}};
  const generate=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/school/academic-engine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generate",replaceExisting,classIds:genScope??undefined})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"Could not generate timetable.");setMessage(`Timetable created: ${d.scheduled} lessons across ${d.classes} classes and ${d.teachers} teachers${d.pairedBlocks?` (${d.pairedBlocks} double blocks)`:d.roomsUsed?` (${d.roomsUsed} rooms used)`:""}.`);}catch(e){setMessage(e instanceof Error?e.message:"Could not generate timetable.");}finally{setBusy(false)}};
 const enabledDays=data.timetable.days.filter(d=>d.enabled);const totalBlocks=enabledDays.reduce((n,d)=>n+(d.periods??[]).length,0);
 const nav=[{id:"schedule",label:"School day & times",meta:`${enabledDays.length} days · ${totalBlocks} blocks`},{id:"assessment",label:"Assessment rules",meta:`${totalWeight}% weighted`},{id:"reports",label:"Report cards",meta:"Publication rules"},{id:"actions",label:"Save & generate",meta:"Apply changes"}];
 return <div className="academic-setup-shell">
   <header className="academic-setup-hero"><div><span className="academic-kicker">ACADEMIC CONTROL CENTRE</span><h2>Configure how your school actually runs.</h2><p>Set the academic calendar, teaching days, bell schedule, lesson lengths, breaks, grading rules and report-card behaviour once. The timetable and academic workflows use these rules everywhere.</p></div><div className="academic-hero-actions"><Link href="/school/terms" className="academic-btn academic-btn-ghost">Terms & calendar →</Link><button className="academic-btn academic-btn-primary" onClick={()=>void save()} disabled={busy||Math.abs(totalWeight-100)>0.01}>{busy?"Saving…":"Save setup"}</button></div></header>
   <div className="academic-health"><div><span className="health-dot good"/><div><b>{enabledDays.length} teaching days</b><small>Your active weekly pattern</small></div></div><div><span className="health-dot"/><div><b>{formatDuration(data.timetable.periodMinutes)} default</b><small>Standard lesson duration</small></div></div><div><span className={`health-dot ${Math.abs(totalWeight-100)<0.01?"good":"bad"}`}/><div><b>{totalWeight}% assessment weights</b><small>{Math.abs(totalWeight-100)<0.01?"Ready to save":"Must equal 100%"}</small></div></div><div><span className="health-dot"/><div><b>{data.timetable.breaks.length} breaks</b><small>Across the school day</small></div></div></div>
   <nav className="academic-section-nav">{nav.map(item=><button key={item.id} className={activeSection===item.id?"active":""} onClick={()=>setActiveSection(item.id)}><span>{item.label}</span><small>{item.meta}</small></button>)}</nav>
   {activeSection==="schedule"&&<section className="academic-section-grid">
     <div className="academic-card academic-card-wide"><div className="academic-card-heading"><div><span className="academic-kicker">01 · SCHOOL DAY</span><h3>Teaching days and operating hours</h3><p>Choose exactly which days are used for instruction and the daily window available for lessons. Times use the school’s local clock.</p></div><button className="academic-btn academic-btn-soft" onClick={rebuildAll}>Rebuild from defaults</button></div>
       <div className="day-grid">{data.timetable.days.map((d,i)=><div className={`day-config ${d.enabled?"enabled":"disabled"}`} key={d.dayOfWeek}><label className="day-toggle"><input type="checkbox" checked={d.enabled} onChange={e=>updateDay(d.dayOfWeek,{enabled:e.target.checked})}/><span className="day-name">{dayNames[i]}</span><span className="day-status">{d.enabled?"Teaching":"Off"}</span></label>{d.enabled&&<div className="day-times"><label>School starts<input type="time" value={d.start} onChange={e=>updateDay(d.dayOfWeek,{start:e.target.value})}/></label><label>School ends<input type="time" value={d.end} onChange={e=>updateDay(d.dayOfWeek,{end:e.target.value})}/></label></div>}</div>)}</div>
     </div>
     <div className="academic-card"><div className="academic-card-heading"><div><span className="academic-kicker">02 · LESSON DURATION</span><h3>Default lesson length</h3><p>Periods are not limited to one hour. Choose the hours and minutes the school normally uses; individual blocks can still be edited below.</p></div></div>
       <div className="duration-picker"><label>Hours<select value={durationHours} onChange={e=>setDefaultDuration(Number(e.target.value),durationMinutes)}>{Array.from({length:9},(_,i)=><option key={i} value={i}>{i} hour{i===1?"":"s"}</option>)}</select></label><span>+</span><label>Minutes<select value={durationMinutes} onChange={e=>setDefaultDuration(durationHours,Number(e.target.value))}>{Array.from({length:60},(_,i)=><option key={i} value={i}>{i} min</option>)}</select></label></div>
       <div className="duration-preview"><strong>{formatDuration(data.timetable.periodMinutes)}</strong><span>Used when SukuuNova automatically builds new lesson blocks.</span></div>
       <label className="full-control">Maximum lesson blocks per day<input type="number" min="1" max="16" value={data.timetable.periodsPerDay} onChange={e=>setData({...data,timetable:{...data.timetable,periodsPerDay:clamp(Number(e.target.value),1,16)}})}/></label>
     </div>
     <div className="academic-card"><div className="academic-card-heading"><div><span className="academic-kicker">03 · BREAKS</span><h3>Breaks, lunch and non-teaching time</h3><p>These ranges are excluded when the timetable generator places lessons.</p></div><button className="academic-btn academic-btn-soft" onClick={addBreak}>+ Add break</button></div>
       <div className="break-list">{data.timetable.breaks.map((b,i)=><div className="break-config" key={i}><input aria-label="Break name" value={b.name} onChange={e=>updateBreak(i,{name:e.target.value})}/><input aria-label="Break start" type="time" value={b.start} onChange={e=>updateBreak(i,{start:e.target.value})}/><span>to</span><input aria-label="Break end" type="time" value={b.end} onChange={e=>updateBreak(i,{end:e.target.value})}/><button className="icon-delete" onClick={()=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.filter((_,j)=>j!==i)}})} aria-label={`Remove ${b.name}`}>×</button></div>)}</div>
     </div>
     <div className="academic-card academic-card-wide"><div className="academic-card-heading"><div><span className="academic-kicker">04 · EXACT BELL SCHEDULE</span><h3>Build the real time blocks used by each day</h3><p>This is the source of truth for timetable display and printing. For example, a block can be <b>12:30 PM → 2:00 PM</b> without being forced into a 60-minute period.</p></div></div>
       <div className="period-day-list">{data.timetable.days.filter(d=>d.enabled).map(d=><div className="period-day" key={d.dayOfWeek}><div className="period-day-head"><div><b>{dayNames[d.dayOfWeek-1]}</b><span>{(d.periods??[]).length} lesson blocks</span></div><button className="academic-btn academic-btn-soft" onClick={()=>addPeriod(d.dayOfWeek)}>+ Add block</button></div><div className="period-table"><div className="period-table-head"><span>Block</span><span>Starts</span><span>Ends</span><span>Duration</span><span/></div>{(d.periods??[]).map((p,j)=><div className="period-table-row" key={j}><strong>P{p.period}</strong><input type="time" value={p.start} onChange={e=>updatePeriod(d.dayOfWeek,j,{start:e.target.value})}/><input type="time" value={p.end} onChange={e=>updatePeriod(d.dayOfWeek,j,{end:e.target.value})}/><span className="duration-chip">{formatDuration(Math.max(0,mins(p.end)-mins(p.start)))}</span><button className="icon-delete" onClick={()=>removePeriod(d.dayOfWeek,j)} aria-label={`Remove period ${p.period}`}>×</button></div>)}</div></div>)}</div>
     </div>
   </section>}
   {activeSection==="assessment"&&<section className="academic-section-grid">
     <div className="academic-card academic-card-wide"><div className="academic-card-heading"><div><span className="academic-kicker">05 · ASSESSMENT ENGINE</span><h3>How a term result is calculated</h3><p>Define the school-wide assessment categories and their contribution to the final result. These rules keep grading consistent across classes.</p></div><span className={`weight-total ${Math.abs(totalWeight-100)<0.01?"good":"bad"}`}>{totalWeight}%</span></div>
       <div className="assessment-list">{data.assessment.categories.map((c,i)=><div className="assessment-row" key={i}><div className="assessment-number">{String(i+1).padStart(2,"0")}</div><input value={c.name} onChange={e=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.map((x,j)=>j===i?{...x,name:e.target.value}:x)}})} /><div className="weight-control"><input type="number" min="0" max="100" value={c.weight} onChange={e=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.map((x,j)=>j===i?{...x,weight:clamp(Number(e.target.value),0,100)}:x)}})}/><span>%</span></div><button className="icon-delete" onClick={()=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.filter((_,j)=>j!==i)}})} aria-label={`Remove ${c.name}`}>×</button></div>)}</div>
       <button className="academic-btn academic-btn-soft add-wide" onClick={()=>setData({...data,assessment:{...data.assessment,categories:[...data.assessment.categories,{name:"New category",weight:0}]}})}>+ Add assessment category</button>
       <div className="assessment-progress"><div><span>Assessment distribution</span><b>{totalWeight}% / 100%</b></div><div className="progress-track"><i style={{width:`${Math.min(100,totalWeight)}%`}}/></div></div>
     </div>
     <div className="academic-card"><div className="academic-card-heading"><div><span className="academic-kicker">06 · SCORE BEHAVIOUR</span><h3>Consistent score handling</h3><p>Decide how SukuuNova rounds results and handles assessments that have no score.</p></div></div>
       <label className="full-control">Rounding<select value={data.assessment.rounding} onChange={e=>setData({...data,assessment:{...data.assessment,rounding:e.target.value as Data["assessment"]["rounding"]}})}><option value="nearest">Nearest whole number</option><option value="down">Always round down</option><option value="up">Always round up</option></select></label>
       <label className="full-control">Missing score policy<select value={data.assessment.missingScorePolicy} onChange={e=>setData({...data,assessment:{...data.assessment,missingScorePolicy:e.target.value as Data["assessment"]["missingScorePolicy"]}})}><option value="blank">Leave blank</option><option value="zero">Treat as zero</option></select></label>
       <label className="switch-row"><input type="checkbox" checked={data.assessment.allowTeacherOverride} onChange={e=>setData({...data,assessment:{...data.assessment,allowTeacherOverride:e.target.checked}})}/><span><b>Allow teacher override</b><small>Permit authorised teachers to override centrally configured weighting where allowed.</small></span></label>
     </div>
   </section>}
   {activeSection==="reports"&&<section className="academic-section-grid">
     <div className="academic-card academic-card-wide"><div className="academic-card-heading"><div><span className="academic-kicker">07 · REPORT CARD CONTENT</span><h3>Decide what a completed term report contains</h3><p>These controls shape the generated report card. Term dates remain managed in Terms & Academic Calendar.</p></div><Link href="/school/terms" className="academic-btn academic-btn-soft">Manage terms →</Link></div>
       <div className="report-option-grid">{[["includePosition","Class position","Show each learner’s position in the class."],["includeSubjectPosition","Subject position","Show subject-level ranking where configured."],["includeAttendance","Attendance","Include attendance totals and attendance rate."],["includeTeacherRemark","Class teacher remark","Include the class teacher’s final remark."],["includeHeadRemark","Head’s remark","Include the school head’s final remark."],["includeSignatures","Signatures","Reserve signature areas for approval."],["includeSchoolContacts","School contacts","Print the school’s contact details."],["showGrades","Grade labels","Show grade letters alongside scores."],["showClassAverage","Class averages","Show class averages on relevant report sections."]].map(([key,label,desc])=><label className="report-option" key={key}><input type="checkbox" checked={Boolean(data.reportCard[key])} onChange={e=>setData({...data,reportCard:{...data.reportCard,[key]:e.target.checked}})}/><span><b>{label}</b><small>{desc}</small></span></label>)}</div>
     </div>
     <div className="academic-card"><div className="academic-card-heading"><div><span className="academic-kicker">08 · RANKING</span><h3>Class ranking method</h3><p>Choose how the final ordering is calculated.</p></div></div><label className="full-control">Ranking method<select value={String(data.reportCard.rankMethod??"total_average")} onChange={e=>setData({...data,reportCard:{...data.reportCard,rankMethod:e.target.value}})}><option value="total_average">Total average</option><option value="weighted_total">Weighted total</option></select></label><div className="setup-note"><b>Term-aware by design</b><span>Terms are real date windows. When a term ends, its results, attendance and reports remain available for historical summaries instead of being replaced.</span></div></div>
   </section>}
    {activeSection==="actions"&&<section className="academic-actions-section"><div className="academic-card action-card"><div><span className="academic-kicker">09 · APPLY</span><h3>Save the academic structure, then generate the timetable.</h3><p>Save first so the school’s exact lesson ranges become the permanent source of truth. Generate only after subjects and teachers are assigned to classes. Scoped runs respect slots outside their scope — hand-edited lessons elsewhere are never moved.</p></div><div className="gen-scope"><strong>Generate scope</strong><label><input type="checkbox" checked={genScope===null} onChange={()=>setGenScope(null)}/> Whole school</label><div className="gen-classes">{(data.classes??[]).map(c=><label key={c.id}><input type="checkbox" checked={genScope!==null&&genScope.includes(c.id)} onChange={e=>{const cur=genScope??(data.classes??[]).map(x=>x.id);setGenScope(e.target.checked?[...cur,c.id]:cur.filter(x=>x!==c.id));}}/>{c.level?`${c.level} · `:""}{c.name}</label>)}</div><label><input type="checkbox" checked={replaceExisting} onChange={e=>setReplaceExisting(e.target.checked)}/> Replace existing slots in scope (off = add only where empty)</label></div><div className="action-buttons"><button className="academic-btn academic-btn-primary" disabled={busy||Math.abs(totalWeight-100)>0.01} onClick={()=>void save()}>{busy?"Saving…":"Save academic setup"}</button><button className="academic-btn academic-btn-dark" disabled={busy} onClick={()=>void generate()}><strong>Generate timetable</strong><small>Build from current class · subject · teacher assignments</small></button></div>{message&&<div className={`academic-message ${message.toLowerCase().includes("error")||message.toLowerCase().includes("must")||message.toLowerCase().includes("could not")?"error":"success"}`}>{message}</div>}</div><div className="academic-card quick-links"><div><span className="academic-kicker">QUICK LINKS</span><h3>Continue the academic workflow</h3></div><Link href="/school/timetable">Open timetable <span>→</span></Link><Link href="/school/timetable/print">Print all class timetables <span>→</span></Link><Link href="/school/gradebook">Enter term results <span>→</span></Link><Link href="/school/terms">Review term summaries <span>→</span></Link><Link href="/school/settings">School-wide settings <span>→</span></Link></div></section>}
   {message&&activeSection!=="actions"&&<div className="academic-message success">{message}</div>}
 </div>;
}