"use client";
import { useEffect, useMemo, useState } from "react";

type Day={dayOfWeek:number;name:string;enabled:boolean;start:string;end:string};
type Break={name:string;start:string;end:string};
type Assessment={name:string;weight:number};
type Data={timetable:{days:Day[];periodMinutes:number;breaks:Break[];periodsPerDay:number;published:boolean};assessment:{categories:Assessment[];rounding:"nearest"|"down"|"up";missingScorePolicy:"blank"|"zero";allowTeacherOverride:boolean};reportCard:Record<string,boolean|string>};
const dayNames=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export function AcademicSetupConsole(){const [data,setData]=useState<Data|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
useEffect(()=>{fetch("/api/school/academic-engine").then(r=>r.json()).then(setData).catch(()=>setMessage("We could not load academic setup."));},[]);
const totalWeight=useMemo(()=>data?.assessment.categories.reduce((n,c)=>n+Number(c.weight),0)??0,[data]);
if(!data)return <div className="app-card app-panel"><p>Loading your academic setup…</p></div>;
const save=async()=>{setBusy(true);setMessage("");try{if(Math.abs(totalWeight-100)>0.01)throw new Error("Assessment weights must total 100%.");const r=await fetch("/api/school/academic-engine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",...data})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save setup.");setData(d);setMessage("Academic rules saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save setup.");}finally{setBusy(false)}};
const generate=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/school/academic-engine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generate",replaceExisting:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not generate timetable.");setMessage(`Timetable created: ${d.scheduled} periods across ${d.classes} classes and ${d.teachers} teachers.`);}catch(e){setMessage(e instanceof Error?e.message:"Could not generate timetable.");}finally{setBusy(false)}};
return <div className="app-dashboard-grid"><section className="app-card app-panel"><div className="app-card-head"><div><span className="module-overline">1 · School day</span><h2>Tell SukuuNova how the day runs.</h2><p>Choose the days, opening/closing time, teaching period length and named breaks. The generator works around these rules.</p></div><span className="app-pill">{data.timetable.periodMinutes} min periods</span></div><div className="app-list">{data.timetable.days.map((d,i)=><div className="app-list-row" key={d.dayOfWeek}><input type="checkbox" checked={d.enabled} onChange={e=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(x=>x.dayOfWeek===d.dayOfWeek?{...x,enabled:e.target.checked}:x)}})}/><div style={{flex:1}}><b>{dayNames[i]}</b><span><input value={d.start} onChange={e=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(x=>x.dayOfWeek===d.dayOfWeek?{...x,start:e.target.value}:x)}})} style={{width:80}}/> to <input value={d.end} onChange={e=>setData({...data,timetable:{...data.timetable,days:data.timetable.days.map(x=>x.dayOfWeek===d.dayOfWeek?{...x,end:e.target.value}:x)}})} style={{width:80}}/></span></div></div>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14}}><label>Period length<select value={data.timetable.periodMinutes} onChange={e=>setData({...data,timetable:{...data.timetable,periodMinutes:Number(e.target.value)}})}><option value={30}>30 min</option><option value={35}>35 min</option><option value={40}>40 min</option><option value={45}>45 min</option><option value={50}>50 min</option><option value={60}>60 min</option></select></label><label>Maximum periods/day<input type="number" min={1} max={16} value={data.timetable.periodsPerDay} onChange={e=>setData({...data,timetable:{...data.timetable,periodsPerDay:Number(e.target.value)}})}/></label></div><div style={{marginTop:14}}><b>Breaks & lunch</b>{data.timetable.breaks.map((b,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1.4fr .8fr .8fr auto",gap:8,marginTop:8}}><input value={b.name} onChange={e=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.map((x,j)=>j===i?{...x,name:e.target.value}:x)}})}/><input value={b.start} onChange={e=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.map((x,j)=>j===i?{...x,start:e.target.value}:x)}})}/><input value={b.end} onChange={e=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.map((x,j)=>j===i?{...x,end:e.target.value}:x)}})}/><button className="app-pill" onClick={()=>setData({...data,timetable:{...data.timetable,breaks:data.timetable.breaks.filter((_,j)=>j!==i)}})}>Remove</button></div>)}<button className="app-pill" style={{marginTop:9}} onClick={()=>setData({...data,timetable:{...data.timetable,breaks:[...data.timetable.breaks,{name:"Break",start:"10:00",end:"10:20"}]}})}>+ Add break</button></div></section>
<section className="app-card app-panel"><div className="app-card-head"><div><span className="module-overline">2 · Assessment rules</span><h2>Let the school decide what counts.</h2><p>Homework, exercises, classwork, quizzes, projects and exams can each carry their own share of the final result.</p></div><span className={`app-pill ${Math.abs(totalWeight-100)<0.01?"":"attention"}`}>{totalWeight}% total</span></div><div className="app-list">{data.assessment.categories.map((c,i)=><div className="app-list-row" key={i}><div style={{flex:1}}><input value={c.name} onChange={e=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.map((x,j)=>j===i?{...x,name:e.target.value}:x)}})}/></div><input type="number" min={0} max={100} value={c.weight} onChange={e=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.map((x,j)=>j===i?{...x,weight:Number(e.target.value)}:x)}})} style={{width:85}}/><button className="app-pill" onClick={()=>setData({...data,assessment:{...data.assessment,categories:data.assessment.categories.filter((_,j)=>j!==i)}})}>Remove</button></div>)}</div><button className="app-pill" style={{marginTop:10}} onClick={()=>setData({...data,assessment:{...data.assessment,categories:[...data.assessment.categories,{name:"New category",weight:0}]}})}>+ Add assessment category</button><div className="app-banner" style={{marginTop:14}}><div><h3>Teacher control</h3><p>{data.assessment.allowTeacherOverride?"Teachers can override category rules where permitted.":"The school controls the weighting centrally, so marks stay consistent across teachers."}</p></div><button className="app-pill" onClick={()=>setData({...data,assessment:{...data.assessment,allowTeacherOverride:!data.assessment.allowTeacherOverride}})}>{data.assessment.allowTeacherOverride?"Allow less control":"Allow teacher override"}</button></div></section>
<section className="app-card app-panel"><div className="app-card-head"><div><span className="module-overline">3 · Report cards</span><h2>Build the school's final report automatically.</h2><p>Use your school identity and academic data to produce consistent, printable reports. Rankings and subject positions are calculated from the school's chosen rules.</p></div></div><div className="app-list">{[["includePosition","Class position"],["includeSubjectPosition","Subject position"],["includeAttendance","Attendance"],["includeTeacherRemark","Class teacher remarks"],["includeHeadRemark","Head's remark"],["includeSignatures","Signatures"],["includeSchoolContacts","School contacts"],["showGrades","Grade labels"],["showClassAverage","Class averages"]].map(([key,label])=><label className="app-list-row" key={key}><input type="checkbox" checked={Boolean(data.reportCard[key])} onChange={e=>setData({...data,reportCard:{...data.reportCard,[key]:e.target.checked}})}/><div><b>{label}</b><span>Include this on generated reports</span></div></label>)}</div></section>
<section className="app-card app-panel"><div className="app-card-head"><div><span className="module-overline">4 · One-click automation</span><h2>Save once. Generate the timetable.</h2><p>SukuuNova uses each class's subject-teacher assignments, weekly subject frequency, available school hours and breaks, then builds a clash-free draft. Review it on the Timetable page before publishing.</p></div></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="app-primary-action" disabled={busy||Math.abs(totalWeight-100)>0.01} onClick={()=>void save()}>{busy?"Saving…":"Save academic setup →"}</button><button className="app-action" disabled={busy} onClick={()=>void generate()}><strong>Generate timetable</strong>Build from current subject + teacher assignments</button></div>{message&&<div className="app-banner" style={{marginTop:12}}><div><h3>{message}</h3></div></div>}</section></div>}
