"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BatteryCharging, Bolt, Cable, CircuitBoard, Gauge, Lightbulb, LogOut, ScanLine, ShieldCheck, Sparkles, TriangleAlert, Zap } from "lucide-react";
import { circuitForgeChargeGain, circuitForgeComboGain, circuitForgeFaultDamage, circuitForgeFuseRecovery, circuitForgeScanRecovery, circuitForgeStabilityGain, circuitForgeWindowMs } from "@/lib/circuit-forge";
import type { CircuitForgeScene } from "@/lib/circuit-forge-content";
import "./circuit-forge.css";

type Question={id:string;prompt:string;options:string[];scene?:unknown};
type Plan={masteryPercent:number|null;supportMode:"guided"|"supported"|"independent"|"challenge";missionMode:"onboarding"|"recovery"|"reinforcement"|"balanced"|"stretch";speedScale:number;hazardDensity:number;hintStrength:0|1|2;bossGate:boolean;worldKey:"aurora-causeway"|"meteor-foundry"|"prism-canyon"|"nova-citadel"};
type Round={id:string;difficulty:number;answers:string[];questions:Question[];learningPlan?:Plan|null};
type Props={learnerName:string;round:Round;onComplete:(answers:string[])=>void;onExit:(answers:string[])=>void};
const firstOpen=(answers:string[],length:number)=>{const index=answers.findIndex((answer)=>!answer.trim());return index<0?length:index;};

export default function CircuitForge({learnerName,round,onComplete,onExit}:Props){
 const answersRef=useRef([...round.answers]),completeRef=useRef(onComplete),exitRef=useRef(onExit),commitRef=useRef<()=>void>(()=>undefined),scanRef=useRef<()=>void>(()=>undefined),completedRef=useRef(false),startedRef=useRef(Date.now());
 const [checkpoint,setCheckpoint]=useState(firstOpen(round.answers,round.questions.length)),[selected,setSelected]=useState(0),[pressure,setPressure]=useState(0),[stability,setStability]=useState(82),[charge,setCharge]=useState(8),[combo,setCombo]=useState(0),[scans,setScans]=useState(2),[scanOpen,setScanOpen]=useState(false),[switching,setSwitching]=useState(false),[message,setMessage]=useState("Microgrid control online. Restore each circuit without exposing the school grid to unsafe faults.");
 completeRef.current=onComplete;exitRef.current=onExit;
 const question=round.questions[checkpoint],scene=(question?.scene??{}) as Partial<CircuitForgeScene>,plan=round.learningPlan,boss=Boolean(plan?.bossGate&&checkpoint===round.questions.length-1),faultLevel=Math.max(1,Math.min(5,Number(scene.faultLevel??round.difficulty))),clues=Array.isArray(scene.circuitTags)?scene.circuitTags.slice(0,3):[];
 const duration=useMemo(()=>circuitForgeWindowMs(round.difficulty,plan?.speedScale??1,plan?.supportMode??"independent"),[round.difficulty,plan?.speedScale,plan?.supportMode]);
 const progress=Math.round((Math.min(checkpoint,round.questions.length)/Math.max(1,round.questions.length))*100),energized=question?selected%2===0:false;
 useEffect(()=>{startedRef.current=Date.now();setPressure(0);setSelected(0);setScanOpen(false);if(question)setMessage(boss?"FINAL GRID EVENT: stabilise the distribution bus before protection trips.":`${scene.bay??`GRID-${checkpoint+1}`} active · ${scene.sector??"school microgrid"}.`);},[boss,checkpoint,question,scene.bay,scene.sector]);
 useEffect(()=>{if(checkpoint>=round.questions.length){if(!completedRef.current){completedRef.current=true;window.setTimeout(()=>completeRef.current([...answersRef.current]),420);}return;}const timer=window.setInterval(()=>{const elapsed=Date.now()-startedRef.current;if(elapsed>=duration){const damage=circuitForgeFaultDamage(100,plan?.hazardDensity??.9,boss);setStability((value)=>Math.max(18,value-damage));setCombo(0);startedRef.current=Date.now()-Math.round(duration*.5);setPressure(50);setMessage(`Protection event: grid stability -${damage}. Trace the path and isolate the fault.`);}else setPressure(Math.min(100,(elapsed/duration)*100));},120);return()=>window.clearInterval(timer);},[boss,checkpoint,duration,plan?.hazardDensity,round.questions.length]);
 const scan=()=>{if(!question||scans<1||switching)return;setScans((value)=>Math.max(0,value-1));setPressure((current)=>{const next=circuitForgeScanRecovery(current,plan?.hintStrength??0);startedRef.current=Date.now()-Math.round(next/100*duration);return next;});setScanOpen(true);setMessage(`Grid scan: ${clues.length?clues.join(" · "):scene.cue??"Trace source, path, load and return."} Diagnostic clues never reveal the graded switching plan.`);};scanRef.current=scan;
 const commit=()=>{if(!question||switching||completedRef.current)return;const answer=question.options[selected];if(!answer)return;answersRef.current[checkpoint]=answer;const stabilityGain=circuitForgeStabilityGain(pressure,round.difficulty),chargeGain=circuitForgeChargeGain(faultLevel,pressure),comboGain=circuitForgeComboGain(pressure);setStability((value)=>Math.min(100,value+stabilityGain));setCharge((value)=>Math.min(999,value+chargeGain));setCombo((value)=>Math.min(99,value+comboGain));if(pressure<=40)setScans((value)=>Math.min(5,value+1));setSwitching(true);setMessage(`Switch plan sealed for authoritative review. +${chargeGain} grid charge · stability +${stabilityGain}${comboGain?` · chain +${comboGain}`:""}.`);window.setTimeout(()=>{setSwitching(false);setCheckpoint((value)=>value+1);},620);};commitRef.current=commit;
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.key>="1"&&event.key<="4"){const index=Number(event.key)-1;if(index<(question?.options.length??0))setSelected(index);}else if(event.key.toLowerCase()==="g")scanRef.current();else if(event.key.toLowerCase()==="f"){setStability((value)=>circuitForgeFuseRecovery(value));setMessage("Protection reset queued. Use this recovery only after reviewing the circuit evidence.");}else if(event.key==="Enter"){event.preventDefault();commitRef.current();}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);});
 return <section className="circuit-shell" aria-label={`Circuit Forge for ${learnerName}`}>
  <header className="circuit-bar"><div className="circuit-brand"><span><CircuitBoard size={22}/></span><div><strong>CIRCUIT FORGE</strong><small>school microgrid · electricity · fault engineering</small></div></div><button type="button" onClick={()=>exitRef.current([...answersRef.current])}><LogOut size={15}/>Save & exit</button></header>
  <div className="circuit-hud"><div><ShieldCheck size={16}/><strong>{stability}%</strong><span>grid stability</span></div><div><BatteryCharging size={16}/><strong>{charge}</strong><span>grid charge</span></div><div><Sparkles size={16}/><strong>x{Math.max(1,combo)}</strong><span>repair chain</span></div><div><ScanLine size={16}/><strong>{scans}</strong><span>grid scans</span></div></div>
  <div className="circuit-stage"><aside className="circuit-grid"><div className="circuit-sector"><small>{scene.bay??`GRID-${checkpoint+1}`}</small><strong>{scene.sector??"School microgrid"}</strong><span>{scene.device??"Learning load"}</span></div><div className={`circuit-diagram ${energized?"energized":""}`}><div className="circuit-source"><BatteryCharging size={30}/><b>{scene.supplyV??6} V</b></div><i className="wire w1"/><div className="circuit-switch"><Zap size={18}/><span>SW</span></div><i className="wire w2"/><div className="circuit-load"><Lightbulb size={34}/><b>{scene.loadLabel??"load"}</b></div><i className="wire w3"/><div className="circuit-return"><Cable size={24}/><span>return</span></div></div><div className="circuit-meters"><span><Gauge size={14}/>{scene.supplyV??6} V supply</span><span><Bolt size={14}/>{String(scene.mission??"path").toUpperCase()}</span><span><TriangleAlert size={14}/>fault {faultLevel}/5</span></div></aside>
  {question?<main className="circuit-console"><div className="circuit-heading"><div><span>{boss?"MASTER BUS · FINAL GRID EVENT":`${String(scene.mission??"path").toUpperCase()} · NODE ${checkpoint+1}/${round.questions.length}`}</span><strong>{scene.cue??"Trace source, path, load and return."}</strong></div><CircuitBoard size={27}/></div><h2>{question.prompt}</h2><div className="circuit-options">{question.options.slice(0,4).map((option,index)=><button type="button" key={option} className={selected===index?"selected":""} onClick={()=>setSelected(index)} disabled={switching}><b>{index+1}</b><span>{option}</span><i>{selected===index?"ROUTED":"standby"}</i></button>)}</div>{scanOpen?<div className="circuit-scan"><ScanLine size={16}/><span>{clues.join(" · ")}</span></div>:null}<div className="circuit-actions"><button type="button" className="circuit-commit" onClick={commit} disabled={switching}><Zap size={16}/>{switching?"Applying switch plan…":"Commit switch plan"}</button><button type="button" onClick={scan} disabled={scans<1||switching}><ScanLine size={16}/>Grid scan · {scans}</button></div><div className="circuit-status" aria-live="polite"><span>{message}</span><small>1–4 route · G scan · Enter commit</small></div></main>:<main className="circuit-console circuit-finished"><CircuitBoard size={54}/><strong>MICROGRID STABLE · REVIEW READY</strong><span>Uploading sealed switch plans for authoritative science grading…</span></main>}
  <div className="circuit-pressure"><span><TriangleAlert size={13}/> Fault pressure</span><i><b style={{width:`${pressure}%`}}/></i><strong>{Math.round(pressure)}%</strong></div></div>
  <footer className="circuit-footer"><span>Grid restored {progress}%</span><span>{plan?.masteryPercent==null?"Electrical profile calibrating":`Recent mastery ${plan.masteryPercent}%`}</span><span>{plan?.supportMode??"adaptive"} support</span></footer>
 </section>;
}
