"use client";
import { LifeBuoy, MessageCircle, X } from "lucide-react";
import { useState } from "react";

export function HomeHelpBar(){
 const [open,setOpen]=useState(false); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [form,setForm]=useState({name:"",email:"",phone:"",subject:"Help from SukuuNova",message:""});
 async function send(){setBusy(true);const r=await fetch("/api/public/inquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(r.ok)setSent(true);else window.alert(b.message||"We could not send your message.");setBusy(false)}
 return <section className="mx-auto mb-5 max-w-[1480px] rounded-3xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-emerald-600 text-white"><LifeBuoy size={18}/></span><div><strong className="block text-sm font-black text-emerald-950">Need help? Start here.</strong><p className="mt-1 text-xs leading-5 text-emerald-900/70">Tell SukuuNova what you need and our support team can follow up by email or phone/WhatsApp.</p></div></div><button type="button" onClick={()=>setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-[11px] font-black text-white"><MessageCircle size={15}/> Send a help message</button></div>{open?<div className="mt-4 rounded-2xl border border-emerald-200 bg-white p-4"><div className="mb-4 flex items-center justify-between"><div><span className="text-[9px] font-black uppercase tracking-[.15em] text-emerald-700">Direct support</span><h2 className="mt-1 text-base font-black text-slate-950">Message SukuuNova</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close help form"><X size={17}/></button></div>{sent?<div className="rounded-xl bg-emerald-50 p-4 text-xs font-bold text-emerald-800">Your help request is in the support inbox. We now have a way to reply to you.</div>:<div className="grid gap-3 sm:grid-cols-2"><input className="rounded-xl border border-slate-300 px-3 py-3 text-sm" placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="rounded-xl border border-slate-300 px-3 py-3 text-sm" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="rounded-xl border border-slate-300 px-3 py-3 text-sm" placeholder="Phone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="rounded-xl border border-slate-300 px-3 py-3 text-sm" placeholder="What do you need help with?" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><textarea className="min-h-32 rounded-xl border border-slate-300 px-3 py-3 text-sm sm:col-span-2" placeholder="Describe the problem, question or request…" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button disabled={busy||!form.name||!form.message||(!form.email&&!form.phone)} onClick={()=>void send()} className="inline-flex w-fit items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-[11px] font-black text-white disabled:opacity-50"><MessageCircle size={14}/>{busy?"Sending…":"Send help request"}</button></div>}</div>:null}</section>;
}
