"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Gamepad2, Medal, Play, RefreshCw, Rocket, Sparkles, Trophy, X, Zap } from "lucide-react";
import NovaRunner from "./NovaRunner";
import TurboType, { type TurboTypeTelemetry } from "./TurboType";
import AstroLabDefender from "./AstroLabDefender";
import WordKingdom from "./WordKingdom";
import ReadingQuest from "./ReadingQuest";
import CodeBotsFactory from "./CodeBotsFactory";
import GeoQuest from "./GeoQuest";
import CediCityMarket from "./CediCityMarket";
import SignalShield from "./SignalShield";
import EcoGridGhana from "./EcoGridGhana";
import BioQuestHumanSystems from "./BioQuestHumanSystems";
import ChronicleVault from "./ChronicleVault";
import ArcadeProgressionHub from "./ArcadeProgressionHub";
import ArcadeGameLogo from "./ArcadeGameLogo";
import "./nova-learning-arcade.css";

type AgeBand = "age_4_5" | "age_6_8" | "age_9_11" | "age_12_14" | "age_15_18";
type LiveGame = "math" | "keyboard-ninja" | "force-motion-lab" | "word" | "comprehension-quest" | "coding-sequence" | "ghana-map-master" | "money-math-market" | "cyber-safety" | "environment-guardian" | "body-explorer" | "history-timeline";
type Child = { id: string; name: string; classId: string | null; class: { name: string; level: string | null } | null };
type Progress = { game: string; rounds: number; xp: number; level: number; accuracy: number | null; badges: string[] };
type Overview = { children: Child[]; selected: Child | null; progress: Progress[]; streak: number; recent: Array<{ id: string; game: string; correct: number; stars: number; difficulty: number; xp: number; score: number; roundLength: number }>; recommendedAgeBand: AgeBand | null; allowedAgeBands: AgeBand[] };
type QuestionScene = { cue?: string; meterLabels?: string[]; x?: number; y?: number; boardTitle?: string; customer?: string; avatar?: string; basket?: string[]; wallet?: number; mission?: "change" | "basket" | "discount" | "saving" | "budget" | "profit" | "percentage" | "tradeoff"; priceTags?: string[]; incidentType?: "phishing" | "link" | "password" | "privacy" | "wifi" | "update" | "recovery" | "imposter"; source?: string; channel?: string; asset?: string; signalTags?: string[]; threatLevel?: 1 | 2 | 3 | 4 | 5; packetId?: string; ecoMission?: "waste" | "water" | "sanitation" | "energy" | "habitat" | "climate" | "transport" | "ewaste" | "circularity"; zone?: string; event?: string; resource?: string; ecoSignals?: string[]; riskLevel?: 1 | 2 | 3 | 4 | 5; forecast?: string; projectId?: string; bodySystem?: "circulatory" | "respiratory" | "digestive" | "nervous" | "skeletal" | "muscular" | "immune" | "excretory" | "endocrine" | "coordination"; organ?: string; caseTitle?: string; vitalFocus?: string; scanSignals?: string[]; strainLevel?: 1 | 2 | 3 | 4 | 5; bay?: string; caseId?: string };
type Question = { id: string; kind?: string; prompt: string; options: string[]; answer?: string; explanation?: string; correct?: boolean; scene?: QuestionScene };
type LearningPlan = { version: 1; targetDifficulty: number; masteryPercent: number | null; supportMode: "guided" | "supported" | "independent" | "challenge"; missionMode: "onboarding" | "recovery" | "reinforcement" | "balanced" | "stretch"; speedScale: number; hazardDensity: number; hintStrength: 0 | 1 | 2; bossGate: boolean; worldKey: "aurora-causeway" | "meteor-foundry" | "prism-canyon" | "nova-citadel" };
type Round = { id: string; studentId: string; game: string; difficulty: number; status: string; answers: string[]; correct: number | null; xp: number; stars: number; ageBand: AgeBand | null; roundLength: number; score: number | null; questions: Question[]; learningPlan?: LearningPlan | null };
type Leaderboard = { rows: Array<{ rank: number; studentId: string; displayName: string; bestScore: number; totalXp: number; rounds: number }> };
type GameMeta = { game: LiveGame; name: string; cardClass: string; minAgeRank: number; lockedLabel: string; description: string; tags: readonly string[]; playLabel: string; continueLabel: string; saveMessage: string; completionNoun: string; resultUnit: string; resultKicker: string; replayLabel: string; perfectTitle: string };

const ageLabels: Record<AgeBand, string> = { age_4_5: "Age 4–5", age_6_8: "Age 6–8", age_9_11: "Age 9–11", age_12_14: "Age 12–14", age_15_18: "Age 15–18" };
const ageRank: Record<AgeBand, number> = { age_4_5: 0, age_6_8: 1, age_9_11: 2, age_12_14: 3, age_15_18: 4 };
const GAMES: readonly GameMeta[] = [
  { game: "math", name: "Nova Runner", cardClass: "primary", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Race through an original sci-fi world. Jump hazards, collect Nova energy and enter Knowledge Gates where mathematics changes with the learner’s level and recent play.", tags: ["Mathematics", "Adaptive Director", "Runner", "Keyboard + touch", "5–10 min"], playLabel: "Play Nova Runner", continueLabel: "Continue Nova Runner", saveMessage: "Mission saved. Nova Runner will resume from your next Knowledge Gate.", completionNoun: "Mission", resultUnit: "Knowledge Gates", resultKicker: "NOVA RUNNER · MISSION COMPLETE", replayLabel: "mission", perfectTitle: "Legendary run!" },
  { game: "keyboard-ninja", name: "TurboType", cardClass: "turbo-card", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Race by typing exact targets. Every correct character moves your vehicle; accuracy, WPM and troublesome keys shape future practice.", tags: ["ICT", "Typing", "Weak-key training", "Adaptive"], playLabel: "Play TurboType", continueLabel: "Continue TurboType", saveMessage: "Race saved. TurboType will resume at your next checkpoint.", completionNoun: "Race", resultUnit: "typing checkpoints", resultKicker: "TURBOTYPE · RACE COMPLETE", replayLabel: "race", perfectTitle: "Perfect precision!" },
  { game: "force-motion-lab", name: "AstroLab Defender", cardClass: "astro-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Defend a living research station by reading real force-and-motion telemetry, choosing science responses and managing shields, reactor power and navigation.", tags: ["Science", "NovaCore physics", "Systems strategy", "Adaptive"], playLabel: "Play AstroLab", continueLabel: "Continue AstroLab", saveMessage: "Lab secured. AstroLab Defender will resume at the next anomaly.", completionNoun: "Defence mission", resultUnit: "science anomalies", resultKicker: "ASTROLAB DEFENDER · LAB SECURED", replayLabel: "defence mission", perfectTitle: "Lab fully stabilised!" },
  { game: "word", name: "Word Kingdom", cardClass: "word-card", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Protect a fantasy kingdom from the Shadow Scribe. Vocabulary, grammar, opposites, meaning and sentence choices become rune gates while mana and castle defence create a real quest loop.", tags: ["English", "Vocabulary + grammar", "Castle defence", "Adaptive"], playLabel: "Play Word Kingdom", continueLabel: "Continue Word Kingdom", saveMessage: "Quest saved. Word Kingdom will resume at the next rune gate.", completionNoun: "Quest", resultUnit: "kingdom runes", resultKicker: "WORD KINGDOM · CROWN SECURED", replayLabel: "quest", perfectTitle: "Crown restored!" },
  { game: "comprehension-quest", name: "Reading Quest", cardClass: "word-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Explore branching routes through short stories, reports and real-world texts. Manage story fog and focus lanterns while collecting evidence and making defensible reading decisions.", tags: ["English", "Reading comprehension", "Evidence + inference", "Branching exploration"], playLabel: "Play Reading Quest", continueLabel: "Continue Reading Quest", saveMessage: "Expedition saved. Reading Quest will resume at the next chapter.", completionNoun: "Expedition", resultUnit: "evidence chapters", resultKicker: "READING QUEST · MYSTERY MAPPED", replayLabel: "expedition", perfectTitle: "Mystery solved!" },
  { game: "coding-sequence", name: "CodeBots Logic Factory", cardClass: "astro-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Build executable command racks for robot workers while conveyor heat rises. Sequence algorithms, loops, conditions, debugging and real software workflows without turning coding into a decorated quiz.", tags: ["Computing", "Algorithms + logic", "Robot factory", "Adaptive"], playLabel: "Play CodeBots", continueLabel: "Continue CodeBots", saveMessage: "Factory saved. CodeBots will resume at the next bot build.", completionNoun: "Factory run", resultUnit: "bot programs", resultKicker: "CODEBOTS · FACTORY ONLINE", replayLabel: "factory run", perfectTitle: "Factory flawless!" },
  { game: "ghana-map-master", name: "GeoQuest Ghana Expedition", cardClass: "word-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Travel across a living Ghana atlas, choose field routes, manage weather and expedition energy, scan unknown beacons and map regions, capitals, borders and major geographic features.", tags: ["Social Studies", "Ghana geography", "Atlas expedition", "Adaptive"], playLabel: "Play GeoQuest", continueLabel: "Continue GeoQuest", saveMessage: "Survey saved. GeoQuest will resume at the next atlas beacon.", completionNoun: "Survey", resultUnit: "atlas beacons", resultKicker: "GEOQUEST · ATLAS COMPLETE", replayLabel: "survey", perfectTitle: "Atlas mastered!" },
  { game: "money-math-market", name: "Cedi City Market", cardClass: "market-card", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Run a living Ghana-currency market. Serve customers, read baskets and receipts, manage queue pressure, stock and trust, and grow from change-making into budgets, discounts, profit and percentage decisions.", tags: ["Mathematics", "Financial literacy", "Ghana cedi", "Market simulation", "Adaptive"], playLabel: "Play Cedi City Market", continueLabel: "Continue Cedi City", saveMessage: "Market saved. Cedi City will resume with the next customer.", completionNoun: "Market shift", resultUnit: "customer receipts", resultKicker: "CEDI CITY · MARKET CLOSED", replayLabel: "market shift", perfectTitle: "Market master!" },
  { game: "cyber-safety", name: "Signal Shield", cardClass: "signal-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Operate a school CyberOps centre. Triage suspicious messages, inspect link and identity signals, protect accounts and privacy, contain incidents and keep firewall integrity stable under adaptive threat pressure.", tags: ["ICT", "Cyber safety", "Digital citizenship", "Network defence simulation", "Adaptive"], playLabel: "Play Signal Shield", continueLabel: "Continue Signal Shield", saveMessage: "CyberOps saved. Signal Shield will resume at the next incident.", completionNoun: "CyberOps shift", resultUnit: "security incidents", resultKicker: "SIGNAL SHIELD · NETWORK SECURED", replayLabel: "CyberOps shift", perfectTitle: "Network guardian!" },
  { game: "environment-guardian", name: "EcoGrid Ghana", cardClass: "word-card", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Restore a living Ghanaian community by balancing water, waste, energy, habitat and climate resilience. Run field surveys, manage eco stress and grow from simple clean-up choices into systems-level environmental planning.", tags: ["Environmental Studies", "Water + waste", "Climate resilience", "Community strategy", "Adaptive"], playLabel: "Play EcoGrid Ghana", continueLabel: "Continue EcoGrid", saveMessage: "EcoGrid saved. Community restoration will resume at the next project.", completionNoun: "Restoration shift", resultUnit: "restoration projects", resultKicker: "ECOGRID GHANA · COMMUNITY RESTORED", replayLabel: "restoration shift", perfectTitle: "EcoGrid fully restored!" },
  { game: "body-explorer", name: "BioQuest: Human Systems", cardClass: "astro-card", minAgeRank: 1, lockedLabel: "AGE 6+", description: "Enter a virtual anatomy lab and stabilise a living training avatar. Trace organs and body systems, run clue-only BioScans, manage system strain and grow from visible body functions into nervous, immune, endocrine and whole-body coordination.", tags: ["Science", "Human biology", "Anatomy + physiology", "Systems lab", "Adaptive"], playLabel: "Play BioQuest", continueLabel: "Continue BioQuest", saveMessage: "BioLab saved. BioQuest will resume at the next human-systems case.", completionNoun: "BioLab shift", resultUnit: "human-systems cases", resultKicker: "BIOQUEST · SYSTEMS STABILISED", replayLabel: "BioLab shift", perfectTitle: "Human systems master!" },
  { game: "history-timeline", name: "Chronicle Vault", cardClass: "word-card", minAgeRank: 2, lockedLabel: "AGE 9+", description: "Repair a damaged historical archive by rebuilding time rails, testing provenance, tracing cause and consequence, and corroborating evidence before Paradox Pressure destabilises the record.", tags: ["History", "Chronology", "Source analysis", "Cause + consequence", "Adaptive"], playLabel: "Play Chronicle Vault", continueLabel: "Continue Chronicle Vault", saveMessage: "Archive sealed. Chronicle Vault will resume at the next damaged record.", completionNoun: "Archive investigation", resultUnit: "archive records", resultKicker: "CHRONICLE VAULT · ARCHIVE STABLE", replayLabel: "archive investigation", perfectTitle: "Master historian!" }
] as const;

const gameMeta = (game: LiveGame) => GAMES.find((item) => item.game === game) ?? GAMES[0];
function displayAnswer(value?: string) { if (!value) return "—"; try { const parsed = JSON.parse(value); if (Array.isArray(parsed) && parsed.every((item) => typeof item === "string")) return parsed.join(" → "); } catch {} return value; }
async function api(path: string, body?: unknown) { const response = await fetch(path, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? data.error ?? "Could not connect to the Learning Arcade."); return data; }

export default function LearningArcadeV4() {
  const [data, setData] = useState<Overview | null>(null);
  const [round, setRound] = useState<Round | null>(null);
  const [result, setResult] = useState<Round | null>(null);
  const [ageBand, setAgeBand] = useState<AgeBand | "">("");
  const [leaderboard, setLeaderboard] = useState<Leaderboard | null>(null);
  const [leaderboardGame, setLeaderboardGame] = useState<LiveGame>("math");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const request = useRef(0);
  const operation = useRef(false);

  const refresh = async (studentId = "") => { const version = ++request.current; setLoading(true); setError(""); try { const next = await api(`/api/guardian/arcade?studentId=${encodeURIComponent(studentId)}`) as Overview; if (version !== request.current) return; setData(next); setAgeBand(next.recommendedAgeBand ?? next.allowedAgeBands[0] ?? ""); } catch (loadError) { if (version === request.current) setError(loadError instanceof Error ? loadError.message : "Could not load the Learning Arcade."); } finally { if (version === request.current) setLoading(false); } };
  useEffect(() => { void refresh(); return () => { request.current += 1; }; }, []);
  const run = async (action: () => Promise<void>) => { if (operation.current) return; operation.current = true; setBusy(true); setError(""); setMessage(""); try { await action(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "The mission could not be updated."); } finally { operation.current = false; setBusy(false); } };
  const startGame = (game: LiveGame) => run(async () => { if (!data?.selected || !ageBand) return; const next = await api("/api/guardian/arcade", { action: "start", studentId: data.selected.id, game, ageBand, roundLength: 5 }) as Round; setRound(next); setResult(null); setLeaderboard(null); });
  const finishRound = (answers: string[], typingTelemetry?: TurboTypeTelemetry) => run(async () => { if (!round) return; const completed = await api("/api/guardian/arcade", { action: "save", roundId: round.id, answers, finish: true, ...(typingTelemetry ? { typingTelemetry } : {}) }) as Round; const completedGame = round.game as LiveGame; setRound(null); setResult(completed); setMessage(`${gameMeta(completedGame).completionNoun} complete — ${completed.xp} XP earned.`); await refresh(completed.studentId); });
  const exitRound = (answers: string[], typingTelemetry?: TurboTypeTelemetry) => run(async () => { if (!round) return; const currentGame = round.game as LiveGame; await api("/api/guardian/arcade", { action: "save", roundId: round.id, answers, finish: false, ...(typingTelemetry ? { typingTelemetry } : {}) }); const studentId = round.studentId; setRound(null); setMessage(gameMeta(currentGame).saveMessage); await refresh(studentId); });
  const loadLeaderboard = (game: LiveGame) => run(async () => { if (!data?.selected || !ageBand) return; const params = new URLSearchParams({ view: "leaderboard", studentId: data.selected.id, game, scope: "standard", period: "weekly", ageBand }); setLeaderboardGame(game); setLeaderboard(await api(`/api/guardian/arcade?${params.toString()}`) as Leaderboard); });
  const progressFor = (game: LiveGame) => data?.progress.find((item) => item.game === game);
  const totalXp = useMemo(() => GAMES.reduce((sum, item) => sum + (data?.progress.find((progress) => progress.game === item.game)?.xp ?? 0), 0), [data?.progress]);
  const highestGameLevel = Math.max(1, ...GAMES.map((item) => progressFor(item.game)?.level ?? 1));
  const currentAgeRank = ageBand ? ageRank[ageBand] : -1;
  const eligibleFor = (game: LiveGame) => currentAgeRank >= gameMeta(game).minAgeRank;

  if (round && data?.selected) {
    const common = { learnerName: data.selected.name, round, onComplete: (answers: string[]) => void finishRound(answers), onExit: (answers: string[]) => void exitRound(answers) };
    let gameView;
    switch (round.game as LiveGame) {
      case "keyboard-ninja": gameView = <TurboType learnerName={data.selected.name} round={round} onComplete={(answers, telemetry) => void finishRound(answers, telemetry)} onExit={(answers, telemetry) => void exitRound(answers, telemetry)}/>; break;
      case "force-motion-lab": gameView = <AstroLabDefender {...common}/>; break;
      case "word": gameView = <WordKingdom {...common}/>; break;
      case "comprehension-quest": gameView = <ReadingQuest {...common}/>; break;
      case "coding-sequence": gameView = <CodeBotsFactory {...common}/>; break;
      case "ghana-map-master": gameView = <GeoQuest {...common}/>; break;
      case "money-math-market": gameView = <CediCityMarket {...common}/>; break;
      case "cyber-safety": gameView = <SignalShield {...common}/>; break;
      case "environment-guardian": gameView = <EcoGridGhana {...common}/>; break;
      case "body-explorer": gameView = <BioQuestHumanSystems {...common}/>; break;
      case "history-timeline": gameView = <ChronicleVault {...common}/>; break;
      default: gameView = <NovaRunner {...common}/>; break;
    }
    return <div className="nova-arcade">{gameView}{busy ? <div className="nova-arcade-message">Saving game progress…</div> : null}{error ? <div className="nova-arcade-alert" role="alert">{error}</div> : null}</div>;
  }

  if (result) {
    const resultGame = result.game as LiveGame;
    const meta = gameMeta(resultGame);
    return <div className="nova-finish"><section className="nova-finish-card"><div className="nova-finish-top"><div className="nova-finish-mark"><Trophy size={34}/></div><span className="nova-arcade-kicker">{meta.resultKicker}</span><h1>{result.stars === 3 ? meta.perfectTitle : result.stars === 2 ? "Strong mission!" : "World cleared!"}</h1><p>{result.correct}/{result.roundLength} {meta.resultUnit} cleared correctly. The Adaptive Director will use this performance for the next game.</p><div className="nova-rewards"><div><strong>{result.stars}/3</strong><span>Stars</span></div><div><strong>+{result.xp}</strong><span>XP</span></div><div><strong>{result.score ?? 0}</strong><span>Score</span></div></div></div><div className="nova-result-list">{result.questions.map((question, index) => <div className={`nova-result ${question.correct ? "good" : "bad"}`} key={question.id}><div className="nova-result-icon">{question.correct ? <Check size={18}/> : <X size={18}/>}</div><div><p>{question.prompt}</p><small>{question.correct ? `Correct — ${displayAnswer(result.answers[index])}` : `You entered ${displayAnswer(result.answers[index])}. Target: ${displayAnswer(question.answer)}. ${question.explanation ?? ""}`}</small></div></div>)}</div><div className="nova-finish-actions"><button type="button" onClick={() => { setResult(null); void startGame(resultGame); }} disabled={busy}><RefreshCw size={16}/> Play another {meta.replayLabel}</button><button type="button" onClick={() => setResult(null)}>Back to Arcade</button></div></section></div>;
  }

  return <div className="nova-arcade">
    <section className="nova-arcade-hero"><div className="nova-arcade-hero-copy"><span className="nova-arcade-kicker"><Sparkles size={13}/> SUKUUNOVA LEARNING ARCADE</span><h1>Learn inside the adventure.</h1><p>Real gameplay, adaptive school learning and measurable skill progression now share one Arcade universe.</p></div><div className="nova-arcade-hero-card"><div className="nova-arcade-avatar">{data?.selected?.name?.trim()?.[0]?.toUpperCase() ?? "N"}</div><div><small>PLAYER</small><strong>{data?.selected?.name ?? (loading ? "Loading learner…" : "Choose a learner")}</strong><div className="nova-arcade-stat-grid"><div><b>{highestGameLevel}</b><span>Highest game level</span></div><div><b>{data?.streak ?? 0}</b><span>Day streak</span></div><div><b>{totalXp}</b><span>Total XP</span></div></div></div></div></section>
    {error ? <div className="nova-arcade-alert" role="alert">{error}</div> : null}{message ? <div className="nova-arcade-message">{message}</div> : null}
    <div className="nova-arcade-toolbar"><div><h2>Choose your mission</h2><p>Only experiences that meet the new game standard appear as playable.</p></div>{data?.children?.length ? <select className="nova-arcade-select" aria-label="Learner" value={data.selected?.id ?? ""} onChange={(event) => void refresh(event.target.value)} disabled={loading || busy}>{data.children.map((child) => <option key={child.id} value={child.id}>{child.name} · {child.class?.name ?? "No class"}</option>)}</select> : null}</div>
    {data?.selected ? <ArcadeProgressionHub key={data.selected.id} studentId={data.selected.id} playerName={data.selected.name}/> : null}
    <div className="nova-game-grid">{GAMES.map((meta) => { const progress = progressFor(meta.game); const eligible = eligibleFor(meta.game); const primary = meta.game === "math"; return <article className={`nova-game-card ${meta.cardClass}`} key={meta.game}>{primary ? null : <span className={`nova-coming ${eligible ? "live" : ""}`}>{eligible ? "LIVE" : meta.lockedLabel}</span>}<ArcadeGameLogo game={meta.game}/><h3>{meta.name}</h3><p>{meta.description}</p><div className="nova-game-tags">{meta.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="nova-game-actions"><button className="nova-play-button" type="button" onClick={() => void startGame(meta.game)} disabled={busy || loading || !data?.selected || !ageBand || !eligible}><Play size={17} fill="currentColor"/>{eligible ? (progress?.rounds ? meta.continueLabel : meta.playLabel) : `Available from ${meta.lockedLabel.replace("AGE ", "Age ")}`}</button><button className={primary ? "nova-rank-button" : "nova-secondary-button"} type="button" onClick={() => void loadLeaderboard(meta.game)} disabled={busy || !data?.selected || !ageBand || !eligible}><Medal size={16}/>{primary ? "Weekly ranking" : "Ranking"}</button></div>{primary && data?.allowedAgeBands?.length ? <div className="nova-game-actions"><label htmlFor="nova-age" className="nova-age-label">Learning band</label><select id="nova-age" className="nova-arcade-select" value={ageBand} onChange={(event) => setAgeBand(event.target.value as AgeBand)}>{data.allowedAgeBands.map((age) => <option key={age} value={age}>{ageLabels[age]}</option>)}</select></div> : null}</article>; })}</div>
    {leaderboard ? <section className="nova-arcade-panel"><div className="nova-arcade-panel-head"><div><h3>{gameMeta(leaderboardGame).name} · Weekly school-standard ranking</h3><p>Ranking stays inside the learner’s permitted school context.</p></div><Trophy size={22}/></div><div className="nova-leaderboard">{leaderboard.rows.length ? leaderboard.rows.map((row) => <div className="nova-leader-row" key={row.studentId}><b>#{row.rank}</b><strong>{row.displayName}</strong><span>{row.bestScore} best</span><span>{row.totalXp} XP · {row.rounds} runs</span></div>) : <div className="nova-empty">No ranked games yet. Be the first this week.</div>}</div></section> : null}
    <section className="nova-arcade-panel"><div className="nova-arcade-panel-head"><div><h3>Arcade foundation</h3><p>Twelve distinct game loops now share one adaptive learning director and one authoritative progression universe.</p></div><Gamepad2 size={22}/></div><div className="nova-game-tags"><span><Rocket size={12}/> real-time gameplay</span><span><Zap size={12}/> adaptive learning director</span><span>daily + weekly missions</span><span>achievement cabinet</span><span>NovaCore physics</span><span>typing telemetry</span><span>Ghana geography</span><span>financial literacy</span><span>cyber safety</span><span>environmental strategy</span><span>human biology</span><span>historical reasoning</span><span>save/resume</span><span>school-scoped ranking</span><span>server-side grading</span></div></section>
  </div>;
}
