/* eslint-disable @next/next/no-img-element */
"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BookCopy, BookMarked, BookOpen, BookmarkPlus, Download, LibraryBig, LockKeyhole, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

type Row = Record<string, unknown> & { dueAt?: string | null };
type Props = { schoolName: string };
const endpoint = "/api/school/operations/library";
const text = (value: unknown, fallback = "—") => typeof value === "string" && value.trim() ? value : fallback;
const number = (value: unknown) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
const rows = (value: unknown): Row[] => Array.isArray(value) ? value.filter((item): item is Row => Boolean(item) && typeof item === "object") : [];
const object = (value: unknown): Row => value && typeof value === "object" && !Array.isArray(value) ? value as Row : {};
const date = (value: unknown) => { const parsed = value ? new Date(String(value)) : null; return parsed && !Number.isNaN(parsed.getTime()) ? parsed.toLocaleDateString("en-GH", { day: "2-digit", month: "short", year: "numeric" }) : "—"; };

async function api(init?: RequestInit) {
  const response = await fetch(endpoint, { cache: "no-store", ...init });
  const body: unknown = await response.json().catch(() => ({}));
  if (!response.ok) {
    const data = object(body);
    throw new Error(text(data.message, text(data.error, "Library request failed.")));
  }
  return object(body);
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-white/10 bg-white/[0.035] p-4 shadow-sm ${className}`}>{children}</section>;
}
function Field({ label, name, placeholder, type = "text", required = false }: { label: string; name: string; placeholder?: string; type?: string; required?: boolean }) {
  return <label className="grid gap-1.5 text-[11px] font-bold text-slate-300"><span>{label}</span><input name={name} type={type} placeholder={placeholder} required={required} className="rounded-xl border border-white/10 bg-slate-950/40 px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-emerald-300/50" /></label>;
}
function Select({ label, name, children, defaultValue }: { label: string; name: string; children: React.ReactNode; defaultValue?: string }) {
  return <label className="grid gap-1.5 text-[11px] font-bold text-slate-300"><span>{label}</span><select name={name} defaultValue={defaultValue} className="rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-300/50">{children}</select></label>;
}
function Button({ children, disabled = false, type = "button", onClick }: { children: React.ReactNode; disabled?: boolean; type?: "button" | "submit"; onClick?: () => void }) {
  return <button type={type} disabled={disabled} onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-300 px-3.5 py-2.5 text-[11px] font-black text-slate-950 transition hover:translate-y-[-1px] hover:bg-emerald-200 disabled:cursor-not-allowed disabled:opacity-50">{children}</button>;
}
function SecondaryButton({ children, disabled = false, onClick }: { children: React.ReactNode; disabled?: boolean; onClick?: () => void }) {
  return <button type="button" disabled={disabled} onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3.5 py-2.5 text-[11px] font-black text-slate-200 transition hover:bg-white/[0.07] disabled:opacity-50">{children}</button>;
}

export default function LibraryStudio({ schoolName }: Props) {
  const mutation = useRef(false);
  const [data, setData] = useState<Row>({});
  const [tab, setTab] = useState("catalogue");
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    try { setError(""); setData(await api()); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Library could not be loaded."); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const post = async (body: Row, message: string) => {
    if (mutation.current) return;
    mutation.current = true; setBusy(true); setError(""); setNotice("");
    try {
      await api({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      setNotice(message); await load();
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Action failed."); }
    finally { mutation.current = false; setBusy(false); }
  };
  const submit = async (event: FormEvent<HTMLFormElement>, action: string, message: string) => {
    event.preventDefault(); const form = event.currentTarget; const body: Row = { action };
    new FormData(form).forEach((value, key) => { if (value !== "") body[key] = String(value); });
    if (typeof body.tags === "string") body.tags = String(body.tags).split(",").map(value => value.trim()).filter(Boolean);
    await post(body, message); form.reset();
  };

  const books = rows(data.books), loans = rows(data.loans), copies = rows(data.copies), reservations = rows(data.reservations), assignments = rows(data.assignments);
  const students = rows(data.students), classes = rows(data.classes), subjects = rows(data.subjects);
  const canManage = Boolean(data.canManage);
  const filteredBooks = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return books;
    return books.filter(book => [book.title, book.author, book.category, book.materialType, JSON.stringify(book.tags)].some(value => String(value ?? "").toLowerCase().includes(q)));
  }, [books, query]);
  const openLoans = loans.filter(loan => ["borrowed", "overdue"].includes(text(loan.displayStatus, text(loan.status)).toLowerCase()));
  const digitalCount = books.filter(book => Boolean(book.digitalAvailable)).length;
  const readOnlyCount = books.filter(book => Boolean(book.digitalAvailable) && !Boolean(book.downloadAllowed)).length;
  const overdueCount = loans.filter(loan => text(loan.displayStatus).toLowerCase() === "overdue").length;
  const tabs = canManage
    ? [["catalogue","Discover"],["circulation","Circulation"],["access","Digital access"],["copies","Copies"],["resources","Recommendations"],["add","Add resource"]]
    : [["catalogue","Discover"],["circulation","Circulation"]];

  return <div className="grid gap-5">
    <section className="overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-emerald-300/[0.10] via-white/[0.035] to-indigo-300/[0.07] p-5 md:p-7">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div className="max-w-3xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/[0.07] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-emerald-200"><LibraryBig size={14}/> SukuuNova Library</div><h1 className="text-2xl font-black tracking-tight text-white md:text-3xl">A real reading library for {schoolName}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Digital resources open inside SukuuNova by default. Downloading is a separate school-controlled right for each title, while physical books retain circulation and accession history.</p></div>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Titles",books.length],["Digital",digitalCount],["Read only",readOnlyCount],["Overdue",overdueCount]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-slate-950/35 px-4 py-3"><strong className="block text-xl font-black text-white">{value}</strong><span className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{label}</span></div>)}</div>
      </div>
    </section>

    {(notice || error) && <div className={`rounded-xl border px-4 py-3 text-xs font-bold ${error ? "border-red-300/20 bg-red-300/[0.06] text-red-200" : "border-emerald-300/20 bg-emerald-300/[0.06] text-emerald-200"}`}>{error || notice}</div>}

    <nav className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-[11px] font-black transition ${tab===key?"bg-white text-slate-950":"border border-white/10 bg-white/[0.03] text-slate-400 hover:text-white"}`}>{label}</button>)}</nav>

    {tab === "catalogue" && <div className="grid gap-4">
      <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search books, authors, subjects, PDFs, past papers…" className="w-full rounded-xl border border-white/10 bg-slate-950/40 py-3 pl-10 pr-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-emerald-300/40"/></div><span className="text-[10px] font-bold text-slate-500">{filteredBooks.length} resources</span></div></Card>
      {filteredBooks.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filteredBooks.map(book=>{
        const digital=Boolean(book.digitalAvailable), downloadable=Boolean(book.downloadAllowed);
        return <article key={text(book.id)} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035] shadow-sm"><div className="flex h-48 items-center justify-center overflow-hidden bg-white/[0.025]">{text(book.coverUrl,"")?<img src={text(book.coverUrl)} alt="" className="h-full w-full object-cover"/>:<div className="text-center"><BookOpen size={34} className="mx-auto text-emerald-200"/><strong className="mt-3 block max-w-48 text-lg font-black text-white">{text(book.title)}</strong></div>}</div><div className="p-4"><div className="flex flex-wrap gap-1.5"><span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-black uppercase text-slate-400">{text(book.category,"General")}</span><span className="rounded-full border border-white/10 px-2 py-1 text-[8px] font-black uppercase text-slate-400">{text(book.materialType,"book")}</span>{digital&&<span className="rounded-full border border-emerald-300/20 bg-emerald-300/[0.06] px-2 py-1 text-[8px] font-black uppercase text-emerald-200">{downloadable?"Read + download":"Read only"}</span>}</div><h2 className="mt-3 text-base font-black text-white">{text(book.title)}</h2><p className="mt-1 text-xs text-slate-500">{text(book.author,"School resource")}</p>{text(book.description,"")&&<p className="mt-3 line-clamp-3 text-[11px] leading-5 text-slate-400">{text(book.description)}</p>}<div className="mt-4 flex items-center justify-between text-[10px] text-slate-500"><span>{number(book.availableCopies)} physical copies available</span>{number(book.estimatedMinutes)>0&&<span>~{number(book.estimatedMinutes)} min</span>}</div><div className="mt-4 flex flex-wrap gap-2">{digital&&<Link href={`/school/library/${text(book.id)}/read`} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-3 py-2 text-[10px] font-black text-slate-950"><BookOpen size={14}/> Read in SukuuNova</Link>}{downloadable&&<a href={`/api/school/operations/library/content/${encodeURIComponent(text(book.id))}?download=1`} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-[10px] font-black text-slate-300"><Download size={14}/> Download</a>}{digital&&!downloadable&&<span className="inline-flex items-center gap-1.5 rounded-xl border border-white/10 px-3 py-2 text-[9px] font-bold text-slate-500"><LockKeyhole size={13}/> School protected</span>}</div></div></article>;
      })}</div>:<Card><div className="py-14 text-center"><BookOpen className="mx-auto text-slate-600"/><strong className="mt-3 block text-white">No library resources yet</strong><p className="mt-1 text-xs text-slate-500">Add the first physical or digital resource to begin the collection.</p></div></Card>}
    </div>}

    {tab === "circulation" && <div className="grid gap-4 xl:grid-cols-[.72fr,1.28fr]">
      <Card><div className="mb-4"><h2 className="font-black text-white">Issue a physical resource</h2><p className="mt-1 text-xs text-slate-500">If accession records exist, SukuuNova automatically assigns an available copy.</p></div><form className="grid gap-3" onSubmit={event=>submit(event,"borrow","Resource issued successfully.")}><Select label="Resource" name="bookId"><option value="">Choose title</option>{books.map(book=><option key={text(book.id)} value={text(book.id)} disabled={number(book.availableCopies)<1}>{text(book.title)} · {number(book.availableCopies)} available</option>)}</Select><Select label="Learner" name="studentId"><option value="">Choose learner</option>{students.map(student=><option key={text(student.id)} value={text(student.id)}>{text(student.name)} · {text(student.admissionNo)}</option>)}</Select><Field label="Loan days" name="days" type="number" placeholder="14"/><Button type="submit" disabled={busy}><BookMarked size={14}/> Issue resource</Button></form></Card>
      <Card><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-white">Open circulation</h2><p className="mt-1 text-xs text-slate-500">Borrowed and overdue items.</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] font-bold text-slate-400">{openLoans.length} open</span></div><div className="grid gap-2">{openLoans.length?openLoans.map(loan=><div key={text(loan.id)} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-slate-950/30 p-3 sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-sm text-white">{text(loan.bookTitle)}</strong><span className="mt-1 block text-[10px] text-slate-500">{text(loan.studentName)} · due {date(loan.dueAt)}{text(loan.accessionNo,"")?` · ${text(loan.accessionNo)}`:""}</span></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${text(loan.displayStatus).toLowerCase()==="overdue"?"bg-red-300/[0.08] text-red-200":"bg-amber-300/[0.08] text-amber-200"}`}>{text(loan.displayStatus,text(loan.status))}</span><SecondaryButton disabled={busy} onClick={()=>void post({action:"return",loanId:loan.id},"Return recorded.")}>Return</SecondaryButton></div></div>):<p className="py-12 text-center text-xs text-slate-500">No open loans.</p>}</div></Card>
    </div>}

    {tab === "access" && canManage && <div className="grid gap-4"><Card><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-emerald-200"/><div><h2 className="font-black text-white">Digital rights & reading policy</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Reader access is independent from download permission. A learner never receives the original source URL; the protected content endpoint checks this policy on every request.</p></div></div></Card><div className="grid gap-3">{books.filter(book=>Boolean(book.digitalSourceConfigured)).map(book=><Card key={text(book.id)}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><strong className="text-sm text-white">{text(book.title)}</strong><span className="mt-1 block text-[10px] text-slate-500">{Boolean(book.readerEnabled)?"Online reader enabled":"Reader disabled"} · {Boolean(book.downloadAllowed)?"Downloads allowed":"Read-only download policy"} · {text(book.visibility,"school")}</span>{text(book.rightsNote,"")&&<span className="mt-1 block text-[10px] text-slate-600">{text(book.rightsNote)}</span>}</div><div className="flex flex-wrap gap-2"><SecondaryButton disabled={busy} onClick={()=>void post({action:"updateAccessPolicy",bookId:book.id,readerEnabled:!Boolean(book.readerEnabled),downloadAllowed:Boolean(book.readerEnabled)?Boolean(book.downloadAllowed):false,visibility:book.visibility,audience:book.audience,rightsNote:book.rightsNote,estimatedMinutes:book.estimatedMinutes},Boolean(book.readerEnabled)?"Reader disabled.":"Reader enabled.")}>{Boolean(book.readerEnabled)?"Disable reader":"Enable reader"}</SecondaryButton><SecondaryButton disabled={busy||!Boolean(book.readerEnabled)} onClick={()=>void post({action:"updateAccessPolicy",bookId:book.id,readerEnabled:true,downloadAllowed:!Boolean(book.downloadAllowed),visibility:book.visibility,audience:book.audience,rightsNote:book.rightsNote,estimatedMinutes:book.estimatedMinutes},Boolean(book.downloadAllowed)?"Download disabled; resource is read-only.":"Download enabled for this resource.")}>{Boolean(book.downloadAllowed)?"Make read only":"Allow download"}</SecondaryButton><select value={text(book.visibility,"school")} onChange={event=>void post({action:"updateAccessPolicy",bookId:book.id,readerEnabled:Boolean(book.readerEnabled),downloadAllowed:Boolean(book.downloadAllowed),visibility:event.target.value,audience:book.audience,rightsNote:book.rightsNote,estimatedMinutes:book.estimatedMinutes},"Visibility updated.")} className="rounded-xl border border-white/10 bg-slate-950/60 px-3 py-2 text-[11px] font-bold text-white"><option value="school">School learners</option><option value="staff">Staff only</option><option value="restricted">Assigned only</option></select></div></div></Card>)}</div></div>}

    {tab === "copies" && canManage && <div className="grid gap-4 xl:grid-cols-[.65fr,1.35fr]"><Card><h2 className="font-black text-white">Add accession/copy</h2><p className="mt-1 text-xs text-slate-500">Track individual physical copies, barcodes, shelves and condition.</p><form className="mt-4 grid gap-3" onSubmit={event=>submit(event,"addCopy","Copy added to the accession register.")}><Select label="Title" name="bookId"><option value="">Choose title</option>{books.map(book=><option key={text(book.id)} value={text(book.id)}>{text(book.title)}</option>)}</Select><Field label="Accession number" name="accessionNo" placeholder="LIB-2026-0001" required/><Field label="Barcode / QR value" name="barcode" placeholder="Optional"/><Field label="Shelf location" name="shelfLocation" placeholder="A2 · Shelf 4"/><Select label="Condition" name="condition" defaultValue="good"><option value="new">New</option><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></Select><Select label="Initial status" name="status" defaultValue="available"><option value="available">Available</option><option value="repair">Repair</option><option value="withdrawn">Withdrawn</option></Select><Button type="submit" disabled={busy}><BookCopy size={14}/> Add copy</Button></form></Card><Card><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-white">Accession register</h2><p className="mt-1 text-xs text-slate-500">Copy-level inventory attached to catalogue titles.</p></div><span className="text-xs font-bold text-slate-500">{copies.length} registered</span></div><div className="grid gap-2">{copies.length?copies.map(copy=><div key={text(copy.id)} className="grid gap-2 rounded-xl border border-white/10 bg-slate-950/30 p-3 sm:grid-cols-[1.3fr,.7fr,.7fr,.7fr]"><div><strong className="text-xs text-white">{text(copy.bookTitle)}</strong><span className="mt-1 block text-[10px] text-slate-500">{text(copy.accessionNo)}{text(copy.barcode,"")?` · ${text(copy.barcode)}`:""}</span></div><span className="text-[10px] text-slate-400">Shelf<br/><b className="text-white">{text(copy.shelfLocation)}</b></span><span className="text-[10px] text-slate-400">Condition<br/><b className="text-white">{text(copy.condition)}</b></span><span className="text-[10px] text-slate-400">Status<br/><b className="text-white">{text(copy.status)}</b></span></div>):<p className="py-12 text-center text-xs text-slate-500">No accession-level copies registered yet. Legacy title copy counts remain valid.</p>}</div></Card></div>}

    {tab === "resources" && canManage && <div className="grid gap-4 xl:grid-cols-[.7fr,1.3fr]"><Card><h2 className="font-black text-white">Recommend or require a resource</h2><p className="mt-1 text-xs text-slate-500">Target a learner, class, subject, or leave targets blank for a school-wide recommendation.</p><form className="mt-4 grid gap-3" onSubmit={event=>submit(event,"assignResource","Learning resource assigned.")}><Select label="Resource" name="bookId"><option value="">Choose resource</option>{books.map(book=><option key={text(book.id)} value={text(book.id)}>{text(book.title)}</option>)}</Select><Select label="Kind" name="kind" defaultValue="recommended"><option value="recommended">Recommended</option><option value="required">Required reading</option><option value="reference">Reference</option></Select><Select label="Class (optional)" name="classId"><option value="">All / not class-specific</option>{classes.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)} · {text(item.level)}</option>)}</Select><Select label="Learner (optional)" name="studentId"><option value="">All / not learner-specific</option>{students.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</Select><Select label="Subject (optional)" name="subjectId"><option value="">General</option>{subjects.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</Select><Field label="Due date (optional)" name="dueAt" type="datetime-local"/><Field label="Teacher/library note" name="note" placeholder="Why this resource matters…"/><Button type="submit" disabled={busy}><BookmarkPlus size={14}/> Assign resource</Button></form></Card><Card><div className="mb-4"><h2 className="font-black text-white">Resource recommendations</h2><p className="mt-1 text-xs text-slate-500">What learners are being directed to read or use.</p></div><div className="grid gap-2">{assignments.length?assignments.map(item=><div key={text(item.id)} className="rounded-xl border border-white/10 bg-slate-950/30 p-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-xs text-white">{text(item.bookTitle)}</strong><span className="mt-1 block text-[10px] text-slate-500">{text(item.kind)} · {text(item.studentName,text(item.className,text(item.subjectName,"School-wide")))}</span></div>{item.dueAt&&<span className="text-[9px] font-bold text-slate-500">Due {date(item.dueAt)}</span>}</div>{text(item.note,"")&&<p className="mt-2 text-[10px] leading-5 text-slate-400">{text(item.note)}</p>}</div>):<p className="py-12 text-center text-xs text-slate-500">No recommendations yet.</p>}</div></Card></div>}

    {tab === "add" && canManage && <Card><div className="mb-5 flex items-start gap-3"><Sparkles className="mt-1 text-emerald-200"/><div><h2 className="font-black text-white">Add a library resource</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">For digital content, provide an approved storage URL/path. Learners will read through SukuuNova; download is off by default and must be deliberately enabled.</p></div></div><form className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" onSubmit={event=>submit(event,"createBook","Library resource created.")}><Field label="Title" name="title" required/><Field label="Author / creator" name="author"/><Field label="ISBN" name="isbn"/><Field label="Category / subject" name="category" placeholder="Science"/><Select label="Material type" name="materialType" defaultValue="book"><option value="book">Physical book</option><option value="ebook">eBook</option><option value="pdf">PDF</option><option value="worksheet">Worksheet</option><option value="past-paper">Past paper</option><option value="audio">Audio</option><option value="video">Video</option><option value="document">Document</option><option value="magazine">Magazine</option><option value="other">Other</option></Select><Field label="Physical copy count" name="copies" type="number" placeholder="1"/><Field label="Cover image URL/path" name="coverUrl"/><Field label="Protected digital source URL/path" name="fileUrl" placeholder="/library-files/... or approved HTTPS host"/><Select label="Online reader" name="readerEnabled" defaultValue="true"><option value="true">Enabled</option><option value="false">Disabled</option></Select><Select label="Download policy" name="downloadAllowed" defaultValue="false"><option value="false">Read only — no download</option><option value="true">Allow download</option></Select><Select label="Visibility" name="visibility" defaultValue="school"><option value="school">School learners</option><option value="staff">Staff only</option><option value="restricted">Assigned learners/classes only</option></Select><Field label="Estimated reading minutes" name="estimatedMinutes" type="number"/><Field label="Publisher" name="publisher"/><Field label="Published year" name="publishedYear" type="number"/><Field label="Language" name="language" placeholder="English"/><Field label="Tags (comma separated)" name="tags" placeholder="science, basic 5, revision"/><Field label="Rights / licence note" name="rightsNote" placeholder="Licensed for school reading; no redistribution"/><label className="grid gap-1.5 text-[11px] font-bold text-slate-300 md:col-span-2 xl:col-span-3"><span>Description</span><textarea name="description" rows={4} className="rounded-xl border border-white/10 bg-slate-950/40 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-300/50"/></label><div className="md:col-span-2 xl:col-span-3"><Button type="submit" disabled={busy}><LibraryBig size={14}/> Add to library</Button></div></form></Card>}

    {reservations.length>0&&canManage&&<Card><div className="flex items-start gap-3"><UsersRound className="mt-0.5 text-amber-200"/><div><h2 className="font-black text-white">Reservation queue</h2><p className="mt-1 text-xs text-slate-500">{reservations.length} active learner reservation{reservations.length===1?"":"s"}. These are fulfilled automatically when that learner is issued the title.</p></div></div></Card>}
  </div>;
}
