"use client";
import { useEffect,useState } from "react";

type SupportTicket={id:string;subject:string;status:string};
type Notice={id:string;reason:string;startedAt:string};
type RiskFlag={id:string;studentName:string;reason:string};
type Draft={id:string;type:string;status:string;draftText:string};
type Branch={schoolId:string;schoolName:string;students:number;feeArrears:number|string};
type GroupReport={groupId:string;name:string;branches:Branch[]};
type Phase4Data={support:SupportTicket[];notice:Notice[];risk:RiskFlag[];drafts:Draft[];groupReport:GroupReport[]};
type ApiPayload={result?:{confirmationToken?:string;reply?:string};error?:string};
const emptyData:Phase4Data={support:[],notice:[],risk:[],drafts:[],groupReport:[]};

export default function Phase4Console(){
 const[data,setData]=useState<Phase4Data>(emptyData),[message,setMessage]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[emergency,setEmergency]=useState(""),[token,setToken]=useState(""),[remark,setRemark]=useState({studentId:"",termId:""}),[group,setGroup]=useState({name:"",memberSchoolIds:""}),[topic,setTopic]=useState("Lesson topic");
 async function load(){const r=await fetch("/api/phase4");if(!r.ok)return;const d=await r.json() as Partial<Phase4Data>;setData({support:Array.isArray(d.support)?d.support:[],notice:Array.isArray(d.notice)?d.notice:[],risk:Array.isArray(d.risk)?d.risk:[],drafts:Array.isArray(d.drafts)?d.drafts:[],groupReport:Array.isArray(d.groupReport)?d.groupReport:[]});}
 useEffect(()=>{void load()},[]);
 async function post(payload:Record<string,unknown>){const r=await fetch("/api/phase4",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json() as ApiPayload;setMessage(d.error||d.result?.reply||(r.ok?"Saved.":"Request failed."));if(r.ok){if(payload.action==="emergencyPrepare")setToken(d.result?.confirmationToken||"");if(payload.action==="emergencyConfirm")setToken("");await load();}return d;}
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><header><p className="text-sm font-medium">SukuuNova</p><h1 className="text-3xl font-semibold">Phase 4</h1><p className="text-slate-600">Support, early-warning insights, controlled AI drafts, multi-branch ownership, and emergency communications.</p></header>{message&&<div className="rounded-lg border p-3 text-sm">{message}</div>}
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h2 className="font-semibold">Support ticket</h2><input className="mt-3 w-full rounded-md border px-3 py-2" placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)}/><textarea className="mt-2 min-h-24 w-full rounded-md border px-3 py-2" placeholder="Describe the issue" value={body} onChange={e=>setBody(e.target.value)}/><button className="mt-2 rounded-md bg-black px-4 py-2 text-white" onClick={()=>void post({action:"createTicket",subject,body})}>Raise ticket</button><div className="mt-3 space-y-2 text-sm">{data.support.slice(0,5).map(t=><div key={t.id} className="rounded bg-slate-50 p-2">{t.subject} · {t.status}</div>)}</div></div>
 <div className="rounded-xl border p-4"><h2 className="font-semibold">Early-warning flags</h2><p className="mt-1 text-xs text-slate-500">Scheduled and informational only. No automatic family message or grade change occurs.</p><div className="mt-3 space-y-2 text-sm">{data.risk.slice(0,8).map(r=><div key={r.id} className="rounded bg-slate-50 p-2"><b>{r.studentName}</b> · {r.reason}</div>)}</div></div></section>
 <section className="rounded-xl border p-4"><h2 className="font-semibold">AI-assisted drafts</h2><p className="mt-1 text-sm text-slate-600">Drafts remain <b>suggested</b> until a teacher explicitly accepts or discards them.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><div><input className="w-full rounded-md border px-3 py-2" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Lesson topic"/><button className="mt-2 rounded-md border px-3 py-2" onClick={()=>void post({action:"aiGenerate",type:"lesson_note",context:{subject:"General",topic,objectives:"Explain, demonstrate, practice",className:"Current class"}})}>Generate lesson note</button></div><div className="space-y-2"><input className="w-full rounded-md border px-3 py-2" value={remark.studentId} onChange={e=>setRemark({...remark,studentId:e.target.value})} placeholder="Student ID for report remark"/><input className="w-full rounded-md border px-3 py-2" value={remark.termId} onChange={e=>setRemark({...remark,termId:e.target.value})} placeholder="Term ID"/><button className="rounded-md border px-3 py-2" onClick={()=>void post({action:"aiGenerate",type:"report_card_remark",context:remark})}>Generate report-card remark</button></div></div><div className="mt-4 space-y-2">{data.drafts.slice(0,8).map(d=><div key={d.id} className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-medium uppercase">{d.type} · {d.status}</div><p className="mt-1 text-sm">{d.draftText}</p>{d.status==="suggested"&&<div className="mt-2 flex gap-2"><button className="rounded border px-2 py-1 text-xs" onClick={()=>void post({action:"aiAccept",draftId:d.id})}>Accept</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>void post({action:"aiDiscard",draftId:d.id})}>Discard</button></div>}</div>)}</div></section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h2 className="font-semibold">Owner multi-branch group</h2><input className="mt-3 w-full rounded-md border px-3 py-2" value={group.name} onChange={e=>setGroup({...group,name:e.target.value})} placeholder="Group name"/><input className="mt-2 w-full rounded-md border px-3 py-2" value={group.memberSchoolIds} onChange={e=>setGroup({...group,memberSchoolIds:e.target.value})} placeholder="Other branch school IDs, comma-separated"/><button className="mt-2 rounded-md border px-3 py-2" onClick={()=>void post({action:"groupCreate",name:group.name,memberSchoolIds:group.memberSchoolIds.split(",").map(x=>x.trim()).filter(Boolean)})}>Create group</button><div className="mt-3 space-y-2 text-sm">{data.groupReport.map(g=><div key={g.groupId}><b>{g.name}</b>{g.branches.map(b=><div key={b.schoolId} className="rounded bg-slate-50 p-2">{b.schoolName} · {b.students} active students · GHS {Number(b.feeArrears).toFixed(2)} outstanding</div>)}</div>)}</div></div>
 <div className="rounded-xl border border-red-200 p-4"><h2 className="font-semibold">Emergency broadcast</h2><p className="mt-1 text-sm text-red-700">Preparation only calculates recipients and creates a short-lived confirmation token. Nothing is queued until you confirm.</p><textarea className="mt-3 min-h-24 w-full rounded-md border px-3 py-2" placeholder="Emergency message" value={emergency} onChange={e=>setEmergency(e.target.value)}/><div className="mt-2 flex flex-wrap gap-2"><button className="rounded-md border px-3 py-2" onClick={()=>void post({action:"emergencyPrepare",message:emergency})}>Prepare alert</button>{token&&<button className="rounded-md bg-red-600 px-3 py-2 text-white" onClick={()=>void post({action:"emergencyConfirm",confirmationToken:token,message:emergency})}>Confirm & send</button>}</div></div></section>
 {data.notice.length>0&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Platform support access notice</h2>{data.notice.map(n=><div key={n.id} className="mt-2 rounded bg-slate-50 p-2 text-sm">Platform support accessed this account for: {n.reason} · {new Date(n.startedAt).toLocaleString()}</div>)}</section>}
 </main>;
}