"use client";

import { useEffect, useMemo, useState } from "react";
import { BellRing, CalendarClock, FileCog, Percent, ReceiptText, Save } from "lucide-react";

type School = { id: string; name: string; uniqueCode: string };
type RulesResponse = { activeStudents: number; estimate: { base: number; discountedBase: number; subtotal: number; tax: number; total: number }; rules: { billingMode: "flat" | "per_student"; currency: string; studentRate: number; flatRate: number; billingDay: number; graceDays: number; trialDays: number; minimumCharge: number; maximumCharge: number | null; active: boolean; autoGenerateInvoices: boolean; invoiceDueDays: number; taxPercent: number; discountPercent: number; invoicePrefix: string; sendBillingNotifications: boolean } };

export default function PlatformAdvancedBillingRules({ schools }: { schools: School[] }) {
  const [schoolId, setSchoolId] = useState(schools[0]?.id ?? ""), [data, setData] = useState<RulesResponse | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [draft, setDraft] = useState<RulesResponse["rules"] | null>(null);
  const selectedSchool = useMemo(() => schools.find((school) => school.id === schoolId), [schools, schoolId]);
  async function load(id: string) { if (!id) return; setBusy(true); try { const response = await fetch(`/api/platform/billing-rules?schoolId=${encodeURIComponent(id)}`, { cache: "no-store" }); if (response.ok) { const next = await response.json() as RulesResponse; setData(next); setDraft(next.rules); } } finally { setBusy(false); } }
  useEffect(() => { void load(schoolId); }, [schoolId]);
  const save = async () => { if (!draft) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/platform/billing-rules", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "save", schoolId, ...draft }) }); const result = await response.json() as { message?: string; error?: string }; setMessage(response.ok ? "Advanced billing controls saved." : (result.message ?? result.error ?? "Unable to save billing controls.")); if (response.ok) await load(schoolId); } finally { setBusy(false); } };
  if (!draft) return <section className="app-card app-panel" style={{ marginTop: 18, padding: 22 }}><strong>{schools.length ? "Choose a school to open advanced billing controls." : "No school accounts available to this operator."}</strong></section>;
  const estimated = data?.estimate.total ?? 0;
  return <section className="app-card app-panel" style={{ marginTop: 18, padding: 22 }}>
    <div className="app-card-head"><div><span className="app-eyebrow">ADVANCED BILLING RULES</span><h2>Make invoices predictable</h2><p>Set due terms, discounts, taxes, automation and invoice identity without changing the underlying subscription model.</p></div><FileCog size={20}/></div>
    <div className="platform-form-grid"><label><span>School</span><select value={schoolId} onChange={(e) => setSchoolId(e.target.value)}><option value="">Choose a school…</option>{schools.map((school) => <option key={school.id} value={school.id}>{school.name} · {school.uniqueCode}</option>)}</select></label><label><span>Invoice prefix</span><input value={draft.invoicePrefix} onChange={(e) => setDraft({ ...draft, invoicePrefix: e.target.value })}/></label><label><span>Invoice due after (days)</span><input type="number" min="0" max="90" value={draft.invoiceDueDays} onChange={(e) => setDraft({ ...draft, invoiceDueDays: Number(e.target.value) })}/></label><label><span>Billing day</span><input type="number" min="1" max="28" value={draft.billingDay} onChange={(e) => setDraft({ ...draft, billingDay: Number(e.target.value) })}/></label><label><span>Tax (%)</span><div style={{ position: "relative" }}><Percent size={13} style={{ position: "absolute", left: 11, top: 13, color: "var(--sn-muted)" }}/><input style={{ paddingLeft: 30 }} type="number" min="0" max="100" step="0.01" value={draft.taxPercent} onChange={(e) => setDraft({ ...draft, taxPercent: Number(e.target.value) })}/></div></label><label><span>Discount (%)</span><div style={{ position: "relative" }}><Percent size={13} style={{ position: "absolute", left: 11, top: 13, color: "var(--sn-muted)" }}/><input style={{ paddingLeft: 30 }} type="number" min="0" max="100" step="0.01" value={draft.discountPercent} onChange={(e) => setDraft({ ...draft, discountPercent: Number(e.target.value) })}/></div></label></div>
    <div className="platform-toggle-grid"><label><input type="checkbox" checked={draft.autoGenerateInvoices} onChange={(e) => setDraft({ ...draft, autoGenerateInvoices: e.target.checked })}/><span><strong>Auto-generate recurring invoices</strong><small>Create the configured monthly invoice automatically when the billing day arrives.</small></span></label><label><input type="checkbox" checked={draft.sendBillingNotifications} onChange={(e) => setDraft({ ...draft, sendBillingNotifications: e.target.checked })}/><span><strong>Send billing notifications</strong><small>Enable invoice and payment reminders through the school’s configured channels.</small></span></label></div>
    <div className="platform-calculation-card"><div><span className="platform-calculation-label">Current estimate</span><strong>{draft.currency === "GHS" ? "₵" : draft.currency + " "}{Number(estimated).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><small>{data?.activeStudents.toLocaleString() ?? "0"} active students · {draft.discountPercent}% discount · {draft.taxPercent}% tax</small></div><ReceiptText size={22}/></div>
    {selectedSchool && <div className="platform-rule-list"><div><strong>Billing schedule</strong><span>Bill on day {draft.billingDay} · due after {draft.invoiceDueDays} days · {draft.graceDays} grace days.</span></div><div><strong>Trial</strong><span>{draft.trialDays > 0 ? `${draft.trialDays} days from activation` : "No trial period"}.</span></div><div><strong>Notifications</strong><span>{draft.sendBillingNotifications ? "Enabled" : "Disabled"} for this school.</span></div></div>}
    {message && <div className="app-banner" style={{ marginTop: 14 }} role="status"><div><h3>{message}</h3><p>Changes are permission-checked and written to the audit trail.</p></div><BellRing size={16}/></div>}
    <button type="button" className="app-action" onClick={() => void save()} disabled={busy}><Save size={14}/><strong>{busy ? "Saving…" : "Save advanced billing rules"}</strong></button>
  </section>;
}
