"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CheckCircle2, LockKeyhole, Settings2, ShieldCheck, SlidersHorizontal, UserCog } from "lucide-react";

type Settings = Record<string, Record<string, unknown>>;
type Section = "defaults" | "security" | "lifecycle" | "messaging";
type NavItem = { id: Section; label: string; Icon: typeof Settings2 };
const NAV_ITEMS: NavItem[] = [
  { id: "defaults", label: "Network defaults", Icon: Settings2 },
  { id: "security", label: "Security", Icon: ShieldCheck },
  { id: "lifecycle", label: "School lifecycle", Icon: LockKeyhole },
  { id: "messaging", label: "Messaging defaults", Icon: SlidersHorizontal },
];
const bool = (value: unknown) => Boolean(value);

export default function PlatformControlSettingsStudio() {
  const [settings, setSettings] = useState<Settings | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [section, setSection] = useState<Section>("defaults");
  async function load() { setBusy(true); try { const response = await fetch("/api/platform/control-plane?view=settings", { cache: "no-store" }); if (response.ok) setSettings(await response.json() as Settings); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  const save = async (key: string, value: Record<string, unknown>) => { setBusy(true); setMessage(""); try { const response = await fetch("/api/platform/control-plane", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "savePlatformSettings", key, value }) }); const data = await response.json() as { message?: string; error?: string }; setMessage(response.ok ? "Platform setting saved successfully." : (data.message ?? data.error ?? "Unable to save setting.")); if (response.ok) await load(); } finally { setBusy(false); } };
  if (!settings) return <div className="app-card app-panel platform-empty"><strong>Loading platform controls…</strong><span>Fetching the current governed defaults.</span></div>;
  const current = settings[`platform.${section}`] ?? {};
  return <div className="platform-settings-v2">
    {message && <div className="app-banner" role="status"><div><h3>{message}</h3><p>Configuration changes are permission-gated and audited.</p></div><span className="app-pill">Audited</span></div>}
    <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", marginBottom: 2 }}><div className="platform-settings-v2-nav" style={{ flex: 1, margin: 0 }}>{NAV_ITEMS.map(({ id, label, Icon }) => <button type="button" key={id} className={section === id ? "is-active" : ""} onClick={() => setSection(id)}><Icon size={16}/><span>{label}</span></button>)}</div><Link href="/account/settings" className="app-action"><UserCog size={14}/><strong>My account settings</strong></Link></div>
    {section === "defaults" && <section className="app-card app-panel"><div className="app-card-head"><div><span className="app-eyebrow">NETWORK DEFAULTS</span><h2>How new schools start</h2><p>These defaults are templates for provisioning, not hidden magic. A school can override its billing and operational settings later.</p></div><Settings2 size={20}/></div><div className="platform-form-grid"><label><span>Default currency</span><input value={String(current.currency ?? "GHS")} onChange={(e) => setSettings({ ...settings, "platform.defaults": { ...current, currency: e.target.value.toUpperCase() } })}/></label><label><span>Default timezone</span><input value={String(current.timezone ?? "Africa/Accra")} onChange={(e) => setSettings({ ...settings, "platform.defaults": { ...current, timezone: e.target.value } })}/></label><label><span>Locale</span><input value={String(current.locale ?? "en-GH")} onChange={(e) => setSettings({ ...settings, "platform.defaults": { ...current, locale: e.target.value } })}/></label><label><span>Default billing model</span><select value={String(current.defaultBillingMode ?? "flat")} onChange={(e) => setSettings({ ...settings, "platform.defaults": { ...current, defaultBillingMode: e.target.value } })}><option value="flat">Flat rate</option><option value="per_student">Per student</option></select></label><label><span>Default grace period (days)</span><input type="number" min="0" max="90" value={Number(current.defaultGraceDays ?? 7)} onChange={(e) => setSettings({ ...settings, "platform.defaults": { ...current, defaultGraceDays: Number(e.target.value) } })}/></label></div><button type="button" className="app-action" onClick={() => void save("platform.defaults", settings["platform.defaults"] ?? {})} disabled={busy}><CheckCircle2 size={14}/><strong>Save network defaults</strong></button></section>}
    {section === "security" && <section className="app-card app-panel"><div className="app-card-head"><div><span className="app-eyebrow">SECURITY POLICY</span><h2>Platform access rules</h2><p>Centralize the rules that govern administrator sessions and sensitive support access.</p></div><ShieldCheck size={20}/></div><div className="platform-toggle-grid"><label><input type="checkbox" checked={bool(current.requirePasswordChange)} onChange={(e) => setSettings({ ...settings, "platform.security": { ...current, requirePasswordChange: e.target.checked } })}/><span><strong>Force new school owners to change their password</strong><small>Recommended for every provisioned owner account.</small></span></label><label><input type="checkbox" checked={bool(current.enableMfa)} onChange={(e) => setSettings({ ...settings, "platform.security": { ...current, enableMfa: e.target.checked } })}/><span><strong>Enable MFA policy</strong><small>Turns on the platform-wide MFA requirement when supported by the authentication flow.</small></span></label><label><input type="checkbox" checked={bool(current.allowImpersonation)} onChange={(e) => setSettings({ ...settings, "platform.security": { ...current, allowImpersonation: e.target.checked } })}/><span><strong>Allow audited school impersonation</strong><small>Keep support access explicit, time-limited and auditable.</small></span></label></div><div className="platform-form-grid"><label><span>Maximum admin session (hours)</span><input type="number" min="1" max="168" value={Number(current.sessionHours ?? 12)} onChange={(e) => setSettings({ ...settings, "platform.security": { ...current, sessionHours: Number(e.target.value) } })}/></label><label><span>Audit retention (days)</span><input type="number" min="30" max="3650" value={Number(current.auditRetentionDays ?? 730)} onChange={(e) => setSettings({ ...settings, "platform.security": { ...current, auditRetentionDays: Number(e.target.value) } })}/></label></div><button type="button" className="app-action" onClick={() => void save("platform.security", settings["platform.security"] ?? {})} disabled={busy}><ShieldCheck size={14}/><strong>Save security policy</strong></button></section>}
    {section === "lifecycle" && <section className="app-card app-panel"><div className="app-card-head"><div><span className="app-eyebrow">TENANT LIFECYCLE</span><h2>How school accounts can be controlled</h2><p>Keep lifecycle actions deliberate and protect destructive operations with a clear policy.</p></div><LockKeyhole size={20}/></div><div className="platform-toggle-grid"><label><input type="checkbox" checked={bool(current.allowLock)} onChange={(e) => setSettings({ ...settings, "platform.lifecycle": { ...current, allowLock: e.target.checked } })}/><span><strong>Allow lock / restricted mode</strong><small>Freeze school access while preserving tenant data.</small></span></label><label><input type="checkbox" checked={bool(current.allowSuspend)} onChange={(e) => setSettings({ ...settings, "platform.lifecycle": { ...current, allowSuspend: e.target.checked } })}/><span><strong>Allow suspension</strong><small>Stop operational access without deleting records.</small></span></label><label><input type="checkbox" checked={bool(current.allowArchive)} onChange={(e) => setSettings({ ...settings, "platform.lifecycle": { ...current, allowArchive: e.target.checked } })}/><span><strong>Allow archive</strong><small>Remove a tenant from normal operations while keeping history.</small></span></label><label><input type="checkbox" checked={bool(current.allowDelete)} onChange={(e) => setSettings({ ...settings, "platform.lifecycle": { ...current, allowDelete: e.target.checked } })}/><span><strong>Allow delete workflow</strong><small>Keep this disabled until your retention and backup policy is ready.</small></span></label></div><label className="platform-field-wide"><span>Delete confirmation phrase</span><input value={String(current.requireDeletePhrase ?? "DELETE SCHOOL")} onChange={(e) => setSettings({ ...settings, "platform.lifecycle": { ...current, requireDeletePhrase: e.target.value } })}/></label><button type="button" className="app-action" onClick={() => void save("platform.lifecycle", settings["platform.lifecycle"] ?? {})} disabled={busy}><LockKeyhole size={14}/><strong>Save lifecycle policy</strong></button></section>}
    {section === "messaging" && <section className="app-card app-panel"><div className="app-card-head"><div><span className="app-eyebrow">MESSAGING DEFAULTS</span><h2>SMS & WhatsApp operating rules</h2><p>Provider purchasing and school resale are intentionally separated from subscription billing.</p></div><SlidersHorizontal size={20}/></div><div className="platform-toggle-grid"><label><input type="checkbox" checked={bool(current.enableSms)} onChange={(e) => setSettings({ ...settings, "platform.messaging": { ...current, enableSms: e.target.checked } })}/><span><strong>Enable SMS service</strong><small>Allow schools to receive allocated SMS capacity.</small></span></label><label><input type="checkbox" checked={bool(current.enableWhatsapp)} onChange={(e) => setSettings({ ...settings, "platform.messaging": { ...current, enableWhatsapp: e.target.checked } })}/><span><strong>Enable WhatsApp service</strong><small>Allow schools to receive allocated WhatsApp capacity.</small></span></label></div><div className="platform-form-grid"><label><span>Service currency</span><input value={String(current.currency ?? "GHS")} onChange={(e) => setSettings({ ...settings, "platform.messaging": { ...current, currency: e.target.value.toUpperCase() } })}/></label><label><span>Default low balance threshold</span><input type="number" min="0" value={Number(current.lowBalanceThreshold ?? 50)} onChange={(e) => setSettings({ ...settings, "platform.messaging": { ...current, lowBalanceThreshold: Number(e.target.value) } })}/></label></div><button type="button" className="app-action" onClick={() => void save("platform.messaging", settings["platform.messaging"] ?? {})} disabled={busy}><SlidersHorizontal size={14}/><strong>Save messaging defaults</strong></button></section>}
  </div>;
}
