"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Clock3, ExternalLink, Filter, RefreshCw, Search, ShieldCheck } from "lucide-react";

type AuditEvent={id:string;actorId:string;action:string;targetSchoolId?:string|null;targetEntity?:string|null;createdAt:string;meta?:unknown};
type Payload={events:AuditEvent[]};

export default function PlatformAuditConsole(){
  const [events,setEvents]=useState<AuditEvent[]>([]),[query,setQuery]=useState(""),[action,setAction]=useState("all"),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  async function load(){setLoading(true);try{const response=await fetch("/api/platform/admin?view=audit&limit=200",{cache:"no-store"});const data=await response.json() as Payload & {error?:string;message?:string};if(!response.ok){setMessage(data.message??data.error??"Unable to load audit history.");return;}setEvents(data.events??[]);setMessage("");}finally{setLoading(false);}}
  useEffect(()=>{void load()},[]);
  const actionOptions=useMemo(()=>Array.from(new Set(events.map((event)=>event.action))).sort(),[events]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return events.filter((event)=>action==="all"||event.action===action).filter((event)=>!q||event.action.toLowerCase().includes(q)||event.actorId.toLowerCase().includes(q)||String(event.targetEntity??"").toLowerCase().includes(q)||String(event.targetSchoolId??"").toLowerCase().includes(q));},[action,events,query]);
  const todayCount=useMemo(()=>events.filter((event)=>new Date(event.createdAt).toDateString()===new Date().toDateString()).length,[events]);
  const sensitiveCount=useMemo(()=>events.filter((event)=>/imperson|delete|suspend|permission|password|role|setting/i.test(event.action)).length,[events]);
  return <div className="audit-page-stack">
    <section className="platform-page-header"><div><span className="platform-eyebrow">Governance & evidence</span><h2>Audit Log</h2><p>Search the control plane by action, operator, school or target. Audit is the evidence layer for every sensitive platform decision.</p></div><button type="button" className="app-pill" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> Refresh</button></section>
    {message&&<div className="app-banner" role="status"><div><h3>{message}</h3><p>The audit reader is permission-scoped and read-only from this surface.</p></div></div>}
    <div className="app-grid kpis platform-kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Events loaded</span><span className="app-kpi-icon"><ShieldCheck size={17}/></span></div><div className="app-kpi-value">{events.length.toLocaleString()}</div><div className="app-kpi-meta">Latest 200 platform events</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Today</span><span className="app-kpi-icon"><Clock3 size={17}/></span></div><div className="app-kpi-value">{todayCount}</div><div className="app-kpi-meta">Events recorded today</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Sensitive</span><span className="app-kpi-icon"><Filter size={17}/></span></div><div className="app-kpi-value">{sensitiveCount}</div><div className="app-kpi-meta">Access, role, settings and lifecycle actions</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Search results</span><span className="app-kpi-icon"><Search size={17}/></span></div><div className="app-kpi-value">{visible.length}</div><div className="app-kpi-meta">Matching the current filter</div></div></div>
    <section className="app-card app-panel audit-controls"><div className="audit-search"><Search size={15}/><input aria-label="Search audit events" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search action, operator, school or target"/></div><div className="audit-filter"><span>Action</span><select aria-label="Filter by action" value={action} onChange={(event)=>setAction(event.target.value)}><option value="all">All actions</option>{actionOptions.map((option)=><option key={option} value={option}>{option}</option>)}</select></div><Link className="app-pill" href="/platform/search">Cross-system search</Link></section>
    <section className="app-card app-panel audit-table"><div className="audit-table-head"><span>Event</span><span>Operator</span><span>Target</span><span>Timestamp</span><span></span></div>{visible.map((event)=><div className="audit-row" key={event.id}><div><b>{event.action}</b><small>{event.id}</small></div><div><span>{event.actorId}</span></div><div><span>{event.targetEntity ?? "Platform"}</span><small>{event.targetSchoolId ? `School ${event.targetSchoolId}` : "Network-wide"}</small></div><div><span>{new Date(event.createdAt).toLocaleString()}</span></div><div>{event.targetSchoolId?<Link aria-label="Open school" className="app-icon-button audit-open" href={`/platform/schools/${event.targetSchoolId}`}><ExternalLink size={13}/></Link>:null}</div></div>)}{visible.length===0&&<div className="platform-empty">No audit events match the current search.</div>}</section>
    <style jsx global>{`\n      .audit-page-stack{display:grid;gap:16px;margin-top:22px}.audit-controls{display:grid;grid-template-columns:minmax(260px,1fr) auto auto;gap:10px;align-items:center;padding:12px}.audit-search{display:flex;align-items:center;gap:8px;height:38px;padding:0 10px;border:1px solid #dbe3ec;border-radius:10px;background:#fff;color:#7d8c9b}.audit-search input{border:0;outline:0;background:transparent;min-width:0;flex:1;font:inherit;font-size:10px;color:#30465a}.audit-filter{display:flex;align-items:center;gap:6px}.audit-filter span{font-size:8px;font-weight:850;color:#788797;text-transform:uppercase;letter-spacing:.07em}.audit-filter select{height:38px;border:1px solid #dbe3ec;border-radius:9px;background:#fff;color:#536577;font:inherit;font-size:9px;padding:0 9px;max-width:260px}.audit-table{overflow:hidden}.audit-table-head,.audit-row{display:grid;grid-template-columns:minmax(230px,1.45fr) minmax(130px,.8fr) minmax(170px,1fr) 170px 42px;gap:12px;align-items:center}.audit-table-head{padding:10px 18px;background:#f7f9fb;border-bottom:1px solid #e2e8ee;color:#738193;font-size:7.5px;font-weight:900;text-transform:uppercase;letter-spacing:.1em}.audit-row{padding:12px 18px;border-bottom:1px solid #edf1f5;min-height:62px}.audit-row:last-child{border-bottom:0}.audit-row:hover{background:#fbfcfe}.audit-row b,.audit-row span{display:block;font-size:9.5px;color:#2d4154;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.audit-row small{display:block;margin-top:3px;font-size:7.8px;color:#8794a2;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.audit-open{width:30px;height:30px}.audit-open:hover{transform:none}@media(max-width:900px){.audit-controls{grid-template-columns:1fr}.audit-table-head{display:none}.audit-row{grid-template-columns:minmax(0,1fr) auto;gap:7px;padding:12px 14px}.audit-row>div:nth-child(2),.audit-row>div:nth-child(3),.audit-row>div:nth-child(4){grid-column:1/-1}.audit-row>div:nth-child(5){grid-column:2;grid-row:1}}\n    `}</style>
  </div>;
}
