"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, GraduationCap, School, Users } from "lucide-react";
import { AppShell } from "@/components/AppShell";

type Section="overview"|"schools"|"plans"|"billing"|"analytics"|"support"|"admins"|"audit"|"health"|"settings";
type Plan={id:string;name:string;price:number|string;featureFlags?:string[]};
type SchoolRecord={id:string;name:string;uniqueCode:string;status:string;createdAt:string;studentCount:number;userCount:number;classCount:number;attendanceToday:number;invoices:number;unpaidInvoices:number;collected:number;subscriptionPlan?:Plan|null};
type Overview={totals:{schools:number;activeSchools:number;suspendedSchools:number;students:number;users:number;classes:number;invoices:number;unpaidInvoices:number;collected:number};schools:SchoolRecord[]};
type Worker={id:string;name:string;email:string;role:string;status:string;permissions:string[]};
type AdminData={admins:Worker[];permissions:string[]};
type AuditEvent={id:string;actorId:string;action:string;targetSchoolId?:string|null;targetEntity?:string|null;createdAt:string};
type AuditData={events:AuditEvent[]};
type Health={database:string;api:string;nextjs:string;latencyMs:number;checkedAt:string};
type SchoolSnapshot={school:{id:string;name:string;uniqueCode:string;status:string;createdAt:string;subscriptionPlan?:Plan|null};students:Array<{id:string;name:string;admissionNo:string;classId:string|null;status:string}>;users:Array<{id:string;name:string;email:string|null;phone:string|null;status:string;createdAt:string}>;classes:Array<{id:string;name:string;level:string|null;classTeacherId:string|null}>;subjects:Array<{id:string;name:string}>;attendanceToday:Array<{id:string;studentId:string;type:string;recordedAt:string}>;recentAudit:AuditEvent[]};
type Role="platform_admin"|"support_admin"|"billing_admin"|"analytics_admin";
const permissionGroups:Record<string,string[]>={Governance:["schools.view","schools.manage","schools.suspend","schools.impersonate","settings.manage"],Finance:["billing.view","billing.manage","plans.manage"],Insight:["analytics.view","audit.view"],Operations:["support.view","support.manage"],Security:["admins.view","admins.manage","security.manage"]};
const titles:Record<Section,[string,string]>={overview:["Control Center","See the health, commercial position and operating footprint of the full SukuuNova network."],schools:["School Network","Every school account, plan, status and support entry point in one place."],plans:["Plans & Entitlements","Design what schools can use, what they pay, and what happens when a plan changes."],billing:["Platform Billing","Monitor invoices, payments, arrears and the commercial state of every school."],analytics:["Network Analytics","Compare adoption, attendance, people and operational signals across schools."],support:["Support & Audited Access","Resolve cases and enter an explicitly audited school support session."],admins:["Workers & Permissions","Create your internal platform workers and grant exactly the capabilities they need."],audit:["Audit & Security","Review sensitive platform actions and investigate account activity."],health:["System Health","Watch database, API and application health before schools report a problem."],settings:["Platform Settings","Network-wide operating rules, security controls and defaults."]};
function Card({children,wide=false}:{children:React.ReactNode;wide?:boolean}){return <section className="app-card app-panel" style={{gridColumn:wide?"1 / -1":undefined}}>{children}</section>}
function Header({title,sub}:{title:string;sub:string}){return <div className="app-card-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
export default function PlatformAdminWorkspace({section}:{section:Section}){
 const [overview,setOverview]=useState<Overview|null>(null),[adminData,setAdminData]=useState<AdminData|null>(null),[auditData,setAuditData]=useState<AuditData|null>(null),[health,setHealth]=useState<Health|null>(null),[school,setSchool]=useState<SchoolSnapshot|null>(null),[selectedSchool,setSelectedSchool]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[worker,setWorker]=useState<{name:string;email:string;password:string;role:Role;permissions:string[]}>({name:"",email:"",password:"",role:"support_admin",permissions:["support.view","support.manage"]});
 const load=useCallback(async()=>{setLoading(true);try{if(["overview","schools","analytics","billing"].includes(section)){const r=await fetch("/api/platform/admin?view=overview");if(r.ok)setOverview(await r.json() as Overview);}else if(section==="admins"){const r=await fetch("/api/platform/admin?view=admins");if(r.ok)setAdminData(await r.json() as AdminData);}else if(section==="audit"){const r=await fetch("/api/platform/admin?view=audit&limit=150");if(r.ok)setAuditData(await r.json() as AuditData);}else if(section==="health"){const r=await fetch("/api/platform/admin?view=health");if(r.ok)setHealth(await r.json() as Health);}}finally{setLoading(false)}},[section]);
 useEffect(()=>{void load()},[load]);
 const doPost=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch("/api/platform/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {error?:string};setMessage(d.error||"Operation completed and audited.");if(r.ok)void load();return d},[load]);
 const getSchool=useCallback(async(id:string)=>{setSelectedSchool(id);const r=await fetch(`/api/platform/admin?view=school&schoolId=${encodeURIComponent(id)}`);setSchool(r.ok?await r.json() as SchoolSnapshot:null)},[]);
 const schools=overview?.schools??[];const totals=overview?.totals;const planCards=useMemo(()=>[{name:"Foundation",price:"Free",desc:"Core school workspace and foundational operations"},{name:"Growth",price:"₵250 / month",desc:"Advanced operations, finance and school-life modules"},{name:"Enterprise",price:"₵500 / month",desc:"Full platform capability with advanced safeguards"}],[]);const permissionOptions=Object.values(permissionGroups).flat();
 return <AppShell universe="platform" title={titles[section][0]} subtitle={titles[section][1]} active={section==="overview"?"Overview":section==="schools"?"Schools":section==="plans"?"Plans & Entitlements":section==="billing"?"Platform Billing":section==="admins"?"Workers & Permissions":section==="audit"?"Audit Log":section==="health"?"System Health":section==="support"?"Support":"Overview"}>
 {message&&<div className="app-banner"><div><h3>{message}</h3><p>Platform control action recorded</p></div><span className="app-pill">Audited</span></div>}{loading&&<div className="app-card app-panel"><p>Loading platform data…</p></div>}
 {!loading&&section==="overview"&&<><div className="app-grid kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Schools</span><span className="app-kpi-icon" aria-hidden="true"><School size={17} strokeWidth={2.1}/></span></div><div className="app-kpi-value">{totals?.schools??0}</div><div className="app-kpi-meta">{totals?.activeSchools??0} active · {totals?.suspendedSchools??0} suspended</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Students</span><span className="app-kpi-icon" aria-hidden="true"><GraduationCap size={17} strokeWidth={2.1}/></span></div><div className="app-kpi-value">{totals?.students??0}</div><div className="app-kpi-meta">Across school accounts</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Users</span><span className="app-kpi-icon" aria-hidden="true"><Users size={17} strokeWidth={2.1}/></span></div><div className="app-kpi-value">{totals?.users??0}</div><div className="app-kpi-meta">Staff, teachers and operators</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Collected</span><span className="app-kpi-icon" aria-hidden="true">₵</span></div><div className="app-kpi-value">₵{Number(totals?.collected??0).toLocaleString()}</div><div className="app-kpi-meta">Recorded platform payments</div></div></div><div className="app-dashboard-grid"><Card><Header title="Schools needing attention" sub="Suspensions and unpaid commercial accounts."/>{schools.filter(s=>s.status!=="active"||s.unpaidInvoices>0).slice(0,8).map(s=><div className="app-list-row" key={s.id}><span className="app-list-icon" aria-hidden="true"><AlertCircle size={16} strokeWidth={2.1}/></span><div><b>{s.name}</b><span>{s.uniqueCode} · {s.status} · {s.subscriptionPlan?.name||"No plan"}</span></div><button className="app-pill" onClick={()=>void getSchool(s.id)}>Inspect</button></div>)}</Card><Card><Header title="Network posture" sub="Commercial and operational footprint."/><div className="app-list-row"><div><b>{totals?.classes??0}</b><span>Classes tracked</span></div></div><div className="app-list-row"><div><b>{totals?.invoices??0}</b><span>Platform invoices</span></div></div><div className="app-list-row"><div><b>{totals?.unpaidInvoices??0}</b><span>Invoices not fully paid</span></div></div></Card></div></>}
 {!loading&&section==="schools"&&<div className="app-dashboard-grid"><Card wide><Header title="School accounts" sub="Inspect the complete school footprint from one control surface."/>{schools.map(s=><div className="app-list-row" key={s.id}><span className="app-list-icon" aria-hidden="true"><School size={16} strokeWidth={2.1}/></span><div><b>{s.name}</b><span>{s.uniqueCode} · {s.status} · {s.subscriptionPlan?.name||"No plan"} · {s.studentCount} students · {s.userCount} users</span></div><button className="app-action" onClick={()=>void getSchool(s.id)}><strong>Inspect</strong>School</button><button className="app-pill" onClick={async()=>{await fetch("/api/platform/phase4",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"suspendSchool",schoolId:s.id,suspended:s.status!=="suspended"})});await load()}}>{s.status==="suspended"?"Reactivate":"Suspend"}</button></div>)}</Card>{school&&<Card wide><Header title={school.school.name} sub={`${school.school.uniqueCode} · ${school.school.status} · ${school.school.subscriptionPlan?.name||"No plan"}`}/><div className="app-dashboard-grid"><div><div className="app-list-row"><div><b>{school.students.length}</b><span>Students in inspection view</span></div></div><div className="app-list-row"><div><b>{school.users.length}</b><span>Accounts in inspection view</span></div></div><div className="app-list-row"><div><b>{school.classes.length}</b><span>Classes</span></div></div><div className="app-list-row"><div><b>{school.subjects.length}</b><span>Subjects</span></div></div><div className="app-list-row"><div><b>{school.attendanceToday.length}</b><span>Attendance events today</span></div></div></div><div><h3>Recent school users</h3>{school.users.slice(0,10).map(u=><div className="app-list-row" key={u.id}><div><b>{u.name}</b><span>{u.email||u.phone||"No contact"} · {u.status}</span></div></div>)}</div></div></Card>}</div>}
 {!loading&&section==="plans"&&<div className="app-dashboard-grid">{planCards.map(p=><Card key={p.name}><Header title={p.name} sub={p.desc}/><div className="app-kpi-value" style={{fontSize:28,margin:"18px 0"}}>{p.price}</div><div className="app-list-row"><div><b>Entitlements</b><span>Feature-gated school workspace</span></div></div><Link className="app-action" href="/platform/billing"><strong>Open billing</strong>and assign plan</Link></Card>)}<Card wide><Header title="Lifecycle policy" sub="Separate subscription, billing and access state so administrators can make deliberate decisions."/><p style={{color:"#a9c1c2",lineHeight:1.6}}>A school can be assigned a plan, invoiced, reconciled, suspended for platform access, or reactivated without deleting its operational history.</p></Card></div>}
 {!loading&&section==="billing"&&<Card wide><Header title="Commercial network" sub="Every school’s subscription and invoice posture."/>{schools.map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.subscriptionPlan?.name||"No plan"} · {s.unpaidInvoices} unpaid · ₵{Number(s.collected||0).toLocaleString()} collected</span></div><button className="app-action" onClick={async()=>{const r=await fetch(`/api/platform/phase4?view=billing&schoolId=${encodeURIComponent(s.id)}`);if(r.ok){const d=await r.json() as {invoices?:unknown[];payments?:unknown[]};setMessage(`${d.invoices?.length??0} invoices · ${d.payments?.length??0} payments loaded for ${s.name}.`)}}}><strong>Review</strong>billing</button></div>)}</Card>}
 {!loading&&section==="analytics"&&<div className="app-dashboard-grid"><Card><Header title="School adoption" sub="People and operational footprint by school."/>{schools.slice(0,20).map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.studentCount} students · {s.userCount} users · {s.classCount} classes</span></div><span className="app-pill">{s.status}</span></div>)}</Card><Card><Header title="Attendance pulse" sub="Recorded student check-ins today."/>{schools.slice(0,20).map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.attendanceToday} recorded check-ins</span></div></div>)}</Card></div>}
 {!loading&&section==="support"&&<div className="app-dashboard-grid"><Card><Header title="Support cases" sub="Load a school’s support queue."/><select value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)} style={{width:"100%"}}><option value="">Choose school…</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="app-action" style={{marginTop:10}} onClick={async()=>{if(!selectedSchool)return;const r=await fetch(`/api/platform/admin?view=support&schoolId=${selectedSchool}`);if(r.ok){const d=await r.json() as {tickets?:unknown[]};setMessage(`${d.tickets?.length??0} support cases loaded.`)}}}><strong>Load</strong>cases</button></Card><Card><Header title="Audited access" sub="Time-limited support sessions are recorded before entry."/><Link className="app-action" href="/platform/schools"><strong>Go to school network</strong>select a school for support access</Link></Card></div>}
 {!loading&&section==="admins"&&<div className="app-dashboard-grid"><Card><Header title="Create platform worker" sub="Create delegated operators with narrowly scoped capabilities."/><div style={{display:"grid",gap:8}}><input placeholder="Full name" value={worker.name} onChange={e=>setWorker({...worker,name:e.target.value})}/><input placeholder="Email" value={worker.email} onChange={e=>setWorker({...worker,email:e.target.value})}/><input placeholder="Temporary password (12+ characters)" type="password" value={worker.password} onChange={e=>setWorker({...worker,password:e.target.value})}/><select value={worker.role} onChange={e=>setWorker({...worker,role:e.target.value as Role})}><option value="platform_admin">Platform Admin</option><option value="support_admin">Support Admin</option><option value="billing_admin">Billing Admin</option><option value="analytics_admin">Analytics Admin</option></select>{permissionOptions.map(p=><label key={p} style={{display:"block",margin:"6px 0"}}><input type="checkbox" checked={worker.permissions.includes(p)} onChange={e=>setWorker({...worker,permissions:e.target.checked?[...worker.permissions,p]:worker.permissions.filter(x=>x!==p)})}/> {p}</label>)}<button className="app-action" onClick={()=>void doPost({action:"createWorker",...worker})}><strong>Create worker</strong>Grant selected permissions</button><Link className="app-pill" href="/platform/forgot-password">Password recovery</Link></div></Card><Card><Header title="Current workers" sub="Suspend or reactivate internal platform operators."/>{(adminData?.admins??[]).map(a=><div className="app-list-row" key={a.id}><div><b>{a.name}</b><span>{a.email} · {a.role} · {a.status}</span></div><button className="app-pill" onClick={()=>void doPost({action:"updateWorker",adminId:a.id,status:a.status==="active"?"suspended":"active",permissions:a.permissions})}>{a.status==="active"?"Suspend":"Reactivate"}</button></div>)}</Card></div>}
 {!loading&&section==="audit"&&<Card wide><Header title="Platform audit trail" sub="Sensitive operations are reviewable by actor, target and time."/>{(auditData?.events??[]).map(e=><div className="app-list-row" key={e.id}><div><b>{e.action}</b><span>{e.actorId} · {e.targetSchoolId||e.targetEntity||"Platform"} · {new Date(e.createdAt).toLocaleString()}</span></div></div>)}</Card>}
 {!loading&&section==="health"&&<div className="app-grid kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Database</span></div><div className="app-kpi-value">{health?.database??"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">API</span></div><div className="app-kpi-value">{health?.api??"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Next.js</span></div><div className="app-kpi-value">{health?.nextjs??"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">DB latency</span></div><div className="app-kpi-value">{health?.latencyMs??"—"} ms</div></div></div>}
 {!loading&&section==="settings"&&<div className="app-dashboard-grid"><Card><Header title="Privilege model" sub="Platform control follows least privilege with a Super Admin at the top."/><div className="app-list-row"><div><b>Super Admin</b><span>All schools, billing, workers, security and platform controls.</span></div></div><div className="app-list-row"><div><b>Platform Admin</b><span>School, billing, analytics and support operations.</span></div></div><div className="app-list-row"><div><b>Support Admin</b><span>Support workflows and audited school access.</span></div></div></Card><Card><Header title="Account recovery" sub="Protect administrator continuity without exposing password hashes."/><Link className="app-action" href="/platform/forgot-password"><strong>Platform password recovery</strong>Issue a short-lived reset token</Link></Card></div>}
 </AppShell>;
}
