"use client";
import { useEffect,useState } from "react";

const empty={uniqueCode:"",schoolName:"",ownerName:"",ownerEmail:"",ownerPassword:""};
export default function PlatformConsole(){
 const[schools,setSchools]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[form,setForm]=useState(empty),[q,setQ]=useState(""),[results,setResults]=useState<any[]>([]),[message,setMessage]=useState(""),[selectedPlan,setSelectedPlan]=useState<Record<string,string>>({}),[imp,setImp]=useState({schoolId:"",userId:"",reason:""}),[supportSchool,setSupportSchool]=useState(""),[tickets,setTickets]=useState<any[]>([]),[ticketBody,setTicketBody]=useState("");
 async function load(){const[s,p]=await Promise.all([fetch("/api/platform/phase4?view=schools"),fetch("/api/platform/phase4?view=plans")]);if(s.ok)setSchools((await s.json()).schools||[]);if(p.ok)setPlans((await p.json()).plans||[])}
 useEffect(()=>{void load()},[]);
 async function post(payload:any){const r=await fetch("/api/platform/phase4",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setMessage(d?.error||d?.result?.message||(r.ok?"Saved.":"Request failed."));if(r.ok)await load();return d}
 return <main className="mx-auto max-w-7xl space-y-6 p-6"><header><p className="text-sm font-medium">SukuuNova</p><h1 className="text-3xl font-semibold">Super-admin console</h1><p className="text-slate-600">Run schools, subscriptions, investigation, support, and audited support access without bypassing tenant controls.</p></header>{message&&<div className="rounded-lg border p-3 text-sm">{message}</div>}
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h2 className="font-semibold">Create school</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{([['uniqueCode','School code'],['schoolName','School name'],['ownerName','Owner name'],['ownerEmail','Owner email'],['ownerPassword','Owner password']] as const).map(([k,label])=><input key={k} type={k==='ownerPassword'?'password':k==='ownerEmail'?'email':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={label} className="rounded-md border px-3 py-2"/> )}</div><button className="mt-3 rounded-md bg-black px-4 py-2 text-white" onClick={async()=>{await post({action:"createSchool",...form});setForm(empty)}}>Create school</button></div>
 <div className="rounded-xl border p-4"><h2 className="font-semibold">Cross-school investigation</h2><form className="mt-3 flex gap-2" onSubmit={async e=>{e.preventDefault();const d=await post({action:"search",q});setResults(d.results||[])}}><input value={q} onChange={e=>setQ(e.target.value)} className="min-w-0 flex-1 rounded-md border px-3 py-2" placeholder="Student, staff, admission number…"/><button className="rounded-md bg-black px-4 py-2 text-white">Search</button></form><div className="mt-3 space-y-2 text-sm">{results.map((r,i)=><div key={i} className="rounded-lg bg-slate-50 p-3"><b>{r.school?.name||r.schoolId}</b><div className="text-xs text-slate-600">Students: {(r.students||[]).map((x:any)=>`${x.name} (${x.id})`).join(", ")||"none"}</div><div className="text-xs text-slate-600">Users: {(r.users||[]).map((x:any)=>`${x.name} (${x.id})`).join(", ")||"none"}</div></div>)}</div></div></section>
 <section className="rounded-xl border p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Schools & feature plans</h2><span className="text-xs text-slate-500">Foundation / Growth / Enterprise</span></div><div className="mt-3 space-y-3">{schools.map(s=>{const id=s.id||s.schoolId;return <div key={id} className="grid gap-3 rounded-lg bg-slate-50 p-3 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="font-medium">{s.name||s.uniqueCode}</div><div className="text-xs text-slate-500">{s.uniqueCode} · {s.status} · {s.subscriptionPlan?.name||"No plan"}</div></div><div className="flex gap-2"><select value={selectedPlan[id]||""} onChange={e=>setSelectedPlan({...selectedPlan,[id]:e.target.value})} className="rounded-md border bg-white px-2 py-1.5 text-sm"><option value="">Select plan…</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!selectedPlan[id]} className="rounded-md border bg-white px-3 py-1.5 text-sm disabled:opacity-40" onClick={()=>post({action:"assignPlan",schoolId:id,planId:selectedPlan[id]})}>Assign</button></div><button className="rounded-md border bg-white px-3 py-1.5 text-sm" onClick={()=>post({action:"suspendSchool",schoolId:id,suspended:s.status!=="suspended"})}>{s.status==="suspended"?"Reactivate":"Suspend"}</button></div>})}</div></section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h2 className="font-semibold">Audited impersonation</h2><div className="mt-3 grid gap-2"><input value={imp.schoolId} onChange={e=>setImp({...imp,schoolId:e.target.value})} placeholder="School ID" className="rounded-md border px-3 py-2"/><input value={imp.userId} onChange={e=>setImp({...imp,userId:e.target.value})} placeholder="User ID" className="rounded-md border px-3 py-2"/><textarea value={imp.reason} onChange={e=>setImp({...imp,reason:e.target.value})} placeholder="Reason for support access" className="min-h-24 rounded-md border px-3 py-2"/><button className="rounded-md border px-4 py-2" onClick={()=>post({action:"impersonate",...imp})}>Start 30-minute audited session</button></div></div>
 <div className="rounded-xl border p-4"><h2 className="font-semibold">Support tickets</h2><div className="mt-3 flex gap-2"><input value={supportSchool} onChange={e=>setSupportSchool(e.target.value)} placeholder="School ID" className="min-w-0 flex-1 rounded-md border px-3 py-2"/><button className="rounded-md border px-3 py-2" onClick={async()=>{const r=await fetch(`/api/platform/phase4?view=support&schoolId=${encodeURIComponent(supportSchool)}`);if(r.ok)setTickets((await r.json()).tickets||[])}}>Load</button></div><textarea value={ticketBody} onChange={e=>setTicketBody(e.target.value)} placeholder="Reply when updating a selected ticket" className="mt-2 min-h-20 w-full rounded-md border px-3 py-2"/>{tickets.slice(0,8).map(t=><div key={t.id} className="mt-2 rounded bg-slate-50 p-2 text-sm"><div className="font-medium">{t.subject} · {t.status}</div><div className="mt-2 flex gap-2"><button className="rounded border px-2 py-1 text-xs" onClick={()=>post({action:"supportUpdate",schoolId:supportSchool,ticketId:t.id,status:"in_progress",body:ticketBody||undefined})}>In progress</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>post({action:"supportUpdate",schoolId:supportSchool,ticketId:t.id,status:"resolved",body:ticketBody||undefined})}>Resolve</button></div></div>)}</div></section>
 </main>
}
