"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/AppShell";

type Section="overview"|"schools"|"plans"|"billing"|"analytics"|"support"|"admins"|"audit"|"health"|"settings";
type School=Record<string,any>; type Admin=Record<string,any>;
const permissionGroups:Record<string,string[]>={Governance:["schools.view","schools.manage","schools.suspend","schools.impersonate","settings.manage"],Finance:["billing.view","billing.manage","plans.manage"],Insight:["analytics.view","audit.view"],Operations:["support.view","support.manage"],Security:["admins.view","admins.manage","security.manage"]};
const titles:Record<Section,[string,string]>={overview:["Control Center","See the health, commercial position and operating footprint of the full SukuuNova network."],schools:["School Network","Every school account, plan, status and support entry point in one place."],plans:["Plans & Entitlements","Design what schools can use, what they pay, and what happens when a plan changes."],billing:["Platform Billing","Monitor invoices, payments, arrears and the commercial state of every school."],analytics:["Network Analytics","Compare adoption, attendance, people and operational signals across schools."],support:["Support & Audited Access","Resolve cases and enter an explicitly audited school support session."],admins:["Workers & Permissions","Create your internal platform workers and grant exactly the capabilities they need."],audit:["Audit & Security","Review sensitive platform actions and investigate account activity."],health:["System Health","Watch database, API and application health before schools report a problem."],settings:["Platform Settings","Network-wide operating rules, security controls and defaults."]};
function Card({children,wide=false}:{children:React.ReactNode;wide?:boolean}){return <section className="app-card app-panel" style={{gridColumn:wide?"1/-1":undefined}}>{children}</section>}
function Header({title,sub}:{title:string;sub:string}){return <div className="app-card-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
export default function PlatformAdminWorkspace({section}:{section:Section}){
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(""),[selectedSchool,setSelectedSchool]=useState(""),[school,setSchool]=useState<any>(null),[worker,setWorker]=useState({name:"",email:"",password:"",role:"support_admin",permissions:["support.view","support.manage"]}),[admins,setAdmins]=useState<Admin[]>([]),[audit,setAudit]=useState<any[]>([]),[health,setHealth]=useState<any>(null),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{if(section==="overview"||section==="schools"||section==="analytics")setData(await (await fetch("/api/platform/admin?view=overview")).json());if(section==="admins")setData(await (await fetch("/api/platform/admin?view=admins")).json());if(section==="audit")setData(await (await fetch("/api/platform/admin?view=audit&limit=150")).json());if(section==="health")setData(await (await fetch("/api/platform/admin?view=health")).json());}finally{setLoading(false)}}
 useEffect(()=>{void load()},[section]);
 const totals=data?.totals||{};const schools:School[]=data?.schools||[];const permissions:(string[])[]=Object.values(permissionGroups);
 async function doPost(body:any){const r=await fetch("/api/platform/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(d.error||d.worker?"Saved successfully.":"Operation complete.");if(r.ok)void load();return d}
 async function getSchool(id:string){setSelectedSchool(id);if(!id)return;const r=await fetch(`/api/platform/admin?view=school&schoolId=${encodeURIComponent(id)}`);setSchool(r.ok?await r.json():null)}
 const planCards=useMemo(()=>[{name:"Foundation",price:"Free",desc:"Core school workspace and foundational operations"},{name:"Growth",price:"₵250 / month",desc:"Advanced operations, finance and school-life modules"},{name:"Enterprise",price:"₵500 / month",desc:"Full platform capability with advanced safeguards"}],[]);
 return <AppShell universe="platform" title={titles[section][0]} subtitle={titles[section][1]} active={section==="overview"?"Overview":section==="schools"?"Schools":section==="plans"?"Subscriptions":section==="billing"?"Platform Billing":section==="admins"?"Administrators":section==="audit"?"Audit Log":section==="health"?"System Health":section==="support"?"Support":"Overview"}>
  {message&&<div className="app-banner"><div><h3>{message}</h3><p>Platform control action recorded</p></div><span className="app-pill">Audited</span></div>}
  {loading&&<div className="app-card app-panel"><p>Loading platform data…</p></div>}
  {!loading&&section==="overview"&&<>
    <div className="app-grid kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Schools</span><span className="app-kpi-icon">⌂</span></div><div className="app-kpi-value">{totals.schools||0}</div><div className="app-kpi-meta">{totals.activeSchools||0} active · {totals.suspendedSchools||0} suspended</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Students</span><span className="app-kpi-icon">♟</span></div><div className="app-kpi-value">{totals.students||0}</div><div className="app-kpi-meta">Across active school accounts</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">School users</span><span className="app-kpi-icon">♙</span></div><div className="app-kpi-value">{totals.users||0}</div><div className="app-kpi-meta">Staff, teachers and operators</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Collected</span><span className="app-kpi-icon">₵</span></div><div className="app-kpi-value">₵{Number(totals.collected||0).toLocaleString()}</div><div className="app-kpi-meta">Recorded platform payments</div></div></div>
    <div className="app-dashboard-grid"><Card><Header title="Schools needing attention" sub="Status and commercial signals that deserve an admin look."/>{schools.filter(s=>s.status!=="active"||s.unpaidInvoices>0).slice(0,8).map(s=><div className="app-list-row" key={s.id}><span className="app-list-icon">!</span><div><b>{s.name}</b><span>{s.uniqueCode} · {s.status} · {s.subscriptionPlan?.name||"No plan"}</span></div><Link className="app-pill" href={`/platform/schools?school=${s.id}`}>Open</Link></div>)}</Card><Card><Header title="Network posture" sub="What the platform knows about the estate."/><div className="app-list"><div className="app-list-row"><div><b>{totals.classes||0}</b><span>Classes tracked</span></div></div><div className="app-list-row"><div><b>{totals.invoices||0}</b><span>Platform invoices</span></div></div><div className="app-list-row"><div><b>{totals.unpaidInvoices||0}</b><span>Invoices not fully paid</span></div></div></div></Card></div>
  </>}
  {!loading&&section==="schools"&&<div className="app-dashboard-grid"><Card wide><Header title="School accounts" sub="Select a school to inspect people, academics, attendance, plan and recent audit activity."/><div className="app-list">{schools.map(s=><div className="app-list-row" key={s.id}><span className="app-list-icon">⌂</span><div><b>{s.name}</b><span>{s.uniqueCode} · {s.status} · {s.subscriptionPlan?.name||"No plan"}</span></div><span className="app-pill">{s.studentCount||0} students</span><button className="app-action" onClick={()=>void getSchool(s.id)}><strong>Inspect</strong>School</button><button className="app-pill" onClick={()=>void fetch("/api/platform/phase4",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"suspendSchool",schoolId:s.id,suspended:s.status!=="suspended"})}).then(()=>load())}>{s.status==="suspended"?"Reactivate":"Suspend"}</button></div>)}</div></Card>{school&&<Card wide><Header title={school.school.name} sub={`${school.school.uniqueCode} · ${school.school.status} · ${school.school.subscriptionPlan?.name||"No plan"}`}/><div className="app-dashboard-grid"><div className="app-list"><div className="app-list-row"><div><b>{school.students.length}</b><span>Recent/active students visible</span></div></div><div className="app-list-row"><div><b>{school.users.length}</b><span>School accounts visible</span></div></div><div className="app-list-row"><div><b>{school.classes.length}</b><span>Classes</span></div></div><div className="app-list-row"><div><b>{school.subjects.length}</b><span>Subjects</span></div></div></div><div><h3 style={{marginTop:0}}>Recent users</h3>{school.users.slice(0,8).map((u:any)=><div className="app-list-row" key={u.id}><div><b>{u.name}</b><span>{u.email||u.phone||"No contact"} · {u.status}</span></div></div>)}</div></div></Card>}</div>}
  {!loading&&section==="plans"&&<div className="app-dashboard-grid">{planCards.map(p=><Card key={p.name}><Header title={p.name} sub={p.desc}/><div className="app-kpi-value" style={{fontSize:28,margin:"18px 0"}}>{p.price}</div><div className="app-list-row"><div><b>Entitlements</b><span>Feature-gated school workspace</span></div></div><Link className="app-action" href="/platform/billing"><strong>Manage</strong>plans and billing</Link></Card>)}<Card wide><Header title="Plan policy" sub="Subscription control is separate from school status so commercial and access decisions remain explicit."/><p style={{color:"#a9c1c2",lineHeight:1.6}}>A school can be kept active, moved to another plan, or suspended. Suspension blocks the school directory while preserving history for reactivation and audit review. Billing managers can reconcile invoices independently.</p></Card></div>}
  {!loading&&section==="billing"&&<Card wide><Header title="Commercial network" sub="Review each school’s subscription and invoice posture."/>{schools.map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.subscriptionPlan?.name||"No plan"} · {s.status} · {s.unpaidInvoices||0} unpaid invoices</span></div><button className="app-action" onClick={async()=>{const r=await fetch(`/api/platform/phase4?view=billing&schoolId=${encodeURIComponent(s.id)}`);const d=await r.json();alert(JSON.stringify(d,null,2))}}><strong>Billing</strong>details</button></div>)}</Card>}
  {!loading&&section==="analytics"&&<div className="app-dashboard-grid"><Card><Header title="Adoption" sub="Schools with active operational footprints."/>{schools.slice(0,12).map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.studentCount||0} students · {s.userCount||0} users · {s.classCount||0} classes</span></div><span className="app-pill">{s.status}</span></div>)}</Card><Card><Header title="Attendance pulse" sub="Today’s recorded student check-ins by school."/>{schools.slice(0,12).map(s=><div className="app-list-row" key={s.id}><div><b>{s.name}</b><span>{s.attendanceToday||0} recorded check-ins</span></div></div>)}</Card></div>}
  {!loading&&section==="support"&&<div className="app-dashboard-grid"><Card><Header title="Support queue" sub="Select a school to load its live support cases."/><div className="app-form-row" style={{display:"flex",gap:8}}><select value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)} style={{flex:1}}><option value="">Choose school…</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="app-action" onClick={async()=>{if(!selectedSchool)return;const r=await fetch(`/api/platform/phase4?view=support&schoolId=${selectedSchool}`);const d=await r.json();alert(JSON.stringify(d,null,2))}}><strong>Load</strong>cases</button></div></Card><Card><Header title="Audited support access" sub="Use only for legitimate support and investigation."/><Link className="app-action" href="/platform/schools"><strong>Choose school</strong>then start audited session</Link></Card></div>}
  {!loading&&section==="admins"&&<div className="app-dashboard-grid"><Card><Header title="Create platform worker" sub="Workers are separate from school users and receive narrowly scoped platform permissions."/><div className="app-form-grid" style={{display:"grid",gap:8}}><input placeholder="Full name" value={worker.name} onChange={e=>setWorker({...worker,name:e.target.value})}/><input placeholder="Email" value={worker.email} onChange={e=>setWorker({...worker,email:e.target.value})}/><input placeholder="Temporary password (12+ chars)" type="password" value={worker.password} onChange={e=>setWorker({...worker,password:e.target.value})}/><select value={worker.role} onChange={e=>setWorker({...worker,role:e.target.value})}><option value="platform_admin">Platform Admin</option><option value="support_admin">Support Admin</option><option value="billing_admin">Billing Admin</option><option value="analytics_admin">Analytics Admin</option></select><div>{permissions.flatMap(g=>g).map(p=><label key={p} style={{display:"block",margin:"6px 0"}}><input type="checkbox" checked={worker.permissions.includes(p)} onChange={e=>setWorker({...worker,permissions:e.target.checked?[...worker.permissions,p]:worker.permissions.filter(x=>x!==p)})}/> {p}</label>)}</div><button className="app-action" onClick={()=>void doPost({action:"createWorker",...worker})}><strong>Create worker</strong>Grant selected permissions</button><Link className="app-pill" href="/platform/forgot-password">Password recovery</Link></div></Card><Card><Header title="Current workers" sub="Suspend a worker instantly or review their current role."/>{(data?.admins||[]).map((a:Admin)=><div className="app-list-row" key={a.id}><div><b>{a.name}</b><span>{a.email} · {a.role} · {a.status}</span></div><button className="app-pill" onClick={()=>void doPost({action:"updateWorker",adminId:a.id,status:a.status==="active"?"suspended":"active",permissions:a.permissions})}>{a.status==="active"?"Suspend":"Reactivate"}</button></div>)}</Card></div>}
  {!loading&&section==="audit"&&<Card wide><Header title="Platform audit trail" sub="Sensitive administrative activity should be reviewable, filterable and exportable."/>{(data?.events||[]).map((e:any)=><div className="app-list-row" key={e.id}><div><b>{e.action}</b><span>{e.actorId} · {e.targetSchoolId||e.targetEntity||"Platform"} · {new Date(e.createdAt).toLocaleString()}</span></div></div>)}</Card>}
  {!loading&&section==="health"&&<div className="app-grid kpis"><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Database</span></div><div className="app-kpi-value">{health?.database||"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">API</span></div><div className="app-kpi-value">{health?.api||"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">Next.js</span></div><div className="app-kpi-value">{health?.nextjs||"unknown"}</div></div><div className="app-card app-kpi"><div className="app-kpi-top"><span className="app-kpi-label">DB latency</span></div><div className="app-kpi-value">{health?.latencyMs??"—"} ms</div></div></div>}
  {!loading&&section==="settings"&&<div className="app-dashboard-grid"><Card><Header title="Access policy" sub="Keep privileged control separate from normal support work."/><div className="app-list"><div className="app-list-row"><div><b>Super Admin</b><span>All platform controls, worker management and security.</span></div></div><div className="app-list-row"><div><b>Platform Admin</b><span>School, billing, analytics and support operations.</span></div></div><div className="app-list-row"><div><b>Support Admin</b><span>Support plus explicitly audited impersonation.</span></div></div></div></Card><Card><Header title="Recovery & continuity" sub="Account recovery and sensitive access must be operational before go-live."/><Link className="app-action" href="/platform/forgot-password"><strong>Platform password reset</strong>Request a 30-minute recovery token</Link></Card></div>}
 </AppShell>
}
