"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, CheckCircle2, Clock3, Database, RefreshCw, ServerCog, ShieldCheck, XCircle } from "lucide-react";

type Health={database:string;api:string;nextjs:string;latencyMs:number;checkedAt:string};

function State({value}:{value:string}){const good=value.toLowerCase()==="operational"||value.toLowerCase()==="ok"||value.toLowerCase()==="healthy";return <span className={`health-state ${good?"is-good":"is-bad"}`}>{good?<CheckCircle2 size={12}/>:<XCircle size={12}/>} {value}</span>}

export default function PlatformSystemHealth(){
 const [health,setHealth]=useState<Health|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[auto,setAuto]=useState(true);
 const requestRef=useRef<AbortController|null>(null);
 const load=async()=>{
  if(requestRef.current)return;
  const controller=new AbortController();requestRef.current=controller;setLoading(true);
  try{const r=await fetch("/api/platform/admin?view=health",{cache:"no-store",signal:controller.signal});const d=await r.json() as Health & {error?:string;message?:string};if(!r.ok){setMessage(d.message??d.error??"Health check failed.");return;}setHealth(d);setMessage("");}
  catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setMessage("Unable to reach the health endpoint.")}
  finally{if(requestRef.current===controller){requestRef.current=null;setLoading(false)}}
 };
 useEffect(()=>{void load();return()=>requestRef.current?.abort()},[]);
 useEffect(()=>{if(!auto)return;const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id)},[auto]);
 const checked=health?new Date(health.checkedAt).toLocaleString():"Not checked";
 return <div className="health-page-stack">
  <section className="platform-page-header"><div><span className="platform-eyebrow">Operations telemetry</span><h2>System Health</h2><p>See whether the control plane, API and database are responsive before an incident becomes a school-facing problem.</p></div><div className="platform-header-actions"><label className="health-auto"><input type="checkbox" checked={auto} onChange={(e)=>setAuto(e.target.checked)}/> Auto-refresh</label><button className="app-pill" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> {loading?"Checking":"Run check"}</button></div></section>
  {message&&<div className="app-banner" role="alert"><div><h3>{message}</h3><p>The health page is read-only and safe to refresh.</p></div></div>}
  <div className="health-summary app-card"> <div className="health-summary-main"><span className="health-pulse"><Activity size={18}/></span><div><b>{health&&health.database==="operational"&&health.api==="operational"&&health.nextjs==="operational"?"All reported systems operational":"Review system state"}</b><small>Last checked {checked}</small></div></div><div className="health-latency"><span>Database latency</span><strong>{health?`${health.latencyMs}ms`:"—"}</strong><small>Round-trip SELECT 1</small></div></div>
  <div className="health-grid">
   <section className="app-card app-panel"><div className="app-card-head"><div><h2>Service checks</h2><p>Core dependencies used by the platform control plane.</p></div><ShieldCheck size={18} color="var(--sn-muted)"/></div><div className="health-check-row"><span className="health-icon"><Database size={15}/></span><div><b>PostgreSQL</b><small>Database connectivity and query responsiveness</small></div><State value={health?.database??"Not checked"}/></div><div className="health-check-row"><span className="health-icon"><ServerCog size={15}/></span><div><b>API routes</b><small>Server route availability and request handling</small></div><State value={health?.api??"Not checked"}/></div><div className="health-check-row"><span className="health-icon"><Activity size={15}/></span><div><b>Next.js application</b><small>Application process health</small></div><State value={health?.nextjs??"Not checked"}/></div></section>
   <section className="app-card app-panel"><div className="app-card-head"><div><h2>Operator interpretation</h2><p>Health is a signal, not an incident diagnosis.</p></div><Clock3 size={18} color="var(--sn-muted)"/></div><div className="health-guidance"><div><b>Operational</b><span>Core checks are responding. Continue normal platform operations.</span></div><div><b>Degraded</b><span>Slow or partial checks should trigger inspection of recent deployments, queues and dependencies.</span></div><div><b>Incident</b><span>Failed checks require evidence from logs before restart, rollback or other intervention.</span></div></div></section>
  </div>
  <section className="app-card app-panel health-note"><h2>What this check does not claim</h2><p>This lightweight probe confirms application/database responsiveness. It does not by itself prove queue delivery, scheduled jobs, third-party messaging, storage, backups or end-user login success. Those need their own telemetry and workflow checks as the platform matures.</p></section>
  <style jsx global>{`\n  .health-page-stack{display:grid;gap:16px;margin-top:22px}.health-auto{display:flex;align-items:center;gap:7px;height:34px;padding:0 9px;border:1px solid #dbe3ec;border-radius:9px;background:#fff;color:#667789;font-size:8.5px;font-weight:800}.health-summary{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:18px 20px;background:linear-gradient(135deg,#fff 0%,#f6faff 100%);border-color:#d8e3ed}.health-summary-main{display:flex;align-items:center;gap:11px}.health-pulse{display:grid;place-items:center;width:36px;height:36px;border-radius:11px;background:#eaf7f0;color:#2b8355}.health-summary-main b{display:block;font-size:12px;color:#26394b}.health-summary-main small{display:block;margin-top:3px;color:#83909e;font-size:9px}.health-latency{min-width:130px;padding-left:18px;border-left:1px solid #e5ebf0}.health-latency span,.health-latency small{display:block;color:#82909e;font-size:8.5px}.health-latency strong{display:block;margin:2px 0;font-size:18px;color:#294158}.health-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.health-check-row{display:flex;align-items:center;gap:10px;padding:13px 20px;border-top:1px solid #edf1f5}.health-icon{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#f1f5f8;color:#5c7388;flex:none}.health-check-row>div{min-width:0;flex:1}.health-check-row b{display:block;font-size:10.5px;color:#2a3c4d}.health-check-row small{display:block;margin-top:3px;font-size:8.5px;color:#8592a0;line-height:1.35}.health-state{display:inline-flex;align-items:center;gap:4px;padding:5px 7px;border-radius:999px;font-size:7.5px;font-weight:850;white-space:nowrap}.health-state.is-good{background:#edf9f2;color:#27794d}.health-state.is-bad{background:#fff0ee;color:#a74740}.health-guidance{display:grid;padding:0 20px 18px}.health-guidance>div{padding:11px 0;border-top:1px solid #edf1f5}.health-guidance>div:first-child{border-top:0}.health-guidance b{display:block;font-size:9.5px;color:#2f4356}.health-guidance span{display:block;margin-top:3px;font-size:8.5px;color:#83919f;line-height:1.45}.health-note{padding:18px 20px}.health-note h2{margin:0;font-size:13px;color:#34495c}.health-note p{margin:6px 0 0;max-width:900px;color:#7d8c9a;font-size:9.5px;line-height:1.55}@media(max-width:900px){.health-grid{grid-template-columns:1fr}}@media(max-width:620px){.health-summary{align-items:flex-start;flex-direction:column}.health-latency{width:100%;padding:10px 0 0;border-left:0;border-top:1px solid #e5ebf0}.health-header{} }\n  `}</style>
 </div>
}
