"use client";

import { useEffect, useState } from "react";
import type { CSSProperties, FormEvent } from "react";

type Posting={id:string;title:string;department?:string|null;employmentType?:string|null;description?:string|null;instructions?:string|null;closingDate?:string|null;status:string;screeningQuestions?:unknown};
type Props={schoolId:string;token:string};
const str=(v:unknown,f="")=>typeof v==="string"&&v.trim()?v:f;

export default function PublicJobApplication({schoolId,token}:Props){
 const[posting,setPosting]=useState<Posting|null>(null),[error,setError]=useState(""),[sent,setSent]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState<Record<string,string>>({});
 useEffect(()=>{fetch(`/api/public/jobs/${schoolId}/${token}`,{cache:"no-store"}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||j?.message||"This vacancy is unavailable.");setPosting(j.posting)}).catch(e=>setError(e instanceof Error?e.message:"This vacancy is unavailable."))},[schoolId,token]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const qs=Array.isArray(posting?.screeningQuestions)?posting?.screeningQuestions:[],answers:Record<string,string>={};for(const q of qs as Array<Record<string,unknown>>){const id=String(q.id||"");if(id)answers[id]=form[`q_${id}`]||"";}const r=await fetch(`/api/public/jobs/${schoolId}/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,email:form.email,phone:form.phone,resumeUrl:form.resumeUrl,coverLetter:form.coverLetter,answers})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||j?.message||"Your application could not be submitted.");setSent(String(j.applicationId||"submitted"))}catch(e){setError(e instanceof Error?e.message:"Your application could not be submitted.")}finally{setBusy(false)}}
 if(error&&!posting)return <main style={page}><div style={card}><span style={eyebrow}>CAREERS</span><h1>Application unavailable</h1><p>{error}</p></div></main>;
 if(!posting)return <main style={page}><div style={card}><span style={eyebrow}>CAREERS</span><h1>Loading vacancy…</h1></div></main>;
 if(sent)return <main style={page}><div style={success}><div style={check}>✓</div><span style={eyebrow}>APPLICATION RECEIVED</span><h1>Thank you, {str(form.name,"applicant")}.</h1><p>Your application has been securely recorded. Keep your application reference for your records.</p><code>{sent}</code><a style={button} href="/">Return to school site</a></div></main>;
 const qs=Array.isArray(posting.screeningQuestions)?posting.screeningQuestions as Array<Record<string,unknown>>:[];
 return <main style={page}><div style={shell}><header style={brand}><div><span style={eyebrow}>CAREERS</span><h1>{posting.title}</h1><p>{str(posting.department,"School")} · {str(posting.employmentType,"Employment")}{posting.closingDate?` · Closes ${new Date(posting.closingDate).toLocaleDateString("en-GH")}`:""}</p></div><span style={openPill}>OPEN</span></header><section style={details}><div><h2>About the role</h2><p>{str(posting.description,"The school has opened this opportunity for qualified applicants.")}</p></div>{posting.instructions&&<div style={instructions}><strong>Application instructions</strong><p>{posting.instructions}</p></div>}</section><form onSubmit={submit} style={formStyle}><div style={section}><span style={eyebrow}>YOUR DETAILS</span><h2>Tell us about yourself</h2><div style={grid}><label>Full name<input required value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email address<input type="email" value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone number<input value={form.phone||""} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>CV / resume link<input value={form.resumeUrl||""} placeholder="Public file link" onChange={e=>setForm({...form,resumeUrl:e.target.value})}/></label></div><p style={hint}>Provide at least an email address or phone number so the school can contact you.</p></div>{qs.length>0&&<div style={section}><span style={eyebrow}>SCREENING</span><h2>A few role-specific questions</h2>{qs.map(q=><label key={String(q.id)} style={{display:"grid",gap:6,marginBottom:14}}>{String(q.label)}{q.required!==false&&<em> required</em>}{Array.isArray(q.options)&&q.options.length>0?<select required={q.required!==false} value={form[`q_${String(q.id)}`]||""} onChange={e=>setForm({...form,[`q_${String(q.id)}`]:e.target.value})}><option value="">Choose an answer</option>{(q.options as unknown[]).map(o=><option key={String(o)}>{String(o)}</option>)}</select>:<textarea required={q.required!==false} rows={3} value={form[`q_${String(q.id)}`]||""} onChange={e=>setForm({...form,[`q_${String(q.id)}`]:e.target.value})}/>}</label>)}</div>}<div style={section}><span style={eyebrow}>YOUR STORY</span><h2>Anything else we should know?</h2><textarea rows={7} placeholder="Cover letter, relevant experience, availability or supporting context" value={form.coverLetter||""} onChange={e=>setForm({...form,coverLetter:e.target.value})}/></div>{error&&<div style={errorBox}>{error}</div>}<button disabled={busy} style={button}>{busy?"Submitting application…":"Submit application"}</button><p style={fine}>By submitting, you are sending these details directly to the school for recruitment review.</p></form></div></main>;
}
const page:CSSProperties={minHeight:"100vh",background:"#f3f6f4",padding:"40px 16px",color:"#14211e",fontFamily:"Inter,system-ui,sans-serif"}; const shell:CSSProperties={maxWidth:980,margin:"0 auto"}; const card:CSSProperties={maxWidth:620,margin:"10vh auto",background:"white",border:"1px solid #dfe7e3",borderRadius:28,padding:36,boxShadow:"0 25px 70px rgba(20,33,30,.09)"}; const success:CSSProperties={...card,textAlign:"center"}; const eyebrow:CSSProperties={fontSize:11,fontWeight:800,letterSpacing:".14em",color:"#176b61"}; const brand:CSSProperties={background:"linear-gradient(135deg,#10201d,#23564d)",color:"white",padding:"34px",borderRadius:28,display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-end",boxShadow:"0 22px 60px rgba(20,33,30,.15)"}; const openPill:CSSProperties={padding:"8px 11px",borderRadius:999,background:"rgba(255,255,255,.12)",fontSize:10,fontWeight:900}; const details:CSSProperties={display:"grid",gridTemplateColumns:"1.3fr .7fr",gap:14,marginTop:14}; const instructions:CSSProperties={background:"#e8f5ef",padding:20,borderRadius:20}; const formStyle:CSSProperties={background:"white",marginTop:14,border:"1px solid #dfe7e3",borderRadius:24,padding:24,boxShadow:"0 18px 50px rgba(20,33,30,.06)"}; const section:CSSProperties={padding:"4px 0 24px",marginBottom:20,borderBottom:"1px solid #edf1ef"}; const grid:CSSProperties={display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}; const hint:CSSProperties={fontSize:11,color:"#687672"}; const fine:CSSProperties={fontSize:11,color:"#687672",textAlign:"center"}; const button:CSSProperties={display:"inline-flex",justifyContent:"center",alignItems:"center",width:"100%",border:0,background:"#176b61",color:"white",padding:"14px 16px",borderRadius:14,fontWeight:800,textDecoration:"none",cursor:"pointer"}; const check:CSSProperties={width:62,height:62,borderRadius:"50%",display:"grid",placeItems:"center",background:"#e2f4ed",color:"#176b61",fontSize:30,fontWeight:900,margin:"0 auto 16px"}; const errorBox:CSSProperties={padding:12,borderRadius:12,background:"#fff0ef",color:"#9e3930",fontSize:12,marginBottom:12};
