"use client";
import { useEffect, useState } from "react";

type Lead={id:string;name:string;email?:string|null;phone?:string|null;channel:string;subject?:string|null;message:string;status:string;createdAt:string;repliedAt?:string|null;repliedVia?:string|null};

function wa(phone:string,message:string){return `https://wa.me/${phone.replace(/[^\d]/g,"")}?text=${encodeURIComponent(message)}`;}
export function PublicLeadInbox(){
 const [leads,setLeads]=useState<Lead[]>([]); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState("all");
 const load=()=>fetch("/api/platform/public").then(r=>r.json()).then(d=>setLeads((d.inquiries??[]) as Lead[])).finally(()=>setLoading(false)); useEffect(()=>{void load()},[]);
 const update=async(id:string,status:string,via?:string)=>{await fetch(`/api/platform/inquiries/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status,repliedVia:via})});void load();};
 const shown=filter==="all"?leads:leads.filter(l=>l.status===filter);
 return <div className="app-dashboard-grid"><section className="app-card app-panel"><div className="app-card-head"><div><h2>Visitor inbox</h2><p>Website conversations land here. Keep the reply human: call, email or open WhatsApp from the contact card.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="new">New</option><option value="open">Open</option><option value="resolved">Resolved</option></select></div>{loading?<p>Loading conversations…</p>:shown.length===0?<div className="app-list-row"><div><b>No messages here yet.</b><span>When someone writes from the website, you will see it here.</span></div></div>:shown.map(l=><article className="app-list-row" key={l.id}><div style={{flex:1}}><b>{l.name}{l.subject?` · ${l.subject}`:""}</b><span>{new Date(l.createdAt).toLocaleString()} · {l.status}</span><p style={{margin:"8px 0 0",color:"#b9cdce",whiteSpace:"pre-wrap"}}>{l.message}</p><small>{l.email||""}{l.email&&l.phone?" · ":""}{l.phone||""}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}>{l.email&&<a className="app-pill" href={`mailto:${l.email}?subject=${encodeURIComponent(`Re: ${l.subject||"SukuuNova enquiry"}`)}`}>Email</a>}{l.phone&&<a className="app-pill" href={`sms:${l.phone}?&body=${encodeURIComponent(`Hi ${l.name}, thanks for reaching out to SukuuNova.`)}`}>SMS</a>}{l.phone&&<a className="app-pill" href={wa(l.phone,`Hi ${l.name}, thanks for reaching out to SukuuNova.`)} target="_blank" rel="noreferrer">WhatsApp</a>}<button className="app-pill" onClick={()=>void update(l.id,l.status==="resolved"?"open":"resolved",l.status==="resolved"?undefined:"website_reply")}>{l.status==="resolved"?"Re-open":"Mark resolved"}</button></div></article>)}</section></div>;
}
