"use client";
import { useEffect, useState } from "react";

type Settings = { brandName:string; tagline:string; supportEmail?:string|null; supportPhone?:string|null; whatsappNumber?:string|null; tiktokHandle?:string|null; instagramHandle?:string|null; facebookHandle?:string|null; linkedinHandle?:string|null; youtubeHandle?:string|null; xHandle?:string|null; websiteUrl?:string|null; showSocialLinks:boolean; showLeadChat:boolean };
const defaults: Settings = {brandName:"SukuuNova",tagline:"A calmer, more connected way to run a school.",showSocialLinks:true,showLeadChat:true};
const fields: Array<[keyof Settings,string,string]> = [
 ["supportEmail","Support email","hello@example.com"],["supportPhone","Support phone","+233…"],["whatsappNumber","WhatsApp number","+233…"],["tiktokHandle","TikTok handle or URL","@yourbusiness"],["instagramHandle","Instagram handle or URL","@yourbusiness"],["facebookHandle","Facebook handle or URL","facebook.com/yourbusiness"],["linkedinHandle","LinkedIn handle or URL","linkedin.com/company/…"],["youtubeHandle","YouTube handle or URL","@yourchannel"],["xHandle","X handle or URL","@yourbusiness"],["websiteUrl","Website URL","https://…"]
];
export function PublicPresenceConsole(){
 const [settings,setSettings]=useState<Settings>(defaults); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/platform/public").then(r=>r.json()).then(d=>setSettings({...defaults,...d.settings})).catch(()=>setStatus("We could not load public settings.")).finally(()=>setLoading(false));},[]);
 const save=async()=>{setStatus("Saving…");const r=await fetch("/api/platform/public",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});const d=await r.json();setStatus(d.message||d.error||"Saved.");};
 return <div className="app-dashboard-grid"><section className="app-card app-panel"><div className="app-card-head"><div><h2>Public presence</h2><p>Control the details visitors see on the SukuuNova homepage. Use handles, URLs and business contact details here — never store social-media passwords in SukuuNova.</p></div></div>{loading?<p>Loading…</p>:<div style={{display:"grid",gap:10}}><label>Brand name<input value={settings.brandName} onChange={e=>setSettings({...settings,brandName:e.target.value})}/></label><label>Tagline<input value={settings.tagline} onChange={e=>setSettings({...settings,tagline:e.target.value})}/></label>{fields.map(([key,label,placeholder])=><label key={key}>{label}<input value={String(settings[key]??"")} placeholder={placeholder} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<label><input type="checkbox" checked={settings.showSocialLinks} onChange={e=>setSettings({...settings,showSocialLinks:e.target.checked})}/> Show social/contact links on homepage</label><label><input type="checkbox" checked={settings.showLeadChat} onChange={e=>setSettings({...settings,showLeadChat:e.target.checked})}/> Show visitor message box on homepage</label><button className="app-action" onClick={save}><strong>Save public presence</strong>Update homepage</button>{status&&<div className="app-banner"><div><h3>{status}</h3><p>Changes are audited.</p></div></div>}</div>}</section><section className="app-card app-panel"><div className="app-card-head"><div><h2>What visitors will see</h2><p>Friendly, human contact options with direct paths to your real channels.</p></div></div><div className="app-list-row"><div><b>{settings.brandName}</b><span>{settings.tagline}</span></div></div>{settings.whatsappNumber&&<div className="app-list-row"><div><b>WhatsApp</b><span>{settings.whatsappNumber}</span></div><a className="app-pill" href={`https://wa.me/${settings.whatsappNumber.replace(/[^\d]/g,"")}`}>Open</a></div>}{settings.supportEmail&&<div className="app-list-row"><div><b>Email</b><span>{settings.supportEmail}</span></div><a className="app-pill" href={`mailto:${settings.supportEmail}`}>Write</a></div>}{settings.supportPhone&&<div className="app-list-row"><div><b>Phone</b><span>{settings.supportPhone}</span></div><a className="app-pill" href={`tel:${settings.supportPhone}`}>Call</a></div>}</section></div>;
}
