"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Mode = "analytics" | "reports" | "help";
const btnPrimary = "rounded-xl bg-slate-950 px-4 py-2.5 text-[10px] font-black text-white transition hover:bg-slate-800";
const btnSecondary = "rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-[10px] font-black text-slate-700 transition hover:bg-slate-50";
const panel = "rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,.05)]";
const field = "w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-xs text-slate-900 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";

function Hero({ kicker, title, detail, children }: { kicker: string; title: string; detail: string; children?: React.ReactNode }) {
  return <section className="rounded-3xl border border-slate-200 bg-slate-950 p-6 text-white shadow-[0_18px_50px_rgba(15,23,42,.16)]"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><span className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-300">{kicker}</span><h2 className="mt-2 text-2xl font-black tracking-tight">{title}</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-slate-300">{detail}</p></div>{children}</div></section>;
}

function Kpi({ label, value, note }: { label: string; value: string; note: string }) { return <div className={panel}><span className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">{label}</span><strong className="mt-2 block text-2xl font-black text-slate-950">{value}</strong><span className="mt-1 block text-[10px] leading-4 text-slate-500">{note}</span></div>; }

export default function ReportsAdminStudioPro({ mode, schoolName }: { mode: Mode; schoolName: string }) {
  const [period, setPeriod] = useState("Current term");
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState(false);
  const categories = useMemo(() => ["Academic", "Attendance", "Finance", "People", "Operations", "Management"].filter((x) => x.toLowerCase().includes(query.toLowerCase())), [query]);

  if (mode === "analytics") return <div className="space-y-5">
    <Hero kicker="Executive intelligence" title={`School Analytics · ${schoolName}`} detail="A leadership cockpit: compare terms, spot exceptions, drill into the affected module and move directly to the operational action."><div className="rounded-2xl border border-white/10 bg-white/5 p-4 xl:min-w-56"><span className="block text-[9px] font-black uppercase tracking-[.12em] text-slate-400">Reporting period</span><select value={period} onChange={(e) => setPeriod(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold text-white"><option>Current term</option><option>Previous term</option><option>Academic year</option><option>Custom range</option></select></div></Hero>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi label="Students" value="Live" note="Enrolment, movement and class distribution"/><Kpi label="Attendance" value="Live" note="Presence, absence and lateness trends"/><Kpi label="Academics" value="Live" note="Results, missing marks and performance"/><Kpi label="Finance" value="Live" note="Collections, arrears and payment activity"/></div>
    <div className="grid gap-5 xl:grid-cols-[1.4fr,.6fr]"><section className={panel}><div className="flex flex-wrap gap-2">{["Overview","Students","Attendance","Academics","Finance","Operations"].map((item) => <button key={item} className={item === "Overview" ? btnPrimary : btnSecondary} type="button">{item}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="text-[9px] font-black uppercase text-slate-500">Trend canvas</span><div className="mt-4 h-44 rounded-xl border border-dashed border-slate-300 bg-white p-5"><div className="flex h-full items-end gap-2">{[30,45,35,62,58,72,66,82,76,88].map((height, i) => <div key={i} className="flex-1 rounded-t bg-emerald-600/80" style={{ height: `${height}%` }} />)}</div></div><p className="mt-2 text-[9px] text-slate-400">Live chart surface for term-over-term data.</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="text-[9px] font-black uppercase text-slate-500">Decision queue</span><div className="mt-3 space-y-2">{["3 attendance exceptions","2 fee-risk groups","1 missing result set","6 communication failures"].map((item, i) => <Link key={item} href={i === 0 ? "/school/attendance/exceptions" : i === 1 ? "/school/fees/arrears" : i === 2 ? "/school/gradebook" : "/school/communications/messages"} className="flex items-center justify-between rounded-xl bg-white px-3 py-3 text-[10px] font-bold text-slate-700 hover:bg-slate-50"><span>{item}</span><span>→</span></Link>)}</div></div></div></section><aside className={panel}><span className="text-[9px] font-black uppercase tracking-[.12em] text-emerald-700">Leadership actions</span><h3 className="mt-2 text-base font-black text-slate-950">Move from signal to action</h3><div className="mt-4 space-y-2"><Link href="/school/reports" className="block rounded-xl bg-slate-950 px-4 py-3 text-[10px] font-black text-white">Build a report</Link><Link href="/school/downloads" className="block rounded-xl border border-slate-300 bg-white px-4 py-3 text-[10px] font-black text-slate-700">Export official data</Link><Link href="/school/settings/access" className="block rounded-xl border border-slate-300 bg-white px-4 py-3 text-[10px] font-black text-slate-700">Review access governance</Link></div></aside></div>
    <section className={panel}><h3 className="text-sm font-black text-slate-950">Analytics design controls</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["Default school filters","Role-specific dashboards","Threshold alerts","Scheduled executive briefs"].map((item) => <label key={item} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-[10px] font-bold text-slate-700"><span>{item}</span><input type="checkbox" defaultChecked /></label>)}</div></section>
  </div>;

  if (mode === "reports") return <div className="space-y-5">
    <Hero kicker="Official reporting" title="Reports Centre" detail="Design repeatable reports with a saved scope, term context, filters, audience and output format. The same definition can later drive scheduled PDF/Excel packs."><Link className={btnPrimary} href="/school/downloads">Open Downloads & Exports</Link></Hero>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi label="Saved reports" value="0" note="Reusable report definitions"/><Kpi label="Scheduled runs" value="0" note="Automatic report jobs"/><Kpi label="Completed" value="0" note="Generated report packs"/><Kpi label="Needs attention" value="0" note="Failed or awaiting approval"/></div>
    <section className={panel}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 className="text-sm font-black text-slate-950">Report catalogue</h3><p className="mt-1 text-[10px] text-slate-500">Start from a school report family, then refine it.</p></div><input className={`${field} md:max-w-xs`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search report types…" /></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{categories.map((category) => <article key={category} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-white px-2 py-1 text-[8px] font-black uppercase tracking-[.1em] text-slate-500">{category}</span><span className="text-[9px] font-black text-slate-400">Template</span></div><h4 className="mt-3 text-xs font-black text-slate-950">{category} report pack</h4><p className="mt-1 text-[10px] leading-5 text-slate-500">Filters by term, class, subject or cohort; save the definition and produce a branded document.</p><div className="mt-4 flex gap-2"><button className={btnPrimary} type="button" onClick={() => setSaved(true)}>Configure</button><button className={btnSecondary} type="button">Preview</button></div></article>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><h3 className="text-sm font-black text-slate-950">Report workflow</h3><div className="mt-4 grid gap-2 sm:grid-cols-4">{[["01","Scope","School + term"],["02","Filter","Class / cohort / period"],["03","Review","Preview + approve"],["04","Produce","PDF / Excel / CSV / JSON"]].map(([n,a,b]) => <div key={n} className="rounded-xl bg-slate-50 p-3"><span className="text-[9px] font-black text-slate-400">{n}</span><strong className="mt-1 block text-[10px] font-black text-slate-900">{a}</strong><span className="mt-1 block text-[9px] text-slate-500">{b}</span></div>)}</div></section><section className={panel}><h3 className="text-sm font-black text-slate-950">Scheduled distribution</h3><p className="mt-1 text-[10px] text-slate-500">Send approved reports to authorised recipients automatically on a defined schedule.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={field}><option>Every week</option><option>Every month</option><option>Every term</option></select><select className={field}><option>School leadership</option><option>Finance team</option><option>Academic team</option></select></div><button className={`${btnPrimary} mt-3`} type="button" onClick={() => setSaved(true)}>Save distribution</button></section></div>{saved && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[10px] font-bold text-emerald-900">The report definition is ready to connect to the persistent report scheduler.</div>}
  </div>;

  return <div className="space-y-5">
    <Hero kicker="Product support" title="Help & Support" detail={`A dedicated support centre for ${schoolName}: searchable guides, troubleshooting, service information and a structured support request path.`}><span className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-[10px] font-bold text-slate-300">Support context included automatically</span></Hero>
    <section className={panel}><div className="flex flex-col gap-3 md:flex-row md:items-center"><input className={field} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search: fees, report cards, exports, attendance, users…" /><button className={btnPrimary} type="button">Search help</button></div></section>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{t:"Getting started",d:"Set up school identity, terms, people and permissions."},{t:"Academics",d:"Timetable, assessments, gradebook and report cards."},{t:"Finance",d:"Fees, payments, balances, receipts and payroll."},{t:"Communication",d:"Messages, SMS, WhatsApp, announcements and automation."}].map((x)=><section key={x.t} className={panel}><h3 className="text-sm font-black text-slate-950">{x.t}</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">{x.d}</p><button type="button" className={`${btnSecondary} mt-4`}>Browse guides</button></section>)}</div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr,.9fr]"><section className={panel}><h3 className="text-sm font-black text-slate-950">Popular guides</h3><div className="mt-3 divide-y divide-slate-200">{["Create the first academic term","Create an administrator / IT sub-account","Approve and publish report cards","Set up SMS and WhatsApp","Generate an official export","Resolve a failed payment"].map((x)=><button key={x} type="button" className="flex w-full items-center justify-between py-3 text-left text-[10px] font-bold text-slate-700 hover:text-slate-950"><span>{x}</span><span>→</span></button>)}</div></section><section className="rounded-2xl border border-slate-900 bg-slate-950 p-5 text-white"><h3 className="text-sm font-black">Create a support request</h3><p className="mt-2 text-[10px] leading-5 text-slate-300">The future support form should attach the school, account, page, browser, severity and relevant audit context automatically so the operator does not repeat information.</p><button className="mt-4 w-full rounded-xl bg-emerald-500 px-4 py-3 text-[10px] font-black text-white" type="button">Open support request</button></section></div>
  </div>;
}
