"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Mode = "analytics" | "reports" | "roles" | "access" | "settings" | "help";

type Card = { title: string; detail: string; metric?: string };

const commonButton = "rounded-xl px-4 py-2.5 text-[10px] font-black transition";
const primary = `${commonButton} bg-slate-950 text-white hover:bg-slate-800`;
const secondary = `${commonButton} border border-slate-300 bg-white text-slate-700 hover:bg-slate-50`;
const input = "w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-xs text-slate-900 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100";

function Header({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_12px_40px_rgba(15,23,42,.07)]"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-700">{eyebrow}</span><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">{title}</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-500">{detail}</p></div>{action}</div></section>;
}

function StatGrid({ cards }: { cards: Card[] }) {
  return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <div key={card.title} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500">{card.title}</span><strong className="mt-2 block text-2xl font-black text-slate-950">{card.metric ?? "—"}</strong><p className="mt-1 text-[10px] leading-4 text-slate-500">{card.detail}</p></div>)}</div>;
}

export default function ReportsAdminStudio({ mode, schoolName }: { mode: Mode; schoolName: string }) {
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState(false);
  const [tab, setTab] = useState("Overview");
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ attendance: true, fee: true, reportCard: true, emergency: true });

  const searchPlaceholder = useMemo(() => ({ analytics: "Find a metric…", reports: "Find a report…", roles: "Find a role or permission…", access: "Find an account…", settings: "Search school settings…", help: "Search help articles…" }[mode]), [mode]);

  function toggle(key: string) { setEnabled((current) => ({ ...current, [key]: !current[key] })); }

  if (mode === "analytics") return <div className="space-y-5"><Header eyebrow="School intelligence" title="School Analytics" detail={`A decision dashboard for ${schoolName}. Bring attendance, academics, finance, people, communication and operations into one view.`} action={<button className={secondary} type="button" onClick={() => setSaved(true)}>Configure dashboard</button>} /><StatGrid cards={[{ title: "Students", metric: "—", detail: "Active learners and enrolment movement." }, { title: "Attendance", metric: "—", detail: "Daily presence, absence and lateness." }, { title: "Academics", metric: "—", detail: "Results, completion and performance trends." }, { title: "Finance", metric: "—", detail: "Collections, balances and fee risk." }]} /><div className="grid gap-5 xl:grid-cols-[1.4fr,.6fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap gap-2">{["Overview","Students","Attendance","Academics","Finance","Operations"].map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`${commonButton} ${tab === item ? "bg-slate-950 text-white" : "border border-slate-300 bg-white text-slate-600"}`}>{item}</button>)}</div><div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><strong className="block text-sm font-black text-slate-900">{tab} intelligence workspace</strong><p className="mx-auto mt-2 max-w-xl text-[11px] leading-5 text-slate-500">Charts, comparisons, term-over-term trends, exceptions, drill-downs and scheduled insight reports belong here. Filters should inherit the selected academic year and term automatically.</p></div></section><aside className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><span className="text-[9px] font-black uppercase tracking-[.12em] text-emerald-300">Executive view</span><h3 className="mt-2 text-lg font-black">What needs attention?</h3><div className="mt-5 space-y-3">{["Attendance exceptions","Fee arrears","Missing academic results","Operational alerts"].map((item, index) => <div key={item} className="flex items-center justify-between border-b border-white/10 pb-3 text-[10px]"><span>{item}</span><span className="rounded-full bg-white/10 px-2 py-1">{index === 0 ? "Review" : "—"}</span></div>)}</div></aside></div>{saved && <Notice text="Dashboard preferences are ready to be connected to persisted school analytics settings." />}</div>;

  if (mode === "reports") return <div className="space-y-5"><Header eyebrow="Reports centre" title="Reports" detail="Run official school reports, save recurring report definitions and keep a traceable history of generated documents." action={<Link className={primary} href="/school/downloads">Open Export Centre</Link>} /><div className="grid gap-3 md:grid-cols-3">{[{ t: "Academic performance", d: "Results, grades, positions and subject summaries." }, { t: "Attendance", d: "Daily, monthly and term attendance summaries." }, { t: "Finance", d: "Fees, payments, balances and collections." }, { t: "People", d: "Student, guardian and staff registers." }, { t: "Operations", d: "Library, transport, feeding and asset activity." }, { t: "Management pack", d: "Combine approved reports into an executive bundle." }].map((item) => <section key={item.t} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="text-xs font-black text-slate-950">{item.t}</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">{item.d}</p><button type="button" className={`${secondary} mt-4`}>Configure report</button></section>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-black text-slate-950">Scheduled reports</h3><p className="mt-1 text-[10px] text-slate-500">Create recurring reports for principals, directors, boards or authorised staff.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input className={input} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={searchPlaceholder} /><select className={input}><option>Monthly</option><option>Weekly</option><option>Every term</option></select><button className={primary} type="button" onClick={() => setSaved(true)}>Save schedule</button></div></section>{saved && <Notice text="Report scheduling preference saved for this workspace session." />}</div>;

  if (mode === "roles") return <div className="space-y-5"><Header eyebrow="Access governance" title="Roles & Permissions" detail="Define what administrators, finance users, teachers, IT staff and other school workers can see and do. Keep sensitive functions separated by least privilege." action={<button className={primary} type="button" onClick={() => setSaved(true)}>Create role</button>} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["Owner / Director","Administrator","IT Administrator","Finance Officer","Teacher","Registrar","Transport Manager","Read-only Manager"].map((role) => <section key={role} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="text-xs font-black text-slate-950">{role}</h3><p className="mt-2 text-[10px] text-slate-500">Custom permissions, scope and approval rules.</p><button className={`${secondary} mt-4`} type="button">Manage access</button></section>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 className="text-sm font-black text-slate-950">Permission catalogue</h3><p className="mt-1 text-[10px] text-slate-500">Permissions can be grouped by module and optionally limited to actions such as view, create, approve, export or administer.</p></div><input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-xs text-slate-900 md:w-64" placeholder={searchPlaceholder} value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{["People records","Academic results","Report cards","Finance & payroll","Communication","Recruitment","Inventory","School settings","Exports & downloads"].map((permission) => <label key={permission} className="flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-3"><span className="text-[10px] font-bold text-slate-700">{permission}</span><input type="checkbox" defaultChecked /></label>)}</div></section>{saved && <Notice text="Role creation workflow is ready for persistence and approval rules." />}</div>;

  if (mode === "access") return <div className="space-y-5"><Header eyebrow="People access" title="Sub-accounts & Access" detail="Create controlled accounts for administrators, IT users and trusted assistants without sharing the owner's login. Delegate exactly the work each person needs." action={<button className={primary} type="button" onClick={() => setSaved(true)}>Create sub-account</button>} /><div className="grid gap-3 md:grid-cols-4"><StatGrid cards={[{ title: "Owner", metric: "1", detail: "Primary school account." }, { title: "Administrators", metric: "—", detail: "School administrators." }, { title: "IT users", metric: "—", detail: "Technical access accounts." }, { title: "Delegated users", metric: "—", detail: "Other authorised workers." }]} /></div><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-black text-slate-950">Create a delegated account</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><input className={input} placeholder="Full name" /><input className={input} placeholder="Work email" /><select className={input}><option>Administrator</option><option>IT Administrator</option><option>Finance Officer</option><option>Teacher</option><option>Custom role</option></select><select className={input}><option>Whole school</option><option>Selected modules</option><option>Read-only</option></select></div><div className="mt-4 flex flex-wrap gap-2"><button className={primary} type="button" onClick={() => setSaved(true)}>Create secure account</button><button className={secondary} type="button">Review invitation policy</button></div></section><section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="text-sm font-black text-emerald-950">Owner delegation</h3><p className="mt-1 text-[10px] leading-5 text-emerald-900">The owner can create an administrator or IT account with an equivalent role, but the owner's password and recovery methods remain private. Future controls should include expiry, MFA, session management, impersonation approval and audit history.</p></section>{saved && <Notice text="Delegated-account controls are staged for the connected school account workflow." />}</div>;

  if (mode === "settings") return <div className="space-y-5"><Header eyebrow="School control centre" title="School Settings" detail={`One place to control how ${schoolName} operates. Identity, academic calendar, communications, finance behaviour, security, integrations and document branding belong here.`} action={<button className={primary} type="button" onClick={() => setSaved(true)}>Save changes</button>} /><div className="grid gap-5 lg:grid-cols-[220px,1fr]"><nav className="rounded-2xl border border-slate-200 bg-white p-3">{["General","Academic year","Terms & calendar","Branding & documents","Communication","Finance","Security","Integrations","Data & privacy","Automation"].map((item, index) => <button key={item} type="button" onClick={() => setTab(item)} className={`block w-full rounded-xl px-3 py-2.5 text-left text-[10px] font-black ${tab === item ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-50"}`}>{item}</button>)}</nav><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-base font-black text-slate-950">{tab}</h3><p className="mt-1 text-[10px] text-slate-500">Fine-grained control for school administrators.</p><div className="mt-5 grid gap-3">{["Enable automated parent communications","Require approval before external messages","Use school logo on generated documents","Allow parent portal report-card access","Enable audit trail for sensitive actions","Require MFA for administrators"].map((item, index) => <label key={item} className="flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-4"><span className="pr-5 text-[10px] font-bold text-slate-700">{item}</span><input type="checkbox" defaultChecked={index < 4} /></label>)}</div></section></div>{saved && <Notice text="Settings changes staged. Connect each control to its persisted school setting before production use." />}</div>;

  return <div className="space-y-5"><Header eyebrow="SukuuNova support" title="Help & Support" detail="Get answers, follow guided workflows and contact SukuuNova support without leaving the school workspace." action={<Link className={primary} href="/school/communications/messages">Message support</Link>} /><div className="grid gap-4 md:grid-cols-3">{[{ title: "Getting started", detail: "Understand people, academics, fees, communication and school setup." }, { title: "Troubleshooting", detail: "Find common fixes for login, reports, exports, notifications and integrations." }, { title: "Administrator centre", detail: "Manage permissions, access, security and school configuration." }].map((item) => <section key={item.title} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-sm font-black text-slate-950">{item.title}</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">{item.detail}</p><button className={`${secondary} mt-4`} type="button">Open guide</button></section>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 className="text-sm font-black text-slate-950">Search SukuuNova help</h3><p className="mt-1 text-[10px] text-slate-500">Search by page, action or error message.</p></div><input className="rounded-xl border border-slate-300 bg-white px-3 py-3 text-xs text-slate-900 md:w-80" placeholder={searchPlaceholder} value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{["How report cards are published","How to set up terms","How exports work","How to create delegated accounts"].map((item) => <button key={item} type="button" className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-left text-[10px] font-bold text-slate-700 hover:bg-white">{item}</button>)}</div></section><section className="rounded-2xl border border-slate-900 bg-slate-950 p-5 text-white"><h3 className="text-sm font-black">Contact SukuuNova support</h3><p className="mt-1 max-w-2xl text-[10px] leading-5 text-slate-300">When a guide is not enough, submit the school, module, error and what you were trying to do. A future support case centre can track priority, status, attachments and response history.</p><button className={`${commonButton} mt-4 bg-emerald-500 text-slate-950`} type="button">Open support case</button></section></div>;
}

function Notice({ text }: { text: string }) { return <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[10px] font-semibold text-emerald-900">{text}</div>; }
