"use client";

import { FormEvent, useMemo, useState } from "react";

type LeadershipAccount = { id: string; name: string; email: string | null; role: string; temporaryPassword: string };
type CreatedSchool = { id: string; leadership: LeadershipAccount[]; name: string; uniqueCode: string; ownerEmail: string; ownerPassword: string; billing: string };

const sections = ["School identity", "Owner & access", "Commercial setup", "Operational defaults"] as const;

export function SchoolOnboardingForm() {
  const [notice, setNotice] = useState("Provision a complete school tenant, not just a login account."), [created, setCreated] = useState<CreatedSchool | null>(null), [busy, setBusy] = useState(false);
  const [principalEnabled, setPrincipalEnabled] = useState(false);
  const [administratorEnabled, setAdministratorEnabled] = useState(false);
  const [billingMode, setBillingMode] = useState("flat");
  const selectedDescription = useMemo(() => billingMode === "per_student" ? "The invoice engine multiplies active students by the rate you set." : "The invoice engine uses one recurring amount for the school.", [billingMode]);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const input = Object.fromEntries(new FormData(form).entries());
    if (busy) return;
    const leadership = [
      ...(principalEnabled ? [{ role: "Principal", name: input.principalName, email: input.principalEmail }] : []),
      ...(administratorEnabled ? [{ role: "Administrator", name: input.administratorName, email: input.administratorEmail }] : []),
    ];
    setCreated(null); setBusy(true); setNotice("Creating the tenant, baseline roles, access and commercial rules…");
    try {
      const response = await fetch("/api/platform/schools", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...input, billingMode, leadership }) });
      const result = await response.json() as { message?: string; result?: { school?: { id?: string; name?: string; uniqueCode?: string }; leadership?: LeadershipAccount[]; billing?: { billingMode?: string; studentRate?: number; flatRate?: number } } };
      if (!response.ok) { setNotice(result.message ?? "Onboarding failed."); return; }
      const school = result.result?.school;
      setCreated({ id: school?.id ?? "", leadership: result.result?.leadership ?? [], name: school?.name ?? String(input.schoolName), uniqueCode: school?.uniqueCode ?? String(input.uniqueCode), ownerEmail: String(input.ownerEmail), ownerPassword: String(input.ownerPassword), billing: billingMode === "per_student" ? `${input.currency || "GHS"} ${input.studentRate || 0} per active student` : `${input.currency || "GHS"} ${input.flatRate || 0} flat monthly rate` });
      setNotice("School created. The tenant is ready for its first operational setup pass.");
      form.reset(); setBillingMode("flat"); setPrincipalEnabled(false); setAdministratorEnabled(false);
    } catch { setNotice("Onboarding failed. Please try again."); }
    finally { setBusy(false); }
  }

  const field = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-sky-500 focus:ring-2 focus:ring-sky-100";
  const label = "text-xs font-bold uppercase tracking-[0.08em] text-slate-500";
  return <div>
    {created ? <section className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-slate-900" role="status" aria-live="polite"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">School ready</p><h2 className="mt-1 text-2xl font-black tracking-tight">{created.name}</h2><p className="mt-2 text-sm text-slate-600">The initial handoff is shown once. The owner must change this password on first login.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-4"><span className="block text-xs text-slate-500">School code</span><strong>{created.uniqueCode}</strong></div><div className="rounded-xl bg-white p-4"><span className="block text-xs text-slate-500">Owner email</span><strong className="break-all">{created.ownerEmail}</strong></div><div className="rounded-xl bg-white p-4"><span className="block text-xs text-slate-500">Initial password</span><strong className="break-all">{created.ownerPassword}</strong></div><div className="rounded-xl bg-white p-4"><span className="block text-xs text-slate-500">Billing rule</span><strong>{created.billing}</strong></div></div>{created.leadership.map((person) => <div key={person.id} className="mt-3 rounded-xl bg-white p-4"><strong>{person.role}: {person.name}</strong><p className="break-all">{person.email}</p><p className="break-all">Temporary password: <code>{person.temporaryPassword}</code></p><p>Must change password on first login.</p></div>)}
      <ol className="mt-4 list-decimal space-y-1 pl-5 text-sm"><li>Securely hand each account holder their own login credentials.</li><li>Owner signs in and replaces the temporary password.</li><li>Configure the academic year, term, classes and subjects.</li><li>Add staff, teaching assignments, students and guardian links.</li><li>Review academic readiness before opening school workflows.</li></ol>
      <div className="mt-5 flex flex-wrap gap-2">{created.id ? <a href={`/platform/schools/${created.id}`} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Open School 360</a> : null}<button type="button" onClick={() => setCreated(null)} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-700">Hide credentials</button><a href={`/platform/schools`} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Open school network</a><a href={`/login/school`} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-700">School login</a></div></section> : <div className="mt-7 rounded-xl bg-slate-100 p-4 text-sm text-slate-700" role="status">{notice}</div>}

    <form className="mt-8 grid gap-5" onSubmit={submit}>
      <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-sky-700">01 · {sections[0]}</p><h2 className="mt-1 text-lg font-black text-slate-900">Identify the tenant clearly</h2><p className="mt-1 text-xs leading-5 text-slate-500">These details become the school’s operating identity.</p></div><div className="grid gap-4 md:grid-cols-2"><label><span className={label}>School name</span><input className={field} name="schoolName" placeholder="e.g. Accra Academy" required /></label><label><span className={label}>School login code</span><input className={field} name="uniqueCode" placeholder="e.g. accra-academy" pattern="[a-z0-9-]{3,40}" title="3–40 lowercase letters, numbers, or hyphens" required /></label><label><span className={label}>School type</span><select className={field} name="schoolType" defaultValue="basic_school"><option value="basic_school">Basic school</option><option value="senior_high">Senior high school</option><option value="private_school">Private school</option><option value="international">International school</option><option value="other">Other</option></select></label><label><span className={label}>Country</span><input className={field} name="country" defaultValue="Ghana" /></label><label><span className={label}>Region / state</span><input className={field} name="region" placeholder="e.g. Greater Accra" /></label><label><span className={label}>City / district</span><input className={field} name="city" placeholder="e.g. Accra" /></label><label className="md:col-span-2"><span className={label}>School address</span><input className={field} name="address" placeholder="Street address or postal address" /></label><label><span className={label}>School phone</span><input className={field} name="schoolPhone" placeholder="+233 …" /></label><label><span className={label}>School email</span><input className={field} name="schoolEmail" type="email" placeholder="office@school.example" /></label></div></section>

      <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-sky-700">02 · {sections[1]}</p><h2 className="mt-1 text-lg font-black text-slate-900">Create the first accountable operator</h2><p className="mt-1 text-xs leading-5 text-slate-500">The owner starts with the system Owner role and a forced password change.</p></div><div className="grid gap-4 md:grid-cols-2"><label><span className={label}>Owner name</span><input className={field} name="ownerName" placeholder="Full name" required /></label><label><span className={label}>Owner email</span><input className={field} name="ownerEmail" type="email" placeholder="owner@school.example" required /></label><label><span className={label}>Initial password</span><input className={field} name="ownerPassword" type="password" minLength={12} placeholder="12+ characters" required /></label><label><span className={label}>Owner phone</span><input className={field} name="ownerPhone" placeholder="Optional" /></label></div></section>

      <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5">
        <h2 className="text-lg font-black text-slate-900">Optional leadership accounts</h2>
        <p className="mt-1 text-xs leading-5 text-slate-500">Separate temporary passwords are generated securely. Each account must change its password on first login.</p>
        <label className="mt-4 flex items-center gap-2"><input type="checkbox" checked={principalEnabled} onChange={(event) => setPrincipalEnabled(event.target.checked)} />Create Principal / Headmaster account</label>
        {principalEnabled ? <div className="mt-3 grid gap-4 md:grid-cols-2"><label><span className={label}>Principal name</span><input className={field} name="principalName" minLength={2} maxLength={160} required /></label><label><span className={label}>Principal email</span><input className={field} name="principalEmail" type="email" required /></label></div> : null}
        <label className="mt-4 flex items-center gap-2"><input type="checkbox" checked={administratorEnabled} onChange={(event) => setAdministratorEnabled(event.target.checked)} />Create Administrator account</label>
        {administratorEnabled ? <div className="mt-3 grid gap-4 md:grid-cols-2"><label><span className={label}>Administrator name</span><input className={field} name="administratorName" minLength={2} maxLength={160} required /></label><label><span className={label}>Administrator email</span><input className={field} name="administratorEmail" type="email" required /></label></div> : null}
      </section>

      <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-sky-700">03 · {sections[2]}</p><h2 className="mt-1 text-lg font-black text-slate-900">Choose how this school is billed</h2><p className="mt-1 text-xs leading-5 text-slate-500">Subscription billing is separate from SMS/WhatsApp credit resale.</p></div><div className="grid gap-3 md:grid-cols-2"><button type="button" onClick={() => setBillingMode("per_student")} className={`rounded-2xl border p-5 text-left ${billingMode === "per_student" ? "border-sky-500 bg-white ring-2 ring-sky-100" : "border-slate-200 bg-white"}`}><strong className="block text-sm text-slate-900">Per student</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{selectedDescription}</span></button><button type="button" onClick={() => setBillingMode("flat")} className={`rounded-2xl border p-5 text-left ${billingMode === "flat" ? "border-sky-500 bg-white ring-2 ring-sky-100" : "border-slate-200 bg-white"}`}><strong className="block text-sm text-slate-900">Flat rate</strong><span className="mt-1 block text-xs leading-5 text-slate-500">One predictable recurring subscription amount.</span></button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className={label}>Currency</span><input className={field} name="currency" defaultValue="GHS" /></label><label><span className={label}>Student rate</span><input className={field} name="studentRate" type="number" min="0" step="0.01" defaultValue="0" disabled={billingMode !== "per_student"} /></label><label><span className={label}>Flat monthly rate</span><input className={field} name="flatRate" type="number" min="0" step="0.01" defaultValue="0" disabled={billingMode !== "flat"} /></label><label><span className={label}>Grace period (days)</span><input className={field} name="graceDays" type="number" min="0" max="90" defaultValue="7" /></label><label><span className={label}>Trial (days)</span><input className={field} name="trialDays" type="number" min="0" max="365" defaultValue="0" /></label></div></section>

      <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-sky-700">04 · {sections[3]}</p><h2 className="mt-1 text-lg font-black text-slate-900">Set the operating baseline</h2><p className="mt-1 text-xs leading-5 text-slate-500">Keep defaults explicit so the new school does not start with unexplained hidden assumptions.</p></div><div className="grid gap-4 md:grid-cols-2"><label><span className={label}>Timezone</span><input className={field} name="timezone" defaultValue="Africa/Accra" /></label><label><span className={label}>Billing day</span><input className={field} name="billingDay" type="number" min="1" max="28" defaultValue="1" /></label></div></section>

      <button disabled={busy} className="rounded-2xl bg-slate-900 px-5 py-4 text-sm font-black text-white shadow-lg shadow-slate-200 disabled:cursor-not-allowed disabled:opacity-60">{busy ? "Provisioning school…" : "Create & provision school"}</button>
    </form>
  </div>;
}
