"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { Check, CheckCircle2, Clock3, CopyCheck, FilePlus2, GraduationCap, Layers3, Save, Send, Sparkles, UsersRound } from "lucide-react";
import { parseMarkSheetPaste, type MarkStatus } from "@/lib/mark-sheet-input";

type Assignment={classId:string;subjectId:string;class:{id:string;name:string;level:string|null};subject:{id:string;name:string}};
type Term={id:string;name:string;startDate:string;endDate:string;isLocked:boolean;lifecycle?:{state:string;daysUntilEnd:number}};
type Contexts={assignments:Assignment[];terms:Term[];activeTermId:string|null;activeTerm:Term|null;timezone:string};
type Student={id:string;name:string;admissionNo:string};
type Score={id:string;studentId:string;value:number|string;status:MarkStatus;enteredAt:string};
type Work={id:string;assessmentId:string|null;title:string;kind:string;workDate:string;weekNumber:number;workNumber:number;maxScore:number|string;markingMode:string;status:string;dueAt:string|null;attemptLimit:number;attemptScorePolicy:"highest"|"latest"};
type Assessment={id:string;name:string;type:string;maxScore:number|string;weight:number|string;scores:Score[]};
type Roster={students:Student[];works:Work[];assessments:Assessment[];notes:Array<{id:string;title:string;status:string}>};
type Question={id:string;type:string;prompt:string;points:number;options:string;answers:string};

const dateKey=()=>new Date().toISOString().slice(0,10);
const questionTypes=[
 ["multiple_choice","Multiple choice"],["multiple_select","Choose all that apply"],["true_false","True / false"],["short_answer","Short answer"],["fill_blank","Fill in the blank"],["numeric","Numeric answer"],["ordering","Put in order"],["long_answer","Written / essay answer"]
] as const;
const usesOptions=(type:string)=>["multiple_choice","multiple_select","ordering"].includes(type);
const split=(text:string)=>text.split("\n").map(value=>value.trim()).filter(Boolean);
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function defaultQuestion():Question{return{id:uid(),type:"multiple_choice",prompt:"",points:1,options:"Option A\nOption B\nOption C\nOption D",answers:""};}
function answerHelp(type:string){if(type==="long_answer")return"Teacher keywords / key ideas, one per line. The system suggests a score; you still confirm it.";if(type==="short_answer")return"Accepted answer(s), one per line. Exact normalized matches can auto-mark.";if(type==="multiple_select")return"Every correct option, one per line.";if(type==="ordering")return"Correct order, one item per line.";if(type==="true_false")return"Enter true or false.";if(type==="numeric")return"Accepted numeric value(s), one per line.";if(type==="fill_blank")return"Accepted missing word(s), one per line.";return"Correct option, exactly as written above.";}
async function api(url:string,init?:RequestInit){const response=await fetch(url,init);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||body.error||"Request failed.");return body;}

export default function TeacherAcademicStudioV3(){
 const markRefs=useRef<Array<HTMLInputElement|null>>([]);
 const[contexts,setContexts]=useState<Contexts>({assignments:[],terms:[],activeTermId:null,activeTerm:null,timezone:"Africa/Accra"});
 const[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[roster,setRoster]=useState<Roster|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[selectedWorkId,setSelectedWorkId]=useState(""),[marks,setMarks]=useState<Record<string,string>>({}),[statuses,setStatuses]=useState<Record<string,MarkStatus>>({}),[dirty,setDirty]=useState<Record<string,boolean>>({}),[selectedStudents,setSelectedStudents]=useState<string[]>([]),[bulkScore,setBulkScore]=useState("");
 const[work,setWork]=useState({kind:"Homework",title:"",instructions:"",workDate:dateKey(),weekNumber:1,workNumber:1,maxScore:10,markingMode:"auto",attemptLimit:1,attemptScorePolicy:"highest" as "highest"|"latest",opensAt:"",dueAt:""});
 const[questions,setQuestions]=useState<Question[]>([defaultQuestion()]);

 const classes=useMemo(()=>Array.from(new Map(contexts.assignments.map(item=>[item.classId,item.class])).values()),[contexts.assignments]);
 const subjectAssignments=useMemo(()=>contexts.assignments.filter(item=>item.classId===classId),[contexts.assignments,classId]);
 const assignment=contexts.assignments.find(item=>item.classId===classId&&item.subjectId===subjectId);
 const selectedWork=roster?.works.find(item=>item.id===selectedWorkId);
 const assessment=roster?.assessments.find(item=>item.id===selectedWork?.assessmentId);
 const allocated=questions.reduce((sum,item)=>sum+(Number(item.points)||0),0);
 const dirtyCount=Object.values(dirty).filter(Boolean).length;
 const activeTerm=contexts.activeTerm;
 const writable=Boolean(contexts.activeTermId&&activeTerm&&!activeTerm.isLocked);

 async function loadContexts(){try{const data=await api("/api/school/teacher-academic-workspace") as Contexts;setContexts(data);const first=data.assignments[0];setClassId(current=>current||first?.classId||"");setSubjectId(current=>current||first?.subjectId||"");}catch(cause){setError(cause instanceof Error?cause.message:"Could not load teaching scope.");}}
 async function loadRoster(nextClass=classId,nextSubject=subjectId){if(!nextClass||!nextSubject||!contexts.activeTermId){setRoster(null);return;}try{const data=await api(`/api/school/teacher-academic-workspace?classId=${encodeURIComponent(nextClass)}&subjectId=${encodeURIComponent(nextSubject)}&termId=${encodeURIComponent(contexts.activeTermId)}`) as Roster;setRoster(data);setSelectedWorkId(current=>data.works.some(item=>item.id===current)?current:data.works[0]?.id||"");setSelectedStudents([]);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load class workspace.");}}
 useEffect(()=>{void loadContexts()},[]);
 useEffect(()=>{if(classId&&subjectId&&contexts.activeTermId)void loadRoster();},[classId,subjectId,contexts.activeTermId]);
 useEffect(()=>{const current=roster?.assessments.find(item=>item.id===roster?.works.find(work=>work.id===selectedWorkId)?.assessmentId);setMarks(Object.fromEntries((current?.scores||[]).map(score=>[score.studentId,String(score.value)])));setStatuses(Object.fromEntries((current?.scores||[]).map(score=>[score.studentId,score.status])));setDirty({});setSelectedStudents([]);},[selectedWorkId,roster]);
 useEffect(()=>{if(!dirtyCount)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirtyCount]);

 function chooseClass(value:string){if(dirtyCount&&!window.confirm("Discard unsaved mark changes?"))return;setClassId(value);const next=contexts.assignments.find(item=>item.classId===value);setSubjectId(next?.subjectId||"");setDirty({});}
 function mark(studentId:string,value:string,status:MarkStatus=statuses[studentId]||"present"){setMarks(current=>({...current,[studentId]:value}));setStatuses(current=>({...current,[studentId]:status}));setDirty(current=>({...current,[studentId]:true}));}
 function toggleStudent(id:string){setSelectedStudents(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);}
 function applyBulk(){const value=Number(bulkScore);const max=Number(selectedWork?.maxScore||0);if(!selectedStudents.length){setError("Select one or more learners first.");return;}if(!Number.isFinite(value)||value<0||value>max){setError(`Bulk mark must be between 0 and ${max}.`);return;}for(const id of selectedStudents)mark(id,String(value),"present");setNotice(`${selectedStudents.length} selected learner${selectedStudents.length===1?"":"s"} now have ${value}/${max}. Review, then save.`);setError("");}
 function pasteMarks(text:string,start:number){try{const students=roster?.students||[];const changes=parseMarkSheetPaste(text,start,students.length,Number(selectedWork?.maxScore||0));for(const change of changes){const student=students[change.row];if(student)mark(student.id,change.value,change.status);}setNotice(`${changes.length} pasted row${changes.length===1?"":"s"} ready to review.`);}catch(cause){setError(cause instanceof Error?cause.message:"Could not paste marks.");}}

 async function saveMarks(){if(!selectedWorkId||!roster)return;setBusy(true);setError("");setNotice("");try{const existing=new Map((assessment?.scores||[]).map(score=>[score.studentId,score]));const payload=roster.students.filter(student=>dirty[student.id]&&(marks[student.id]??"").trim()!=="").map(student=>{const before=existing.get(student.id);return{studentId:student.id,value:Number(marks[student.id]),status:statuses[student.id]||"present",expected:before?{id:before.id,value:Number(before.value),status:before.status,enteredAt:before.enteredAt}:null}});if(!payload.length)throw new Error("Change at least one mark before saving.");const max=Number(selectedWork?.maxScore||0);if(payload.some(item=>!Number.isFinite(item.value)||item.value<0||item.value>max))throw new Error(`Every mark must be between 0 and ${max}.`);if(payload.some(item=>item.status!=="present"&&item.value!==0))throw new Error("Absent or excused learners must store 0.");const result=await api("/api/school/teacher-academic-workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"saveMarks",workId:selectedWorkId,marks:payload})});setNotice(`${result.result.saved} mark${result.result.saved===1?"":"s"} saved and synchronized with the gradebook.`);setDirty({});await loadRoster();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save marks.");}finally{setBusy(false)}}
 async function createWork(){if(!contexts.activeTermId) return;setBusy(true);setError("");setNotice("");try{if(allocated!==Number(work.maxScore))throw new Error(`Question marks total ${allocated}, but the work is out of ${work.maxScore}. Make them equal before saving.`);if(!questions.length)throw new Error("Add at least one question.");const opensAt=work.opensAt?new Date(work.opensAt).toISOString():null,dueAt=work.dueAt?new Date(work.dueAt).toISOString():null;await api("/api/school/teacher-academic-workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"createWork",termId:contexts.activeTermId,classId,subjectId,...work,opensAt,dueAt,questionList:questions.map(question=>({type:question.type,prompt:question.prompt,points:Number(question.points),options:usesOptions(question.type)?split(question.options):[],acceptedAnswers:split(question.answers)}))})});setNotice("Assessment saved as a draft. Open it in the mark sheet to publish when ready.");setWork(current=>({...current,title:"",instructions:"",workNumber:current.workNumber+1}));setQuestions([defaultQuestion()]);await loadRoster();}catch(cause){setError(cause instanceof Error?cause.message:"Could not create work.");}finally{setBusy(false)}}
 async function publish(){if(!selectedWorkId)return;setBusy(true);setError("");try{await api("/api/school/teacher-academic-workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publishWork",workId:selectedWorkId})});setNotice("Activity published. Learners and linked guardians can now use its configured submission window.");await loadRoster();}catch(cause){setError(cause instanceof Error?cause.message:"Could not publish work.");}finally{setBusy(false)}}
 function equalize(){if(!questions.length)return;const total=Number(work.maxScore)||0;const base=Math.floor(total*100/questions.length)/100;let used=0;setQuestions(current=>current.map((item,index)=>{const points=index===current.length-1?Math.round((total-used)*100)/100:base;used+=points;return{...item,points}}));}

 return <div className="tas-page">
  <section className="tas-hero"><div><span>TEACHER · ASSESSMENT STUDIO</span><h1>Create the assessment once. Let marks, submissions and the gradebook stay connected.</h1><p>The school controls the academic term. You choose only the class, subject, week, date, work number and assessment design.</p></div><div className="tas-term"><Clock3 size={19}/><span>Current school term</span><strong>{activeTerm?.name||"No live term"}</strong><small>{activeTerm?.lifecycle?.daysUntilEnd!=null?`${activeTerm.lifecycle.daysUntilEnd} day(s) to configured term end · ${contexts.timezone}`:"Leadership controls the term calendar."}</small></div></section>
  {error?<div className="tas-alert bad" role="alert">{error}</div>:null}{notice?<div className="tas-alert good" role="status"><CheckCircle2 size={16}/>{notice}</div>:null}
  <section className="tas-context"><header><div><span>TEACHING CONTEXT</span><h2>Choose the class and subject you are working on</h2></div><div className="tas-scope"><UsersRound size={15}/>Only assigned teaching scope appears</div></header><div className="tas-context-grid"><label>Class<select value={classId} onChange={e=>chooseClass(e.target.value)}>{classes.map(item=><option key={item.id} value={item.id}>{item.level?`${item.level} · `:""}{item.name}</option>)}</select></label><label>Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjectAssignments.map(item=><option key={item.subjectId} value={item.subjectId}>{item.subject.name}</option>)}</select></label><div className="tas-context-readonly"><span>Academic term</span><b>{activeTerm?.name||"Not active"}</b><small>Not selectable by teachers</small></div><div className="tas-context-readonly"><span>Learners</span><b>{roster?.students.length??0}</b><small>{assignment?`${assignment.class.name} · ${assignment.subject.name}`:"No teaching assignment"}</small></div></div></section>

  <section className="tas-section" id="marks"><header><div><span>FAST MARK SHEET</span><h2>Enter or edit marks without wasting time</h2><p>Choose a work, paste a column, type down the list, or select several learners and apply one score.</p></div><Layers3 size={22}/></header><div className="tas-workbar"><label>Assessment / work<select value={selectedWorkId} onChange={e=>{if(dirtyCount&&!window.confirm("Discard unsaved mark changes?"))return;setSelectedWorkId(e.target.value)}}><option value="">Choose work…</option>{(roster?.works||[]).map(item=><option key={item.id} value={item.id}>{item.kind} · Week {item.weekNumber} · #{item.workNumber} · {item.title}</option>)}</select></label><div className="tas-workmeta">{selectedWork?<><span>Out of <b>{Number(selectedWork.maxScore)}</b></span><span>{selectedWork.status}</span><span>{selectedWork.markingMode}</span></>:<span>Create or choose a work.</span>}</div>{selectedWork?.status==="draft"?<button disabled={busy||!writable} onClick={()=>void publish()}><Send size={15}/>Publish</button>:selectedWork?.status==="published"?<Link href={`/teacher/studio/review?workId=${encodeURIComponent(selectedWork.id)}`}>Review submissions →</Link>:null}</div>
   {selectedWork?<><div className="tas-bulk"><span><CopyCheck size={16}/><b>Same score for several learners</b></span><input inputMode="decimal" placeholder={`0–${Number(selectedWork.maxScore)}`} value={bulkScore} onChange={e=>setBulkScore(e.target.value)}/><button onClick={applyBulk} disabled={!selectedStudents.length}>Apply to {selectedStudents.length||"selected"}</button><button onClick={()=>setSelectedStudents((roster?.students||[]).map(student=>student.id))}>Select all</button><button onClick={()=>setSelectedStudents([])}>Clear</button></div><div className="tas-table-wrap"><table><thead><tr><th><span className="sr-only">Select</span></th><th>Learner</th><th>Score</th><th>Status</th><th>Out of</th></tr></thead><tbody>{(roster?.students||[]).map((student,index)=><tr key={student.id} className={selectedStudents.includes(student.id)?"selected":""}><td><input type="checkbox" aria-label={`Select ${student.name}`} checked={selectedStudents.includes(student.id)} onChange={()=>toggleStudent(student.id)}/></td><td><b>{student.name}</b><small>{student.admissionNo}</small></td><td><input ref={element=>{markRefs.current[index]=element}} inputMode="decimal" value={marks[student.id]??""} placeholder="—" onChange={e=>mark(student.id,e.target.value)} onPaste={e=>{e.preventDefault();pasteMarks(e.clipboardData.getData("text"),index)}} onKeyDown={e=>{if(["Enter","ArrowDown","ArrowUp"].includes(e.key)){e.preventDefault();const next=index+(e.key==="ArrowUp"||(e.key==="Enter"&&e.shiftKey)?-1:1);markRefs.current[next]?.focus();markRefs.current[next]?.select()}}}/></td><td><select value={statuses[student.id]||"present"} onChange={e=>{const status=e.target.value as MarkStatus;mark(student.id,status==="present"?(marks[student.id]??""):"0",status)}}><option value="present">Present</option><option value="absent">Absent</option><option value="excused">Excused</option></select></td><td>{Number(selectedWork.maxScore)}</td></tr>)}</tbody></table></div><footer className="tas-savebar"><span>{dirtyCount} unsaved row{dirtyCount===1?"":"s"}</span><button className="tas-primary" disabled={!dirtyCount||busy||!writable} onClick={()=>void saveMarks()}><Save size={15}/>{busy?"Saving…":"Save changed marks"}</button></footer></>:<div className="tas-empty"><GraduationCap size={28}/><b>No assessment selected.</b><span>Create one below or choose an existing work.</span></div>}
  </section>

  <section className="tas-section" id="activities"><header><div><span>ADVANCED ACTIVITY BUILDER</span><h2>Build forms that go beyond a basic Google Form</h2><p>Multiple question types, per-question marks, retries, automatic objective marking, teacher-assisted written marking and precise opening/closing times.</p></div><Sparkles size={22}/></header><div className="tas-builder-grid"><label>Assessment type<select value={work.kind} onChange={e=>setWork({...work,kind:e.target.value})}>{["Participation","Classwork","Exercise","Homework","Quiz","Exam"].map(item=><option key={item}>{item}</option>)}</select></label><label>Week<input type="number" min={1} max={60} value={work.weekNumber} onChange={e=>setWork({...work,weekNumber:Number(e.target.value)})}/></label><label>Work number<input type="number" min={1} max={50} value={work.workNumber} onChange={e=>setWork({...work,workNumber:Number(e.target.value)})}/></label><label>Assessment date<input type="date" value={work.workDate} onChange={e=>setWork({...work,workDate:e.target.value})}/></label><label>Maximum score<input type="number" min={1} value={work.maxScore} onChange={e=>setWork({...work,maxScore:Number(e.target.value)})}/></label><label>Marking<select value={work.markingMode} onChange={e=>setWork({...work,markingMode:e.target.value})}><option value="auto">Auto-mark objective answers</option><option value="review">Auto + teacher review for written answers</option><option value="manual">Teacher marks manually</option></select></label><label>Attempts<input type="number" min={1} max={10} value={work.attemptLimit} onChange={e=>setWork({...work,attemptLimit:Number(e.target.value)})}/></label><label>Gradebook attempt<select disabled={work.attemptLimit<=1} value={work.attemptScorePolicy} onChange={e=>setWork({...work,attemptScorePolicy:e.target.value as "highest"|"latest"})}><option value="highest">Highest graded attempt</option><option value="latest">Latest graded attempt</option></select></label><label>Opens at<input type="datetime-local" value={work.opensAt} onChange={e=>setWork({...work,opensAt:e.target.value})}/></label><label>Closes at<input type="datetime-local" value={work.dueAt} onChange={e=>setWork({...work,dueAt:e.target.value})}/></label><label className="wide">Title<input value={work.title} onChange={e=>setWork({...work,title:e.target.value})} placeholder="e.g. Week 4 Fractions Quiz — Work 2"/></label><label className="wide">Learner instructions<textarea rows={3} value={work.instructions} onChange={e=>setWork({...work,instructions:e.target.value})} placeholder="What should learners do? Include any materials or submission rules."/></label></div>
   <div className="tas-question-head"><div><b>Questions</b><span>{questions.length} question{questions.length===1?"":"s"} · {allocated}/{work.maxScore} marks allocated</span></div><div><button onClick={equalize}>Distribute marks</button><button onClick={()=>setQuestions(current=>[...current,defaultQuestion()])}><FilePlus2 size={15}/>Add question</button></div></div><div className="tas-questions">{questions.map((question,index)=><article key={question.id}><div className="tas-qno"><strong>{index+1}</strong><button aria-label={`Delete question ${index+1}`} onClick={()=>setQuestions(current=>current.filter(item=>item.id!==question.id))}>×</button></div><div className="tas-qbody"><div className="tas-qtop"><select value={question.type} onChange={e=>setQuestions(current=>current.map(item=>item.id===question.id?{...item,type:e.target.value,options:usesOptions(e.target.value)?item.options:"",answers:""}:item))}>{questionTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Marks<input type="number" min={.01} step="0.01" value={question.points} onChange={e=>setQuestions(current=>current.map(item=>item.id===question.id?{...item,points:Number(e.target.value)}:item))}/></label></div><textarea rows={2} value={question.prompt} onChange={e=>setQuestions(current=>current.map(item=>item.id===question.id?{...item,prompt:e.target.value}:item))} placeholder={question.type==="fill_blank"?"Write the question and place ___ where the answer belongs.":"Write the question clearly…"}/>{usesOptions(question.type)?<label>Options / ordering items<textarea rows={4} value={question.options} onChange={e=>setQuestions(current=>current.map(item=>item.id===question.id?{...item,options:e.target.value}:item))} placeholder="One item per line"/></label>:null}<label>{question.type==="long_answer"?"Key ideas for assisted marking":"Accepted answer(s)"}<textarea rows={3} value={question.answers} onChange={e=>setQuestions(current=>current.map(item=>item.id===question.id?{...item,answers:e.target.value}:item))} placeholder={answerHelp(question.type)}/><small>{answerHelp(question.type)}</small></label></div></article>)}</div><footer className="tas-builder-save"><span className={allocated===Number(work.maxScore)?"ready":"warning"}>{allocated===Number(work.maxScore)?<><Check size={14}/>Question marks match overall score</>:`Allocate exactly ${work.maxScore} marks before saving`}</span><button className="tas-primary" disabled={busy||!writable||allocated!==Number(work.maxScore)||!work.title.trim()} onClick={()=>void createWork()}><Save size={15}/>Save assessment draft</button></footer>
  </section>
 </div>;
}
