"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpenCheck, CheckCircle2, Clock3, FileEdit, Plus, Save, Send, Sparkles } from "lucide-react";
import TeacherDocumentEditor, { starterLessonBlocks, type LessonBlock } from "@/components/TeacherDocumentEditor";

type Assignment={classId:string;subjectId:string;class:{name:string;level:string|null};subject:{name:string}};
type Term={id:string;name:string;startDate:string;endDate:string;isLocked:boolean;academicYear:{name:string};lifecycle:{state:string;daysUntilEnd:number}};
type Row={id:string;updatedAt:string;classId:string;className:string;subjectId:string;subjectName:string;termId:string|null;termName:string|null;title:string;topic:string|null;subTopic:string|null;curriculumObjective:string|null;learningOutcomes:string|null;priorKnowledge:string|null;materials:string|null;introduction:string|null;development:string|null;differentiatedActivities:string|null;assessment:string|null;conclusion:string|null;homework:string|null;objective:string|null;content:string;resources:unknown;documentContent:unknown;plannedDate:string;status:string;reviewNote:string|null;reviewerName:string|null;reviewedAt:string|null;submittedAt:string|null;completedAt:string|null;reflection:string|null};
type Data={assignments:Assignment[];terms:Term[];activeTermId:string|null;timezone:string;rows:Row[]};
type Form={id?:string;expectedUpdatedAt?:string;classId:string;subjectId:string;plannedDate:string;weekNumber:number;title:string;topic:string;subTopic:string;curriculumObjective:string;learningOutcomes:string;priorKnowledge:string;materials:string;introduction:string;development:string;differentiatedActivities:string;assessment:string;conclusion:string;homework:string;objective:string;resources:{label:string;url:string}[];blocks:LessonBlock[]};

const today=()=>new Date().toISOString().slice(0,10);
const empty=(assignment?:Assignment):Form=>({classId:assignment?.classId||"",subjectId:assignment?.subjectId||"",plannedDate:today(),weekNumber:1,title:"",topic:"",subTopic:"",curriculumObjective:"",learningOutcomes:"",priorKnowledge:"",materials:"",introduction:"",development:"",differentiatedActivities:"",assessment:"",conclusion:"",homework:"",objective:"",resources:[],blocks:starterLessonBlocks()});
function blocksFrom(value:unknown):LessonBlock[]{if(!value||typeof value!=="object"||Array.isArray(value))return starterLessonBlocks();const blocks=(value as {blocks?:unknown}).blocks;return Array.isArray(blocks)&&blocks.length?blocks as LessonBlock[]:starterLessonBlocks();}
function resourcesFrom(value:unknown):{label:string;url:string}[]{return Array.isArray(value)?value.filter((item):item is {label:string;url:string}=>!!item&&typeof item==="object"&&typeof (item as {label?:unknown}).label==="string"&&typeof (item as {url?:unknown}).url==="string"):[];}
function formFrom(row:Row):Form{return{id:row.id,expectedUpdatedAt:row.updatedAt,classId:row.classId,subjectId:row.subjectId,plannedDate:row.plannedDate.slice(0,10),weekNumber:Number((row.documentContent as {weekNumber?:number}|null)?.weekNumber||1),title:row.title,topic:row.topic||"",subTopic:row.subTopic||"",curriculumObjective:row.curriculumObjective||"",learningOutcomes:row.learningOutcomes||"",priorKnowledge:row.priorKnowledge||"",materials:row.materials||"",introduction:row.introduction||"",development:row.development||"",differentiatedActivities:row.differentiatedActivities||"",assessment:row.assessment||"",conclusion:row.conclusion||"",homework:row.homework||"",objective:row.objective||"",resources:resourcesFrom(row.resources),blocks:blocksFrom(row.documentContent)};}
async function api(init?:RequestInit){const r=await fetch("/api/teacher/lesson-studio",init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Lesson request failed.");return d;}

export default function TeacherLessonStudio(){
 const[data,setData]=useState<Data|null>(null),[editing,setEditing]=useState(false),[form,setForm]=useState<Form>(empty()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[filter,setFilter]=useState("all"),[reflection,setReflection]=useState("");
 const activeTerm=data?.terms.find(term=>term.id===data.activeTermId)||null;
 const assignments=useMemo(()=>data?.assignments??[],[data]);
 const visible=useMemo(()=>{const rows=data?.rows??[];return filter==="all"?rows:rows.filter(row=>row.status===filter)},[data,filter]);
 const selectedAssignment=assignments.find(item=>item.classId===form.classId&&item.subjectId===form.subjectId);
 const load=async()=>{try{const next=await api() as Data;setData(next);setForm(current=>current.classId?current:empty(next.assignments[0]));}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load lessons.")}};
 useEffect(()=>{void load()},[]);
 const start=()=>{setForm(empty(assignments[0]));setEditing(true);setError("");setNotice("")};
 const edit=(row:Row)=>{setForm(formFrom(row));setEditing(true);setError("");setNotice("")};
 async function save(status:"draft"|"submitted"){
  if(!data?.activeTermId){setError("There is no active academic term today.");return;}setBusy(true);setError("");setNotice("");
  try{const result=await api({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",...form,termId:data.activeTermId,status})});setNotice(status==="submitted"?"Lesson note submitted to academic leadership for verification.":"Lesson note saved as a private draft.");setEditing(false);setForm(empty(assignments[0]));await load();return result;}catch(cause){setError(cause instanceof Error?cause.message:"Could not save lesson.")}finally{setBusy(false)}
 }
 async function transition(row:Row,status:"completed"|"archived") {setBusy(true);setError("");try{await api({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"transition",id:row.id,status,reflection:status==="completed"?reflection:undefined})});setNotice(status==="completed"?"Lesson marked taught and reflection saved.":"Lesson archived.");setReflection("");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Could not update lesson.")}finally{setBusy(false)}}
 const counts=Object.fromEntries(["draft","submitted","approved","changes_requested","completed","archived"].map(status=>[status,(data?.rows??[]).filter(row=>row.status===status).length]));
 return <div className="tls-page">
  <section className="tls-hero"><div><span>TEACHER · LESSON STUDIO</span><h1>Write, structure and submit lesson notes like real teaching documents.</h1><p>Build a rich weekly lesson document, keep curriculum fields structured for leadership, then submit it into the existing human verification workflow.</p></div><div className="tls-term"><Clock3 size={20}/><span>School-selected term</span><strong>{activeTerm?.name||"No active term"}</strong><small>{activeTerm?`${activeTerm.academicYear.name} · ${activeTerm.lifecycle.daysUntilEnd} day(s) to configured end`:"Leadership must configure a live term."}</small></div></section>
  {error?<div className="tls-alert bad" role="alert">{error}</div>:null}{notice?<div className="tls-alert good" role="status"><CheckCircle2 size={16}/>{notice}</div>:null}
  {!editing?<><section className="tls-kpis"><article><strong>{data?.rows.length??0}</strong><span>My lesson plans</span></article><article><strong>{counts.submitted||0}</strong><span>Awaiting review</span></article><article><strong>{counts.changes_requested||0}</strong><span>Needs revision</span></article><article><strong>{(counts.approved||0)+(counts.completed||0)}</strong><span>Approved / taught</span></article></section>
   <section className="tls-card"><header><div><span>MY LESSON PIPELINE</span><h2>Weekly plans and verification</h2></div><button className="tls-primary" type="button" disabled={!activeTerm||!assignments.length} onClick={start}><Plus size={16}/>New lesson note</button></header><div className="tls-tabs">{[["all","All"],["draft","Drafts"],["submitted","Awaiting review"],["changes_requested","Needs changes"],["approved","Approved"],["completed","Taught"]].map(([key,label])=><button type="button" key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div><div className="tls-list">{visible.length?visible.map(row=><article key={row.id}><div className="tls-doc-icon"><FileEdit size={19}/></div><div><span>{row.className} · {row.subjectName} · {new Date(row.plannedDate).toLocaleDateString("en-GB")}</span><h3>{row.title}</h3><p>{row.topic||row.learningOutcomes||row.content.slice(0,180)}</p>{row.reviewNote?<div className="tls-review-note"><b>{row.status==="changes_requested"?"Leadership revision note":"Review note"}</b><span>{row.reviewNote}</span></div>:null}</div><aside><span className={`tls-status ${row.status}`}>{row.status.replaceAll("_"," ")}</span>{["draft","changes_requested"].includes(row.status)?<button type="button" onClick={()=>edit(row)}>Continue editing</button>:null}{row.status==="approved"?<><textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="After teaching, add a short reflection…"/><button type="button" disabled={busy||reflection.trim().length<10} onClick={()=>void transition(row,"completed")}>Mark taught</button></>:null}{row.status==="completed"?<button type="button" disabled={busy} onClick={()=>void transition(row,"archived")}>Archive</button>:null}</aside></article>):<div className="tls-empty"><BookOpenCheck size={32}/><b>No lesson plans in this view.</b><span>Create a lesson note or switch the pipeline filter.</span></div>}</div></section></>:
  <section className="tls-editor-shell"><header><div><span>{form.id?"EDIT LESSON DOCUMENT":"NEW LESSON DOCUMENT"}</span><h2>{form.title||"Untitled lesson note"}</h2><p>{selectedAssignment?`${selectedAssignment.class.level?`${selectedAssignment.class.level} · `:""}${selectedAssignment.class.name} · ${selectedAssignment.subject.name}`:"Choose a teaching context"} · {activeTerm?.name||"No active term"}</p></div><div><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button type="button" disabled={busy} onClick={()=>void save("draft")}><Save size={15}/>Save draft</button><button className="tls-primary" type="button" disabled={busy||!activeTerm} onClick={()=>void save("submitted")}><Send size={15}/>Submit for verification</button></div></header>
   <div className="tls-context-grid"><label>Class & subject<select value={`${form.classId}:${form.subjectId}`} onChange={e=>{const chosen=assignments.find(item=>`${item.classId}:${item.subjectId}`===e.target.value);if(chosen)setForm({...form,classId:chosen.classId,subjectId:chosen.subjectId})}}>{assignments.map(item=><option key={`${item.classId}:${item.subjectId}`} value={`${item.classId}:${item.subjectId}`}>{item.class.level?`${item.class.level} · `:""}{item.class.name} · {item.subject.name}</option>)}</select></label><label>Week<input type="number" min={1} max={60} value={form.weekNumber} onChange={e=>setForm({...form,weekNumber:Number(e.target.value)})}/></label><label>Teaching date<input type="date" value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label><label>Lesson title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Equivalent fractions using visual models"/></label><label>Topic<input value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Sub-topic<input value={form.subTopic} onChange={e=>setForm({...form,subTopic:e.target.value})}/></label></div>
   <div className="tls-intelligence"><div><Sparkles size={17}/><span><b>Structured teaching intelligence</b>These fields make leadership review, search and future analytics dependable.</span></div><div className="tls-field-grid"><label>Curriculum objective<textarea rows={3} value={form.curriculumObjective} onChange={e=>setForm({...form,curriculumObjective:e.target.value})}/></label><label>Learning outcomes *<textarea rows={3} value={form.learningOutcomes} onChange={e=>setForm({...form,learningOutcomes:e.target.value})} placeholder="What should learners know or be able to do?"/></label><label>Prior knowledge<textarea rows={3} value={form.priorKnowledge} onChange={e=>setForm({...form,priorKnowledge:e.target.value})}/></label><label>Materials / TLRs<textarea rows={3} value={form.materials} onChange={e=>setForm({...form,materials:e.target.value})}/></label><label>Introduction<textarea rows={4} value={form.introduction} onChange={e=>setForm({...form,introduction:e.target.value})}/></label><label>Development / learner activities *<textarea rows={4} value={form.development} onChange={e=>setForm({...form,development:e.target.value})}/></label><label>Differentiation<textarea rows={4} value={form.differentiatedActivities} onChange={e=>setForm({...form,differentiatedActivities:e.target.value})}/></label><label>Assessment evidence *<textarea rows={4} value={form.assessment} onChange={e=>setForm({...form,assessment:e.target.value})}/></label><label>Conclusion / plenary<textarea rows={3} value={form.conclusion} onChange={e=>setForm({...form,conclusion:e.target.value})}/></label><label>Homework / extension<textarea rows={3} value={form.homework} onChange={e=>setForm({...form,homework:e.target.value})}/></label></div></div>
   <div className="tls-document"><div className="tls-document-head"><div><span>RICH LESSON DOCUMENT</span><h3>Build the actual note</h3></div><p>Headings, paragraphs, lists, quotations, callouts, images and tables are stored as structured blocks rather than unsafe pasted HTML.</p></div><TeacherDocumentEditor value={form.blocks} onChange={blocks=>setForm({...form,blocks})}/></div>
   <footer className="tls-editor-actions"><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button type="button" disabled={busy} onClick={()=>void save("draft")}><Save size={15}/>Save draft</button><button className="tls-primary" type="button" disabled={busy||!activeTerm} onClick={()=>void save("submitted")}><Send size={15}/>Submit to leadership</button></footer>
  </section>}
 </div>;
}
