"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { BellRing, CalendarClock, CheckCircle2, Home, LayoutPanelTop, Save, ShieldCheck, SlidersHorizontal } from "lucide-react";
import "./settings.css";

type Admin = { name: string; email: string; role: string; status: string };
type Preferences = {
  defaultLanding: "/platform" | "/platform/schools" | "/platform/audit" | "/platform/billing";
  timezone: string; dateFormat: "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD"; timeFormat: "12h" | "24h";
  compactInterface: boolean; reduceMotion: boolean; notifySecurity: boolean; notifyBilling: boolean; notifySupport: boolean; notifySystem: boolean;
};

const defaults: Preferences = { defaultLanding: "/platform", timezone: "Africa/Accra", dateFormat: "DD/MM/YYYY", timeFormat: "24h", compactInterface: false, reduceMotion: false, notifySecurity: true, notifyBilling: true, notifySupport: true, notifySystem: true };

export default function AccountSettingsPage() {
  const [admin, setAdmin] = useState<Admin | null>(null), [prefs, setPrefs] = useState<Preferences>(defaults), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { void (async () => { const response = await fetch("/api/account/settings", { cache: "no-store" }); if (response.ok) { const data = await response.json() as { admin: Admin; preferences: Preferences }; setAdmin(data.admin); setPrefs({ ...defaults, ...data.preferences }); } })(); }, []);
  const save = async () => { setBusy(true); setMessage(""); try { const response = await fetch("/api/account/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(prefs) }); const data = await response.json() as { message?: string; error?: string }; setMessage(response.ok ? "Account preferences saved." : (data.message ?? data.error ?? "Unable to save preferences.")); } finally { setBusy(false); } };
  return <main className="account-settings-page"><header><div><span className="account-settings-eyebrow">MY WORKSPACE</span><h1>Account Settings</h1><p>Configure how your SukuuNova platform administrator workspace behaves. Security credentials remain in the dedicated security centre.</p></div><div className="account-settings-actions"><Link href="/account/security" className="account-settings-button secondary"><ShieldCheck size={14}/>Security centre</Link><button type="button" className="account-settings-button" onClick={() => void save()} disabled={busy}><Save size={14}/>{busy ? "Saving…" : "Save preferences"}</button></div></header>
    {message && <div className="account-settings-message" role="status"><CheckCircle2 size={15}/><span>{message}</span></div>}
    {admin && <section className="account-settings-profile"><div><span>Signed-in administrator</span><strong>{admin.name}</strong><small>{admin.email}</small></div><div><span>Role</span><strong>{admin.role}</strong><small>{admin.status}</small></div></section>}
    <div className="account-settings-grid"><section className="account-settings-card"><div className="account-settings-card-head"><div><span>Workspace</span><h2>Default behaviour</h2><p>Make your most common destination and display conventions persistent.</p></div><Home size={19}/></div><label>Default landing page<select value={prefs.defaultLanding} onChange={(e) => setPrefs({ ...prefs, defaultLanding: e.target.value as Preferences["defaultLanding"] })}><option value="/platform">Control Center</option><option value="/platform/schools">Schools</option><option value="/platform/audit">Audit Log</option><option value="/platform/billing">Platform Billing</option></select></label><label>Timezone<input value={prefs.timezone} onChange={(e) => setPrefs({ ...prefs, timezone: e.target.value })}/></label></section>
      <section className="account-settings-card"><div className="account-settings-card-head"><div><span>Display</span><h2>Date, time & density</h2><p>Keep numbers and operational timestamps easy to read throughout the workspace.</p></div><LayoutPanelTop size={19}/></div><label>Date format<select value={prefs.dateFormat} onChange={(e) => setPrefs({ ...prefs, dateFormat: e.target.value as Preferences["dateFormat"] })}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label>Time format<select value={prefs.timeFormat} onChange={(e) => setPrefs({ ...prefs, timeFormat: e.target.value as Preferences["timeFormat"] })}><option value="24h">24-hour</option><option value="12h">12-hour</option></select></label><div className="account-settings-checks"><label><input type="checkbox" checked={prefs.compactInterface} onChange={(e) => setPrefs({ ...prefs, compactInterface: e.target.checked })}/><span><strong>Compact interface</strong><small>Prefer denser navigation and controls.</small></span></label><label><input type="checkbox" checked={prefs.reduceMotion} onChange={(e) => setPrefs({ ...prefs, reduceMotion: e.target.checked })}/><span><strong>Reduce motion</strong><small>Limit transition and animation effects.</small></span></label></div></section>
      <section className="account-settings-card account-settings-card-wide"><div className="account-settings-card-head"><div><span>Notifications</span><h2>Operator alerts</h2><p>Choose which categories deserve attention from your administrator workspace.</p></div><BellRing size={19}/></div><div className="account-settings-notifications"><label><input type="checkbox" checked={prefs.notifySecurity} onChange={(e) => setPrefs({ ...prefs, notifySecurity: e.target.checked })}/><span><strong>Security alerts</strong><small>Authentication, privileged actions and access changes.</small></span></label><label><input type="checkbox" checked={prefs.notifyBilling} onChange={(e) => setPrefs({ ...prefs, notifyBilling: e.target.checked })}/><span><strong>Billing alerts</strong><small>Invoice, payment and commercial exceptions.</small></span></label><label><input type="checkbox" checked={prefs.notifySupport} onChange={(e) => setPrefs({ ...prefs, notifySupport: e.target.checked })}/><span><strong>Support alerts</strong><small>Urgent customer cases and unresolved queues.</small></span></label><label><input type="checkbox" checked={prefs.notifySystem} onChange={(e) => setPrefs({ ...prefs, notifySystem: e.target.checked })}/><span><strong>System alerts</strong><small>Application health, jobs, migrations and outages.</small></span></label></div></section>
      <section className="account-settings-card account-settings-card-wide"><div className="account-settings-card-head"><div><span>Control boundaries</span><h2>What this page does not change</h2><p>Security-sensitive controls stay separated so a preference change can never silently alter administrator privileges.</p></div><SlidersHorizontal size={19}/></div><div className="account-settings-boundaries"><div><strong>Permissions</strong><small>Managed by Workers & Permissions.</small></div><div><strong>School scope</strong><small>Managed by Worker School Scope.</small></div><div><strong>Password & sessions</strong><small>Managed by Security Centre and session controls.</small></div><div><strong>Platform policy</strong><small>Managed by Platform Settings.</small></div></div></section></div>
  </main>;
}
