import { NextResponse } from "next/server";
import { z } from "zod";
import { requireSchoolSession } from "@/lib/auth";
import { withTenant } from "@/lib/db";
import { routeError } from "@/lib/errors";
import { parseJson } from "@/lib/http";
import { hasPermission } from "@/lib/rbac";
import { requireSchoolFeatureInTransaction } from "@/lib/feature-flags";
import { createPayrollRun, commitPayrollRun, markPayrollPaid, planPayrollRun, renderPlannedPayslips, setSalaryStructure, visiblePayslips } from "@/lib/payroll-service";
const deduction=z.object({label:z.string().trim().min(1).max(80),type:z.enum(["fixed","percent"]),value:z.number().finite().nonnegative().max(1_000_000_000)});
const schema=z.discriminatedUnion("action",[z.object({action:z.literal("salaryStructure"),staffId:z.string().min(1).max(100),grossSalary:z.number().finite().positive().max(1_000_000_000),deductions:z.array(deduction).max(50)}),z.object({action:z.literal("createRun"),period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/)}),z.object({action:z.literal("processRun"),payrollRunId:z.string().min(1).max(100)}),z.object({action:z.literal("markPaid"),payrollRunId:z.string().min(1).max(100)})]);
export async function GET(){try{const session=await requireSchoolSession();const data=await withTenant(session.schoolId,async(tx)=>{await requireSchoolFeatureInTransaction(tx,session.schoolId,"payroll");const payslips=(await visiblePayslips(tx,{schoolId:session.schoolId,userId:session.userId})).map(({pdfData:_pdfData,...row})=>row);const canManage=await hasPermission(tx,session.userId,"payroll:manage");if(!canManage)return{canManage,payslips,runs:[],structures:[],staff:[]};const[runs,structures,staff]=await Promise.all([tx.payrollRun.findMany({where:{schoolId:session.schoolId},orderBy:{period:"desc"}}),tx.salaryStructure.findMany({where:{schoolId:session.schoolId},include:{staff:{select:{name:true}}},orderBy:{staff:{name:"asc"}}}),tx.user.findMany({where:{schoolId:session.schoolId,status:"active"},select:{id:true,name:true,email:true},orderBy:{name:"asc"}})]);return{canManage,payslips,runs,structures,staff};});return NextResponse.json(data);}catch(error){return routeError(error);}}
export async function POST(request:Request){try{const session=await requireSchoolSession();const input=await parseJson(request,schema);if(input.action==="processRun"){const plan=await withTenant(session.schoolId,async(tx)=>{await requireSchoolFeatureInTransaction(tx,session.schoolId,"payroll");return planPayrollRun(tx,{schoolId:session.schoolId,actorId:session.userId,payrollRunId:input.payrollRunId});});const rendered=await renderPlannedPayslips(plan);const result=await withTenant(session.schoolId,async(tx)=>{await requireSchoolFeatureInTransaction(tx,session.schoolId,"payroll");return commitPayrollRun(tx,{schoolId:session.schoolId,actorId:session.userId,payrollRunId:input.payrollRunId,rendered});});return NextResponse.json({ok:true,result});}const result=await withTenant<unknown>(session.schoolId,async(tx)=>{await requireSchoolFeatureInTransaction(tx,session.schoolId,"payroll");const common={schoolId:session.schoolId,actorId:session.userId};switch(input.action){case"salaryStructure":return setSalaryStructure(tx,{...common,...input});case"createRun":return createPayrollRun(tx,{...common,period:input.period});case"markPaid":return markPayrollPaid(tx,{...common,payrollRunId:input.payrollRunId});}});return NextResponse.json({ok:true,result});}catch(error){return routeError(error);}}
