import { NextResponse } from "next/server";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { requireSchoolSession } from "@/lib/school-auth";
import { withTenant } from "@/lib/db";
import { getSchoolAuthorization } from "@/lib/authorization";
import { ForbiddenError, routeError } from "@/lib/errors";
import { appendSchoolAudit } from "@/lib/audit";

const sendSchema=z.object({action:z.literal("send"),title:z.string().trim().min(2).max(160),body:z.string().trim().min(1).max(5000),recipientId:z.string().trim().min(1).max(100)});
const readSchema=z.object({action:z.literal("mark_read"),messageId:z.string().min(1).max(120)});
function meta(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function payload(title:string,id:string,name:string,extra:Record<string,unknown>={}){return JSON.parse(JSON.stringify({title,senderType:"school_user",senderId:id,senderName:name,attachments:[],...extra}));}
export async function GET(){try{const session=await requireSchoolSession();return withTenant(session.schoolId,async tx=>{const access=await getSchoolAuthorization(tx,session.userId);if(!access.isTeacher)throw new ForbiddenError("Teacher messaging is not available for this account.");const[rows,recipients]=await Promise.all([tx.message.findMany({where:{schoolId:session.schoolId,channel:"in_app",recipientId:session.userId},orderBy:{createdAt:"desc"},take:100,select:{id:true,body:true,status:true,createdAt:true,templateVariables:true,mediaUrl:true}}),tx.user.findMany({where:{schoolId:session.schoolId,status:"active",guardianProfiles:{some:{schoolId:session.schoolId}}},orderBy:{name:"asc"},take:500,select:{id:true,name:true,phone:true,email:true,guardianProfiles:{select:{id:true}},userRoles:{select:{role:{select:{name:true,key:true}}}}}})]);const messages=rows.map(m=>{const p=meta(m.templateVariables);return{...m,title:typeof p.title==="string"?p.title:m.body.split("\n")[0],senderName:typeof p.senderName==="string"?p.senderName:"School communication",senderId:typeof p.senderId==="string"?p.senderId:null,readAt:typeof p.readAt==="string"?p.readAt:null,attachments:Array.isArray(p.attachments)?p.attachments:[]}});return NextResponse.json({messages,unreadCount:messages.filter(m=>!m.readAt).length,recipients:recipients.map(r=>({id:r.id,name:r.name,phone:r.phone,email:r.email,roles:r.userRoles.map(x=>x.role.key||x.role.name),isGuardian:true}))});});}catch(error){return routeError(error)}}
export async function POST(request:Request){try{const session=await requireSchoolSession();return withTenant(session.schoolId,async tx=>{const access=await getSchoolAuthorization(tx,session.userId);if(!access.isTeacher)throw new ForbiddenError("Teacher messaging is not available for this account.");const raw=await request.json();if(raw?.action==="mark_read"){const value=readSchema.parse(raw);const m=await tx.message.findFirst({where:{id:value.messageId,schoolId:session.schoolId,recipientId:session.userId,channel:"in_app"},select:{id:true,body:true,templateVariables:true}});if(!m)return NextResponse.json({error:"NOT_FOUND",message:"Message not found."},{status:404});const p=meta(m.templateVariables);await tx.message.update({where:{id:m.id},data:{status:"read",templateVariables:payload(String(p.title||m.body.split("\n")[0]),typeof p.senderId==="string"?p.senderId:"system",typeof p.senderName==="string"?p.senderName:"School communication",{...p,readAt:new Date().toISOString()})}});return NextResponse.json({ok:true});}const input=sendSchema.parse(raw);const recipient=await tx.user.findFirst({where:{id:input.recipientId,schoolId:session.schoolId,status:"active",guardianProfiles:{some:{schoolId:session.schoolId}}},select:{id:true,name:true,phone:true}});if(!recipient)throw new ForbiddenError("Teachers may message linked guardians directly. Choose a valid guardian recipient.");await tx.message.create({data:{schoolId:session.schoolId,channel:"in_app",recipientType:"user",recipientId:recipient.id,recipientPhone:recipient.phone||"",body:`${input.title}\n\n${input.body}`,templateKey:"direct_message",templateVariables:payload(input.title,session.userId,session.name),status:"delivered",attempts:1,sentAt:new Date(),nextAttemptAt:new Date(),idempotencyKey:`teacher:${session.schoolId}:${session.userId}:${recipient.id}:${Date.now()}:${randomBytes(5).toString("hex")}`}});await appendSchoolAudit(tx,{schoolId:session.schoolId,actorId:session.userId,action:"message.sent",entityType:"Message",entityId:`message-${Date.now()}`,after:{title:input.title,recipientId:recipient.id,channel:"in_app",teacherDirectMessage:true}});return NextResponse.json({ok:true,message:`Delivered to ${recipient.name}.`});});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"INVALID_INPUT",message:"Choose a guardian and complete the message."},{status:400});if(error instanceof ForbiddenError)return NextResponse.json({error:error.code,message:error.message},{status:error.status});return routeError(error)}}
