"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {REVIEW_KEY,gradeRecall,normalizeCards,type ReviewCard} from "./review-model";
import {useLearningSound} from "../LearnShell";
export function Remember(){
 const [cards,setCards]=useState<ReviewCard[]>([]),[loaded,setLoaded]=useState(false),[now,setNow]=useState(0),[revealed,setRevealed]=useState(false),[recall,setRecall]=useState(""),[done,setDone]=useState(0),[notice,setNotice]=useState("");
 const [adding,setAdding]=useState(false),[prompt,setPrompt]=useState(""),[answer,setAnswer]=useState(""),[topic,setTopic]=useState("");
 const sound=useLearningSound();
 useEffect(()=>{try{setCards(normalizeCards(JSON.parse(localStorage.getItem(REVIEW_KEY)||"[]")));}catch{setNotice("Saved reviews could not be read. You can still add an idea for this visit.");}setNow(Date.now());setLoaded(true);const t=window.setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t);},[]);
 function persist(next:ReviewCard[]){setCards(next);try{localStorage.setItem(REVIEW_KEY,JSON.stringify(next));}catch{setNotice("Reviews are available for this visit, but your browser could not save them.");}}
 const due=cards.filter(c=>c.due<=now).sort((a,b)=>a.due-b.due),card=due[0];
 function grade(value:"again"|"effort"|"easy"){if(!card||!revealed)return;persist(cards.map(c=>c.id===card.id?gradeRecall(c,value):c));setNow(Date.now());setRevealed(false);setRecall("");setDone(v=>v+1);sound(value==="again"?"retry":"correct");}
 function add(){if(!prompt.trim()||!answer.trim())return;persist([{id:crypto.randomUUID(),subject:"My ideas",topic:topic.trim()||"Personal review",prompt:prompt.trim(),answer:answer.trim(),explanation:"Added by you. Check your source if you are unsure.",due:Date.now(),interval:0,reviews:0,added:Date.now()},...cards].slice(0,200));setPrompt("");setAnswer("");setTopic("");setAdding(false);setRevealed(false);setNow(Date.now());}
 return <main className="studio" style={{maxWidth:900,margin:"auto",padding:"32px 20px"}}><header className="studio-heading"><div><span className="nova-eyebrow">SMALL REVIEWS. ROOM TO REMEMBER.</span><h1>Keep what you learn.</h1><p>Try recalling the answer before you look. Your next review follows how it felt.</p></div></header>
 <div className="studio-tabs"><button onClick={()=>setAdding(!adding)} aria-expanded={adding}>{adding?"Close idea form":"Add an idea to remember"}</button><Link className="studio-button secondary" href="/learn/explore">Practise a subject</Link></div>
 {notice&&<p role="status" className="studio-notice">{notice}</p>}
 {adding&&<form className="studio-project-form" onSubmit={e=>{e.preventDefault();add();}}><label>Topic<input type="text" maxLength={100} value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>Question or prompt<textarea required maxLength={1000} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>Answer to remember<textarea required maxLength={2000} value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="studio-button">Save idea</button></form>}
 {!loaded?<p>Opening your reviews…</p>:card?<section className="studio-canvas" data-testid="remember-card"><span className="nova-eyebrow">{due.length} READY TO REVIEW · {done} REVIEWED TODAY IN THIS VISIT</span><p>{card.subject} · {card.topic}</p><h2>{card.prompt}</h2><label>Recall it in your own words<textarea maxLength={4000} value={recall} onChange={e=>setRecall(e.target.value)} placeholder="Think it through, say it aloud, or write it here."/></label>{!revealed?<button className="studio-button" style={{marginTop:20}} onClick={()=>setRevealed(true)}>Show the answer</button>:<div className="studio-feedback"><h3>{card.answer}</h3><p>{card.explanation}</p><p>Compare with your answer. How did it go?</p><div className="studio-tabs"><button onClick={()=>grade("again")}>I need another try</button><button onClick={()=>grade("effort")}>I remembered with effort</button><button onClick={()=>grade("easy")}>I remembered clearly</button></div><p className="studio-hint">This is your own recall check, not an automatic mark.</p></div>}</section>:<section className="studio-canvas"><h2>{cards.length?"You’re caught up for now.":"Your next useful idea starts here."}</h2><p>{cards.length?"Your reviews will return when they are due. You can stop here or explore something new.":"Text-only questions from your practice are saved here automatically. You can also add an idea yourself."}</p>{cards.length>0&&<p>Next review: {new Date(Math.min(...cards.map(c=>c.due))).toLocaleString()}</p>}<Link className="studio-button" href="/explore">Try Discovery Studio</Link></section>}
 <footer className="studio-footer"><p>Saved on this browser, with up to 200 recent ideas. A missed answer returns sooner; remembered answers are spaced further apart. Clearing browser data removes these reviews. Questions needing a passage or diagram stay in practice so their context is not lost.</p><Link href="/learn">Back to learning →</Link></footer></main>;
}
