"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import "../../login.css";

export default function PlatformPasswordResetPage(){
 const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);const form=new FormData(e.currentTarget);try{const r=await fetch("/api/auth/platform/password-reset/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});const d=await r.json();setMessage(d.message||"If the account exists, recovery instructions have been prepared.");}catch{setMessage("Unable to reach SukuuNova right now. Please try again.")}finally{setPending(false)}}
 return <main className="auth-shell"><section className="auth-visual"><div className="auth-orbit"/><div className="auth-grid"/><div className="auth-copy"><div className="auth-kicker"><span className="auth-dot"/> Platform security</div><h2>Recover your <span>control center</span> access.</h2><p>Start a secure administrator password recovery from the SukuuNova platform control plane.</p></div></section><section className="auth-form-pane"><div className="auth-panel"><Link href="/login/platform" className="auth-brand"><span className="auth-brand-mark">S</span><span><strong>SukuuNova</strong><small>Platform command center</small></span></Link><div className="auth-context platform">🔐 Platform recovery</div><div className="auth-heading"><h1>Reset your password.</h1><p>Enter your administrator email to begin secure account recovery.</p></div><form className="auth-form" onSubmit={submit}><div className="auth-field"><label>Administrator email</label><input name="email" type="email" placeholder="admin@company.com" required/></div>{message&&<p className="auth-error" role="status">{message}</p>}<button className="auth-submit" disabled={pending} type="submit">{pending?"Preparing recovery…":"Continue recovery"}{!pending&&<span>→</span>}</button></form><div className="auth-divider">Remembered it?</div><div className="auth-secondary"><Link href="/login/platform">← Back to sign in</Link><Link href="/">Home</Link></div></div></section></main>;
}
