"use client";
import Link from "next/link";
import { useState } from "react";

type Band={label:string;remark:string;min?:number;max?:number};
type Props={showOverallPosition:boolean;showSubjectPosition:boolean;positionScope:"class"|"year_group";remarkSource:"grade_band"|"position_band";positionBandLabels:Band[];behaviorRatingFields:string[];promotionRule:"manual"|"pass_mark"|"overall_position";positionPromotionCutoffPercent:number};
export default function ReportPolicySettings({initial}:{initial:Props}){
 const [s,setS]=useState(initial);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const save=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/school/settings/reporting",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(s)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save");setMessage("Report card policy saved.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save") }finally{setBusy(false)}};
  const addBand=()=>setS({...s,positionBandLabels:[...s.positionBandLabels,{label:"",remark:"",min:1,max:5}]});
  const addBehavior=()=>setS({...s,behaviorRatingFields:[...s.behaviorRatingFields,"Conduct"]});
  const clampCutoff=(n:number)=>Math.min(100,Math.max(1,Math.round(Number.isFinite(n)?n:50)));
  return <div style={{maxWidth:1050,margin:"0 auto",display:"grid",gap:16}}><section className="app-card app-panel"><h2>Report card policy</h2><p>These controls affect official printed report cards. Changes apply to future renders; existing frozen report calculations are not silently re-ranked.</p><div style={{display:"grid",gap:12,marginTop:16}}><label><input type="checkbox" checked={s.showOverallPosition} onChange={e=>setS({...s,showOverallPosition:e.target.checked})}/> Show overall position</label><label><input type="checkbox" checked={s.showSubjectPosition} onChange={e=>setS({...s,showSubjectPosition:e.target.checked})}/> Show subject positions</label><label>Position scope<select value={s.positionScope} onChange={e=>setS({...s,positionScope:e.target.value as Props["positionScope"]})}><option value="class">Class</option><option value="year_group">Year group / level</option></select></label><label>Remark source<select value={s.remarkSource} onChange={e=>setS({...s,remarkSource:e.target.value as Props["remarkSource"]})}><option value="grade_band">Grade band</option><option value="position_band">Position band</option></select></label><label>Promotion rule<select value={s.promotionRule} onChange={e=>setS({...s,promotionRule:e.target.value as Props["promotionRule"]})}><option value="manual">Manual school decision</option><option value="pass_mark">Pass-mark rule</option><option value="overall_position">Overall-position rule</option></select></label>{s.promotionRule==="overall_position"?<label>Promotion cutoff — top <input type="number" min={1} max={100} value={s.positionPromotionCutoffPercent} onChange={e=>setS({...s,positionPromotionCutoffPercent:clampCutoff(Number(e.target.value))})} style={{width:80}}/>% of ranked learners are promoted</label>:null}</div></section>
  <section className="app-card app-panel"><h3>Position-band labels</h3><p>Optional wording for schools that use position bands. Give each band a position range (1 = top of class); bands without a range share the class evenly in order.</p>{s.positionBandLabels.map((b,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 1fr 70px 70px 2fr auto",gap:8,marginTop:8}}><input placeholder="Band label" value={b.label} onChange={e=>{const x=[...s.positionBandLabels];x[i]={...x[i],label:e.target.value};setS({...s,positionBandLabels:x})}}/><input placeholder="Remark guidance" value={b.remark} onChange={e=>{const x=[...s.positionBandLabels];x[i]={...x[i],remark:e.target.value};setS({...s,positionBandLabels:x})}}/><input type="number" min={1} placeholder="From" value={b.min??""} onChange={e=>{const x=[...s.positionBandLabels];x[i]={...x[i],min:e.target.value===""?undefined:Number(e.target.value)};setS({...s,positionBandLabels:x})}}/><input type="number" min={1} placeholder="To" value={b.max??""} onChange={e=>{const x=[...s.positionBandLabels];x[i]={...x[i],max:e.target.value===""?undefined:Number(e.target.value)};setS({...s,positionBandLabels:x})}}/><button onClick={()=>setS({...s,positionBandLabels:s.positionBandLabels.filter((_,n)=>n!==i)})}>Remove</button></div>)}<button style={{marginTop:10}} onClick={addBand}>+ Add position band</button></section>
 <section className="app-card app-panel"><h3>Behaviour / conduct fields</h3><p>Choose the rating headings to appear on official reports.</p>{s.behaviorRatingFields.map((b,i)=><div key={i} style={{display:"flex",gap:8,marginTop:8}}><input value={b} onChange={e=>{const x=[...s.behaviorRatingFields];x[i]=e.target.value;setS({...s,behaviorRatingFields:x})}}/><button onClick={()=>setS({...s,behaviorRatingFields:s.behaviorRatingFields.filter((_,n)=>n!==i)})}>Remove</button></div>)}<button style={{marginTop:10}} onClick={addBehavior}>+ Add rating field</button></section>
 <section className="app-card app-panel" style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div>{message&&<strong>{message}</strong>}<p>Save the school’s reporting choice before generating new official documents.</p></div><div style={{display:"flex",gap:8}}><Link href="/school/report-cards">Report cards</Link><button className="app-action" onClick={save} disabled={busy}>{busy?"Saving…":"Save policy"}</button></div></section></div>
}
