"use client";
import { useEffect } from "react";
import { Printer } from "lucide-react";

type Period={period:number;start:string;end:string};
type Day={dayOfWeek:number;name:string;enabled:boolean};
type Slot={dayOfWeek:number;period:number;subject:{name:string};teacher:{name:string};class:{name:string};venue?:string|null};
type Data={school:{name:string;logoUrl?:string|null}|null;title:string;mode:"class"|"teacher";days:Day[];periods:Period[];slots:Slot[]};
const fmt=(v:string)=>{const [h,m]=v.split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`};
export default function AutoPrintTimetable({data}:{data:Data}){
 useEffect(()=>{const t=window.setTimeout(()=>window.print(),250);return()=>window.clearTimeout(t)},[]);
 return <main className="quick-print-timetable"><div className="screen-print-actions"><button onClick={()=>window.print()}><Printer size={16}/> Print / Save PDF</button></div><header>{data.school?.logoUrl?<img src={data.school.logoUrl} alt=""/>:null}<div><small>SCHOOL TIMETABLE</small><h1>{data.school?.name??"School"}</h1><h2>{data.title}</h2></div></header><table><thead><tr><th>Period</th>{data.days.map(d=><th key={d.dayOfWeek}>{d.name}</th>)}</tr></thead><tbody>{data.periods.map(p=><tr key={p.period}><th><strong>Period {p.period}</strong><span>{fmt(p.start)}–{fmt(p.end)}</span></th>{data.days.map(d=>{const s=data.slots.find(x=>x.dayOfWeek===d.dayOfWeek&&x.period===p.period);return <td key={`${d.dayOfWeek}:${p.period}`}>{s?<><strong>{s.subject.name}</strong><span>{data.mode==="class"?s.teacher.name:s.class.name}</span>{s.venue?<small>{s.venue.replace(/^room:/,"")}</small>:null}</>:<span>—</span>}</td>})}</tr>)}</tbody></table><style jsx>{`main{min-height:100vh;background:var(--color-text-on-brand);color:var(--color-brand-deep);padding:28px}.screen-print-actions{display:flex;justify-content:flex-end;margin-bottom:18px}.screen-print-actions button{display:flex;gap:7px;align-items:center;padding:9px 13px;border:0;border-radius:9px;background:var(--color-brand-deep);color:var(--color-text-on-brand);font-weight:700}header{display:flex;gap:16px;align-items:center;max-width:1200px;margin:0 auto 20px;border-bottom:3px solid var(--color-brand-deep);padding-bottom:14px}header img{width:58px;height:58px;object-fit:contain}header small{font-size:10px;letter-spacing:.14em;font-weight:800;color:var(--color-brand-deep);opacity:.72}h1{margin:3px 0;font-size:25px}h2{margin:0;font-size:19px}table{width:100%;max-width:1200px;margin:0 auto;border-collapse:collapse;table-layout:fixed;font-size:11px}th,td{border:1px solid var(--color-border-strong);padding:7px;text-align:left;vertical-align:top}thead th{background:var(--color-surface-soft)}tbody>tr>th{width:120px;background:var(--color-bg)}tbody th span,td span,td small{display:block;margin-top:3px;color:var(--color-brand-deep);opacity:.74}td{height:58px}@media print{main{padding:8mm}.screen-print-actions{display:none}header{margin-bottom:6mm}table{font-size:9px}th,td{padding:5px}td{height:15mm}@page{size:A4 landscape;margin:8mm}}`}</style></main>
}
