/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { CSSProperties } from "react";
import { getSchoolDocumentIdentity } from "@/lib/school-document-identity";

type Period={period:number;start:string;end:string};
type Day={dayOfWeek:number;name:string;enabled:boolean;start:string;end:string;periods?:Period[]};
type Config={days:Day[];periodMinutes:number;breaks:{name:string;start:string;end:string}[];periodsPerDay:number;periods?:Period[];published:boolean};
type Person={id:string;name:string};
type School={name:string;uniqueCode:string;logoUrl:string|null;brandColors:unknown};
type Slot={id:string;classId:string;subjectId:string;teacherId:string;dayOfWeek:number;period:number;class:{id:string;name:string;level:string|null};subject:{id:string;name:string};teacher:{id:string;name:string}};
type Data={school:School|null;classes:(Person&{level:string|null})[];subjects:Person[];teachers:Person[];slots:Slot[];timetableConfig:Config};
type Audience="all"|"class"|"teacher";
type Design="modern"|"campus"|"classic"|"pastel"|"bold"|"mono";
type Column={kind:"lesson"|"break";period?:number;name?:string;start:string;end:string};

const designs:{id:Design;name:string;description:string}[]=[
 {id:"modern",name:"Modern School",description:"Clean hierarchy, school accent band and rounded lesson cards."},
 {id:"campus",name:"Campus",description:"Large crest, bold blocks and poster-ready wall presence."},
 {id:"classic",name:"Classic",description:"Serif headings, fine rules and formal letterhead character."},
 {id:"pastel",name:"Pastel",description:"Quiet subject tints and softer edges for calm classroom use."},
 {id:"bold",name:"Bold",description:"High-contrast lesson blocks that stay readable at distance."},
 {id:"mono",name:"Mono",description:"Grayscale-only, no fills and economical ink use."}
];
const pastelPalette=["#edf4ff","#f3edff","#eaf8f1","#fff2e5","#f9ecf3","#e9f6fa"];
const boldPalette=["#2563eb","#7c3aed","#059669","#ea580c","#db2777","#0891b2"];
function mins(v:string){const [h,m]=v.split(":").map(Number);return h*60+m;}
function hourLabel(v:string){const [h,m]=v.split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`;}
function indexFor(value:string){let h=0;for(let i=0;i<value.length;i++)h=(h*31+value.charCodeAt(i))>>>0;return h;}
function themeColours(subject:string){const i=indexFor(subject);return {pastel:pastelPalette[i%pastelPalette.length],bold:boldPalette[i%boldPalette.length]};}
function columnsFor(day:Day,config:Config):Column[]{const periods=day.periods?.length?day.periods:(config.periods?.length?config.periods:[]);const out:Column[]=[];for(const p of periods.slice(0,config.periodsPerDay)){out.push({kind:"lesson",period:p.period,start:p.start,end:p.end});const b=config.breaks.find(x=>mins(x.start)===mins(p.end));if(b)out.push({kind:"break",name:b.name,start:b.start,end:b.end});}return out;}
function escapeHtml(v:string){return v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function escapeRtf(v:string){return v.replaceAll("\\","\\\\").replace(/[{}]/g,"\\$&").replace(/\r?\n/g,"\\line ");}

export default function PrintStudio({data}:{data:Data}){
 const [audience,setAudience]=useState<Audience>("class");
 const [selectedId,setSelectedId]=useState(data.classes[0]?.id??"");
 const [design,setDesign]=useState<Design>("modern");
 const identity=getSchoolDocumentIdentity(data.school??{name:"School",uniqueCode:"",logoUrl:null,brandColors:null});
 const documentStyle={"--school-primary":identity.primary,"--school-accent":identity.accent} as CSSProperties;
 const days=useMemo(()=>data.timetableConfig.days.filter(d=>d.enabled&&d.dayOfWeek>=1&&d.dayOfWeek<=6),[data.timetableConfig.days]);
 const columns=useMemo(()=>{
   const anchor=days[0]??{dayOfWeek:1,name:"Monday",enabled:true,start:"08:00",end:"15:00",periods:[]};
   return columnsFor(anchor,data.timetableConfig);
 },[days,data.timetableConfig]);
 const pages=useMemo(()=>{
   if(audience==="teacher"){const t=data.teachers.find(x=>x.id===selectedId);return t?[{id:t.id,title:`${t.name} · Teacher timetable`,mode:"teacher" as const,slots:data.slots.filter(s=>s.teacherId===t.id)}]:[];}
   if(audience==="class"){const c=data.classes.find(x=>x.id===selectedId);return c?[{id:c.id,title:c.name,mode:"class" as const,slots:data.slots.filter(s=>s.classId===c.id)}]:[];}
   return data.classes.map(c=>({id:c.id,title:c.name,mode:"class" as const,slots:data.slots.filter(s=>s.classId===c.id)}));
 },[audience,selectedId,data.classes,data.teachers,data.slots]);
 const download=(name:string,content:string,type:string)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const csv=()=>{const rows:string[][]=[];for(const page of pages){rows.push([identity.name,page.title]);rows.push(["Day",...columns.map(c=>c.kind==="break"?c.name??"Break":`${hourLabel(c.start)} - ${hourLabel(c.end)}`)]);for(const day of days)rows.push([day.name,...columns.map(c=>{if(c.kind==="break")return c.name??"Break";const s=page.slots.find(x=>x.dayOfWeek===day.dayOfWeek&&x.period===c.period);return s?`${s.subject.name} · ${page.mode==="class"?s.teacher.name:s.class.name}`:"";})]);rows.push([]);}download(`sukuunova-${audience}-timetables.csv`,rows.map(r=>r.map(v=>`"${(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv;charset=utf-8");};
 const word=()=>{const parts:string[]=["{\\rtf1\\ansi\\deff0\\landscape\\paperw16838\\paperh11906"];for(const page of pages){parts.push(`\\pard\\fs34\\b ${escapeRtf(identity.name)}\\b0\\par\\fs28 ${escapeRtf(page.title)}\\par\\fs18`);parts.push("\\par Day\\tab "+columns.map(c=>escapeRtf(c.kind==="break"?c.name??"Break":`${hourLabel(c.start)}-${hourLabel(c.end)}`)).join("\\tab ")+"\\par");for(const day of days){parts.push(escapeRtf(day.name)+"\\tab "+columns.map(c=>{if(c.kind==="break")return escapeRtf(c.name??"Break");const s=page.slots.find(x=>x.dayOfWeek===day.dayOfWeek&&x.period===c.period);return escapeRtf(s?`${s.subject.name} / ${page.mode==="class"?s.teacher.name:s.class.name}`:"");}).join("\\tab ")+"\\par");}parts.push("\\page");}parts.push("}");download(`sukuunova-${audience}-timetables.rtf`,parts.join(""),"application/rtf");};
 const html=()=>download(`sukuunova-${audience}-timetables.html`,`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(identity.name)} Timetables</title><style>${documentStyles(identity)}</style></head><body>${pages.map(p=>renderHtmlPage(identity,days,columns,p.title,p.slots,p.mode,design)).join("")}</body></html>`,"text/html;charset=utf-8");
 return <main className={`print-studio theme-${design}`} style={documentStyle}>
   <section className="studio-top"><div className="studio-intro"><span className="studio-kicker">ACADEMICS / PRINT TIMETABLE</span><h1>School timetable, ready for the wall, staff room or home.</h1><p>Choose the audience and a real document style. The schedule remains untouched; only its presentation changes.</p></div><Link href="/school/timetable" className="studio-back">← Back to timetable editor</Link></section>
   <section className="studio-toolbar"><div className="toolbar-block"><label>Print audience</label><div className="pill-tabs"><button type="button" className={audience==="class"?"active":""} onClick={()=>{setAudience("class");setSelectedId(data.classes[0]?.id??"")}}>One Class</button><button type="button" className={audience==="all"?"active":""} onClick={()=>{setAudience("all");setSelectedId("")}}>All Classes</button><button type="button" className={audience==="teacher"?"active":""} onClick={()=>{setAudience("teacher");setSelectedId(data.teachers[0]?.id??"")}}>One Teacher</button></div></div>{audience!=="all"?<div className="toolbar-block select-block"><label>{audience==="class"?"Class":"Teacher"}</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{(audience==="class"?data.classes:data.teachers).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>:<div className="toolbar-note"><b>{data.classes.length} class pages</b><span>Each class starts on a fresh printed page.</span></div>}</section>
   <section className="design-section"><div className="section-label"><span className="studio-kicker">DESIGN COLLECTION</span><h2>Choose the document character.</h2><p>Every style below changes typography, spacing, colour treatment and print economy—not just the colour of a line.</p></div><div className="design-grid">{designs.map(d=><button type="button" key={d.id} className={`design-card ${design===d.id?"selected":""} ${d.id}`} onClick={()=>setDesign(d.id)}><div className="design-mini"><div className="mini-head"/><div className="mini-grid">{Array.from({length:8},(_,i)=><i key={i}/>)}</div></div><b>{d.name}</b><span>{d.description}</span></button>)}</div></section>
   <section className="paper-wrap"><div className="paper-label"><span>LIVE PREVIEW</span><strong>{audience==="all"?`All ${pages.length} class timetables`:pages[0]?.title??"Timetable"}</strong><span>{data.slots.length} lessons loaded</span></div>{pages.length?pages.map(p=><div className="paper" key={p.id}>{renderPaper(identity,days,columns,p.title,p.slots,p.mode,design)}</div>):<div className="paper"><p>No timetable pages are available yet. Create classes and schedule lessons first.</p></div>}</section>
   <section className="download-panel"><div><span className="studio-kicker">DISTRIBUTE & SHARE</span><h2>Use the same designed source everywhere.</h2><p><b>Print / Save PDF</b> uses the selected school style. <b>Word (.rtf)</b>, <b>CSV</b> and <b>HTML</b> carry the same school identity and timetable data.</p></div><div className="download-actions"><button type="button" className="primary-download" onClick={()=>window.print()}>Print / Save PDF</button><button type="button" onClick={word}>Word (.rtf)</button><button type="button" onClick={csv}>Excel / CSV</button><button type="button" onClick={html}>HTML</button></div></section>
   <style>{`
     .print-studio{--school-primary:#164e63;--school-accent:#dcefeb;color:#18353b}.print-studio .paper{border-top:5px solid var(--school-primary)}
     .print-studio .paper-rule{background:var(--school-primary)}.print-studio .paper-heading small{color:var(--school-primary)}
     .print-studio .lesson-cell{background:#fff}.print-studio .lesson-cell.filled{box-shadow:inset 4px 0 0 var(--lesson-color);background:var(--lesson-bg,#fff)}
     .print-studio.theme-modern .paper{border-radius:16px}.print-studio.theme-modern .paper-header{padding:8px 10px;border-radius:12px;background:linear-gradient(90deg,color-mix(in srgb,var(--school-primary) 14%,white),white)}
     .print-studio.theme-campus .paper{border-radius:0;border-top:0}.print-studio.theme-campus .paper-header{padding:22px;background:var(--school-primary);color:#fff}.print-studio.theme-campus .school-mark{width:78px;height:78px;border:2px solid rgba(255,255,255,.75);background:#fff}.print-studio.theme-campus .paper-heading h2,.print-studio.theme-campus .paper-heading strong,.print-studio.theme-campus .paper-heading small{color:#fff}.print-studio.theme-campus .paper-rule{height:8px;background:var(--school-accent)}
     .print-studio.theme-classic .paper{border-radius:2px;box-shadow:none}.print-studio.theme-classic .paper-heading h2,.print-studio.theme-classic .paper-heading strong,.print-studio.theme-classic .day-cell,.print-studio.theme-classic .lesson-cell b{font-family:Georgia,"Times New Roman",serif}.print-studio.theme-classic .paper-rule{height:1px;background:#283d42}.print-studio.theme-classic .timetable-print-table th,.print-studio.theme-classic .timetable-print-table td{border-color:#86999a}.print-studio.theme-classic .timetable-print-table thead th{background:#fff}
     .print-studio.theme-pastel .paper{background:#fffdfd}.print-studio.theme-pastel .lesson-cell.filled{box-shadow:none;border-radius:8px}.print-studio.theme-pastel .timetable-print-table td,.print-studio.theme-pastel .timetable-print-table th{border-color:#d9dedf}.print-studio.theme-pastel .day-cell{background:#fbfdfd}
     .print-studio.theme-bold .paper-header{padding:16px;background:var(--school-primary);color:#fff}.print-studio.theme-bold .paper-heading h2,.print-studio.theme-bold .paper-heading strong,.print-studio.theme-bold .paper-heading small{color:#fff}.print-studio.theme-bold .paper-rule{height:9px;background:#111}.print-studio.theme-bold .lesson-cell.filled{box-shadow:none;color:#fff;background:var(--lesson-color)}.print-studio.theme-bold .lesson-cell.filled b,.print-studio.theme-bold .lesson-cell.filled span,.print-studio.theme-bold .lesson-cell.filled small{color:#fff}.print-studio.theme-bold .timetable-print-table thead th{background:#111;color:#fff}
     .print-studio.theme-mono .paper{box-shadow:none;border:1px solid #777;border-top:1px solid #111}.print-studio.theme-mono .paper-rule{height:1px;background:#111}.print-studio.theme-mono .timetable-print-table th,.print-studio.theme-mono .timetable-print-table td{border-color:#777}.print-studio.theme-mono .timetable-print-table thead th,.print-studio.theme-mono .day-cell,.print-studio.theme-mono .lesson-cell.filled{background:#fff;color:#111}.print-studio.theme-mono .lesson-cell.filled{box-shadow:inset 3px 0 0 #111}.print-studio.theme-mono .break-cell{background:#fff}.print-studio.theme-mono .paper-heading h2,.print-studio.theme-mono .paper-heading strong,.print-studio.theme-mono .paper-heading small,.print-studio.theme-mono .paper-footer{color:#111}
     .design-mini .mini-head{background:var(--school-primary)}.design-card.campus .mini-head{height:20px}.design-card.classic .mini-head{height:3px}.design-card.pastel .mini-head{background:linear-gradient(90deg,#edf4ff,#f3edff,#eaf8f1)}.design-card.bold .mini-head{height:20px;background:linear-gradient(90deg,#2563eb,#7c3aed,#ea580c)}.design-card.mono .mini-head{background:#111;height:2px}
     @media print{.print-studio .paper{break-inside:avoid;page-break-inside:avoid}.print-studio .paper+.paper{break-before:page;page-break-before:always}.print-studio .lesson-cell.filled{color:inherit}.print-studio.theme-mono .lesson-cell.filled{background:#fff!important;color:#111!important}.print-studio.theme-bold .lesson-cell.filled{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
   `}</style>
 </main>;
}

function renderPaper(identity:ReturnType<typeof getSchoolDocumentIdentity>,days:Day[],columns:Column[],title:string,slots:Slot[],mode:"class"|"teacher",design:Design){return <><header className="paper-header"><div className="school-mark">{identity.logoUrl?<img src={identity.logoUrl} alt={`${identity.name} logo`}/>:null}</div><div className="paper-heading"><small>WEEKLY TIMETABLE</small><h2>{identity.name}</h2><strong>{title}</strong></div><div className="paper-badge"><span>{mode.toUpperCase()}</span><b>{design.toUpperCase()}</b></div></header><div className="paper-rule"/><div className="paper-note"><span>School times from Academic Setup</span><span>{identity.uniqueCode}</span></div><div className="paper-table-scroll"><table className="timetable-print-table"><thead><tr><th className="day-heading">DAY</th>{columns.map((c,i)=><th key={i} className={c.kind==="break"?"break-head":"time-head"}>{c.kind==="break"?<span>{c.name}</span>:<><b>{hourLabel(c.start)}</b><small>{hourLabel(c.end)}</small></>}</th>)}</tr></thead><tbody>{days.map(day=><tr key={day.dayOfWeek}><th className="day-cell"><b>{day.name.slice(0,3).toUpperCase()}</b><span>{day.name}</span></th>{columns.map((c,i)=>{if(c.kind==="break")return <td key={i} className="break-cell"><span>{c.name}</span></td>;const s=slots.find(x=>x.dayOfWeek===day.dayOfWeek&&x.period===c.period);if(!s)return <td key={i} className="lesson-cell"/>;const theme=themeColours(s.subject.name);return <td key={i} className="lesson-cell filled" style={{"--lesson-color":design==="bold"?theme.bold:identity.primary,"--lesson-bg":design==="pastel"?theme.pastel:"#fff"} as CSSProperties}><b>{s.subject.name}</b><span>{mode==="class"?s.teacher.name:s.class.name}</span>{mode==="teacher"?<small>{s.class.name}</small>:null}</td>})}</tr>)}</tbody></table></div><footer className="paper-footer"><span>{identity.name}</span><span>{identity.watermark}</span></footer></>}
function renderHtmlPage(identity:ReturnType<typeof getSchoolDocumentIdentity>,days:Day[],columns:Column[],title:string,slots:Slot[],mode:"class"|"teacher",design:Design){return `<section class="paper theme-${design}"><header class="paper-header"><div class="school-mark">${identity.logoUrl?`<img src="${escapeHtml(identity.logoUrl)}" alt="logo">`:""}</div><div class="paper-heading"><small>WEEKLY TIMETABLE</small><h2>${escapeHtml(identity.name)}</h2><strong>${escapeHtml(title)}</strong></div></header><div class="paper-rule"></div><table class="timetable-print-table"><thead><tr><th>DAY</th>${columns.map(c=>`<th>${escapeHtml(c.kind==="break"?c.name??"Break":`${hourLabel(c.start)} - ${hourLabel(c.end)}`)}</th>`).join("")}</tr></thead><tbody>${days.map(day=>`<tr><th>${escapeHtml(day.name)}</th>${columns.map(c=>{if(c.kind==="break")return `<td class="break-cell">${escapeHtml(c.name??"Break")}</td>`;const s=slots.find(x=>x.dayOfWeek===day.dayOfWeek&&x.period===c.period);return `<td class="lesson-cell ${s?"filled":""}">${s?`<b>${escapeHtml(s.subject.name)}</b><span>${escapeHtml(mode==="class"?s.teacher.name:s.class.name)}</span>`:""}</td>`}).join("")}</tr>`).join("")}</tbody></table><footer>${escapeHtml(identity.name)} • ${escapeHtml(identity.uniqueCode)} • ${escapeHtml(identity.watermark)}</footer></section>`;}
function documentStyles(identity:ReturnType<typeof getSchoolDocumentIdentity>){return `:root{--school-primary:${identity.primary};--school-accent:${identity.accent}}body{font-family:Arial,sans-serif;margin:0;padding:24px;background:#f4f7f6;color:#17353a}.paper{max-width:1280px;margin:0 auto 28px;padding:24px;background:#fff}.paper-header{display:grid;grid-template-columns:68px 1fr auto;align-items:center;gap:16px}.school-mark{width:62px;height:62px;display:grid;place-items:center;overflow:hidden;background:#fff;border:1px solid #d6dfdd}.school-mark img{width:100%;height:100%;object-fit:contain}.paper-heading small{display:block;color:var(--school-primary);font-size:9px;letter-spacing:.18em;font-weight:900}.paper-heading h2{margin:4px 0 2px;font-size:25px}.paper-heading strong{font-size:13px}.paper-rule{height:4px;margin:14px 0;background:var(--school-primary)}.timetable-print-table{width:100%;border-collapse:collapse;table-layout:fixed}.timetable-print-table th,.timetable-print-table td{border:1px solid #b9cac7;padding:8px;text-align:center}.timetable-print-table thead th{background:color-mix(in srgb,var(--school-accent) 55%,white);min-height:46px}.timetable-print-table tbody th{text-align:left;background:#f8faf9}.lesson-cell{height:62px;vertical-align:middle}.lesson-cell b,.lesson-cell span{display:block}.lesson-cell b{font-size:11px}.lesson-cell span{font-size:9px;margin-top:4px}.break-cell{background:#f2e8e2}.paper-footer,footer{display:flex;justify-content:space-between;border-top:1px solid #dce6e3;padding-top:9px;margin-top:9px;font-size:8px;color:#718287}.paper:not(:last-child){page-break-after:always}.theme-campus .paper-header{background:var(--school-primary);color:#fff;padding:22px}.theme-campus .paper-heading h2,.theme-campus .paper-heading strong,.theme-campus .paper-heading small{color:#fff}.theme-campus .paper-rule{height:8px;background:var(--school-accent)}.theme-classic .paper{border:1px solid #8b9898;box-shadow:none}.theme-classic .paper-heading h2,.theme-classic .paper-heading strong{font-family:Georgia,"Times New Roman",serif}.theme-classic .paper-rule{height:1px;background:#283d42}.theme-pastel .lesson-cell.filled{background:var(--lesson-bg,#fff)}.theme-bold .lesson-cell.filled{background:var(--lesson-color,var(--school-primary));color:#fff}.theme-mono .paper{border:1px solid #777;box-shadow:none}.theme-mono .paper-rule{height:1px;background:#111}.theme-mono .timetable-print-table th,.theme-mono .timetable-print-table td{background:#fff!important;color:#111;border-color:#777}@page{size:A4 landscape;margin:8mm}@media print{body{padding:0;background:#fff}.paper{margin:0;max-width:none;padding:0}.paper+.paper{break-before:page;page-break-before:always}.lesson-cell.filled{print-color-adjust:exact;-webkit-print-color-adjust:exact}.theme-mono .lesson-cell.filled{background:#fff!important;color:#111!important}}`;}
