import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { db } from "@/lib/db";
import { getSchoolSession } from "@/lib/school-auth";

type ModuleConfig = {
  title: string;
  group: string;
  description: string;
  action: string;
  tabs: string[];
  columns: string[];
  workflow: string[];
  capabilities: string[];
};

const modules: Record<string, ModuleConfig> = {
  students: { title: "Students", group: "People", description: "Manage learner profiles, admission numbers, class placement, guardians, attendance, academics and fee accounts.", action: "Add student", tabs: ["All students", "Active", "Pending", "Graduated", "Archived"], columns: ["Student", "Admission no.", "Class", "Guardians", "Attendance", "Fees", "Status"], workflow: ["Capture learner details", "Link guardians and documents", "Assign class", "Track attendance, academics and fees", "Transfer, graduate or archive"], capabilities: ["Student profiles", "Admission numbers", "Class placement", "Guardian links", "Documents", "Attendance history", "Academic history", "Fee account", "Transfers"] },
  guardians: { title: "Parents & Guardians", group: "People", description: "Manage family contacts, learner relationships, communication access and pickup permissions.", action: "Add guardian", tabs: ["All guardians", "Primary contacts", "Portal access", "Needs attention"], columns: ["Guardian", "Phone", "Learners", "Primary", "Portal", "Status"], workflow: ["Create family contact", "Link learners", "Set primary relationship", "Enable communication access", "Review family history"], capabilities: ["Family profiles", "Relationships", "Primary contacts", "Portal access", "Communication history", "Pickup permissions"] },
  staff: { title: "Staff & Teachers", group: "People", description: "Manage staff records, roles, teaching assignments, attendance and payroll readiness.", action: "Add staff", tabs: ["All staff", "Teachers", "Administrators", "Inactive"], columns: ["Staff member", "Role", "Teaching load", "Attendance", "Payroll", "Status"], workflow: ["Create staff account", "Assign role", "Assign classes and subjects", "Track attendance", "Prepare payroll"], capabilities: ["Staff directory", "Roles", "Permissions", "Teaching assignments", "Attendance", "Salary structures", "Payroll", "Payslips"] },
  "admissions/enquiries": { title: "Admissions Enquiries", group: "Admissions", description: "Capture prospective-family enquiries and move qualified prospects into applications.", action: "Add enquiry", tabs: ["New", "Contacted", "Qualified", "Converted", "Closed"], columns: ["Prospect", "Interested class", "Contact", "Source", "Owner", "Status"], workflow: ["Capture enquiry", "Contact family", "Qualify interest", "Convert to application", "Follow up or close"], capabilities: ["Lead register", "Follow-up", "Sources", "Conversion tracking"] },
  "admissions/applications": { title: "Applications", group: "Admissions", description: "Review new learner applications, documents and admission decisions.", action: "New application", tabs: ["Draft", "Submitted", "Review", "Accepted", "Rejected"], columns: ["Applicant", "Class", "Submitted", "Reviewer", "Decision"], workflow: ["Receive application", "Validate details", "Review documents", "Accept or reject", "Prepare enrolment"], capabilities: ["Applications", "Document review", "Decisions", "Admission workflow"] },
  "admissions/enrolment": { title: "Enrolment", group: "Admissions", description: "Turn approved applications into official student records and class placements.", action: "Start enrolment", tabs: ["Ready", "In progress", "Completed", "Withdrawn"], columns: ["Applicant", "Class", "Admission no.", "Start date", "Status"], workflow: ["Approve applicant", "Create student", "Assign admission number", "Place class", "Activate learner"] , capabilities: ["Student creation", "Admission numbers", "Class placement", "Activation"] },
  classes: { title: "Classes & Houses", group: "Admissions", description: "Design the academic structure that organizes learners, teachers and subjects.", action: "Create class", tabs: ["Classes", "Houses", "Class teachers", "Capacity"], columns: ["Class", "Level", "Students", "Class teacher", "Subjects", "Status"], workflow: ["Define class structure", "Assign class teacher", "Connect subjects", "Place learners", "Monitor capacity"], capabilities: ["Classes", "Levels", "Houses", "Class teachers", "Subject assignments", "Capacity"] },
  subjects: { title: "Subjects", group: "Academics", description: "Manage the subject catalogue and connect it to classes, teachers, assessments and the timetable.", action: "Add subject", tabs: ["All subjects", "Core", "Electives", "Unassigned"], columns: ["Subject", "Classes", "Teachers", "Assessments", "Timetable slots"], workflow: ["Create subject", "Assign classes", "Assign teachers", "Schedule periods", "Assess performance"], capabilities: ["Subject catalogue", "Class assignment", "Teacher assignment", "Curriculum mapping", "Assessment linkage"] },
  timetable: { title: "Timetable", group: "Academics", description: "Build weekly schedules, detect clashes and manage authorized substitute coverage.", action: "Add timetable slot", tabs: ["Weekly timetable", "Teacher view", "Class view", "Substitutes"], columns: ["Day", "Period", "Class", "Subject", "Teacher", "Substitute"], workflow: ["Define periods", "Schedule class and subject", "Assign teacher", "Check clashes", "Assign substitute"], capabilities: ["Weekly timetable", "Teacher view", "Class view", "Conflict detection", "Substitutes"] },
  lessons: { title: "Lessons & Planning", group: "Academics", description: "Plan lessons, schemes and classroom activities around the school's curriculum.", action: "Create lesson", tabs: ["Planned", "This week", "Completed", "Templates"], columns: ["Lesson", "Class", "Subject", "Teacher", "Date", "Status"], workflow: ["Choose class and subject", "Plan objectives", "Add resources", "Deliver lesson", "Record completion"], capabilities: ["Lesson plans", "Objectives", "Resources", "Teacher planning", "Completion tracking"] },
  homework: { title: "Homework & Exercises", group: "Academics", description: "Create exercises, assign work to classes, collect submissions and review learner completion.", action: "Create exercise", tabs: ["Draft", "Assigned", "Due", "Submitted", "Reviewed"], columns: ["Exercise", "Class", "Subject", "Due", "Submitted", "Status"], workflow: ["Create exercise", "Assign audience", "Set due date", "Collect work", "Review and grade"], capabilities: ["Assignments", "Exercises", "Due dates", "Submission tracking", "Grading"] },
  gradebook: { title: "Gradebook", group: "Academics", description: "Review marks by learner, class, subject and assessment and identify missing scores.", action: "Open gradebook", tabs: ["By class", "By subject", "Missing scores", "Published"], columns: ["Learner", "Class", "Subject", "Assessment", "Score", "Grade", "Entered by"], workflow: ["Select term", "Review assessments", "Enter or correct scores", "Check completion", "Publish results"], capabilities: ["Score entry", "Bulk entry", "Missing scores", "Grade calculation", "Performance analysis"] },
  exams: { title: "Exams & Assessments", group: "Academics", description: "Plan tests and examinations, define weights, collect scores and lock approved results.", action: "Create assessment", tabs: ["Planned", "Open", "Submitted", "Locked", "Results"], columns: ["Assessment", "Term", "Class", "Subject", "Weight", "Scores", "Status"], workflow: ["Create assessment", "Set class and subject", "Collect scores", "Moderate results", "Lock results"], capabilities: ["Assessment setup", "Weights", "Score entry", "Moderation", "Result locking"] },
  "report-cards": { title: "Report Cards", group: "Academics", description: "Generate, review, approve, brand and publish learner report cards.", action: "Generate report cards", tabs: ["Draft", "For review", "Approved", "Sent"], columns: ["Learner", "Class", "Term", "Template", "Status", "Approved", "Sent"], workflow: ["Collect verified results", "Generate reports", "Review", "Approve", "Publish to families"], capabilities: ["Report generation", "Templates", "Branding", "Approval workflow", "PDF output"] },
  attendance: { title: "Student Attendance", group: "Attendance", description: "Take daily registers, manage lateness and absences, investigate exceptions and alert families.", action: "Take attendance", tabs: ["Today", "History", "Absences", "Late", "Exceptions"], columns: ["Date", "Class", "Present", "Late", "Absent", "Method", "Recorded by"], workflow: ["Select class and date", "Mark attendance", "Record reason", "Review exceptions", "Notify families"], capabilities: ["Daily register", "Attendance history", "Late tracking", "Absence reasons", "Parent alerts", "Reports"] },
  "staff-attendance": { title: "Staff Attendance", group: "Attendance", description: "Track staff attendance, late arrivals and workforce attendance trends.", action: "Record staff attendance", tabs: ["Today", "History", "Late", "Absent"], columns: ["Date", "Staff member", "Status", "Method", "Recorded by"], workflow: ["Open staff register", "Record status", "Review late cases", "Track trends", "Link to HR/payroll"], capabilities: ["Daily register", "Late tracking", "Trends", "Payroll linkage", "HR reporting"] },
  fees: { title: "School Fees", group: "Finance", description: "Configure fee structures, bill learners, monitor collections and manage outstanding balances.", action: "Create fee item", tabs: ["Overview", "Fee items", "Billed", "Collected", "Arrears"], columns: ["Fee item", "Term", "Class", "Amount", "Billed", "Collected", "Balance"], workflow: ["Define fee", "Assign term/class", "Generate invoices", "Collect payments", "Follow up balances"], capabilities: ["Fee structures", "Term billing", "Invoices", "Receipts", "Payments", "Arrears", "Reports"] },
  "fees/invoices": { title: "Invoices", group: "Finance", description: "Manage student invoices, line items, balances and payment status.", action: "Create invoice", tabs: ["All", "Unpaid", "Part-paid", "Paid", "Overdue"], columns: ["Invoice", "Student", "Term", "Total", "Paid", "Balance", "Status"], workflow: ["Generate invoice", "Review lines", "Receive payment", "Track balance", "Escalate overdue"], capabilities: ["Invoice generation", "Line items", "Partial payments", "Balances", "Receipts"] },
  "fees/payments": { title: "Payments", group: "Finance", description: "Record fee payments, references, payment methods and authorized reversals.", action: "Record payment", tabs: ["Today", "Recent", "Unreconciled", "Reversed"], columns: ["Date", "Student", "Invoice", "Amount", "Method", "Reference", "Status"], workflow: ["Select invoice", "Capture payment", "Issue receipt", "Reconcile", "Reverse when authorized"], capabilities: ["Cash", "Bank", "Mobile money", "References", "Receipts", "Reconciliation", "Reversals"] },
  "fees/arrears": { title: "Arrears & Balances", group: "Finance", description: "Identify outstanding accounts, prioritize follow-up and track cleared balances.", action: "Review arrears", tabs: ["All owing", "Due soon", "Overdue", "High balance", "Cleared"], columns: ["Student", "Class", "Invoice total", "Paid", "Balance", "Days overdue", "Action"], workflow: ["Calculate balance", "Segment accounts", "Send reminder", "Record arrangement", "Close cleared balance"], capabilities: ["Balance aging", "Overdue queue", "Reminders", "Payment plans", "Collections reporting"] },
  "communications/messages": { title: "Messages", group: "Communication", description: "Manage school-to-family messages and inspect delivery status and history.", action: "Compose message", tabs: ["Inbox", "Sent", "Queued", "Failed"], columns: ["Recipient", "Channel", "Subject", "Sent", "Status"], workflow: ["Choose audience", "Compose", "Review recipients", "Send", "Monitor delivery"], capabilities: ["Targeted messages", "Templates", "SMS", "WhatsApp", "Delivery tracking"] },
  "communications/announcements": { title: "Announcements", group: "Communication", description: "Publish school announcements to targeted groups on a schedule.", action: "Create announcement", tabs: ["Draft", "Scheduled", "Published", "Expired"], columns: ["Title", "Audience", "Published", "Channel", "Status"], workflow: ["Write announcement", "Select audience", "Schedule or publish", "Track reach", "Archive"], capabilities: ["Audience targeting", "Scheduling", "Channels", "Publication history"] },
  "communications/broadcasts": { title: "SMS / WhatsApp", group: "Communication", description: "Run targeted broadcasts and manage approved communication templates and delivery.", action: "Create broadcast", tabs: ["Compose", "Queued", "Sent", "Failed", "Templates"], columns: ["Audience", "Channel", "Template", "Recipients", "Delivered", "Failed"], workflow: ["Choose audience", "Select template", "Preview", "Send", "Review delivery"], capabilities: ["SMS", "WhatsApp", "Templates", "Recipient groups", "Delivery logs"] },
  events: { title: "Events", group: "Communication", description: "Manage the school calendar, meetings, activities and operational dates.", action: "Create event", tabs: ["Upcoming", "Calendar", "Past", "Operational"], columns: ["Event", "Type", "Start", "End", "Attendance", "Status"], workflow: ["Create event", "Set date and audience", "Add operational impact", "Communicate", "Review completion"], capabilities: ["Calendar", "Academic events", "Meetings", "Operational effects"] },
  library: { title: "Library", group: "School Life", description: "Manage the library catalogue, lending, returns and overdue resources.", action: "Add book", tabs: ["Catalogue", "Borrowed", "Overdue", "Returns"], columns: ["Book", "Category", "Available", "Borrowed", "Due", "Status"], workflow: ["Catalogue resource", "Issue to learner", "Track due date", "Receive return", "Follow up overdue"], capabilities: ["Catalogue", "Circulation", "Borrower history", "Due dates", "Overdue tracking"] },
  transport: { title: "Transport", group: "School Life", description: "Organize routes, vehicles, drivers, stops and learner transport assignments.", action: "Create route", tabs: ["Routes", "Vehicles", "Stops", "Assignments"], columns: ["Route", "Vehicle", "Driver", "Stops", "Students", "Status"], workflow: ["Create route", "Add vehicle and driver", "Define stops", "Assign learners", "Monitor changes"], capabilities: ["Routes", "Vehicles", "Drivers", "Stops", "Assignments"] },
  feeding: { title: "Feeding", group: "School Life", description: "Plan meals, menus and feeding records for school service.", action: "Create meal plan", tabs: ["Today", "Menu", "Attendance", "History"], columns: ["Date", "Meal", "Menu", "Expected", "Served", "Status"], workflow: ["Plan menu", "Set expected numbers", "Record service", "Review feeding", "Track history"], capabilities: ["Meal plans", "Menus", "Feeding register", "Service records"] },
  inventory: { title: "Assets & Inventory", group: "School Life", description: "Track assets, stock, locations, assignments, maintenance and lifecycle status.", action: "Add asset", tabs: ["Assets", "Stock", "Assigned", "Maintenance", "Retired"], columns: ["Item", "Category", "Location", "Qty", "Assigned to", "Condition"], workflow: ["Register asset", "Assign location", "Record movement", "Track maintenance", "Retire asset"], capabilities: ["Asset register", "Stock control", "Locations", "Assignments", "Maintenance", "Lifecycle"] },
  "hr/recruitment": { title: "Recruitment", group: "School Life", description: "Manage vacancies, applicants, interview stages and hiring decisions.", action: "Create vacancy", tabs: ["Open", "Applicants", "Interview", "Offers", "Closed"], columns: ["Candidate", "Position", "Stage", "Interview", "Owner", "Status"], workflow: ["Create vacancy", "Review applications", "Interview", "Decide", "Onboard"], capabilities: ["Vacancies", "Applications", "Shortlisting", "Interviews", "Offers"] },
  "reports/analytics": { title: "School Analytics", group: "Reports & Admin", description: "Explore live school indicators across enrolment, attendance, academics and finance.", action: "Open analytics", tabs: ["Overview", "Students", "Attendance", "Academics", "Finance"], columns: ["Metric", "Period", "Current", "Previous", "Trend"], workflow: ["Choose area", "Select period", "Inspect metrics", "Drill into records", "Export insight"], capabilities: ["KPI trends", "Drill-down", "Attendance analytics", "Academic analytics", "Finance analytics"] },
  reports: { title: "School Reports", group: "Reports & Admin", description: "Generate operational reports from live school records.", action: "Build report", tabs: ["Saved reports", "Academic", "Attendance", "Finance", "Operations"], columns: ["Report", "Area", "Last run", "Owner", "Format"], workflow: ["Choose report", "Set filters", "Preview", "Export or schedule", "Share securely"], capabilities: ["Academic reports", "Attendance reports", "Finance reports", "Operations reports", "Export"] },
  "settings/roles": { title: "Roles & Permissions", group: "Reports & Admin", description: "Control what school users can view and change.", action: "Create role", tabs: ["Roles", "Permissions", "Overrides", "Audit"], columns: ["Role", "Users", "Permissions", "Overrides", "Status"], workflow: ["Create role", "Choose permissions", "Assign users", "Add overrides", "Review audit"], capabilities: ["Roles", "Permissions", "User assignment", "Overrides", "Audit"] },
  settings: { title: "School Settings", group: "Reports & Admin", description: "Configure academic years, terms, grading, attendance, branding, notifications and security.", action: "Open settings", tabs: ["General", "Academics", "Attendance", "Finance", "Branding", "Notifications", "Security"], columns: ["Setting area", "Current state", "Owner", "Last updated"], workflow: ["Review defaults", "Configure academics", "Set operational rules", "Brand communications", "Review security"], capabilities: ["Academic year", "Terms", "Grading", "Attendance rules", "Branding", "Notifications", "Security"] },
  search: { title: "Search", group: "Workspace", description: "Find people, classes, invoices, assessments, messages and school records from one place.", action: "Search", tabs: ["All", "People", "Academics", "Finance", "Communication"], columns: ["Result", "Type", "Area", "Updated", "Status"], workflow: ["Enter search", "Filter by area", "Open record", "Take authorized action"], capabilities: ["Global search", "Area filters", "Quick actions"] },
  help: { title: "Help & Support", group: "Workspace", description: "Get guidance for configuring and operating your school workspace.", action: "Open support", tabs: ["Guides", "Support", "System status"], columns: ["Resource", "Area", "Updated", "Status"], workflow: ["Find guide", "Review instructions", "Contact support", "Track resolution"], capabilities: ["Guides", "Support", "System status"] }
};

async function countFor(module: string, schoolId: string): Promise<number> {
  switch (module) {
    case "students": return db.student.count({ where: { schoolId } });
    case "guardians": return db.guardian.count({ where: { schoolId } });
    case "staff": return db.user.count({ where: { schoolId } });
    case "classes": return db.class.count({ where: { schoolId } });
    case "subjects": return db.subject.count({ where: { schoolId } });
    case "timetable": return db.timetableSlot.count({ where: { schoolId } });
    case "gradebook": return db.score.count({ where: { schoolId } });
    case "exams": return db.assessment.count({ where: { schoolId } });
    case "report-cards": return db.reportCard.count({ where: { schoolId } });
    case "attendance": return db.attendanceEvent.count({ where: { schoolId, studentId: { not: null } } });
    case "staff-attendance": return db.attendanceEvent.count({ where: { schoolId, staffId: { not: null } } });
    case "fees": return db.feeItem.count({ where: { schoolId } });
    case "fees/invoices": return db.invoice.count({ where: { schoolId } });
    case "fees/payments": return db.payment.count({ where: { schoolId } });
    case "fees/arrears": return db.invoice.count({ where: { schoolId, status: { in: ["unpaid", "part-paid", "overdue"] } } });
    case "communications/messages": return db.message.count({ where: { schoolId } });
    case "events": return db.calendarEvent.count({ where: { schoolId } });
    case "settings/roles": return db.role.count({ where: { schoolId } });
    default: return 0;
  }
}

export default async function SchoolModulePage({ params }: { params: Promise<{ module: string[] }> }) {
  const { module } = await params;
  const key = module.join("/");
  const config = modules[key];
  if (!config) redirect("/dashboard");
  const session = await getSchoolSession();
  if (!session) redirect("/login/school");
  const school = await db.school.findUnique({ where: { id: session.schoolId } });
  if (!school) redirect("/login/school");
  const count = await countFor(key, school.id);
  return <AppShell universe="school" title={config.title} subtitle={`${school.name} · ${school.uniqueCode}`} active={config.title} schoolName={school.name} schoolCode={school.uniqueCode} userName={session.name} role="School Administrator">
    <div className="module-shell">
      <section className="app-card module-hero"><div className="module-hero-row"><div><span className="module-kicker">{config.group}</span><h2>{config.title}</h2><p>{config.description}</p><div className="module-actions"><Link className="module-button primary" href={`/school/${key}`}>{config.action} →</Link><Link className="module-button secondary" href="/dashboard">Back to overview</Link></div></div><div className="app-kpi module-stat"><small>Live records</small><strong>{count.toLocaleString()}</strong><span>Real records in this school</span></div></div></section>
      <section className="module-stats"><div className="app-card module-stat"><small>Current records</small><strong>{count.toLocaleString()}</strong><span>Database-backed</span></div><div className="app-card module-stat"><small>Workflow stages</small><strong>{config.workflow.length}</strong><span>Process steps</span></div><div className="app-card module-stat"><small>Capabilities</small><strong>{config.capabilities.length}</strong><span>Core functions</span></div><div className="app-card module-stat"><small>Data policy</small><strong>Live</strong><span>No invented school data</span></div></section>
      <div className="module-layout"><section className="app-card module-panel"><div className="module-tabs">{config.tabs.map((tab)=> <span key={tab} className="module-tab">{tab}</span>)}</div><div className="module-toolbar"><div className="module-filters"><input className="module-input" placeholder={`Search ${config.title.toLowerCase()}...`} /><select className="module-select" defaultValue="all"><option value="all">All statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="archived">Archived</option></select></div><span className="app-pill">{count.toLocaleString()} records</span></div><div className="module-responsive"><table className="module-table"><thead><tr>{config.columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody><tr><td colSpan={config.columns.length}><div className="module-empty"><strong>{count === 0 ? "No live records yet" : "Live records are available"}</strong><span>{count === 0 ? `Start with “${config.action}” or import your existing school data.` : "Use the search, filters and workflow controls to work with these records."}</span></div></td></tr></tbody></table></div></section><aside className="module-side-stack"><section className="app-card module-side-card"><h3>Workflow</h3><p>How this school process moves from setup to completion.</p><div className="module-list">{config.workflow.map((step,index)=><div className="module-list-row" key={step}><span className="module-list-no">{index+1}</span><div><b>{step}</b><span>Tracked in this school workspace.</span></div></div>)}</div></section><section className="app-card module-side-card"><h3>Included capabilities</h3><p>Operational functions planned for this workspace.</p><div className="module-pill-row">{config.capabilities.map((capability)=><span className="module-pill" key={capability}>{capability}</span>)}</div><div className="module-notice">The workspace stays at zero until your school has real records. No demo students, fees, attendance or marks are inserted.</div></section></aside></div>
    </div>
  </AppShell>;
}
