import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { requireSchoolSession } from "@/lib/school-auth";

const modules: Record<string, { title: string; group: string; description: string; action: string; tabs: string[]; fields: string[] }> = {
  students: { title: "Students", group: "People", description: "Student records, admissions, classes, guardians, attendance, academics and fees.", action: "Add student", tabs: ["All students", "Active", "Pending", "Graduated", "Archived"], fields: ["Student", "Admission number", "Class", "Guardians", "Attendance", "Fees", "Status"] },
  guardians: { title: "Parents & Guardians", group: "People", description: "Families, learner relationships, communication access and pickup permissions.", action: "Add guardian", tabs: ["All guardians", "Primary contacts", "Portal access", "Needs attention"], fields: ["Guardian", "Phone", "Learners", "Primary", "Portal", "Status"] },
  staff: { title: "Staff & Teachers", group: "People", description: "Staff profiles, roles, teaching assignments, attendance and payroll readiness.", action: "Add staff", tabs: ["All staff", "Teachers", "Administrators", "Inactive"], fields: ["Staff member", "Role", "Teaching load", "Attendance", "Payroll", "Status"] },
  "admissions/enquiries": { title: "Admissions Enquiries", group: "Admissions", description: "Capture prospective-family enquiries and follow them through the admissions pipeline.", action: "Add enquiry", tabs: ["New", "Contacted", "Qualified", "Converted", "Closed"], fields: ["Prospect", "Interested class", "Contact", "Source", "Owner", "Status"] },
  "admissions/applications": { title: "Applications", group: "Admissions", description: "Review applications, documents, decisions and admission readiness.", action: "New application", tabs: ["Draft", "Submitted", "Review", "Accepted", "Rejected"], fields: ["Applicant", "Class", "Submitted", "Reviewer", "Decision", "Status"] },
  "admissions/enrolment": { title: "Enrolment", group: "Admissions", description: "Turn approved applicants into active student records and class placements.", action: "Start enrolment", tabs: ["Ready", "In progress", "Completed", "Withdrawn"], fields: ["Applicant", "Class", "Admission number", "Start date", "Status"] },
  classes: { title: "Classes & Houses", group: "Admissions", description: "Organize levels, classes, houses, class teachers and learner capacity.", action: "Create class", tabs: ["Classes", "Houses", "Class teachers", "Capacity"], fields: ["Class", "Level", "Students", "Class teacher", "Subjects", "Status"] },
  subjects: { title: "Subjects", group: "Academics", description: "Manage subjects and connect them to classes, teachers, assessments and timetables.", action: "Add subject", tabs: ["All subjects", "Core", "Electives", "Unassigned"], fields: ["Subject", "Classes", "Teachers", "Assessments", "Timetable slots"] },
  timetable: { title: "Timetable", group: "Academics", description: "Build schedules, manage teacher coverage and detect timetable clashes.", action: "Add timetable slot", tabs: ["Weekly timetable", "Teacher view", "Class view", "Substitutes"], fields: ["Day", "Period", "Class", "Subject", "Teacher", "Substitute"] },
  lessons: { title: "Lessons & Planning", group: "Academics", description: "Plan lessons, schemes, objectives, resources and completion.", action: "Create lesson", tabs: ["Planned", "This week", "Completed", "Templates"], fields: ["Lesson", "Class", "Subject", "Teacher", "Date", "Status"] },
  homework: { title: "Homework & Exercises", group: "Academics", description: "Create work, assign it to learners, collect submissions and grade completion.", action: "Create exercise", tabs: ["Draft", "Assigned", "Due", "Submitted", "Reviewed"], fields: ["Exercise", "Class", "Subject", "Due", "Submitted", "Status"] },
  gradebook: { title: "Gradebook", group: "Academics", description: "Manage learner scores, grades, missing marks and publication status.", action: "Open gradebook", tabs: ["By class", "By subject", "Missing scores", "Published"], fields: ["Learner", "Class", "Subject", "Assessment", "Score", "Grade"] },
  exams: { title: "Exams & Assessments", group: "Academics", description: "Plan assessments, collect scores, moderate results and lock approved results.", action: "Create assessment", tabs: ["Planned", "Open", "Submitted", "Locked", "Results"], fields: ["Assessment", "Term", "Class", "Subject", "Weight", "Scores"] },
  "report-cards": { title: "Report Cards", group: "Academics", description: "Generate, review, approve, brand and publish learner report cards.", action: "Generate report cards", tabs: ["Draft", "For review", "Approved", "Sent"], fields: ["Learner", "Class", "Term", "Template", "Status", "Approved"] },
  attendance: { title: "Student Attendance", group: "Attendance", description: "Daily registers, lateness, absence reasons, exceptions and parent alerts.", action: "Take attendance", tabs: ["Today", "History", "Absences", "Late", "Exceptions"], fields: ["Date", "Class", "Present", "Late", "Absent", "Recorded by"] },
  "staff-attendance": { title: "Staff Attendance", group: "Attendance", description: "Track staff presence, lateness, absence and workforce trends.", action: "Record staff attendance", tabs: ["Today", "History", "Late", "Absent"], fields: ["Date", "Staff member", "Status", "Method", "Recorded by"] },
  fees: { title: "School Fees", group: "Finance", description: "Fee structures, billing, collections, balances and arrears.", action: "Create fee item", tabs: ["Overview", "Fee items", "Billed", "Collected", "Arrears"], fields: ["Fee item", "Term", "Class", "Amount", "Collected", "Balance"] },
  "fees/invoices": { title: "Invoices", group: "Finance", description: "Student invoices, line items, balances and payment status.", action: "Create invoice", tabs: ["All", "Unpaid", "Part-paid", "Paid", "Overdue"], fields: ["Invoice", "Student", "Term", "Total", "Paid", "Balance"] },
  "fees/payments": { title: "Payments", group: "Finance", description: "Capture payments, references, receipts, reconciliation and authorized reversals.", action: "Record payment", tabs: ["Today", "Recent", "Unreconciled", "Reversed"], fields: ["Date", "Student", "Invoice", "Amount", "Method", "Reference"] },
  "fees/arrears": { title: "Arrears & Balances", group: "Finance", description: "Find outstanding accounts, aging balances and follow-up priorities.", action: "Review arrears", tabs: ["All owing", "Due soon", "Overdue", "High balance", "Cleared"], fields: ["Student", "Class", "Invoice total", "Paid", "Balance", "Days overdue"] },
  "communications/messages": { title: "Messages", group: "Communication", description: "School-to-family messages with audience targeting and delivery history.", action: "Compose message", tabs: ["Inbox", "Sent", "Queued", "Failed"], fields: ["Recipient", "Channel", "Subject", "Sent", "Status"] },
  "communications/announcements": { title: "Announcements", group: "Communication", description: "Publish targeted school announcements and scheduled notices.", action: "Create announcement", tabs: ["Draft", "Scheduled", "Published", "Expired"], fields: ["Title", "Audience", "Published", "Channel", "Status"] },
  "communications/broadcasts": { title: "SMS / WhatsApp", group: "Communication", description: "Targeted broadcasts, templates, delivery status and communication history.", action: "Create broadcast", tabs: ["Compose", "Queued", "Sent", "Failed", "Templates"], fields: ["Audience", "Channel", "Template", "Recipients", "Delivered", "Failed"] },
  events: { title: "Events", group: "Communication", description: "School calendar, meetings, activities and operational dates.", action: "Create event", tabs: ["Upcoming", "Calendar", "Past", "Operational"], fields: ["Event", "Type", "Start", "End", "Attendance", "Status"] },
  library: { title: "Library", group: "School Life", description: "Catalogue, lending, returns and overdue library resources.", action: "Add book", tabs: ["Catalogue", "Borrowed", "Overdue", "Returns"], fields: ["Book", "Category", "Available", "Borrowed", "Due", "Status"] },
  transport: { title: "Transport", group: "School Life", description: "Routes, vehicles, drivers, stops and learner transport assignments.", action: "Create route", tabs: ["Routes", "Vehicles", "Stops", "Assignments"], fields: ["Route", "Vehicle", "Driver", "Stops", "Students", "Status"] },
  feeding: { title: "Feeding", group: "School Life", description: "Meal planning, menus and feeding service records.", action: "Create meal plan", tabs: ["Today", "Menu", "Service", "History"], fields: ["Date", "Meal", "Menu", "Expected", "Served", "Status"] },
  inventory: { title: "Assets & Inventory", group: "School Life", description: "Asset register, stock, assignments, maintenance and lifecycle status.", action: "Add asset", tabs: ["Assets", "Stock", "Assigned", "Maintenance", "Retired"], fields: ["Item", "Category", "Location", "Quantity", "Assigned to", "Condition"] },
  "hr/recruitment": { title: "Recruitment", group: "School Life", description: "Manage openings, applicants, screening and hiring decisions.", action: "Create vacancy", tabs: ["Open", "Applicants", "Interview", "Offer", "Closed"], fields: ["Position", "Department", "Applicants", "Owner", "Stage", "Status"] },
  "reports/analytics": { title: "School Analytics", group: "Reports & Admin", description: "Cross-school operational analytics built from actual learner, attendance, academic and financial records.", action: "Configure report", tabs: ["Overview", "Students", "Attendance", "Academics", "Finance"], fields: ["Metric", "Period", "Value", "Trend", "Owner"] },
  reports: { title: "Reports", group: "Reports & Admin", description: "Operational, academic, attendance and financial reporting.", action: "Create report", tabs: ["Recent", "Scheduled", "Academic", "Attendance", "Finance"], fields: ["Report", "Category", "Period", "Created", "Owner", "Status"] },
  "settings/roles": { title: "Roles & Permissions", group: "Reports & Admin", description: "Control who can access student, academic, finance, communication and administration functions.", action: "Create role", tabs: ["Roles", "Permissions", "Assignments", "Audit"], fields: ["Role", "Users", "Permissions", "Scope", "Status"] },
  settings: { title: "School Settings", group: "Reports & Admin", description: "Configure the school's identity, academic calendar, grading, communication, finance and security settings.", action: "Save settings", tabs: ["General", "Academic", "Finance", "Communication", "Security"], fields: ["Setting", "Current value", "Category", "Updated", "Updated by"] },
  search: { title: "Search", group: "Workspace", description: "Find students, guardians, staff, invoices, assessments, messages and other school records.", action: "Search", tabs: ["All", "People", "Academics", "Finance", "Communication"], fields: ["Record", "Type", "Owner", "Updated", "Status"] },
  help: { title: "Help & Support", group: "Workspace", description: "Guidance, support requests and school administration help.", action: "Contact support", tabs: ["Guides", "Requests", "Updates"], fields: ["Topic", "Category", "Updated", "Status"] }
};

export default async function SchoolModulePage({ params }: { params: Promise<{ module?: string[] }> }) {
  const session = await requireSchoolSession();
  const resolved = await params;
  const key = (resolved.module ?? []).join("/");
  const config = modules[key];
  if (!config) notFound();
  const href = `/school/${key}`;
  return (
    <AppShell universe="school" title={config.title} subtitle={config.description} active={config.title} schoolName="SukuuNova Test School" schoolCode="test001" userName={session.name} role="Owner">
      <div className="workspace-module">
        <div className="workspace-module-hero">
          <div><span className="workspace-eyebrow">{config.group}</span><h2>{config.title}</h2><p>{config.description}</p></div>
          <Link className="workspace-primary-action" href={`${href}?action=create`}>+ {config.action}</Link>
        </div>
        <div className="workspace-tabs">{config.tabs.map((tab, index) => <Link key={tab} className={`workspace-tab ${index === 0 ? "is-active" : ""}`} href={`${href}?view=${encodeURIComponent(tab)}`}>{tab}</Link>)}</div>
        <div className="workspace-kpis"><article><small>Records</small><strong>0</strong><span>Live school data only</span></article><article><small>Workflow</small><strong>1</strong><span>Ready for setup</span></article><article><small>Capabilities</small><strong>{config.fields.length}</strong><span>Operational fields</span></article></div>
        <section className="workspace-card workspace-table-card">
          <div className="workspace-card-head"><div><h3>{config.title} records</h3><p>No sample data is displayed. Create or import real school records to populate this workspace.</p></div><Link className="workspace-compact-action" href={`${href}?action=create`}>+ {config.action}</Link></div>
          <div className="workspace-table-wrap"><table><thead><tr>{config.fields.map((field) => <th key={field}>{field}</th>)}</tr></thead><tbody><tr><td colSpan={config.fields.length}><div className="workspace-empty"><strong>No records yet</strong><span>This module is ready for real school data.</span></div></td></tr></tbody></table></div>
        </section>
        <div className="workspace-bottom-grid"><section className="workspace-card"><h3>Recommended workflow</h3><ol>{config.tabs.slice(0, 4).map((step) => <li key={step}>{step}</li>)}</ol></section><section className="workspace-card"><h3>Next action</h3><p>Start with <strong>{config.action}</strong>, then the records created here can feed connected school workflows.</p><Link className="workspace-secondary-action" href={`${href}?action=create`}>Open workspace →</Link></section></div>
      </div>
    </AppShell>
  );
}
